### ISSUE TITLE
Demo SVG is broken in Firefox 99

### ISSUE THREAD

**Issue by allo-** [sharkdp/fd#1003]
The demo SVG seems to scale the fonts incorrectly in Firefox 99 on Linux.
Maybe you rather include a GIF for the demo, to make sure it looks the same disregarding which browser (and maybe fonts?) the user is using.

![Screenshot_20220414_195013](https://user-images.githubusercontent.com/1482341/163448961-699b45fa-cf7c-4c09-875b-ed2f7952f364.png)

**Comment by tavianator** [comment]
Can't reproduce on my Firefox 99 installation.  I feel like this might be a hw accel bug.  Not sure it's worth trying to work around it.

**Comment by tmccombs** [comment]
I also can't reproduce with Firefox 99 (On ubuntu 20.04). @allo- maybe report this as a bug to Firefox?

**Comment by cas--** [comment]
This is a known existing  [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1677988) when a user has a minimum font size set. There is an svg workaround to set `font-size` for every `text` element if you feel like fixing it for `fd`.

Same issue with release-it: https://github.com/release-it/release-it/issues/894

**Comment by allo-** [comment]
Yes, I am using a minimum font size, but I thought it should apply to text only and not to (vector) graphics.

**Comment by sharkdp** [comment]
Should be fixed now

**Comment by allo-** [comment]
Yes, it works for me now.

**Comment by masukomi** [comment]
thank you very much for fixing this @sharkdp , and for actually caring about devs with low vision needs. 

I've reported this particular problem to many projects I encounter using this, but this is the first one (to my knowledge) that has ever done anything about it.

**Comment by sharkdp** [comment]
Credit goes to @yyogo :smile:
