### ISSUE TITLE
How to quit fd immediately when one of command passed to -x run failed (return code non-zero)?

### ISSUE THREAD

**Issue by zw963** [sharkdp/fd#1004]
Following is a example, thank you.

```sh
 ╰─ $ fd -erb -x ruby -c
Syntax OK
Syntax OK
./4.rb:1: unterminated string meets end of file                 # is there a way to quit immediately here when ruby -c return code non-zero?
puts "hel
         ^
Syntax OK
Syntax OK
Syntax OK
Syntax OK
Syntax OK
Syntax OK
Syntax OK
Syntax OK
Syntax OK
Syntax OK
Syntax OK
Syntax OK
Syntax OK
Syntax OK
Syntax OK
Syntax OK
 ╰─ $ 1  
```

**Comment by tmccombs** [comment]
I don't think it is currently possible with just fd. 

You could do something like:

```
fd -erb -0 | xargs -0 -n1 sh -c 'ruby -c $0 || exit 255' 
```
which will have xargs exit early.

**Comment by zw963** [comment]
> 

It works,  enough, it slow than directly use with `fd -x`, than you.

**Comment by zw963** [comment]
> You could possibly speed it up by passing the "-P" option with a higher number to xargs to have xargs run commands in parallel .

Cool, it works! far quick then before, though, still slow than use fd directly

time fd -erb -0 | xargs -0 -n1 sh -c 'ruby -c $0 || exit 255 # real    0m8.516s
time fd -erb -0 | xargs -0 -P 8 -n1 sh -c 'ruby -c $0 || exit 255' #  real    0m1.963s
time fd -erb -x ruby -c # real    0m1.223s
