### ISSUE TITLE
Inconsistent command-and-package naming:  fd, fd-find, fdfind

### ISSUE THREAD

**Issue by johnnyutahh** [sharkdp/fd#1009]
Consider finding a consistent name/naming for this project/command/package for better community adoption, marketability?

(Apologies if this is a duplicate issue/inquiry/discussion.)

**Details**

Addressing `fd(1)` iconsistent pkg & cmd names: there's _three_ different `fd(1)`-related names I have to remember in my world. I suspect this can also get confusing for others.

1. on macOS homebrew: the package and command = [fd](https://formulae.brew.sh/formula/fd)
2. on Ubuntu 20.04 the package = `fd-find`
3. on Ubuntu 20.04 the command = `fdfind`

I make an alias `fdfind='fd'` on macOS for consistent cmd naming (between my macOS and Linux platforms).

More context here:  https://stackoverflow.com/a/71931037/605356

**Comment by tmccombs** [comment]
The reason the ubuntu package and command are so named is because there was already an existing package (and executable) with the name `fd` in the debian/ubuntu repos. As for why the executable and package name are inconsistent on ubuntu, I have no idea.

**Comment by johnnyutahh** [comment]
Understood and thanks. I was aware of the `fd`-package-on-Ubuntu name collision.

I think the question becomes: is it worth (re?)branding/naming the `sharkdp/fd` command and packages to a unique name in every context (including all OS distributions), potentially providing consistency for users and general community?

**Comment by tavianator** [comment]
I think `fd` is far too popular at this point to consider renaming it.  It's even [much more popular](https://qa.debian.org/popcon-graph.php?packages=fd-find%2Cfdclone&show_installed=on&want_legend=on&want_ticks=on&from_date=&to_date=&hlght_date=&date_fmt=%25Y-%25m&beenhere=1) on Debian than the `fdclone` package that took `/usr/bin/fd` first.

What I would recommend is adding `/usr/lib/cargo/bin` to your `$PATH`, as [suggested](https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/fd-find/debian/README.Debian) by Debian, so that you can use `fd` on all platforms.

It is kind of weird that the package (`fd-find`) doesn't match the binary (`fdfind`) on Debian/Ubuntu, but that's not something we control.  You could report it to the Debian packager and see if they'd be willing to rename the package or make an alias or something.

**Comment by tmccombs** [comment]
It's also worth pointing out that renaming `fd` to `fdfind` would mean other distributions that use the original `fd` name (for example archlinux) would have to change their packages (or would end up with inconsistent names as well).

**Comment by sharkdp** [comment]
> I'm interested if the main author(s)/maintainor(s) (@sharkdp) have pondered all of the above.

I had nothing to do with the Ubuntu/Debian package or executable naming but I tried really hard to convince them to reconsider their choice of renaming the executable (I don't care too much about the package name). I thought it would be easy to just mark the other package as "conflicting" and still name the executable `fd`, just as in the other package. However, the Debian/Ubuntu authors have a very strict policy about this... and for a good reason. They want scripts that refer to a `fd` executable to perform the exact same thing on every Debian/Ubuntu installation, regardless of the installed package set (well, I guess the script would show an error if the package with the `fd` executable is not installed).

When I chose the name originally, I did in fact search for other packages/executables that were named the same, and didn't find any. But I sure knew that I was asking for trouble when choosing a two-letter name.

I do not intend to rename the project or the executable. `fd` is available on many different systems and distributions, and Debian/Ubuntu is the only one that has problems with the `fd` executable name.

**Comment by sharkdp** [comment]
Closing for now. But feel free to comment here if you think anything has not been clarified.

**Comment by johnnyutahh** [comment]
[This](https://github.com/sharkdp/fd/issues/1009#issuecomment-1126961367) all makes perfect sense. I would have done the same thing in sharkdp's shoes and agree with all of this.  (I hope my comment does not re-open this issue... apologies if so.)
