### ISSUE TITLE
screencast doesn't work for low vision users (see screenshot)

### ISSUE THREAD

**Issue by masukomi** [sharkdp/fd#1021]
if you need a large font (mine's currently set to 22, which isn't huge compared to some low vision folks) then the screencast is unreadable. See attached screenshot: 

<img width="898" alt="CleanShot 2022-05-20 at 15 32 50@2x" src="https://user-images.githubusercontent.com/2829/169599082-e32042cc-0bc7-47fa-9a96-a2b407ef117d.png" alt="screenshot of screencast with ridiculously large fonts. You can only see the bottom sliver of each, and they overlap. It is unreadable " >

**Comment by tavianator** [comment]
Are you using Firefox?  If so, that's a Firefox bug, reported here already too: https://github.com/sharkdp/fd/issues/1003

**Comment by sharkdp** [comment]
Maybe we should go ahead and use that workaround suggested in https://github.com/sharkdp/fd/issues/1003#issuecomment-1102486945

**Comment by sharkdp** [comment]
Should be fixed now
