### ISSUE TITLE
Why does fd skip the "build" directory ?

### ISSUE THREAD

**Issue by sebma** [sharkdp/fd#1023]
Hi,
I'm using fd v8.3.2.
Here is a way to reproduce this behavior : 
```shell
$ git clone https://github.com/soimort/translate-shell
$ cd translate-shell
$ make
$ find -type f -executable | grep -v .git
./translate.awk
./build.awk
./translate
./build/trans
$ fd -tx
build.awk
translate
translate.awk
```

**Comment by herbygillot** [comment]
Looks to me like the `build` directory is listed in `translate-shell`'s `.gitignore`:

https://github.com/soimort/translate-shell/blob/1e3f901c479fc4f838b290f11e1b547b86bdadd4/.gitignore#L2

`fd` ignores the same files that `git` does. If you want `fd` to search through everything, including anything ignored by `git`, use `-I` / `--no-ignore`:

```
> fd -h
...
    -I, --no-ignore                    Do not respect .(git|fd)ignore files
```

**Comment by sebma** [comment]
@herbygillot Thanks.
