### ISSUE TITLE
How to exclude multiple folders from the search?

### ISSUE THREAD

**Issue by haosmos** [sharkdp/fd#1026]
**What version of `fd` are you using?**
[paste the output of `fd 8.3.2` here]

I created a global file:

`~/.gitignore 
`

and execute the command:

`git config --global core.excludesfile ~/.gitignore`

I also created a .fdignore file and put it in like the manual says:

`~/.config/fd/ignore/.fdignore`

In these files (.fdignore and .gitignore) I put the files and folders that I want to exclude from the search.  

After that, I ran the source command ~/.zshrc

I use fzf and fd search to display the search results in previews — here is the setting in my .zshrc file:

```
# fzf's command
export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude 'node_modules'"

# CTRL-T's command
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# ALT-C's command
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND --type d"

export FZF_DEFAULT_OPTS="
--layout=reverse
--info=inline
--height=90%
--preview-window=right:70%
--multi
--prompt='∼ '
--pointer='▶'
--marker='✓'
--preview '([[ -f {} ]] && (bat --style=numbers,header,grid --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
--bind '?:toggle-preview'
--bind 'ctrl-a:select-all'
--bind 'ctrl-y:execute-silent(echo {+} | pbcopy)'
--bind 'ctrl-e:execute(echo {+} | xargs -o vim)'
--bind 'ctrl-v:execute(code {+})'
"

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS"
--color=fg:#4ca5ed,bg:#1b2b34,hl:#4cdb33
--color=fg+:#00ddff,bg+:#343d46,hl+:#2bff05
--color=info:#fac863,prompt:#07ed35,pointer:#07ed35
--color=marker:#5fb3b3,spinner:#07ed35,header:#1fdbce
"

FORGIT_FZF_DEFAULT_OPTS="
--exact
--border
--cycle
--reverse
--preview-window=bottom:80%
--height '80%'
"
```
However, the folders and files I excluded from the search are still found through the fd search. For example, you can see in the picture that the node folder that I excluded from the search (added to the .gitignore .fdignore) is in the search result. 

![WindowsTerminal_osHv8MbkY6](https://user-images.githubusercontent.com/30666874/169708872-dbba00db-e084-46a6-83e5-0773fedb25a8.png)

![Code_sO2WuyqujT](https://user-images.githubusercontent.com/30666874/169708894-b421efac-2dd3-4e63-b619-f478e4badd3b.png)

![WindowsTerminal_doyVpnbyiH](https://user-images.githubusercontent.com/30666874/169708329-4f1fccce-ab1f-41bc-872b-a88aa37c423b.png)

![Code_b3d8Nz77p5](https://user-images.githubusercontent.com/30666874/169708901-ec61c6c2-2ce1-451f-a25d-230341f261cd.png)

How do I exclude folders from the search? 

My work environment: ubuntu 22.04 on WSL2

**Comment by haosmos** [comment]
I created an ignore folder and put the .fdignore file in that folder. So, that's the structure I have: 

![WindowsTerminal_PxkbFrs02i](https://user-images.githubusercontent.com/30666874/172680400-8c90b5f7-a042-4c08-aaea-29641dac0cca.png)

I even created another .fdignore file and put it in the fd folder, but that didn't help either. 

I can't figure out what I'm doing wrong and why fd behaves this way. For example: fd finds only one folder chalk, which I excluded from his search. If I search for the same chalk folder with find it will show more results. But if I search for chalk with fzf then fd does not find chalk:

![WindowsTerminal_f0ViQ8S59G](https://user-images.githubusercontent.com/30666874/172680593-20256f8a-06af-4f5e-9027-452dc5907756.png)

Or another example: If you search for the file .DS_Store with fd at the terminal line, it does not find it. But if you search for that file with fzf, the file is found:

![WindowsTerminal_ZE7F5WRWfx](https://user-images.githubusercontent.com/30666874/172680666-27fa4b7e-d2b9-470f-a90d-97633d7bdd5c.png)
 
Can you tell me why fd shows different results and how can I exclude files and folders I don't want to see or search for?

**Comment by tavianator** [comment]
> I even created another `.fdignore` file and put it in the fd folder, but that didn't help either.

The file should be called `ignore`.  Not `.ignore` or `.fdignore`.

You can check whether it's in the right place with `cat ~/.config/fd/ignore`.  If that prints what you expect, `fd` should find it.

**Comment by laur89** [comment]
Unrelated, but just for info for future searchers:
```sh
# fzf's command
export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude 'node_modules'"

# ALT-C's command
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND --type d"
```

will not do what you'd expect -- fd's `--type f` & `--type d` will stack, meaning `alt+c` will complete _both_ files AND dirs.
