### ISSUE TITLE
After -IH, exclude some of those directories/fiels

### ISSUE THREAD

**Issue by EntilZha** [sharkdp/fd#1030]
**What version of `fd` are you using?**
[paste the output of `fd --version` here]
8.4.0

I'm not certain if I'm doing something wrong or if I've hit a limitation/bug, but I have a setup where I am trying to use `fd` to find all the files that I should zip to deploy to a static server site. My setup is:
1. Keep things in a github repository, hence have a .git folder with .gitignore and such
2. In the repository root, run a deploy script that builds into a directory like `output/`, which is by default on gitignore
3. The deploy script itself is run from a sub-directory, hence the `..` below

What I'm trying to do is run something like `fd -H -I -E '.*\.git/.*' -E bundle.zip -E '\.bundle' '.*' ..`

Running this (or the glob equivalent) shows the files I'm interested in transferring, included the ones normally gitignored, but it is also showing the .git file which I don't want to transfer. I suspect either (1) I'm doing this wrong or (2) the `-IH` flag is making it so that those files cannot be excluded after being included. I'm not sure which is the issue, thoughts?

**Comment by sharkdp** [comment]
Note that the exclude option always takes a *glob* pattern, not a regex.

**Comment by marcospb19** [comment]
I believe this can be closed.
