### ISSUE TITLE
How to search within bare repo respecting .gitignore file?

### ISSUE THREAD

**Issue by blueray453** [sharkdp/fd#1032]
**What version of `fd` are you using?**
 `fd 8.4.0`

I have a bare repo (so do not have .git directory). However, it has a .gitignore file.

How can I find all files except the files ignored by .gitignore?

**Comment by blueray453** [comment]
I want to find 

1. all files that are not ignored by `.gitignore`. For this, I use `fd -H` 
2. all files that are ignored by `.gitignore`. . For this, I use `comm -23 <(fd -HI | sort) <(fd -H | sort)`

This is very handy when using it to fix my `.gitignore` file.

I found that if I put a `.git` empty directory beside `.gitignore`, then it works. It does not need a working git directory anyways.

**Comment by tmccombs** [comment]
Ah, I think you are using "bare repo" to mean something different than I thought. I interpreted "bare repo" to mean what it means in the git documention, as a repo created similar to with `git clone --bare` where it is equivalent to just the .git directory without the working directory, but I think you might be referering to the working directory without the .git directory.

In that case, you could either create an empty .git directory as you found or explicitly use `--ignore-file .gitignore`

**Comment by blueray453** [comment]
By bare repository I meant `--work-tree=` of `git init --bare`. And you understood `--git-dir=` of `git init --bare`. Your understanding is correct in the sense that a repository is actually everything in the `.git` folder. However, the `.gitignore` seats in the `--work-tree=` so I thought as I am talking about `.gitignore`, i might not need to clarify any further.

I should have specifically told that the `.gitignore` in the `--work-tree=` of bare repo.

**Comment by tavianator** [comment]
I didn't realize you can have a work tree associated with a bare repo.  Can you give an example of how to set that up?  I don't see `--work-tree` documented under `git init`

**Comment by tmccombs** [comment]
Hmm, if you use `git worktree add`, the work tree has a `.git` _file_ rather than a directory, I wonder if that confuses `fd`.

**Comment by blueray453** [comment]
> I didn't realize you can have a work tree associated with a bare repo. Can you give an example of how to set that up? I don't see `--work-tree` documented under `git init`

```
git init git init --bare /home/ismail/Desktop/_dotfiles-backup/
git --git-dir=/home/ismail/Desktop/_dotfiles-backup/ --work-tree=$HOME status
git --git-dir=/home/ismail/Desktop/_dotfiles-backup/ --work-tree=$HOME add -A
git --git-dir=/home/ismail/Desktop/_dotfiles-backup/ --work-tree=$HOME commit -am "First Commit"
```

**Comment by tavianator** [comment]
Ohhh.  That's an (ab)use of git I haven't seen until now :)  In this case I'd recommend `--ignore-file=.gitignore`.

You could also try making your home directory a real working tree with something like

```console
$ echo "gitdir: /home/ismail/Desktop/_dotfiles-backup/" >~/.git
```

Which should save you from having to manually pass `--git-dir=` all the time.  I haven't tested it though.  You might have to do `git config core.bare=false` for it to work.
