### ISSUE TITLE
Rare panic

### ISSUE THREAD

**Issue by webermarci** [sharkdp/fd#1033]
What version of fd are you using?
`fd 8.4.0` on `Redhat`

I've encountered a rare panic while scanning through 300 million files spread in around 1000 folders.
The script was scanning each folder one by one and was running for more than 24 hours.

This panic occurred 2 times over the 24 hours:

```
thread '<unnamed>' panicked at 'internal error: entered unreachable code', /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sync/mpsc/mod.rs:1176:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/walk.rs:157:44
```

I was not able to reproduce this behaviour on the same folders again.

**Comment by tavianator** [comment]
This is probably https://github.com/rust-lang/rust/issues/39364.  Interesting to see this get hit in practice.  #933 tracks the most likely workaround in `fd`.
