### ISSUE TITLE
fd output in a single line with separated by space

### ISSUE THREAD

**Issue by Koushikphy** [sharkdp/fd#1034]
**What version of `fd` are you using?**
[paste the output of `fd --version` here]
Version of `fd` is 8.4.0

By default, `fd` prints its output in separate lines. I can pass `-0` that will print the output in a single line separated by null character. But what I want is to print all the output in a single line separated by space. How do I do that?

**Comment by tmccombs** [comment]
would `fd <options> | tr '\n' ' '` work?

**Comment by Koushikphy** [comment]
Does the job. Thanks
