### ISSUE TITLE
`fd` slower than `find` in specific task

### ISSUE THREAD

**Issue by wael444** [sharkdp/fd#1038]
**What version of `fd` are you using?**
fd 8.4.0

i have a script that pulls all executable binaries from $PATH:
```sh
	for d in $(echo "$PATH" | sed 's/:/ /g'); do
			find "$d/" -perm /111 2>/dev/null
	done | sed 's#.*/##' | sort -u
```
with fd:
```sh
	for d in $(echo "$PATH" | sed "s/:/ /g"); do
		fd -Hc never -t x -t l . "$d" 2>/dev/null
	done | sed 's#.*/##' | sort -u
```
checking with hyperfine:
```
% hyperfine --warmup 10 "m path" "m pathfd"
Benchmark 1: m path
  Time (mean ± σ):      57.7 ms ±   6.0 ms    [User: 41.0 ms, System: 36.8 ms]
  Range (min … max):    45.9 ms …  67.6 ms    43 runs

Benchmark 2: m pathfd
  Time (mean ± σ):      80.2 ms ±   2.7 ms    [User: 60.3 ms, System: 68.2 ms]
  Range (min … max):    69.5 ms …  84.7 ms    41 runs
 
Summary
  'm path' ran
    1.39 ± 0.15 times faster than 'm pathfd'
```

now yeah, i know my scripting kind of sucks, but still how is `find` faster than `fd`?

seperate question: why is the output in `fd` always randomized?

**Comment by tavianator** [comment]
Quick point: you might as well pass `-I` as well as `-H` to avoid `fd` looking for a bunch of nonexistent `.gitignore` files.

That doesn't really speed `fd` up too much though.  The main issue is parallelism: with such a small result set, the threading overhead is quite high.  We can try `-j1`:

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `find /usr/bin -type f -perm /111 -o -type l` | 6.1 ± 0.8 | 4.7 | 9.2 | 1.00 |
| `fd -H -t x -t l . /usr/bin` | 37.4 ± 2.2 | 31.8 | 41.6 | 6.10 ± 0.84 |
| `fd -HI -t x -t l . /usr/bin` | 37.3 ± 3.1 | 26.6 | 42.8 | 6.08 ± 0.91 |
| `fd -HI -j1 -t x -t l . /usr/bin` | 17.9 ± 1.2 | 15.4 | 21.0 | 2.92 ± 0.42 |

So, better, but still ~3x worse than `find`.  I think it's because even with `-j1`, there is a walker thread and a receiver thread that pass pathnames over a channel.  This is still a fair bit of overhead:

```
$ strace -cf fd -HI -j1 -t x -t l . /usr/bin >/dev/null
strace: Process 109346 attached
strace: Process 109347 attached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ------------------
 86.09    0.154442          12     12406      4933 futex
 12.87    0.023088           3      6308         1 statx
...
```

It's possible that https://github.com/sharkdp/fd/issues/933 will help with this.  We could also try doing everything on the same thread with `-j1` without channels at all.

> seperate question: why is the output in `fd` always randomized?

Also because of parallelism.  `fd` is multithreaded by default, so thread scheduling has a significant effect on the output order.  That said, even with `-j1` (or `find`), you can't rely on the output staying in a consistent order.

**Comment by wael444** [comment]
```bash
pathfd() {
	for d in $(echo "$PATH" | sed "s/:/ /g"); do
		fd -HLc never -j1 -t x . "$d" 2>/dev/null
	done | sed 's#.*/##' | sort -u
}

path() {
	for d in $(echo "$PATH" | sed "s/:/ /g"); do
		find "$d/" -perm /111 2>/dev/null
	done | sed 's#.*/##' | sort -u
}
```
the  `sed 's#.*/##'` could be fixed by #1037 btw.

```
Benchmark 1: m path
  Time (mean ± σ):      42.7 ms ±  19.6 ms    [User: 31.0 ms, System: 26.9 ms]
  Range (min … max):    12.9 ms …  66.5 ms    207 runs
 
Benchmark 2: m pathfd
  Time (mean ± σ):      74.9 ms ±  33.2 ms    [User: 48.1 ms, System: 53.1 ms]
  Range (min … max):    29.7 ms … 135.8 ms    30 runs
 
Summary
  'm path' ran
    1.75 ± 1.12 times faster than 'm pathfd'
```

**Comment by tavianator** [comment]
One handy thing is `fd` (and `find`) can search more than one path at once.  So maybe try

```sh
pathfd() {
    # This works in bash; in zsh, you'll need ${=PATH//:/ }
    fd -HIL -d1 -t x . ${PATH//:/ } | sed 's|.*/||' | sort -u
}

path() {
    # Assuming GNU find
    find -L ${PATH//:/ } -maxdepth 1 -type f -executable -printf '%f\n' | sort -u
}
```

**Comment by wael444** [comment]
I do sed intentionally for POSIX compliance, but thank you so much for pointing this out.

**Comment by tavianator** [comment]
I added `-d1` (equivalent to `-maxdepth 1` in `find`) to filter out things that aren't really on your `PATH`.  E.g. if you have some executable at `/usr/bin/some/nested/program`, and only `/usr/bin` is on your `PATH`, then `program` by itself won't be found, but your `path`/`pathfd` functions would have returned it.  Limiting the depth to 1 avoids searching any nested directories.

**Comment by wael444** [comment]
**WHAT?!**

```sh
path() {
	local path=$(printf "$PATH" | sed s/:/\ /g)
	case "$1" in 
		fd) fd -HLc never -d1 -t x . $path | sed 's|.*/||' | sort -u ;;
		fi) find $path -maxdepth 1 -perm /111 | sed 's|.*/||' | sort -u ;;
	esac 
} 2>/dev/null
```

```
Benchmark 1: m path fi
  Time (mean ± σ):      14.1 ms ±   5.3 ms    [User: 13.4 ms, System: 7.3 ms]
  Range (min … max):    10.9 ms …  23.4 ms    120 runs
 
  Warning: The first benchmarking run for this command was significantly slower than the rest (23.3 ms). This could be caused by (filesystem) caches that were not filled until after the first run. You should consider using the '--warmup' option to fill those caches before the actual benchmark. Alternatively, use the '--prepare' option to clear the caches before each timing run.
 
Benchmark 2: m path fd
  Time (mean ± σ):       9.7 ms ±   1.0 ms    [User: 16.2 ms, System: 11.7 ms]
  Range (min … max):     8.3 ms …  15.0 ms    248 runs
 
Summary
  'm path fd' ran
    1.45 ± 0.57 times faster than 'm path fi'
```

something else i also found quite ironic but weird?
```
void-live[~/.config/zsh]21ms% m path fd | grep xrankmirrors
xrankmirrors
void-live[~/.config/zsh]18ms% m path fi | grep xrankmirrors
1 void-live[~/.config/zsh]11ms% which xrankmirrors
/home/wael/.local/bin/scripts/xrankmirrors
void-live[~/.config/zsh]3ms% echo $PATH
.../home/wael/.local/bin/scripts...
```

**Comment by tavianator** [comment]
Nice!  With multiple starting points, `fd`'s parallelism has more of a benefit.

Is `~/.local/bin/scripts` a symbolic link?  The only difference I see between those commands is `fd` has `-L` and `find` doesn't.

> I do sed intentionally for POSIX compliance

Just fyi, `-perm /111` isn't POSIX, and neither is `-maxdepth`.

**Comment by wael444** [comment]
> Is ~/.local/bin/scripts a symbolic link? The only difference I see between those commands is fd has -L and find doesn't.

shit good point.

> Just fyi, -perm /111 isn't POSIX, and neither is -maxdepth.

# FUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu.....

**Comment by tavianator** [comment]
There is a POSIX-compliant equivalent to `-perm /111`:

```console
$ find -perm -100 -o -perm -010 -o -perm -001
```

and you could even emulate `-maxdepth 1`:

```console
$ find "$path" -path "$path/*/*" -prune -o \( -perm -100 -o -perm -010 -o -perm -001 \) -print
```

but that only works for one `$path` at a time.
