### ISSUE TITLE
show files as tree structure

### ISSUE THREAD

**Issue by Koushikphy** [sharkdp/fd#1040]
**What version of `fd` are you using?**
8.4.0

Is there a way to show the files found by `fd` as a tree structure instead of just a list?

**Comment by sharkdp** [comment]
https://github.com/sharkdp/fd#printing-the-output-as-a-tree

**Comment by sharkdp** [comment]
That documentation is not competely up to date though. In the meantime, I have personally set
```
alias as-tree="tree --fromfile"
```
and use it like this:
```
fd rs | as-tree
```

**Comment by Koushikphy** [comment]
Okay that solves the question. Thanks

**Comment by sharkdp** [comment]
Let's reopen this so we don't forget to update the documentation
