### ISSUE TITLE
fd 8.4.0 run error

### ISSUE THREAD

**Issue by Trid-collab** [sharkdp/fd#1044]
I am running Ubuntu on WSL2 and installing packages with HOMEBREW. 

When I am installing fd with 'brew install fd', the installation is completed fine. 

However when I am trying to run fd I am getting the following error. 
'home/linuxbrew/.linuxbrew/bin/fd: cannot execute binary file: Exec format error'

I am not facing issues when I am installing other packages like 'midnight commander'

I am not sure what am I missing here.

**Comment by tavianator** [comment]
Strange.  What's the output of

    file /home/linuxbrew/.linuxbrew/bin/fd

**Comment by Trid-collab** [comment]
The output is as follows:

/home/linuxbrew/.linuxbrew/bin/fd: symbolic link to ../Cellar/fd/8.4.0/bin/fd

**Comment by Trid-collab** [comment]
Issue was resolved with help from BREW forum. The issue was with the WSL version. It seems this issue comes up with WSL 1 and not with WSL2. When upgraded to WSL2 it resolved.

@tavianator  Thank you too for for your support
