### ISSUE TITLE
I think I find some bugs about regular-expression.

### ISSUE THREAD

**Issue by GavinGuan24** [sharkdp/fd#1045]
**What version of `fd` are you using?**
[8.4.0]

I'm working on my MacOS with ZSH `zsh 5.7.1 (x86_64-apple-darwin19.0)`.
You can see that.

# '.*' is not working

```sh
$ fd '.*crit.*antd'
pay/crit/crit-web/src/main/antd/src/style/crit-antd.less
$ fd 'pay.*crit.*antd'
$
```

The regular expression `.*crit.*antd` is working, but not `pay.*crit.*antd`

# '/$' is not working

```sh
$ fd -td antd | grep crit
./pay/crit/crit-web/src/main/antd/
$ fd 'pay.*crit.*antd/$'
$
$ fd antd$
pay/crit/crit-web/src/main/antd/
$ fd 'antd/$'
$
```

Why dose fd print '...antd/' with a slash ?
I see, there should be print '...antd' when fd receive argument 'antd$'.

**Comment by tmccombs** [comment]
The trailing slash is the same thing. The filename doesn't include the trailing slash, that is just a display thing, to indicate it is a directory.

`fd -td 'antd$'` should do what you want. (Or match the full path with -p)

**Comment by GavinGuan24** [comment]
'/$' is not important thing, I just wanna know why '.*' is not working.🤔

**Comment by sharkdp** [comment]
See the answer by @lespea

**Comment by GavinGuan24** [comment]
```sh
-p, --full-path                    Search full abs. path (default: filename only)
-t, --type <filetype>              Filter by type: file (f), directory (d), symlink (l), executable (x), empty (e), socket (s), pipe (p)
```

Thanks you all. I got it. Option `-p` is great.
There is a difference in understanding about `fd` 's behavior pattern.
That's why I open this issue.
