### ISSUE TITLE
Ambiguity in piped vs not piped output

### ISSUE THREAD

**Issue by stdedos** [sharkdp/fd#1046]
**What version of `fd` are you using?**
[paste the output of `fd --version` here]
```
$ fd --version
fd 8.4.0
```

_A short journey_:

<details>
<summary><i>I am confused on why piped vs not piped output is different</i></summary>
Hmmm... Do I have other `.editorconfig` files I can reference for my new one?

```console
$ fd .editorconfig
$
```
WAT? 😕
(5 minutes) ... aaaah, okay, it's _a hidden file, and hidden files are not searched by default_:

```console
$ fd -H .editorconfig
kNBcDyXJi/ecRlRPv/BXM_Je/.rPDclZxNgYyr
XFxiJagnA/WJgbrTD/OiInoDSAgiINUnkk/.YZmDuFuCckIL
WIHkZjomi/yIqdYhH/rfdDVKTAUBWSiXAo/GfaHm/lFbq/.xIRDWCIvevaM
fFXOXmAWN/acInlfx/flMaBjiDVIYVYtBI/RsoTY/BbzL/bFr#OkB/zbHTfZ/ifKaY/SfUIW]iXniUyQ/.UgrGwPaQeGmV
.EzjFK/eNeAOoJwm/omvRBNUvZ5263.2/WQSEH/qlBKQv=DShLzMF/OjqIhM.GfUVw.dnXazN.DLIpSSPOdtxn.bVkXV.Gywp/
.EHDIh/wRWiXKLRB/levauwvgX9517.2/JrmiW/YUOpol~LuqpgqS/TojFxD.qwYdl.JEjimx.rKtTUXgepXFs.ZOpma.eIJR/onSvQh.oONnz.gwLsWe.YBfzuemHHpvL.sDbfk.mmnj}XcmJiJ:O.CRL
.iWbGU/bhMyenPRx/ymTRQutnp7866.6/Thawj/dcogoa%tLTmpLj/DKkGys.eRRii.CIdXph.rUtUHfPNGwzu.hKAKv.tHbJ/XSvwvG.TtCRa.iKGOlp.tGqEddLfvCKy.yeJGp.XtEj|JdVAdBg.tjjLfvx.MPsrbBppO.XHi
.zsAeh/ZcXjHpZXA/vVaFyYjIa7460.9/FTgNJ/bsqXby%nlcvMKY/XGLlCa.CMfCh.uSXfFl.pEzyalOgKxvy.HXOTU.wXrm/BpcSne.GjNMZ.rTSqyZ.NlBrgbPyWWrW.JBNTB.TGCK@SfGYrk.xLT
.LSaEq/INMPskppO/JgHjUtlOA9796.6/YqmAQ/wYqCpj,smjcPsb/MYvWBa.LJBtO.yuBOck.xtrLwWIfdigW.LhCyW.xQeL/TGgeon.rkLRD.qWOrwe.YBlrzbPqxjyr.LMrTm.UIUR(DZYvpjy.ADvUPBO}m.ZiL
.awHQa/VLuNyKFhc/bplIgFZBx6563.2/rThOI/EgJjtJ{KCgOMWK/DZrPqH.LCMVE.lODdEt.CsUdpdhPGYgS.zXLfV.gRxy/drCbol.yIjmn.HjSjFq.LhpJOjRJTgrU.vsBXZ.YXzY.GbSJMNQ.klQFcFO.eqr
...
$ fd -H .editorconfig | wc -l
233
$
```

😵 ... but hey, if I look closer, there are paths that _start with a dot_ (i.e. are hidden), and therefore "not mine". How about ...
```console
$ fd -H .editorconfig | grep -vP '^\.'
$
```
**WAT?** 🤯 

(15 minutes later) ... 
```console
$ fd -H .editorconfig | head
./kNBcDyXJi/ecRlRPv/BXM_Je/.rPDclZxNgYyr
./XFxiJagnA/WJgbrTD/OiInoDSAgiINUnkk/.YZmDuFuCckIL
./WIHkZjomi/yIqdYhH/rfdDVKTAUBWSiXAo/GfaHm/lFbq/.xIRDWCIvevaM
./fFXOXmAWN/acInlfx/flMaBjiDVIYVYtBI/RsoTY/BbzL/bFr#OkB/zbHTfZ/ifKaY/SfUIW]iXniUyQ/.UgrGwPaQeGmV
./.EzjFK/eNeAOoJwm/omvRBNUvZ5263.2/WQSEH/qlBKQv=DShLzMF/OjqIhM.GfUVw.dnXazN.DLIpSSPOdtxn.bVkXV.Gywp/
./.EHDIh/wRWiXKLRB/levauwvgX9517.2/JrmiW/YUOpol~LuqpgqS/TojFxD.qwYdl.JEjimx.rKtTUXgepXFs.ZOpma.eIJR/onSvQh.oONnz.gwLsWe.YBfzuemHHpvL.sDbfk.mmnj}XcmJiJ:O.CRL
./.iWbGU/bhMyenPRx/ymTRQutnp7866.6/Thawj/dcogoa%tLTmpLj/DKkGys.eRRii.CIdXph.rUtUHfPNGwzu.hKAKv.tHbJ/XSvwvG.TtCRa.iKGOlp.tGqEddLfvCKy.yeJGp.XtEj|JdVAdBg.tjjLfvx.MPsrbBppO.XHi
./.zsAeh/ZcXjHpZXA/vVaFyYjIa7460.9/FTgNJ/bsqXby%nlcvMKY/XGLlCa.CMfCh.uSXfFl.pEzyalOgKxvy.HXOTU.wXrm/BpcSne.GjNMZ.rTSqyZ.NlBrgbPyWWrW.JBNTB.TGCK@SfGYrk.xLT
./.LSaEq/INMPskppO/JgHjUtlOA9796.6/YqmAQ/wYqCpj,smjcPsb/MYvWBa.LJBtO.yuBOck.xtrLwWIfdigW.LhCyW.xQeL/TGgeon.rkLRD.qWOrwe.YBlrzbPqxjyr.LMrTm.UIUR(DZYvpjy.ADvUPBO}m.ZiL
./.awHQa/VLuNyKFhc/bplIgFZBx6563.2/rThOI/EgJjtJ{KCgOMWK/DZrPqH.LCMVE.lODdEt.CsUdpdhPGYgS.zXLfV.gRxy/drCbol.yIjmn.HjSjFq.LhpJOjRJTgrU.vsBXZ.YXzY.GbSJMNQ.klQFcFO.eqr
$
```

![wat wat wat](https://user-images.githubusercontent.com/81555/47361982-05028300-d6dc-11e8-8b37-b4321bed083c.jpg)
</details>

_I maybe get the reasoning_ behind this option, however, I think it's counter-intuitive (for me) to not be able to _parse_ things the way I am seeing them (unless I specifically `-print`, `-print0`, etc ...).

Is there any way I can reconcile things for myself?

It seems that `--strip-cwd-prefix` helps me do what I want, but then it's annoying to remember to type that as well all the time (and then `-H`, and then _sometimes_ `--glob` etc) ... 
Is there a config file that I can use for this purpose (instead of an alias hidden somewhere)?

**Comment by tavianator** [comment]
Right, this was kind of discussed in https://github.com/sharkdp/fd/issues/760, but not emphasized too much.  I'm very sympathetic to this:

```console
$ fd pattern
a/path/matching/pattern
$ fd pattern | grep '^a/path'
$ # ???
```

See https://github.com/sharkdp/fd/issues/362 for previous discussion about a config file.  Right now there isn't one.  A shell alias might be the best alternative.

**Comment by sharkdp** [comment]
> Right, this was kind of discussed in #760, but not emphasized too much. I'm very sympathetic to this:
> 
> ```
> $ fd pattern
> a/path/matching/pattern
> $ fd pattern | grep '^a/path'
> $ # ???
> ```

I also agree. This is not good. Do we want to change the behavior (again)? I'd hate to include the `./` part in the interactive output :slightly_frowning_face:.

In the past, I have strictly argued against a config file for `fd`. And think I would still like to avoid it. But if we're talking about purely "cosmetical" things (e.g. color settings, precise shape of the *interactive* output), I might be convinced to re-think my position :smile:.

**Comment by tavianator** [comment]
My preference would be to disable the `./` in piped output by default.  It doesn't fully address the security issues anyway since newlines in paths are still an issue (`./foo\n--dangerous-option`).  Most pipes are not to `xargs` IMO.

I would keep the leading `./` in `-0` mode.

**Comment by sharkdp** [comment]
That sounds like a very good idea. It would be (another) breaking change, but I think I'm also in favor of doing that.

FYI: @jcaplan @ykonstant1

**Comment by tavianator** [comment]
At least it's only breaking for one or two releases?

**Comment by tmccombs** [comment]
That seems ok to me too.
