### ISSUE TITLE
can't get correct character output format on windows

### ISSUE THREAD

**Issue by lh1705** [sharkdp/fd#1047]
**What version of `fd` are you using?**
[paste the output of `fd --version` here]
```pwsh
[06/22 21:17] > fd --version
fd 8.4.0

[06/22 21:17] > gin | select OsVersion

OsVersion
---------
10.0.19044

[06/22 21:18] > $PSVersionTable.PSVersion | select Major, Minor, Patch

Major Minor Patch
----- ----- -----
    7     2     4
```

I want to get the ouput result of `fd` by `|` or `\` which included Chinese character, but the truth that I can't get the correct character format which I expected. It likes below:
```pwsh
[06/22 21:25] > fd 测试
测试
测试-01
测试-02

[06/22 21:26] > fd 测试 | scb
[06/22 21:26] > gcb
.\娴嬭瘯
.\娴嬭瘯-01
.\娴嬭瘯-02

[06/22 21:27] > fd 测试 > 1
[06/22 21:27] > cat 1
.\娴嬭瘯
.\娴嬭瘯-01
.\娴嬭瘯-02
```

How can I do? Thanks.

**Comment by tavianator** [comment]
So 测试 is `\u6D4B\u8BD5` and 娴嬭瘯 is `\u5A34\u5B2D\u762F`.  It looks like when `fd` is piped to something else, it's getting treated as Code Page 936 instead of Unicode

```console
$ printf '测试' | xxd
00000000: e6b5 8be8 af95                           ......
$ printf '娴嬭瘯' | iconv -f utf-8 -t cp936 | xxd
00000000: e6b5 8be8 af95                           ......
```

I don't really know enough about Windows I/O to know why that's happening though.

**Comment by lh1705** [comment]
@tmccombs, @tavianator 

I'm sorry to see the reply today. The question cased by system character encoding.
```pwsh
[06/26 13:00] > chcp
活动代码页：936
```
When I enabled utf-8 on windows, everything is ok!
```pwsh
[06/26 13:01] > chcp
Active code page: 65001

[06/26 13:02] > fd 测试
测试.md
```
