### ISSUE TITLE
Version 8.4.0 fails to build for 'armv5te-unknown-linux-gnueabi'

### ISSUE THREAD

**Issue by hgy59** [sharkdp/fd#1049]
Seems to be an issue with rust compiler an I have created an issue there:
https://github.com/rust-lang/compiler-builtins/issues/420#issuecomment-1165374744

Anyway version 8.3.2. successfully builds for 'armv5te-unknown-linux-gnueabi'.

**Comment by tmccombs** [comment]
Thanks for mentioning the issue on the rust compiler project.

**Comment by hgy59** [comment]
This works with the hotfix from https://github.com/rust-lang/compiler-builtins/issues/420#issuecomment-1335159456
for fd 8.4.0 ... 8.7.1

```
ENV += RUSTFLAGS="-Clink-arg=-Wl,--allow-multiple-definition"
```
