### ISSUE TITLE
-t executable flags can't show windows executable 

### ISSUE THREAD

**Issue by xBLACKICEx** [sharkdp/fd#1051]
### `-t executable` flags can't show windows executable 

![图片](https://user-images.githubusercontent.com/51036094/175789762-8fb2d8c8-1208-48de-9893-70cbc0ee285a.png)

**Comment by tavianator** [comment]
Indeed: https://github.com/sharkdp/fd/blob/f227bb291ae9e5890309bea45e55df2795441656/src/filesystem.rs#L49-L52

We could use https://crates.io/crates/faccess for this, since the [implementation](https://github.com/Freaky/faccess/blob/d7f2b450862281e6e842b6cec02730572e53a5ae/src/lib.rs#L126-L375) is pretty long.

**Comment by sharkdp** [comment]
Sounds good to me, if this dependency is reasonable in terms of code size / compile time. Or would we put it behind a `cfg(windows)` and use our own implementation for non-Windows systems?

**Comment by sharkdp** [comment]
I remember we had a similar discussion concerning "hidden" files on Windows. If I recall correctly, Windows has some notion of hidden files that also involves filesystem attributes?

**Comment by tavianator** [comment]
> Sounds good to me, if this dependency is reasonable in terms of code size & compile time. Or would we put it behind a `cfg(windows)` and use our own implementation for non-Windows systems?

It would technically be a breaking change on Unix.  `-t x` looks at permission bits only, while `faccessat()` checks if the current user actually has permissions.  So a mode 700 file owned by someone else is `-t x` but not `-executable` according to `find`.  Maybe it's okay to change this though?

**Comment by sharkdp** [comment]
> So a mode 700 file owned by someone else is `-t x` but not `-executable` according to `find`. Maybe it's okay to change this though?

Oh - I never realized this! I would be in favor of making this compatible with `find`. What do you think?

I guess it would come at the cost of an additional syscall, i.e. with some runtime overhead?
