### ISSUE TITLE
Is there any way to get the same coloring as fd on a user-provided list of paths?

### ISSUE THREAD

**Issue by ckp95** [sharkdp/fd#1058]
I have a script that uses fd in an interactive setting. The colorized output is very useful for legibility when reading through long lists of file paths. However, the file paths aren't always generated from fd. Some come from elsewhere (e.g. read in from a file). I would like the other paths to have the same coloring scheme as fd's, so they look consistent when displayed to the user. Is there a common library I can use for this? Or some way I can pass fd a list of file paths, and it will do nothing except echo them back, but colorized as they would normally be?

**Comment by tavianator** [comment]
https://github.com/sharkdp/lscolors provides a tool that does exactly that :)

```console
$ cargo install lscolors
$ fd >files
$ lscolors <files
./CHANGELOG.md
./CONTRIBUTING.md
...
```

**Comment by ckp95** [comment]
Oh great, thankyou!
