### ISSUE TITLE
can fd skip worktrees?

### ISSUE THREAD

**Issue by FelipeLema** [sharkdp/fd#1059]
How can I tell `fd` to _not_ search worktrees ("don't search `WT` after I've done `git worktree add WT`")

**What version of `fd` are you using?**

`fd 8.3.2`

**Comment by tavianator** [comment]
`fd` doesn't support this directly.  I don't think `git` itself does either.  But here's a potential solution that works for both:

```console
tavianator@tachyon $ mkdir worktrees
tavianator@tachyon $ echo '*' >worktrees/.gitignore
tavianator@tachyon $ git worktree add worktrees/WT
Preparing worktree (new branch 'WT')
HEAD is now at ...
tavianator@tachyon $ fd | grep WT
tavianator@tachyon $
```

**Comment by FelipeLema** [comment]
yup, it seems that `git` hasn't dealt with these corner cases directly ("searching / grepping should include worktrees"). Maybe a dev's flow is supposed to be either worktree-free or worktree-only ? 

thx for the answer. closing.
