### ISSUE TITLE
fd failed to install, please install it again

### ISSUE THREAD

**Issue by Proteinlzl** [sharkdp/fd#1070]
I installed `fd` with `apt install fd-find`
When I call `fd`, there is only the following prompt.
```
fd failed to install, please install it again
```

`fdfind` can be used normally
Here are the details
```
root@08614f5be1cc:~# apt install fd-find
Reading package lists... Done
Building dependency tree
Reading state information... Done
fd-find is already the newest version (7.4.0-2build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@08614f5be1cc:~# fd
fd failed to install, please install it again
```

I used `WSL` to install it.
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```
I have reinstalled it repeatedly and I used `apt install` and `apt dpkg`, but they didn't work.

I noticed that there was a precedent in the previous issue, but he just upgraded Ubuntu, the problem suddenly disappeared.
Also, there is no useful information in the search engine.
Thank you very much for taking time out of your busy schedule to help me

**Comment by Proteinlzl** [comment]
I used `scoop` on `Windows`, `fd` worked, but `fdfind` didn't.
Here are the details
```
PS C:\Windows\system32> fd -V
fd 8.4.0
PS C:\Windows\system32> fdfind
fdfind : 无法将“fdfind”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径
正确，然后再试一次。
所在位置 行:1 字符: 1
+ fdfind
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (fdfind:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32>
```
I wonder why.

**Comment by tavianator** [comment]
Package and binary names are inconsistent on Debian/Ubuntu, and unfortunately it's out of our control.  See https://github.com/sharkdp/fd/issues/1009 for more details, especially this comment: https://github.com/sharkdp/fd/issues/1009#issuecomment-1120226638.
