### ISSUE TITLE
please also provide a release in .rpm format

### ISSUE THREAD

**Issue by uli42** [sharkdp/fd#1071]
Looking at the provided tarballs there not many files so a rpm suitable for multiple distributions should be possible.

**Comment by tmccombs** [comment]
I'm not very familiar with how to create an RPM package. Would you be wiling to make PR to a add creating an rpm package to the github actions?

**Comment by uli42** [comment]
I am not very familiar with the GitHub actions...

It's vacation time but after that I have a look at that

Thayne McCombs ***@***.***> schrieb am Fr., 29. Juli 2022,
18:05:

**Comment by sharkdp** [comment]
Which distribution are you on? Some RPM-based distributions like Fedora are already supported via the official package managers.

**Comment by uli42** [comment]
Rhel7/8  (including CentOS and rocky)

David Peter ***@***.***> schrieb am Mi., 3. Aug. 2022, 08:42:

**Comment by sebma** [comment]
I also use CentOS 7 and RockyLinux 8 (soon 😄 ).

**Comment by sharkdp** [comment]
I'm going to close this. I don't really want to maintain an RPM package in this repository.
