### ISSUE TITLE
"Command not found" error message could be improved

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#1083]
Since fd 8.4, we show this error message:

```
▶ fd foo -X non-existent
[fd error]: Command not found: Command { inner: "non-existent" "./foo", remaining_argument_length: 2079626 }
```
which is confusing for the average user.

The reason for that is the usage of [`argmax::Command`](https://docs.rs/argmax/latest/argmax/struct.Command.html) instead of `std::process::Command`. This should probably be fixed by a custom `Debug` `impl` for  `argmax::Command`, instead of using `#[derive(…)]`. This could then delegate to the `Debug` implementation of the inner `std::process::Command`, to maintain maximum compatibility, even in debug prints.

An even better option might be to not rely on debug formats at all and implement a proper formatting function.

**Comment by fprasx** [comment]
I can give this a crack! Looking at `argmax::Command`, it's API doesn't expose the underlying `std::proces::command` at all, so I'm not sure how to even print something like the name without using the complete `Debug` impl `argmax` provides.
