### ISSUE TITLE
Cannot use the -p flag to filter out directories through regex

### ISSUE THREAD

**Issue by gamife** [sharkdp/fd#1091]
**What version of `fd` are you using?**
fd --version
fd 8.4.0

When I use the `-p` flag to search a `directory` by regular matching, the `.*/$` expression does not take effect. But the directories in the return result end in `/` (e.g.: `dir/`), which confused me.

**Comment by tmccombs** [comment]
The "/" at the end is not actually part of the path. It is added on to the output as a way of indicating that the entry is a directory.

**Comment by sharkdp** [comment]
You can, however, use `--type directory` (or `-td` in short) to only match on directories.

**Comment by tmccombs** [comment]
I'm going to close this, because I don't think there is anything that needs to be done here.
