### ISSUE TITLE
Stdout missing when used with watchexec

### ISSUE THREAD

**Issue by SichangHe** [sharkdp/fd#1105]
I have the following script:
```shell
fd -t f -e c -x \
watchexec -rp -w {} gcc \
-- -g -std=c17 -o {.} {}
```

which should recompile the C program when any changes.

It does compile them. For example, if I delete a binary and save the corresponding C file, the binary comes back.

However, if the compilation fails, the error message is not shown. In fact, the stdout is not piped correctly even if I use `echo` instead:
```shell
fd -t f -e c -x \
watchexec -rp -w {} echo {}
```

The above script produces no output when the given files are changed.

However, if I only use either `fd` or `watchexec`, the output is shown.

Any ideas why this happens? Thanks in advance.

Environment:
```shell
❯ fd --version
fd 8.4.0
❯ uname -a
Darwin network_host 21.6.0 Darwin Kernel Version 21.6.0: _time; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 arm64
```

**Comment by sharkdp** [comment]
> Any ideas why this happens?

Yes. `fd -x` captures all output until the process ends. And `watchexec` does not end. The idea behind this is that we don't want the output of a `fd -x` call to be all messed up because we are running several programs in parallel.

You approach is also problematic because we use a thread pool and only execute N tasks at once, i.e. this will only work for a small number of files.

**Comment by SichangHe** [comment]
I see, `fd` is not intended to do this. I should simply watch each file.

**Comment by tmccombs** [comment]
Maybe you could create a single `watchexec` process that listens on all the files you care about (which could be generated using fd), and use a command or script that uses the environment variables provided by watchexec to decide which files to compile?

**Comment by SichangHe** [comment]
> Maybe you could create a single `watchexec` process that listens on all the files you care about (which could be generated using fd), and use a command or script that uses the environment variables provided by watchexec to decide which files to compile?

That's exactly what I need! The problem was, I didn't know that I need to call a separate program for it to not use the parent program's env that does not have the said variables.

So, the solution is:

`./build.sh`
```shell
target=$WATCHEXEC_COMMON_PATH/$WATCHEXEC_META_CHANGED_PATH
gcc -fdiagnostics-color=always -g -o ${target%.*} $target
```

`./watch_build_all.sh`
```shell
watchexec -rp -e c ./build.sh
```

Thank you @sharkdp @tmccombs!
Steven Hé (Sīchàng)
