### ISSUE TITLE
Cannot find an obvious way to abbreviate the listing of home directory files to show `~` instead of the full path

### ISSUE THREAD

**Issue by ghost** [sharkdp/fd#1107]
Using `fd` 8.4.0 and I want to just abbreviate the output getting fed into my FZF to not show the full home directory path but rather abbreviate the outputs with `~` instead. 

I would like this:
`fd --type file -HL -i -p . $HOME`

to produce this:
`~/<filepath>`

**Comment by sharkdp** [comment]
There is no way to do this currently.

**Comment by tmccombs** [comment]
You could possibly use sed or similar to replace your full home directory path with "~"

**Comment by tavianator** [comment]
`fd | sed "s|^$HOME|~|"` should work, as long as your `$HOME` doesn't contain any regex special characters :)
