### ISSUE TITLE
Allow dot "." to match newlines by default

### ISSUE THREAD

**Issue by iology** [sharkdp/fd#111]
It may seems dangerous to include newlines in the output, though there is an option `-0, --print0` to help.

But even if the so called "dot-all" feature is disabled, we still can match those files with empty pattern "", `^`,  `[^/]*`, etc.

**Comment by iology** [comment]
Oh, it is already the default.

**Comment by iology** [comment]
Sorry, I must see something wrong. Reopened.

**Comment by sharkdp** [comment]
I'm glad that I've never experienced a file with a newline in the name, but I think we should enable this, as you said. It's better to show these results in a potentially confusing way than to not show them at all.

Note that this feature can be enabled via `(?s)`:
``` bash
> ls
'a'$'\n''b'

> fd 'a.b'

> fd '(?s)a.b'
a
b
```

This should be easy to implement via [`RegexBuilder::dot_matches_new_line`](https://doc.rust-lang.org/regex/regex/struct.RegexBuilder.html#method.dot_matches_new_line).

**Comment by iology** [comment]
Ok, I included the patch in #96.
