### ISSUE TITLE
Getting random "thread '<unnamed>' panicked at 'assertion failed"

### ISSUE THREAD

**Issue by hyperknot** [sharkdp/fd#1113]
**What version of `fd` are you using?**
fd 8.4.0

Brand new Macbook M1, installed yesterday with `brew install fd`.

I'm getting randomly the following exception:

```
zsmac16 user ~/Documents $ fd syncthing
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `105553171240160`,
 right: `0`: This is a known bug in the Rust standard library. See https://github.com/rust-lang/rust/issues/39364', /private/tmp/rust-20220304-34642-f8s218/rustc-1.59.0-src/library/std/src/sync/mpsc/shared.rs:251:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `105553171240160`,
 right: `0`', /private/tmp/rust-20220304-34642-f8s218/rustc-1.59.0-src/library/std/src/sync/mpsc/shared.rs:497:9
```

Then I re-run the same command immediately and everything is OK.

Is this related to homebrew install or something else?

**Comment by tavianator** [comment]
Looks like https://github.com/sharkdp/fd/issues/1060, AKA https://github.com/rust-lang/rust/issues/39364

**Comment by hyperknot** [comment]
Anything I can do on my end? Do you think downloading the binary from Releases would fix it?

**Comment by tmccombs** [comment]
There's unlikely anything you can do, except maybe helping to get #933 merged. But I don't have any concrete steps on how to do that. 

Although, since this is a race condition, retrying the comand would likely succeed.
