### ISSUE TITLE
can't search vcs directory

### ISSUE THREAD

**Issue by xenoterracide** [sharkdp/fd#1116]
So, I'm trying to find which repository locally has a certain origin. Seems `fd` can't search the repo itself though. I would expect these lists to be equivalent.

```
❯ fd --no-ignore --glob config
PPM/api/config/
brix-git/brix/config
ppm-orig/api/config/
❯ find . -name config
./pm/backend/.git/config
./pm/architecture/.git/config
./aur/log4net/.git/config
./blog/.git/config
./PPM/.git/config
./PPM/api/config
./brix-rust/.git/config
./brix-git/.git/config
./brix-git/src/brix/.git/config
./brix-git/brix/config
./ppm-orig/.git/config
./ppm-orig/api/config
./bygger/.git/config
```

**Comment by tavianator** [comment]
Did you try `-H`?

**Comment by xenoterracide** [comment]
No, that appears to work. I forgot the fd ignores hidden files as well as ignored files. Fun features but I question if they shouldn't be inverted.
