### ISSUE TITLE
scoop can search fd but cannot install fd

### ISSUE THREAD

**Issue by anglehome** [sharkdp/fd#1140]
**What version of `fd` are you using?**
[paste the output of `fd --version`    

<img width="692" alt="2" src="https://user-images.githubusercontent.com/48746111/196380880-09f48b46-4908-481d-af35-f034116ac731.png">

**Comment by tmccombs** [comment]
https://github.com/sharkdp/fd/releases/download/v8.4.0/fd-v8.4.0-x86_64-pc-windows-msvc.zip is the correct url. Maybe this is a problem with scoop?

**Comment by sharkdp** [comment]
Please report this in the scoop issue tracker.
