### ISSUE TITLE
fd eats all my memory

### ISSUE THREAD

**Issue by ngirard** [sharkdp/fd#1142]
Using fd 8.4.0 on Ubuntu 22.04.1 with Linux kernel 5.15.0.

Running a simple
```sh
fd -td data / > ~/data.lst
```
is enough for `fd` to eat all my memory, ultimately triggering the OOM killer.

**Comment by tavianator** [comment]
Probably the same issue as https://github.com/sharkdp/fd/issues/918

**Comment by ngirard** [comment]
Indeed, looks like so. I missed that issue before creating mine. Feel free to close it if you like.
