### ISSUE TITLE
Wrong syntax?

### ISSUE THREAD

**Issue by vbd** [sharkdp/fd#1143]
fd 8.2.1
Windows 10, CMD

`fd -tf vim -e txt -x copy {/} ziel`
[fd error]: Command not found: "copy" "vim.txt" "ziel"
[fd error]: Command not found: "copy" "vim2.txt" "ziel"

fd should find all files containing vim in the filename and extension txt => does work
-x copy {/} ziel should copy all results to directory ziel => does not work

Wrong syntax or does it have to do something with Windows?

**Comment by vbd** [comment]
`fd vim -e txt -x cmd /c copy {/} ziel` seems to work, but I don't undestand why cmd /c is necessary.

**Comment by tavianator** [comment]
Not a Windows expert but I assume that the `copy` command is built into the shell rather than being a standalone executable

**Comment by tmccombs** [comment]
That's my guess as well

**Comment by vbd** [comment]
Tested it with a stand-alone binary of lsd.exe and it works, without `cmd /c`. Thank you for the explanation.
