### ISSUE TITLE
The only choices for the new issue are "Feature request" and "Question"

### ISSUE THREAD

**Issue by ilyapopov** [sharkdp/fd#1161]
When creating an issue, the only choices one got are "Feature request" and "Question", which automatically attach corresponding labels and use templates. There in no "Bug repost" or generic issue. This is somewhat confusing. Is this intentional?

**Comment by sharkdp** [comment]
Thank you for reporting this. That is not expected. There seems to be a problem with the issue template: https://github.com/sharkdp/fd/blob/master/.github/ISSUE_TEMPLATE/bug_report.yaml

> There is a problem with this template
> 
> body[1]: Required attribute key label is missing. [Learn more](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#bodyi-required-attribute-key-value-is-missing).

**Comment by sharkdp** [comment]
Should be fixed now. Note that you can always open a generic issue using "Open a blank issue." (which is a bit hidden below the other options)

**Comment by ilyapopov** [comment]
Oh, I missed that generic issue link. 

Thank for fixing!
