### ISSUE TITLE
no artifacts for v8.5.3?

### ISSUE THREAD

**Issue by CrystalMethod** [sharkdp/fd#1180]
Regarding https://github.com/sharkdp/fd/blob/master/CHANGELOG.md version v8.5.3 was released some days ago. But there are no artifacts to be found for v8.5.3?

**Comment by sharkdp** [comment]
Thanks for mentioning it. The release was still in draft mode (FYI @tmccombs) and only visible to maintainers (I guess), which is why I didn't notice it:

![image](https://user-images.githubusercontent.com/4209276/203144783-b1ddc5c6-52b8-48c3-8a3a-3a9d0f57fdaa.png)

It should now be public.

**Comment by tmccombs** [comment]
Whoops.
