### ISSUE TITLE
[BUG] The issue with starting dots is still there!

### ISSUE THREAD

**Issue by honzajde** [sharkdp/fd#1182]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

For example: `fd -0 -d1 -tf .`

outputs paths starting with `./`

This is different from `fd -d1 -tf .` which is now fixed (no starting dot)

```
$ fd --version
fd 8.5.3
```

### Describe what you expected to happen:

outputs paths should always start without `./` (unlike find)

### What version of `fd` are you using?

fd 8.5.3

### Which operating system / distribution are you on?

```shell
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

Linux 5.4.0-132-generic x86_64
```

**Comment by tavianator** [comment]
This is on purpose.  From `fd --help`:

> ```
>       --strip-cwd-prefix
>           By default, relative paths are prefixed with './' when -x/--exec, -X/--exec-batch, or
>           -0/--print0 are given, to reduce the risk of a path starting with '-' being treated as a
>           command line option. Use this flag to disable this behaviour.
> ```

**Comment by honzajde** [comment]
@tavianator @sharkdp  I should have read the doc! However, I think, the switch to "more safe" behavior is not logical in this case. I only want the paths to be separated by \0. I am not using --exec. Am I missing anything about how bash/zsh/sh works?

**Comment by tmccombs** [comment]
A common use case for using -0 is to pass to xargs, where it is very much a concern.

**Comment by honzajde** [comment]
Okey, the switch is valid. Although, there is another option to get comparable security by using ` -- ` before the paths.
I wish there was a shorter option then `--strip-cwd-prefix` to opt out...
