### ISSUE TITLE
zsh: command not found: fd

### ISSUE THREAD

**Issue by topmask** [sharkdp/fd#1193]
zsh: command not found: fd

what???????????

**Comment by Sun42** [comment]
Same issue after installing package fd-find (7.4.0-2ubuntu0.1) with apt
 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 fd-find amd64 7.4.0-2ubuntu0.1

**Comment by Sun42** [comment]
I have the same issue when installing from
http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 fd-find amd64 7.4.0-2ubuntu0.1

Installed the 8.5.3 version manually with dpkg and it works fine.

**Comment by topmask** [comment]
> 

thanks you

**Comment by tmccombs** [comment]
If you install from the ubuntu apt repo, the command is named `fdfind` instead of `fd`, because there was an existing command in another apt package that conflicted with the name `fd`. 

The debian package that is listed on the releases page uses the original `fd` name.

**Comment by topmask** [comment]
> 

I installed it on debian

fdfind command appears
fd cannot be used

**Comment by tmccombs** [comment]
You can create an alias or symlink from fd to fdfind. That is what I do on my Ubuntu computer.

**Comment by topmask** [comment]
> You can create an alias or symlink from fd to fdfind. That is what I do on my Ubuntu computer.

thank you.
