### ISSUE TITLE
[BUG] glob search is always case sensitive

### ISSUE THREAD

**Issue by JoopNL** [sharkdp/fd#1202]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

When performing a glob based search, the search is always case sensitive, despite the documentation saying otherwise. Also explicitly specifying -i (--ignore-case), the search is still case sensitive. Example:

```
$ ls
1.txt  2.TXT

$ fd txt
1.txt
2.TXT

$ fd *.txt
1.txt

$ fd -i *.txt
1.txt
```

Note: I'm not specifying -g to perform a glob based search, but it seems to handle this type of search as glob search by default (I don't know if this in the documentation, I didn't see it). In any case, when including the -g parameter in the last 2 examples, the results remain the same.

### Describe what you expected to happen:

The glob search is handled case **IN**sensitive. Example:

```
$ ls
1.txt  2.TXT

$ fd txt
1.txt
2.TXT

$ fd *.txt
1.txt
2.TXT

$ fd -i *.txt
1.txt
2.TXT
```

If this bug is fixed, make sure that -s (--case-sensitive) also still works with glob search. :)

### What version of `fd` are you using?

fd 8.5.3

### Which operating system / distribution are you on?

```shell
Linux 5.10.0-19-amd64 x86_64
Distributor ID: Alpine
Description:    Alpine Linux v3.17
Release:        3.17.0
Codename:       n/a
```

**Comment by tmccombs** [comment]
I think what is happening here is the '*' is getting expanded by your shell.

So it is actually running `fd 1.txt 2.TXT`.  Im not sure why youv aren't getting an error about 2.TXT not being a directory though. 

Try quoting the pattern and using -g:

```
fd -g '*.txt'
```

**Comment by JoopNL** [comment]
Yes, with that command it works correctly. And I see it also works correctly with double quotes: ```fd -g "*.txt"```, which I would not expect if shell expansion was causing this bug/behaviour. So, not entirely sure if that's the cause, but this is a solution in any case. Thanks!

**Comment by tavianator** [comment]
* is not expanded by the shell in either single or double quotes, so they will work equally well
