### ISSUE TITLE
Feature Request: binary and text file types 

### ISSUE THREAD

**Issue by EvanCarroll** [sharkdp/fd#1208]
Currently you can specify `-t f` to find files. It would be nice if this was slightly more powerful though and let us do

* `-t ft`: text files (non-binary)
* `-t fb`: binary files

This would answer a need [many people have](https://stackoverflow.com/questions/29516984/how-to-find-binary-files-in-a-directory). The current UX provided by GNU Find is really garbage here for doing the simple, so `fd` can do something better.

The logic behind telling if something is binary is actually rather complex, so I can understand push back here, but we could simply use `file`'s `src/encoding.c` build the object and link it in. This would provide text-identification for

* Unicode text, UTF-7
* ASCII
* Unicode text, UTF-8 (with BOM)
* Unicode text, UTF-8
* Unicode text, UTF-32, little-endian
* Unicode text, UTF-32, big-endian
* Unicode text, UTF-16, little-endian
* Unicode text, UTF-16, big-endian
* iso-8859-1
* unknown-8bit
* ebcdic

And if none of those, the default is `binary`.

This would be useful for me for example because I'm trying to find all `.so` files on my system that are binary.

**Comment by tavianator** [comment]
One thing that might help is to use `grep`'s binary file detection.  This command will list only (non-empty) text files:

```console
user@host$ fd -t f -X grep -Il .
```
