### ISSUE TITLE
Shell completions OUT_DIR

### ISSUE THREAD

**Issue by ilovezfs** [sharkdp/fd#121]
Setting OUT_DIR doesn't seem to have any effect on where the completions files are created. Am I doing something wrong?

**Comment by sharkdp** [comment]
My guess is that you are running something like `OUT_DIR=/tmp cargo build`. This doesn't work because cargo sets the `OUT_DIR` environment variable on its own.

**Comment by ilovezfs** [comment]
@sharkdp ah OK. So how do we know what directory to find them in programmatically?

**Comment by sharkdp** [comment]
Unfortunately, the name of the build directory has a name that is non-constant. It's something like
```
target/release/build/fd-find-1aca9d9a9b3c7e7e/out
```
where the `1aca9d9a9b3c7e7e` part can change. In the appveyor script, I'm using this for deployment:
https://github.com/sharkdp/fd/blob/e0eab07881263108ce35f75b3507a21fb7aa19ad/appveyor.yml#L60


So using sth. like
``` sh
cp target/release/build/fd-find*/out/fd.bash-completion
```
should be fine on Unix systems.

**Comment by ilovezfs** [comment]
@sharkdp the context for my question is this pull request: https://github.com/Homebrew/homebrew-core/pull/19237

The user is resorting to Pathname.glob to find them, which is basically the same as what you're suggesting, and which one of our maintainers is understandably balking at.

Would you be willing to move that logic into some sort of install script? It looks like FreeBSD even got this working for ripgrep with a standard `make install` target:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220361
https://bugs.freebsd.org/bugzilla/attachment.cgi?id=184138&action=diff

**Comment by sharkdp** [comment]
It seems like they are modifying the `build.rs` script :smile:.

I think we could simply add support for overwriting the output directory in the `build.rs` script.. possibly with a different environment variable?

**Comment by sharkdp** [comment]
@ilovezfs The fix by @ImbaKnugel should be available for the next release.

**Comment by ilovezfs** [comment]
Nice, thanks!
