### ISSUE TITLE
Find based on file checksum (e.g. MD5, SHA-1, etc.)

### ISSUE THREAD

**Issue by frazar** [sharkdp/fd#1210]
First of all, thanks to the author and all contributors for this super handy utility.

An interesting option would be to be able to find the locations of files that match a target MD5 checksum (or SHA-1, etc).

Example:
```
fd --md5 dead385486c74f347b6e67f36f36beef
```

The implementation could be a bit more efficient than [just running find + md5sum](https://superuser.com/questions/653185/finding-a-file-by-md5sum) since it could filter out files early in the hash computation process by checking, for example, that the first character of the checksum does not match the target one.

**Comment by tavianator** [comment]
Comparing the checksums is probably 1,000 to 1,000,000 times faster than computing them in the first place.  Not worth it just to save a nanosecond or so

**Comment by frazar** [comment]
I see. Then there is no real reason to implement this, apart from providing a user shortcut. Closing the issue.
