### ISSUE TITLE
[BUG] test_type_executable failed on v2.6.0

### ISSUE THREAD

**Issue by kimw** [sharkdp/fd#1214]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

Command,

```bash
cargo test
```

Output,

```
failures:

---- test_type_executable stdout ----
thread 'test_type_executable' panicked at '`fd --type executable` did not produce the expected output.
Showing diff between expected and actual:
 executable-file.sh
+not-user-executable-file.sh
', tests/testenv/mod.rs:265:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_type_executable

test result: FAILED. 91 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.63s
```

### What version of `fd` are you using?

fd 8.6.0

### Which operating system / distribution are you on?

```shell
Linux 5.15.0-56-generic x86_64

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by tmccombs** [comment]
You aren't running this as root are you? If you create a file with mode 645, can you execute it in that environment?

**Comment by tmccombs** [comment]
The only way I can reproduce this behavior on my archlinux install is if I run it as root (actually I haven't actually run the test as root, but if I run `fd --type executable` on a file with permissions 645 as root, then it does list that file). We could maybe have a check in that test to exit early if it is run as root. Although, I would probably recommend against running these test as root anyway...

**Comment by kimw** [comment]
Yes, I did the `cargo test` as root. In fact, I did the `cargo test` in a docker container, as following commands:

```bash
docker rm -f xx
docker run --name=xx -d -t \
    -w /builds \
    -e DEBIAN_FRONTEND=noninteractive \
    -v cargo-registry:/usr/local/cargo/registry \
    rust:bullseye &&
docker exec -t xx wget -O fd-8.6.0.tar.gz https://github.com/sharkdp/fd/archive/refs/tags/v8.6.0.tar.gz &&
docker exec -t xx tar -xf fd-8.6.0.tar.gz &&
docker exec -t -w /builds/fd-8.6.0 xx cargo test
```

**Comment by tmccombs** [comment]
You could probably get the test passing by running the docker command with a --user option

**Comment by kimw** [comment]
Thanks for your detailed answers.

Yes, I can pass the test by using `--user`/`-u` option. e.g.,

```sh
docker rm -f xx
docker run --name=xx -d -t \
    -w /builds \
    -e DEBIAN_FRONTEND=noninteractive \
    -v cargo-registry:/usr/local/cargo/registry \
    rust:bullseye &&
docker exec -t xx wget -O fd-8.6.0.tar.gz https://github.com/sharkdp/fd/archive/refs/tags/v8.6.0.tar.gz &&
docker exec -t xx chown -R 1000 /builds &&
docker exec -t -u 1000 xx tar -xf fd-8.6.0.tar.gz &&
docker exec -t -u 1000 -w /builds/fd-8.6.0 xx cargo test
```

But if I do the test, for example in GitLab CI, the building process is always run in a docker container as root user. Could you please add "We could maybe have a check in that test to exit early if it is run as root" into TODO list? It must be very helpful to make the CI handling easier. (Currently I have to make a patch file to comment out https://github.com/sharkdp/fd/blob/v8.6.0/tests/tests.rs#L1214-L1219 temporary)
