### ISSUE TITLE
Is it necessary to put translated readme in other repos?

### ISSUE THREAD

**Issue by Luminous-Coder** [sharkdp/fd#1229]
The readme now has links to other repositories that contains translated readme. However, is it necessary to put only one readme file (and other assets actually) in a standalone repository rather than creating a `README-xx.md` in this one?

**Comment by sharkdp** [comment]
both is fine for me.

**Comment by Luminous-Coder** [comment]
Ok.
I just think that contributing to this project/repository in seperated repositories is kind of strange.
