### ISSUE TITLE
Pattern file

### ISSUE THREAD

**Issue by mbhall88** [sharkdp/fd#1245]
(Apologies if this has been address elsewhere, but I couldn't find anything in issues)

I have a list of 500 patterns I would like to match on. It would be great if I could pass a file of patterns (something like `-f` in ripgrep). 

I know I can pipe the results of searching anything (`.`) through ripgrep, but I then want to execute a command on them, so this becomes quite laborious.

**Comment by tavianator** [comment]
You can do this with ripgrep:

```console
$ fd -0 | rg -0 --null-data -f patterns.txt | xargs -0 echo
```

**Comment by mbhall88** [comment]
Yes, that's what I am currently doing, but thought I would request it as a feature as it's something I do quite a lot and having a pattern file in `fd` would allow me to do everything in one command rather than three pipes.

**Comment by sharkdp** [comment]
I don't see us adding support for that, sorry. Thank you for the request.
