### ISSUE TITLE
I can't search in all Directories recursively

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [sharkdp/fd#1257]
**What version of `fd` are you using?**
[paste the output of `fd --version` here]
`fd --min-depth 2  -t d node_modules`
![image](https://user-images.githubusercontent.com/45184918/219043484-dace5f8e-5cf6-4a5e-b5eb-e713090b739d.png)

**Comment by sharkdp** [comment]
please see the troubleshooting section in the README
