### ISSUE TITLE
fd not working with fzf Ctrl-T shortcut

### ISSUE THREAD

**Issue by Lobbelt** [sharkdp/fd#1258]
**What version of `fd` are you using?**
fd 8.6.0

I configured zsh to use fd for fzf by adding the following to .zshrc:

```
export FZF_DEFAULT_COMMAND='fd --type f --hidden'

export FZF_CTRL_T_COMMAND='$FZF_DEFAULT_COMMAND'
export FZF_ALT_C_COMMAND='fd --type d . --color=never --hidden'
```
The Alt-C command works perfectly well. However, whenever I try to use the Ctrl-T shortcut, fzf is telling me `(eval):1: command not found: fd --type f --hidden`. The thing is - that command also works just fine whenever I type it in manually, including when piping it into fzf. 

Does anyone have any idea what may be causing this?

**Comment by tmccombs** [comment]
It looks like maybe it is trying to find an executable with the name "fd --type f --hidden" instead of just fd

**Comment by sharkdp** [comment]
Or maybe fd only an alias in your shell?

**Comment by Lobbelt** [comment]
> Or maybe fd is only an alias in your shell?

No it's not, I'm on Arch Linux (and I double checked).

**Comment by tavianator** [comment]
Try

```
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```

instead (double quotes)

**Comment by Lobbelt** [comment]
> Try
> 
> ```
> export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
> ```
> 
> instead (double quotes)

This fixed it! Thanks so much.

**Comment by Lobbelt** [comment]
> Try
> 
> ```
> export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
> ```
> 
> instead (double quotes)

This fixed it, thanks so much!

**Comment by Lobbelt** [comment]
> Try
> 
> ```
> export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
> ```
> 
> instead (double quotes)

This fixed it, thank you very much!
