### ISSUE TITLE
[BUG] fd didn't find file in /opt/homebrew/ directory

### ISSUE THREAD

**Issue by snowshoes** [sharkdp/fd#1265]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

os: macOS Monterey v12.5
fd: v8.3.2

`fd` supposed to find all matched files given the simple pattern, and search directory, i.e.

`fd -i -F proxychains.conf /`

which gives me the result:
```
/System/Volumes/Data/usr/local/etc/proxychains.conf
/usr/local/etc/proxychains.conf
```
however, the most obvious matched file is neglected, it's the config file after installing `proxychains-ng` on macOS.

```
/opt/homebrew/etc/proxychains.conf
 5.7K Feb 26 00:51 proxychains.conf
```

even by using the following search pattern,

`fd -i -F proxychains.conf /opt/homebrew/`, which returns no value.

```
homebrew/etc on  stable
[I] ➜ fd -i -F proxychains.conf /opt

homebrew/etc on  stable
[I] ➜ fd -i -F proxychains.conf /opt/homebrew/

```

### Describe what you expected to happen:

expected:

find matched file given the pattern above in path `/opt/hombrew/etc`

### What version of `fd` are you using?

8.3.2

### Which operating system / distribution are you on?

```shell
Darwin 21.6.0 arm64
```

**Comment by tmccombs** [comment]
Did you look at the troubleshooting guide on the readme?

**Comment by snowshoes** [comment]
sorry to bother, I've read the troubleshooting section and the problem resolved, thanks !
