### ISSUE TITLE
Add option to quote pattern

### ISSUE THREAD

**Issue by lukenels** [sharkdp/fd#127]
To make it easy to to search for fixed pattern files, consider adding a flag such as `-q` or `--quote` to interpret the pattern as a literal string as opposed to a regex.

This way commands like `fd --quote 'test.c'` won't interpret the `.` as a regex wildcard.

**Comment by sharkdp** [comment]
I think this is very similar to (or would be possible with) #97?

**Comment by sharkdp** [comment]
@lukenels This is now supported via `--fixed-strings`/`-F`.

**Comment by lukenels** [comment]
Thanks @sharkdp !
