### ISSUE TITLE
[BUG] files ignored by -E can execute cmd by -X

### ISSUE THREAD

**Issue by moroal** [sharkdp/fd#1275]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

fd -E '*.bak' -X rg textInBak

### What version of `fd` are you using?

8.7.0

### Which operating system / distribution are you on?

```shell
win10 enterprise edition
22H2
19045.2604
Windows Feature Experience Pack 120.2212.4190.0
```

**Comment by tavianator** [comment]
I can't reproduce that with `echo`.  I think what's happening is you're feeding some directories to `rg` which then looks in them, not knowing about `fd`'s `-E`.  Try it with `-t f`.

**Comment by moroal** [comment]
Thank you very much, it is what you said, but how to use -t to exclude certain types of files?

**Comment by tmccombs** [comment]
you need both `-t f` and `-E`. `-t f` tells fd to only search files (not directories) and `-E *.bak` tells it to exclude files that end with '.bak'.

**Comment by moroal** [comment]
thanks
