### ISSUE TITLE
Provide -u / -uu flag

### ISSUE THREAD

**Issue by hktonylee** [sharkdp/fd#1277]
Hi team, `fd` is a really awesome tool. I have been using it everyday :) Thanks for all the hard work!

Now the problem is that, I also use `ripgrep`. They have a flag to search for `-I / --no-ignore` by `-u`, and search for hidden files `-H / --hidden` by `-uu`. (They also have `-uuu` to search for binary file but that doesn't apply to us)

 I think it is better to provide this flag in `fd` so as to reduce cognitive loading.

**Comment by hktonylee** [comment]
Ohh thank you! I am using Ubuntu 20.04 that's why I couldn't find in man-page. It is still using v7.4.0

**Comment by FlashSheridan** [comment]
A heads-up that in 8.4.0, `-u` means `--no-ignore --hidden`, but in 8.3.1, `-u` means `--no-ignore`, with “'-uu' is an alias for '--no-ignore --hidden'”.  This meant that instructions I’d written based on 8.4.0 missed important files in 8.3.1.

**Comment by sharkdp** [comment]
> A heads-up that in 8.4.0, `-u` means `--no-ignore --hidden`, but in 8.3.1, `-u` means `--no-ignore`, with “'-uu' is an alias for '--no-ignore --hidden'”. This meant that instructions I’d written based on 8.4.0 missed important files in 8.3.1.

Sorry for this. There was a long discussion about this in https://github.com/sharkdp/fd/issues/840. And it's mentioned in the release notes here: https://github.com/sharkdp/fd/releases/tag/v8.4.0

We generally really try hard not to introduce breaking changes like this.
