### ISSUE TITLE
No shell completions for fish

### ISSUE THREAD

**Issue by abhyuditjain** [sharkdp/fd#1278]
**What version of `fd` are you using?**
[paste the output of `fd --version` here]
```
❯ fd --version
fd 8.7.0
```

I installed it using `cargo install fd-find`.

I can't seem to find any `fd.fish` files after the package has been installed.

**Comment by tmccombs** [comment]
`cargo install` doesn't have a mechanism for copying over shell completion files. You'll need to copy over the files yourself, or install with a method thay does include the completion files.

**Comment by abhyuditjain** [comment]
Copy from where? I was trying to find the files. There aren't any in the source as well.

**Comment by tmccombs** [comment]
You can generate it with `fd --gen-completions=fish`

**Comment by abhyuditjain** [comment]
Oh. Thank you. That works for me!
