### ISSUE TITLE
Add option that displays configurations.

### ISSUE THREAD

**Issue by cohml** [sharkdp/fd#1280]
My `bat` config currently looks like this:

    $ cat ~/.config/bat/config
    --theme="TwoDark"
    --style=changes,header-filename,rule,snip
    --italic-text=always
    --pager="less --chop-long-lines --header=1 --line-num-width=0 --LONG-PROMPT --no-number-headers --RAW-CONTROL-CHARS --shift=4 --status-column --use-color --color=HGk --color=NGk"
    --wrap=never

Sometimes I want to remind myself what some of those fields are set to. So something like the following would be very handy:

    $ bat --config
    italic-text: always
    pager: less --chop-long-lines --header=1 --line-num-width=0 --LONG-PROMPT --no-number-headers --RAW-CONTROL-CHARS --shift=4 --status-column --use-color --color=HGk --color=NGk
    style: changes,header-filename,rule,snip
    theme: TwoDark
    wrap: never

Currently the quickest way to do this is the following, but it's unnecessarily involved:

    $ cat $(bat --config-dir)/config

Bonus points for coloring the names of the fields so that they stand out, `bat`-style.

Double bonus points for the ability to filter the output by named field, such as this:

    $ bat --config theme
    TwoDark

This option may have niche appeal, but would surely be straightforward to add.

If I can ever get around to learning Rust, I will volunteer 😳

**Comment by tavianator** [comment]
Did you mean to write this on the https://github.com/sharkdp/bat repo?

**Comment by cohml** [comment]
@tavianator D'oh! I did indeed.

I just had this thought for a feature, quickly Googled "sharkdp" (+ `bat`, at least I thought), but must tnot hve been paying attention.

I'll close this one and reopen in the `bat` repo. Thanks again.
