### ISSUE TITLE
[BUG] Incorrect usage of `std::process::Command` on Windows when checking for GNU `ls`

### ISSUE THREAD

**Issue by rmg-x** [sharkdp/fd#1291]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

When checking for "GNU ls" on Windows, the way `fd` attempts to run the command is incorrect.

Code in question:
https://github.com/sharkdp/fd/blob/15c795d2e1d7bc5cdca829315b3f37bd1b325928/src/main.rs#L389-L394

### Describe what you expected to happen:

I expect `fd` to use the `/C` argument to run commands on Windows, as seen in the [official Rust documentation for std::process::Command](https://doc.rust-lang.org/std/process/struct.Command.html).

When running the check, this method should probably use `powershell` instead of the command shell as its a modern equivalent that all modern versions of Windows ships with. Users are more likely to be using Powershell over cmd shell.

Microsoft is now using Powershell as the default command-line shell for File Explorer, [read more here](https://support.microsoft.com/en-us/windows/powershell-is-replacing-command-prompt-fdb690cf-876c-d866-2124-21b6fb29a45f).

I'm open to contributing a fix for this but wanted some opinions on how the shell should be handled before doing so. 

### What version of `fd` are you using?

8.6.0

### Which operating system / distribution are you on?

```shell
Windows 11
```

**Comment by rmg-x** [comment]
Just to add more information for the issue.

I'm using `uutils` for the GNU version of `ls`.
It's a cross-platform reimplementation of the GNU coreutils in Rust ([GitHub page](https://github.com/uutils/coreutils))

I did some work on my powershell profile to get the command working correctly:
```powershell
function CoreUtils-Ls() { coreutils ls @args }

Set-Alias -Name ls -Value CoreUtils-Ls -force -option 'Constant','AllScope'
```

**Comment by tmccombs** [comment]
> I expect fd to use the /C argument to run commands on Windows, as seen in the [official Rust documentation for std::process::Command](https://doc.rust-lang.org/std/process/struct.Command.html)

That example is invoking the `cmd` program and passing it a command with the `/C` option. In general that is not necessary. In this case, `fd` is executing the `ls` executable directly, not opening a shell and passing it an ls command. 

> wanted some opinions on how the shell should be handled before doing so

There isn't a shell currently being used here, and I don't think there really needs to be.

> I'm using uutils for the GNU version of ls

nitpick, but uutils is not GNU ls. It aims to be compatible with GNU ls, but it is an independent project.

Anyway for your use case , I think either of the folowing should work, although I don't use windows so I don't know for sure:

1. Create a symlink (or whatever the windows equivalent is) from "ls" to the coreutils binary that is on your PATH
2. Create a powershell script on your path named "ls" that simply runs `coreutils ls @args`

**Comment by rmg-x** [comment]
Yeah, that makes sense, thanks. 

I was trying to show file sizes in the `fd` output and it seems like the only way is through the `--list-details` option so I went down a rabbit hole of trying to get it to work.
