### ISSUE TITLE
Get file path with backslashes

### ISSUE THREAD

**Issue by bluedogtwo** [sharkdp/fd#1300]
**What version of `fd` are you using?**
[fd 8.7.0]

Is it possible to get the result paths with backslashes incase of problematic characters?

**Comment by tavianator** [comment]
What are you feeding the output to?  Exactly which characters need backslashes will be different between languages..  If it's bash, you could do

```console
$ fd
 /
 /j
!/
!/d
!-/
!-/e
(/
(/b
(-/
(-/c
)/
)/g
,/
,/f
-/
-/a
.../
.../h
[/
[/k
\/
\/i
$ fd -X bash -c 'printf "%q\n" "$@"' bash
./-
./-/a
./\(
./\(/b
./\(-
./\(-/c
./\!
./\!/d
./\!-
./\!-/e
./\,
./\,/f
./\)
./\)/g
./...
./.../h
./\\
./\\/i
./\ 
./\ /j
./\[
./\[/k
```

**Comment by robinshen36** [comment]
@algora-pbc attempt

This is exactly the kind of thing I enjoy working on.

Recently finished up something pretty similar.

First thing I'd do is reviewing the regex syntax, then build from there.

No idea what your usual rate is, but thinking $160-$280? Happy to discuss.

Hit me up if you want to chat through details.
