### ISSUE TITLE
How to pass options when always searching from a different directory?

### ISSUE THREAD

**Issue by faxotherapy** [sharkdp/fd#1311]
fd version: 8.7.0

I'l like fd to always search from the home directory (while excluding some other directories). I know I can set the following: `fd . $HOME`

Problem is I can no longer pass any options such as `--strip-cwd-prefix --follow --exclude .git`?

I tried `fd . $HOME --strip-cwd-prefix --follow --exclude .git` or `fd --strip-cwd-prefix --follow --exclude .git . $HOME`, but neither do seem to work.

**Comment by sharkdp** [comment]
> I tried `fd . $HOME --strip-cwd-prefix --follow --exclude .git` or `fd --strip-cwd-prefix --follow --exclude .git . $HOME`, but neither do seem to work.

What exactly is not working? What output do you get and what did you expect?


Not sure if related, but did you see the `--base-directory` option?

      --base-directory <path>
          Change the current working directory of fd to the provided path. This means that search
          results will be shown with respect to the given base path. Note that relative paths
          which are passed to fd via the positional <path> argument or the '--search-path' option
          will also be resolved relative to this directory.

**Comment by faxotherapy** [comment]
Hi, thanks for your reply. I solved the problem by removing `--strip-cwd-prefix` which was the culprit. I haven't found `--base-directory` option in the man page though. Interesting option.
