### ISSUE TITLE
Current setting in .travis.yml isn't using the TARGET env var for building the project

### ISSUE THREAD

**Issue by matematikaadit** [sharkdp/fd#132]
So I've been pondering the current [`.travis.yml`](https://github.com/sharkdp/fd/blob/8d85debc12631d47274da8305e710723aae5dc74/.travis.yml) setting. It has multiple item in the build matrix with different TARGET env var. But there's no usage of the TARGET implied anywhere. Reading [the documentation on building rust project on travis-ci.org](https://docs.travis-ci.com/user/languages/rust/) also confirm that the default "install" and "script" stage on Travis CI isn't using the TARGET var in any meaningful way, except setting it out in the build environment. Which of course, wont be picked up by `cargo build` if we not explicitly using it as the `--target` value.

Here some example how they're used in ripgrep repo,

[`ci/install.sh`](https://github.com/BurntSushi/ripgrep/blob/a98156e71cc2aefd2d3e18c76c6d09cc1ef8c5ac/ci/install.sh#L28)
```bash
install_standard_crates() {
    if [ $(host) != "$TARGET" ]; then
        rustup target add $TARGET
    fi
}
```
[`ci/script.sh`](https://github.com/BurntSushi/ripgrep/blob/a98156e71cc2aefd2d3e18c76c6d09cc1ef8c5ac/ci/script.sh#L19-L29)
```bash
run_test_suite() {
    cargo clean --target $TARGET --verbose
    cargo build --target $TARGET --verbose
    cargo test --target $TARGET --verbose
    # ...
}
```

If you're okay with my slow progress, I wanna submit a PR to solve this issue. Tho, if someone else interested in this, I'm okay with that. For reference here some minimal working example of `.travis.yml` setting for building rust for `x86_64` and `i686` target on linux.

https://github.com/matematikaadit/rust-travis-eureka/blob/e0abfbb4bf6bac0466b0549d7aa6b54e7af4b43c/.travis.yml

It targets:

- x86_64-unknown-linux-gnu
- x86_64-unknown-linux-musl
- i686-unknown-linux-gnu
- i686-unknown-linux-musl

on stable, beta, and nightly channels.

**Comment by sharkdp** [comment]
Thank you very much for reporting this. And also... :flushed:

> If you're okay with my slow progress, I wanna submit a PR to solve this issue. Tho, if someone else interested in this, I'm okay with that.

You are very welcome to submit a PR on this issue! Also, please work at your own pace (or rather, any pace you want).. there are no due dates or deadlines here :smile:
