### ISSUE TITLE
[BUG] `fd` is not in `PATH` after installing with `winget`

### ISSUE THREAD

**Issue by NikGovorov** [sharkdp/fd#1335]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

1. execute `winget install sharkdp.fd`
2. exit terminal
3. open terminal
4. run `fd`

Actual result: `fd.exe` is not in PATH

`~/AppData/Local/Microsoft/WinGet/Packages/sharkdp.fd_Microsoft.Winget.Source_8wekyb3d8bbwe` is in PATH, but `fd.exe` is located in `~/AppData/Local/Microsoft/WinGet/Packages/sharkdp.fd_Microsoft.Winget.Source_8wekyb3d8bbwe/fd-v8.7.0-x86_64-pc-windows-msvc`

### Describe what you expected to happen:

Expected result: `fd.exe` is in PATH

### What version of `fd` are you using?

fd 8.7.0

### Which operating system / distribution are you on?

```shell
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
```

**Comment by ysstudio22** [comment]
I had to manually add the path to the app in the Environmental Variables.  Once I added the path and restarted the terminal it worked.  Just leaving a comment for whomever may find this helpful.
