### ISSUE TITLE
Path should be escaped when running '-x cmd'

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#135]
This seems like a bug to me

``` bash
> touch 'file with spaces'

> fd -x 'ls "{}"'    # this is fine
file with spaces

> fd -x ls       
ls: cannot access 'file': No such file or directory
ls: cannot access 'with': No such file or directory
ls: cannot access 'spaces': No such file or directory
```

@mmstick - I'm mentioning you here just in case you are interested. I'm not trying to assign this to you.

**Comment by mmstick** [comment]
GNU Parallel also implements these flags for this use case -- quoting inputs. Not really a bug, but a convenience flag so you don't have to manually quote it yourself.

**Comment by mmstick** [comment]
The `--quote` flag, that is

**Comment by iology** [comment]
Why not quote it by default?

**Comment by mmstick** [comment]
@iology You can have an input that provides multiple arguments. In that case, you don't want quoting to happen.

**Comment by mmstick** [comment]
Although I guess when all of your inputs are files, it'd make sense to quote by default.

**Comment by sharkdp** [comment]
> Although I guess when all of your inputs are files, it'd make sense to quote by default.

Yes, I also think so. The flag might be useful for `parallel`, but it shouldn't be needed here.

**Comment by mmstick** [comment]
I'll have this fixed soon. Am going to look for a way of possibly optimizing my solution though. Best way to do this isn't to quote, exactly, but to escape special characters.

**Comment by mmstick** [comment]
Am going to convert that `paths` module into an `input` module that uses a state machine to generate input strings, only allocating as needed. Will ensure that the programmer doesn't forget to escape the input before using it, preventing a possible logic error.
