### ISSUE TITLE
[BUG] Doc comment for `ColorWhen` breaks completions for the fish shell

### ISSUE THREAD

**Issue by cstyles** [sharkdp/fd#1367]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

Trying to use tab completion for fd's `--color` option displays an error:

```
$ fd --color=<TAB>fish: Unknown command: default
fish: 
default
^~~~~~^
in command substitution
```

I believe this doc comment is the culprit:

https://github.com/sharkdp/fd/blob/a248607beefac2137cbe068ef74898c46e0705dd/src/cli.rs#L734-L736

The relevant line in the generated fish completions is this one:

```fish
complete -c fd -s c -l color -d 'When to use colors' -r -f -a "{auto	show colors if the output goes to an interactive console (default),always	always use colorized output,never	do not use colorized output}"
```

Because there are parentheses around the word "default", fish will launch a subshell. But when fish does so, it can't find the `default` program and displays an error.

### Possible solutions:
1. Change the parentheses to brackets or something.
1. Patch clap / clap_complete to escape parentheses in doc comments.

### Describe what you expected to happen:

I expect to see the possible completions:

```
$ fd --color=<TAB>
always                                       (always use colorized output)
auto  (show colors if the output goes to an interactive console (default))
never                                        (do not use colorized output)
```

### What version of `fd` are you using?

fd 8.7.0

### Which operating system / distribution are you on?

```shell
Darwin 22.6.0 arm64
```

**Comment by tavianator** [comment]
I think this should be fixed in clap_complete

**Comment by tmccombs** [comment]
Agreed. Clap_complete should escape special characters in the description. Could you open an issue with clap?

**Comment by cstyles** [comment]
The bug was fixed in clap_complete. I opened #1382 to update fd to the new version.
