### ISSUE TITLE
[BUG] Missing files in result list

### ISSUE THREAD

**Issue by linrongbin16** [sharkdp/fd#1368]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

Download this source code base: https://github.com/linrongbin16/fzfx.nvim, cd into it.

Execute command:

```bash
fd . -tf
```

The results are:

<img width="498" alt="image" src="https://github.com/sharkdp/fd/assets/6496887/aa930378-c06c-4618-8a54-a1f5887e61d5">

Cannot find below files:

* `./lua/fzfx/config.lua`
* `./lua/fzfx/git_commits.lua`
* `./lua/fzfx/server.lua`

(Actually looks like all files under `./lua/fzfx` folder are missing)

If I execute command:

```bash
fd . -tf -u
```

Then will show up. But I didn't exclude them in `.gitignore` files.

Here's the `.gitignore`:

```
# Compiled Lua sources
luac.out

# luarocks build files
*.src.rock
*.zip
*.tar.gz

# Object files
*.o
*.os
*.ko
*.obj
*.elf

# Precompiled Headers
*.gch
*.pch

# Libraries
*.lib
*.a
*.la
*.lo
*.def
*.exp

# Shared objects (inc. Windows DLLs)
*.dll
*.so
*.so.*
*.dylib

# Executables
*.exe
*.out
*.app
*.i*86
*.x86_64
*.hex

```

And my `~/.gitconfig` files is:

```
[user]
	email = linrongbin16@outlook.com
	name = linrongbin16
[filter "lfs"]
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
[push]
	default = current
[core]
	fsmonitor = true
	untrackedcache = true
[pull]
	rebase = false
[init]
	defaultBranch = main

```

Would you please help me?

### Describe what you expected to happen:

Some files are missing in `fd` command results.

### What version of `fd` are you using?

fd 8.7.0

### Which operating system / distribution are you on?

```shell
macOS Ventura 13.5.1, Apple M1 MAX chip
```

**Comment by linrongbin16** [comment]
Is there a way to debug what `.ignore` and `.gitignore` files are affected the result list?

**Comment by tmccombs** [comment]
If you use `--no-ignore-vcs`, it will respect .ignore, but not .gitignore, which might help you determine whether it is .ignore, or .gitignore. And `--no-ignore-parent` will avoid looking at ignore files in the parent directoy (from where you start the search). With the two of those you could hopefully narrow in on which file is causing it.

**Comment by linrongbin16** [comment]
I use the `--no-ignore-vcs`:

```bash
fd . -tf --no-ignore-vcs
```

It shows:

<img width="535" alt="image" src="https://github.com/sharkdp/fd/assets/6496887/ca18053b-8e07-4162-8fa8-5387d51d7ecd">

And it shows all the files, but after I delete the `.gitignore` files and run `fd . -tf` and `fd . -tf --no-ignore-parent`, it still shows missing results:

<img width="765" alt="image" src="https://github.com/sharkdp/fd/assets/6496887/c2608557-722d-4cf6-9538-aa64ae10b979">

**Comment by linrongbin16** [comment]
I deleted the testing repo `~/github/linrongbin16/fzfx.nvim`, and clone it again to the same folder, and the fd is working again!

But somehow I think it's very strange that I don't know which gitignore is changing my searching results.

I think it's worthy to add a `--verbose` option to show details of which ignore files are taking effect.

**Comment by tmccombs** [comment]
> I think it's worthy to add a --verbose (or --debug) option to show details of which ignore files are taking effect.

That would probably be fairly difficult to do with the current implementation. For one thing, `fd` makes use of the [`ignore`](https://docs.rs/ignore/latest/ignore/index.html) crate to handling ignore files, but that doesn't have an API to determine which file the ignore came from.  And adding that functionality, or a logging mechanism to `ignore` would probably be somewhat difficult since I think the current implementation just combines applicable rules together, and doesn't keep track of which file the rules came from.
