### ISSUE TITLE
Ignore file that applies only to current dir / applies only to first child subdirectories?

### ISSUE THREAD

**Issue by kgrzywacz** [sharkdp/fd#1370]
**What version of `fd` are you using?**
fd 8.7.0

Is there a way of making an ignore file that would apply only to searches in directory it's in and/or only to first-child subdir?

Context:
I would like to ignore certain sub-directories in my `~` but still be able to search for sub-sub-directories with the same name as well as files that match the name but are in other sub-directories.

Let's say we have following file / dir structure
```
~/test/
~/download/test
```
and `cat ~/.fdignore` returns the following
```
test
```

There are two scenarios:
1. Run `fd test` while in `~` - yields no results, while desired results would be `download/test`.
2. Run `fd test` while in `~/download` - yields no results, while desired result would be `test`.

While second scenario can be solved by
a. running `fd --no-parent-ignore test` - this works, but in more complex scenarios (i.e. while being in git repo) will ignore all other ignore files in parent dirs.
b. using a function like
```
function fd2 {
  if [[ "$(pwd)" == "$HOME" ]]; then
    fd -E test $@
  else
    fd $@
  fi
}
```
I couldn't find a solution to first scenario - is there a way to do it? 
If not - do you think it would be feasible to add this feature?

**Comment by tmccombs** [comment]
If you change .fdignore to use 

```
/test
``` 

then it will only ignore "test" in that directory itself, and not in nested directories.

**Comment by kgrzywacz** [comment]
🤦‍♂️ 
Thank you. It seems to cover all cases.
For some reason I insisted on using `./test`.
