### ISSUE TITLE
The cause of `rustfmt: error while loading shared libraries: libsyntax-6f7d7e35b339f76f.so` on Travis CI

### ISSUE THREAD

**Issue by matematikaadit** [sharkdp/fd#138]
The code formatting test on nightly fail with this error
https://travis-ci.org/sharkdp/fd/jobs/290400026#L602
```
$ cargo fmt -- --write-mode=diff
rustfmt: error while loading shared libraries: libsyntax-6f7d7e35b339f76f.so: cannot open shared object file: No such file or directory
```
The cause of those error is probably because the rustfmt binary being cached from the previous build, but the nightly's  libsyntax is already updated alongside the channel update.

## Solutions
We can chose one of these solution:
1. `--force` rustfmt-nightly reinstall on each build. Example: https://travis-ci.org/matematikaadit/fd/jobs/290417411#L641 . Tho, it's incur an additional build time.
2. Disable the nightly code formatting item from the matrix.
3. Use [cargo-update](https://crates.io/crates/cargo-update) so that `rustfmt-nightly` only updated if there's newer version available.

What do you think? Any other ideas? I'll be glad to submit PR for this.

**Comment by sharkdp** [comment]
Thank you very much for looking into this. Which solution would you propose?

Does anyone have a feeling about how far "ahead" the nightly version of rustfmt is?

/CC @Detegr

**Comment by Detegr** [comment]
The nightly rustfmt is in `Allowed failures` section because I thought these kind of problems may occur. However, I thought the caching would work in a way that if the nightly compiler is updated, it would rebuild `rustfmt-nightly` as well.

I think we could go forward with either of those three options you listed. Although I think it is nice to have the nightly `rustfmt` as well, it's not a necessity. In my opinion the use of `cargo-update` sounds like the most appealing one.

**Comment by matematikaadit** [comment]
Yeah. I think it's just a simple directory caching, which in this case is the `$HOME/.cargo` directory. 

Since `$HOME/.cargo/bin` is in the `$PATH`, the snippet below will always return true and not reinstall the `rustfmt-nightly` after the first build:
```
$ which rustfmt || cargo install rustfmt-nightly
```
Hence, it will always reuse the previous installed `rustfmt` binary even though it's outdated.

---

Below is the build using **cargo-update** to check the `rustfmt` and `rustfmt-nightly` installation
https://travis-ci.org/matematikaadit/fd/builds/290717991

[code formatting check on **stable**](https://travis-ci.org/matematikaadit/fd/jobs/290718003)
```
$ cargo install-update rustfmt
Updating registry `https://github.com/rust-lang/crates.io-index`

Package Installed Latest Needs update
rustfmt v0.9.0 v0.9.0 No

No packages need updating.
```

[code formatting check on **nightly**](https://travis-ci.org/matematikaadit/fd/jobs/290718005)
```
$ cargo install-update rustfmt-nightly
Updating registry `https://github.com/rust-lang/crates.io-index`

Package Installed Latest Needs update
rustfmt-nightly v0.2.8 v0.2.9 Yes

Updating rustfmt-nightly
...
```

---

> Does anyone have a feeling about how far "ahead" the nightly version of rustfmt is?

According the the [rustfmt repo](https://github.com/rust-lang-nursery/rustfmt), **rustfmt-nightly-v0.1** is forked from **rustfmt-v0.9**. So if this list on [crates.io](https://crates.io/crates/rustfmt-nightly/versions) is correct, we can assume that rustfmt-nightly is 20 version ahead of rustfmt.

> In my opinion the use of `cargo-update` sounds like the most appealing one.

Yeah, me too.

**Comment by Detegr** [comment]
Thanks for the detailed information, much appreciated!
> Below is the build using cargo-update to check the rustfmt and rustfmt-nightly installation

Looks great, could you submit a PR for this?
