### ISSUE TITLE
Let glob behave like shell expansion

### ISSUE THREAD

**Issue by flip111** [sharkdp/fd#1380]
```bash
$ mkdir -p a/
$ touch a/alma.txt
$ ls a/*.txt
a/alma.txt
$ fd -g 'a/*.txt'       # empty result
```

This is similar to https://github.com/sharkdp/fd/issues/769 which had as solution to let it match on full path and put `**` in front. Why doesn't it just work on relative paths though? Am i doing something wrong?

**Comment by tmccombs** [comment]
by default fd only matches the file name, not the full path.

**Comment by flip111** [comment]
ok there is a `--full-path` option but not `--relative-path` option

**Comment by tavianator** [comment]
That is https://github.com/sharkdp/fd/issues/839

**Comment by flip111** [comment]
Makes sense, let's close this
