### ISSUE TITLE
Include `.git/` folder in the "gitignored" filtering

### ISSUE THREAD

**Issue by marcospb19** [sharkdp/fd#1387]
I mostly use `fd` in repositories, and I love having the ability of gitignoring pollution from build folders.

However, I keep getting tons of stuff from `.git/`.

I consider `.git/` to be _"gitignored by default"_, but that might just be my POV, any thoughts on this?

I imagine the odds of someone intentionally looking for stuff in the `.git/` directory should be low, but in that case, they can resort to `-I/--no-ignore` (or `--no-ignore-vcs`).

**Comment by skoriop** [comment]
Hi, I'd like to work on this if it's still up :)

**Comment by marcospb19** [comment]
Awesome! Take your shot :) .

`fd` uses `WalkBuilder` from the library `ignore`, take a look at
https://github.com/sharkdp/fd/blob/93cdb2628e89dd5831eee22b8df697aea00eca3b/src/walk.rs#L75 and https://docs.rs/ignore/latest/ignore/struct.WalkBuilder.html.

You might want to check if `WalkBuilder` supports doing this, maybe there's an issue in the `ignore` crate repo?

**Comment by marcospb19** [comment]
Oh, be aware that this wasn't officially approved by maintainers, so there is some chance they'll close your PR, in case they are opposed to this change, I imagine they're not, but it's good to gather confirmation before.

(btw, I'm not a maintainer xD just an user.)

**Comment by raphael-ratepay** [comment]
Why is there no option to opt out of this? 
I had the following to list all my Projects:
```
fd --type d --base-directory ~/Source -H '\.git' | sed 's|/.git||'
```

now if I add --no-ignore-vcs i get all folders inside my ignores (not just the .git folder)

**Comment by Eyjafjallajokull** [comment]
I have the same issue as @raphael-ratepay, as a workaround I've used:
```
fd --hidden --no-ignore --max-depth 5 --type d '^.git$'
```

**Comment by glucas** [comment]
> Why is there no option to opt out of this? I had the following to list all my Projects:
> 
> ```
> fd --type d --base-directory ~/Source -H '\.git' | sed 's|/.git||'

If you use '\.git$', does that help?
