### ISSUE TITLE
[BUG] - complete: nosort: invalid option name

### ISSUE THREAD

**Issue by daniejstriata** [sharkdp/fd#1407]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

Using bash completion on older distros like Amazon Linux 2(EOL: 2025-06-30) causes an error message when logging in:
./fd.bash: line 170: complete: nosort: invalid option name

![image](https://github.com/sharkdp/fd/assets/13314239/dba49f02-a90f-420a-8352-f34564ae3799)

I removed ` -o nosort` but unsure how it would affect the indented functionality of the shell completion.

### What version of `fd` are you using?

fd 8.7.1

### Which operating system / distribution are you on?

```shell
Unix: Linux 5.15.133-86.144.amzn2.x86_64 x86_64

cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
```
```

**Comment by daniejstriata** [comment]
Same will happen on Centos 7.

**Comment by tmccombs** [comment]
Removing that should be fine. It just means the completion results will be sorted.

**Comment by tavianator** [comment]
[`nosort` is from bash 4.4](https://github.com/bminor/bash/blob/a0c0a00fc419b7bc08202a79134fcd5bc0427071/NEWS#L70) which is from 2016-09-15.  Since it's still popular (and hey, macOS is still on bash 3), I think this is worth reporting upstream: https://github.com/clap-rs/clap/issues

**Comment by RobertAKARobin** [comment]
macOS user here, and this is indeed occurring for me too. :)

**Comment by sharkdp** [comment]
this has been reported in https://github.com/clap-rs/clap/issues/5190, but not fixed yet

**Comment by henry-hsieh** [comment]
I made a PR to fix this. The issue should be resolved after next release of clap-rs.

**Comment by henry-hsieh** [comment]
I think the clap-rs [v4.4.13](https://github.com/clap-rs/clap/compare/v4.4.12...v4.4.13) released today is including the change.
