### ISSUE TITLE
How to implement a search directory that includes the directory itself.

### ISSUE THREAD

**Issue by xpbluesmile** [sharkdp/fd#1423]
How to implement a search directory that includes the directory itself. 
For example, using find can operate 

find ./ -type d 
![1](https://github.com/sharkdp/fd/assets/3887637/4e550403-85d8-437c-b5d0-f630d0157d5b)

will list all directories under the current directory (including the directory itself), but fd cannot. 
The operation steps are as follows
Fd - td '.' ./ 
![2](https://github.com/sharkdp/fd/assets/3887637/47f6822f-b875-4776-a6b2-5682d494ff7b)

This operation only lists all subdirectories under the current directory and does not include itself. How to solve this problem

**Comment by tavianator** [comment]
See #364

**Comment by xpbluesmile** [comment]
thanks!
