### ISSUE TITLE
Force to print match at `--exec`

### ISSUE THREAD

**Issue by albfan** [sharkdp/fd#1425]
Debugging a file created by a driver (file patch might vary) I want to see the file and print it:

This can be done with:

```
$ fd -p .*B677.*/range /sys --exec $SHELL -c 'echo \{};cat \{}'
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:044F:B677.0012/range
1080
```

but instead of using shell to run two commands (echo and cat) is it possible to force printing the match like:

```
$ fd -p .*B677.*/range /sys --print-matches --exec cat
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:044F:B677.0012/range
1080
```

Here I made up the parameter `--print-matches` to force to print the match before `--exec` part

**Comment by tmccombs** [comment]
It isn't currently possible.

**Comment by albfan** [comment]
But makes sense? I mean the `bash -c` is a workaround, but I suppose `--exec` is explicitly disabling match print, this `--print-matches` tries to change that.

If so, I can provide a PR

**Comment by tmccombs** [comment]
> but I suppose --exec is explicitly disabling match print

It isn't quite that simple. --exec actually works somewhat differently than the default printing. 

Also, if the intention is to debug the resulting commands, I actually think I'd prefer an option (maybe --verbose?) that prints the command that will be run before running it.

**Comment by albfan** [comment]
of course, that option is just a quick suggestion, let me open a PR and see how it goes.

**Comment by sharkdp** [comment]
This seems very similar to https://github.com/sharkdp/fd/issues/1042. I'll close this as a duplicate, but let me know if you think otherwise.

**Comment by albfan** [comment]
That would work:

From:

```
$ fd -p .*B677.*/range /sys --print-matches --exec cat
/sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:044F:B677.0012/range
1080
```

to

```
$ fd -P .*B677.*/range /sys --print-matches --exec cat
cat /sys/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:044F:B677.0012/range
1080
```

is almost what this issue requested, but with a complex execution string maybe not that useful, or if command uses parent directory you will not see the file found
