### ISSUE TITLE
How do I convert this query from find to fd?

### ISSUE THREAD

**Issue by federicotorrielli** [sharkdp/fd#1430]
I have the following query for a systemd recurring deletion task:
```
/usr/bin/find /home/evilscript/ -maxdepth 1 -name "hs_err_pid*.log" -type f -delete
```
And I want to convert it using fd. I tried using the help but I'm having some problems.
The closest attempt that "probably" works is: `fd -d 1 -t f "^hs_err_pid.*\.log" /home/evilscript/`
But I'm not sure it does have some edge cases I'm currently not understanding...

Thanks in advance!

**Comment by sharkdp** [comment]
You probably want to use `--unrestricted`/`-u` if you are trying to be compatible with `fd`.

You can also replace the regex pattern by a glob if you want (`--glob 'hs_err_pid*.log'`). Otherwise, you would need to add `$` at the end of your pattern.

**Comment by federicotorrielli** [comment]
Thanks!
