### ISSUE TITLE
Wrap fd in a Python extension module

### ISSUE THREAD

**Issue by blais** [sharkdp/fd#1441]
It would be really great if this package would provide its functionality as a Python extension module.
I've seen instances of people calling subprocesses to "fd" in order to get a faster `os.walk()`.
Just an idea,

**Comment by tavianator** [comment]
I think Python bindings to `ignore` would make more sense than `fd`, but that's not a bad idea.  Definitely better than shelling out to `fd`

**Comment by grst** [comment]
In case anyone finds this issue via search:
It seems someone created python bindings for `ignore` here: https://github.com/borsattoz/ignore-python
