### ISSUE TITLE
making --strip-cwd-prefix the default behavior

### ISSUE THREAD

**Issue by Baerbeisser** [sharkdp/fd#1444]
Description:
> By default, relative paths are prefixed with './' when the output goes to a non interactive terminal (TTY). Use this flag to disable this  behaviour.

While stripping paths is nicer to look at, i think this is a rather unexpected behavior if used in scripts (e.g. non interactive terminal).
This was the reason why my function didn't work.
I guess there is a story as to why it is as it is?

**Comment by tmccombs** [comment]
The current behavior is because of https://github.com/sharkdp/fd/issues/760

I don't think we will go back to the previous default without the cwd prefix when executing with --exec --exec-batch, etc.

See also https://github.com/sharkdp/fd/issues/1243
