### ISSUE TITLE
[BUG] fd --help is not colorized, but file names are colorized normally

### ISSUE THREAD

**Issue by ssergiienko** [sharkdp/fd#1446]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

It was 100% working on my system in v8.0.0 and was broken somewhere after.
It doesn't work in clean environment: `env -i fd --help`

Colorizing filenames works as expected.
NO_COLOR env var is **not** set.
`fd --color=always --help` doesn't  help also.
LS_COLORS don't make any difference.

I tried to find any mentions in the changelog, but didn't succeed 

### Describe what you expected to happen:

fd --help should be colorful like it was in v8.0.0

### What version of `fd` are you using?

8.7.1

### Which operating system / distribution are you on?

```shell
Linux 6.4.4-arch1-1-custom-dirty x86_64
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

**Comment by tavianator** [comment]
This is probably just due to Clap 4 removing colors from `--help` by default: https://epage.github.io/blog/2022/09/clap4/#polishing-help-output

**Comment by tmccombs** [comment]
is this something we should add back in?

**Comment by sharkdp** [comment]
It took me a while to get used to it, but I think I like the new (colorless) default better.
