### ISSUE TITLE
[BUG] `fd .`  command can't detect .jpg files on Ubuntu  

### ISSUE THREAD

**Issue by gorkemgul** [sharkdp/fd#1448]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

When we try to use `fd .` command .jpg files can't be found, however, when it comes to `fd -I .`  command, it can detect  .jpg files as well. What causes this problem actually?

![Screenshot from 2023-12-08 10-02-58](https://github.com/sharkdp/fd/assets/104680758/3bf25caf-03b1-4407-814c-9141f5058480)

### Describe what you expected to happen:

I wanted all the files in the given directory to be found.

### What version of `fd` are you using?

7.4.0

### Which operating system / distribution are you on?

```shell
Linux 5.15.0-89-generic x86_64

No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:    20.04
Codename:    focal
```

**Comment by sharkdp** [comment]
Please see https://github.com/sharkdp/fd#fd-does-not-find-my-file
