### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by madneal** [sharkdp/fd#1459]
when trying to build with `cargo build`

```
error: failed to parse manifest at `/Users/xxxx/project/fd/Cargo.toml`

Caused by:
  invalid type: unit variant, expected string only for key `profile.release.strip`
```

**Comment by tavianator** [comment]
What version of Rust are you building with?  It needs to be at least 1.70

**Comment by madneal** [comment]
may can add this requirement in the README

**Comment by tmccombs** [comment]
It is in the README: https://github.com/sharkdp/fd#from-source
