### ISSUE TITLE
Shouldn't fd support using ~ as a subtitute for the home directory when writing paths?

### ISSUE THREAD

**Issue by YousufSSyed** [sharkdp/fd#1485]
For example writing `fd '.*\.app' "~/Library/Preferences/AndroidStudio"` should be the same as `fd '.*\.app' "/Users/yousuf/Library/Preferences/AndroidStudio"`.

**Comment by tmccombs** [comment]
That expansion is done by your shell. At least in zsh and bash, ~ expansion doesn't happen if the ~ is inside of quotes. If you don't put double quotes around the path, then ~ will probably be expanded.
