### ISSUE TITLE
List all directories in cwd, including '.' and '..'

### ISSUE THREAD

**Issue by gnmdrive** [sharkdp/fd#1491]
fd 8.3.1

Hello, is it possible to list all directories including . and ..?
I am currently using this command
```
fd . -H -t d
```
but it doesn't return what I'm looking for

**Comment by tavianator** [comment]
`fd` won't print those entries, but you can always fake it with

```console
$ echo . && echo .. && fd . -H -td
```

**Comment by gnmdrive** [comment]
Thank you, this helped me
