### ISSUE TITLE
Support timestamp in the format @%s (seconds since epoch) like GNU date

### ISSUE THREAD

**Issue by nabellows** [sharkdp/fd#1493]
A lot of my utilities handle dates in the seconds-since-epoch format, and I cannot portably use GNU `date` on MacOS to parse these back to another format for `fd` without slow means such as python wrapper. I think it is a standard enough date format and not ambiguous when prefixed with '@' just as GNU date can handle via `date -d`.

**Comment by tmccombs** [comment]
This was added by #1494
