### ISSUE TITLE
Adding an output mode with network-absolute paths

### ISSUE THREAD

**Issue by rc9000** [sharkdp/fd#1497]
I often scp files between hosts and I'd find it very handy for find or fd to have a option to directly output results in this format

    $HOSTNAME:/path/to/file.txt

I'm also learning rust so I gave it a quick try, it could somewhat look like this:

    rc@hackbookpro:~/git/fd $ ./target/debug/fd --network-path -c never fd 
    hackbookpro.home.local:/Users/rc/git/fd/contrib/completion/_fd
    hackbookpro.home.local:/Users/rc/git/fd/doc/fd.1
                                                                       
    rc@hackbookpro:~/git/fd $ ./target/debug/fd -h | grep network-path      
      -N, --network-path               Prepend hostname for scp copy/paste, implies -a

Would you think this is of general interest? If yes I could clean it up and submit a PR. Otherwise no hard feelings :)

**Comment by tmccombs** [comment]
Once https://github.com/sharkdp/fd/pull/1043 is merged, you could do:

```
fd --format "$HOSTNAME:{}" --absolute-path -c never
```
Would that work?

**Comment by rc9000** [comment]
@tmccombs that's actually better than my variant, nice!
