### ISSUE TITLE
[BUG]  fd --glob seems wrong

### ISSUE THREAD

**Issue by EloB** [sharkdp/fd#1508]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

I've tried to use:
```bash
> mkdir -p hello/world
> touch hello/world/index.js
> fd
# hello/
# hello/world/
# hello/world/index.js
> fd -g 'hello/**/*.js'
# (No output this seems wrong)
> fd -g '**/*.js'
# hello/world/index.js
> fd -g '**/*.js' hello # I know that this is possible but glob usually support that type of pattern above.
# hello/world/index.js
```

### Describe what you expected to happen:

See above

### What version of `fd` are you using?

fd 9.0.0

### Which operating system / distribution are you on?

```shell
uname -srm
Darwin 22.6.0 arm64
```

**Comment by tavianator** [comment]
By default, `fd` is just comparing the file name (e.g. `index.js`) to the glob.  It seems a bit strange that `**/*.js` matches at all, but it happens to work because recursive globs like `**/*` will also match top level files (see https://docs.rs/globset/latest/globset/#syntax).

You can turn on `--full-path` but then the matching is against the *full absolute path* (see #839)

```console
$ fd --full-path -g 'hello/**/*.js' # Probably no results
$ fd --full-path -g "$PWD/hello/**/*.js'
hello/world/index.js
```

**Comment by EloB** [comment]
I think this answers my question. Thanks!

**Comment by tavianator** [comment]
It may be worth printing a warning if a glob includes `/` without `--full-path`.  GNU find does:

```console
$ find -name 'foo/bar'
find: warning: ‘-name’ matches against basenames only, but the given pattern contains a directory separator (‘/’), thus the expression will evaluate to false all the time.  Did you mean ‘-wholename’?
```

**Comment by ElSamhaa** [comment]
Hello, I've hit the same issue today. I think it's intuitive to start the search from the current directory; i.e without the need to prefix with a recursive glob. IIRC, this is the `find` behavior too.

**Comment by tmccombs** [comment]
That sounds a lot like https://github.com/sharkdp/fd/issues/839

Unfortunately, changing the default would be a backwards incompatible change.
