### ISSUE TITLE
`--all` argument

### ISSUE THREAD

**Issue by carschandler** [sharkdp/fd#1516]
The default behavior of ignoring certain directories is nice, but it would be great to have an `--all` argument that ensures all paths are searched. I'm aware that `-IH` is usually enough to get what might be desired here, but sometimes you really do need to search *everything*, and it's nice to have a single argument to enable this rather than have to remember everything to turn back on.

**Comment by tavianator** [comment]
`-u` should be what you're looking for

**Comment by carschandler** [comment]
Welp. Thanks.
