### ISSUE TITLE
Ignore top level .gitignore

### ISSUE THREAD

**Issue by kaihendry** [sharkdp/fd#1518]
**What version of `fd` are you using?**
9.0.0

Due to the nature of my dotfiles https://github.com/kaihendry/dotfiles/blob/master/.gitignore the gitignore makes `fd` useless without -I flag. Is there some global config I can make fd just simply ignore $HOME/.gitignore? 

I did try setting .fdignore to ignore my top level ~/.gitignore but it didn't work.

**Comment by tavianator** [comment]
`--no-ignore-parent` may help

**Comment by kaihendry** [comment]
Looks good, though how do I configure that across my system?
