### ISSUE TITLE
fd? fdfind? fdclone?

### ISSUE THREAD

**Issue by Golddouble** [sharkdp/fd#1524]
Quote from your manual:
> On Debian
> 
> If you run Debian Buster or newer, you can install the [officially maintained Debian package](https://tracker.debian.org/pkg/rust-fd-find):
> 
> sudo apt-get install fd-find
> 
> Note that the binary is called fdfind as the binary name fd is already used by another package. It is recommended that after installation, you add a link to fd by executing command ln -s $(which fdfind) ~/.local/bin/fd, in order to use fd in the same way as in this documentation. Make sure that $HOME/.local/bin is in your $PATH.

**What version of `fd` are you using?**
```
$ fd --version
The command 'fd' was not found, but can be installed with sudo apt install fdclone
```
```
$ fdfind --version
fdfind 8.6.0
```

I use MX-Linux 23. 
Question 1:
Do I understand right, that fdfind is actually the right command if I want to use "sharkdp/fd" ?
Or is there an other search programme with the command "fdfind"?

Question 2:
Or is fdclone the right command and package to install, when I want to use sharkdp/fd" ?

Question 3:
Or is fdmusl the correct command, when I want to use sharkdp/fd" ?

Thank you.

**Comment by tmccombs** [comment]
On debian, if you installed from the official apt repository, it is fdfind.
