### ISSUE TITLE
Ignore cache directories by default

### ISSUE THREAD

**Issue by Subarctic2796** [sharkdp/fd#1525]
Hi I think it would be a good idea if fd ignored files and directories that are cache files or are dependency folders.
Such as:
- zig-cache and zig-out
- rust's target directory
- pycache and files in venvs

I would like to help but I am still a beginner programmer.

**Comment by tavianator** [comment]
This is the main reason that `fd` respects `.gitignore` files.  For those that aren't caught by that, you could add them to your `~/.fdignore`.

But I think it would be too breaking of a change to start ignoring those everywhere by default.  E.g. `target` could be many things, not always a Rust build directory.

**Comment by Subarctic2796** [comment]
That makes sense. I will close the issue then.
