### ISSUE TITLE
[BUG]  fd -e o not works.

### ISSUE THREAD

**Issue by Sunshine-Rain** [sharkdp/fd#1533]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

when i compile ffmpeg, i want to find  .o files.

the command 
` cd libavcodec
 ls *.o

012v.o                      dca_parser.o                h264pred.o                  mqc.o                       speedhqenc.o
4xm.o                       dca_sample_rate_tab.o       h264qpel.o                  mqcdec.o                    speexdec.o
8bps.o                      dca_xll.o                   h265_metadata_bsf.o         mqcenc.o                    srtdec.o
....
`

but  when i use `fd -e o`
the output is blank

### Describe what you expected to happen:

find the .o files

### What version of `fd` are you using?

fd 8.7.1

### Which operating system / distribution are you on?

```shell
mac os 14.3.1
```

**Comment by sharkdp** [comment]
https://github.com/sharkdp/fd?tab=readme-ov-file#fd-does-not-find-my-file

**Comment by Sunshine-Rain** [comment]
> https://github.com/sharkdp/fd?tab=readme-ov-file#fd-does-not-find-my-file

it works after adding the -u flag

sorry for my carelessness
