### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by flaviomartins** [sharkdp/fd#1538]
Please consider providing a package for fd on conda-forge

**Comment by tmccombs** [comment]
It looks like https://conda-forge.org/docs/maintainer/adding_pkgs/#creating-recipes is the instructions on how to do this. 

Bascially, it looks like you need to make a PR to a staging repo for conda-forge with a "recipe" for this package.

**Comment by tmccombs** [comment]
See https://github.com/sharkdp/fd/issues/1088

I'm not sure what is going wrong in your case. Maybe it is compiling using the wrong rust target? for osx_arm64  you need to use the aarch64-apple-darwin target for the rust toolchain. But I'm not sure where that is set in the conda-forge config.

**Comment by flaviomartins** [comment]
> See #1088
> 
> I'm not sure what is going wrong in your case. Maybe it is compiling using the wrong rust target? for osx_arm64 ou need to use the aarch64-apple-darwin target for the rust toolchain. But I'm not sure where that is set in the conda-forge config.

It was failing when running the test. I skip the test for arm64 since the test will be running on x86_64 where the build took place (not sure if azure pipelines has aarch64-apple-darwin machines)

**Comment by tmccombs** [comment]
Ah, yes running tests for an aarch64 executable on x86_64 won't work.

**Comment by flaviomartins** [comment]
Closed in https://github.com/conda-forge/fd-find-feedstock/pull/24#event-12772240584
