### ISSUE TITLE
FD version 10 stopped working on Windows 7

### ISSUE THREAD

**Issue by sergeevabc** [sharkdp/fd#1550]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

![2024-0506-1955 fd10 error on windows7](https://github.com/sharkdp/fd/assets/373718/38faa02b-d796-4387-a7ed-9b9e0a6bda14)

Rust language developers betrayed Windows 7 users by removing the feature to build binaries for this OS. They believe that since Microsoft has stopped supporting this OS (not because new versions bring something revolutionary, but to make money on sales), then they should follow. However, the support is not a determining factor for all users — this OS is sufficiently polished to perform its functions and remains in demand outside relatively well-off places. For example, C language developers understand this and their compilers do not require a new OS. The good hammer continues to hammer regardless of whether the warranty has expired.

This puts the authors of FD, a program written in Rust, in a difficult position because they need to either spit in the face of all those users outside the so-called golden billion who relied on FD all these years, or find a way to compile it ([Tier3][1]? [Rust9x][2]?).

### What version of `fd` are you using?

10

### Which operating system / distribution are you on?

```shell
Windows 7 x64
```

[1]: https://github.com/rust-lang/rust/pull/118150
[2]: https://github.com/rust9x/rust]Rust9x

**Comment by tavianator** [comment]
This seems more like a complaint directed at the Rust project itself than an fd issue.  If there's a way for us to build Windows 7 compatible binaries I think we'd be happy to add a separate build for that.

**Comment by tmccombs** [comment]
It seems like there is a separate target for win7 (that is tier 3). I don't have any objection to adding a build for that

**Comment by tmccombs** [comment]
> Rust does not ship pre-compiled artifacts for this target. To compile for this target, you will either need to build Rust with the target enabled (see "Building the target" above), or build your own copy by using build-std or similar.

well, that makes supporting this more difficult.

**Comment by hellishvictor** [comment]
> ### Checks
> 
>     * [x]  I have read the troubleshooting section and still think this is a bug.
> 
> 
> ### Describe the bug you encountered:
> 
> ![2024-0506-1955 fd10 error on windows7](https://private-user-images.githubusercontent.com/373718/328255283-38faa02b-d796-4387-a7ed-9b9e0a6bda14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3Njk3OTIsIm5iZiI6MTcxNTc2OTQ5MiwicGF0aCI6Ii8zNzM3MTgvMzI4MjU1MjgzLTM4ZmFhMDJiLWQ3OTYtNDM4Ny1hN2VkLTliOWUwYTZiZGExNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxMDM4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzE0Nzg2ODJjYjhhMDUyYTkyNzE3ZTU5MjdjYmU4OTg4OWVjZmE3YzRlODg5MzdlYzJkM2IwNzk3ODI1OTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JDgbGwEmUKa9pPAHybs_MNWb1yfFnSEQTFEzmn6YSEs)
> 
> Rust language developers betrayed Windows 7 users by removing the feature to build binaries for this OS. They believe that since Microsoft has stopped supporting this OS (not because new versions bring something revolutionary, but to make money on sales), then they should follow. However, the support is not a determining factor for all users — this OS is sufficiently polished to perform its functions and remains in demand outside relatively well-off places. For example, C language developers understand this and their compilers do not require a new OS. The good hammer continues to hammer regardless of whether the warranty has expired.
> 
> This puts the authors of FD, a program written in Rust, in a difficult position because they need to either spit in the face of all those users outside the so-called golden billion who relied on FD all these years, or find a way to compile it ([Tier3](https://github.com/rust-lang/rust/pull/118150)? [Rust9x](https://github.com/rust9x/rust%5DRust9x)?).
> ### Describe what you expected to happen:
> 
> _No response_
> ### What version of `fd` are you using?
> 
> 10
> ### Which operating system / distribution are you on?
> 
> ```shell
> Windows 7 x64
> ```

Same here with [fd-v10.1.0-i686-pc-windows-msvc.zip](https://github.com/sharkdp/fd/releases/download/v10.1.0/fd-v10.1.0-i686-pc-windows-msvc.zip) and [fd-v10.1.0-x86_64-pc-windows-msvc.zip](https://github.com/sharkdp/fd/releases/download/v10.1.0/fd-v10.1.0-x86_64-pc-windows-msvc.zip).

**Comment by hellishvictor** [comment]
Ok, I've compile fd v10.1.0 with [the latest version that supports Win 7](https://github.com/rust-lang/compiler-team/issues/651), Rust v1.75, and it output **"error: package `fd-find v10.1.0 (D:\rust\fd)` cannot be built because it requires rustc 1.77.2 or newer, while the currently active rustc version is 1.75.0"**, so I open "D:\rust\fd\Cargo.toml" and changed **rust-version** from **1.77.2** to **1.75.0**, and it worked like a charm and compiled my own targets {x86_64,i686}-win7-windows-msvc xD I'll create a batch file for future builds, I guess that is what you guys do for all that builds on the release section.

**Comment by hellishvictor** [comment]
Ok, I've compile fd v10.1.0 with [the latest version that supports Win 7](https://github.com/rust-lang/compiler-team/issues/651), Rust v1.75, and it output **"error: package `fd-find v10.1.0 (D:\rust\fd)` cannot be built because it requires rustc 1.77.2 or newer, while the currently active rustc version is 1.75.0"**, so I open "D:\rust\fd\Cargo.toml" and changed **rust-version** from **1.77.2** to **1.75.0**, and it worked like a charm and compiled my own targets **{x86_64,i686}-win7-windows-msvc** xD I'll create a batch file for future builds, I guess that is what you guys do for all that builds on the release section.

**Comment by tmccombs** [comment]
I don't like the idea of locking fd into supporting 1.75 forever to support an OS that is no longer officially supported by its vendor.

Also, the main reason for upgrading to 1.77.2 in the first place is because of a CVE that impacts windows . See https://blog.rust-lang.org/2024/04/09/Rust-1.77.2.html.

I don't feel comfortable including a build on the release page that has this known vulnerability.

**Comment by sergeevabc** [comment]
a) @ozwaldorf, the author of Lutgen app, written in Rust, says that he was able to compile Windows 7 compatible (legacy) binary using [Rustc 1.77.2][1]. I verified that it worked as as expected.

b) @tmccombs Rust is no longer a language in which you can create programs that make life easier for as many people as possible. That's what we need to worry about, not what vendors like Microsoft do, because they are driven by the pursuit of profit, not a vision of a better world. Do you code to get that shiny "Silicon Valley approved" badge or to make the world a better place?

[1]: https://github.com/ozwaldorf/lutgen-rs/issues/16#issuecomment-2110546358

**Comment by ozwaldorf** [comment]
Also just to note, there are plans for an explicit legacy/win7 windows target (currently available but you have to build yourself). it's just not stabilized/prebuilt/distributed yet due to them losing end to end testing capabilities, but is a work in progress.

**Comment by tmccombs** [comment]
Sure it's possible to compile for win7 with rust 1.77.2. But it sounds like it is a little more involved. And I don't have windows 7, or any version of windows for that matter, nor do I have access to CI for windows 7 to test that such a binary works. 

If someone were to make a reasonable pull request to add building a win7 binary to the github actions, I would probably merge it, with a disclaimer that said binary is untested (as, like the rust project, fd doesn't have windows 7 ci servers to test it  on).  

I understand your frustration, but I don't currently have a good solution for providing a windows 7 compatible binary on the releases page.

You do have some options though:
- You can set up a rust toolchain for the x86_64-win7-windows-msvc target and compile it yourself
- You can compile it yourself using an older version of rustc, with the caveat that this may require code changes in the future, and there is a potential vulrnerability if you use it with the `--exec` or `--exec-batch` options to invoke a cmd.exe script with untrusted inputs (including the file names). 
- You can continue using an older version of fd, with the same caveats about security as the above point.
- You could consider switching to an operating system that is still supported. Linux and several BSD variants are free and probably run on your existing hardware. This is probably an extreme measure, and I wouldn't recommend it solely to use the latest version of fd, but it is an option, so I include it for completeness.

**Comment by sergeevabc** [comment]
> If someone were to make a reasonable pull request to add building a win7 binary to the github actions, I would probably merge it…

[That's how][1] @ozwaldorf set compilation chain via Github.

[1]: https://github.com/ozwaldorf/lutgen-rs/commit/ccdc1e3892f2f96b5ac595ec3aed662788e65960

**Comment by tmccombs** [comment]
Ah! Support wasn't removed until 1.78.

Yeah I can add a windows build with 1.77 for now

**Comment by sergeevabc** [comment]
Successfully updated FD from 9.0.0 to 10.2.0.
Thank you for supporting Windows 7 users!
