### ISSUE TITLE
Ability to disable one or more `.gitignore` files without having to use `--no-ignore-vcs`

### ISSUE THREAD

**Issue by j-lakeman** [sharkdp/fd#1558]
Would be quite handy to be able to ignore the content of selectable `.gitignore` files. Maybe by listing them in the `.fdignore`, for example: `path_to/.gitignore`
I came across this issue after integrating `fd` deeper into my workflows e.g. in combination with `fzf`.

Nevertheless great application!

**Comment by tmccombs** [comment]
Not sure if it helps your use case, but you could do the other way around, and  use `--no-ignore-vcs`, then specify specific .gitignore files to use with `--ignore-file`

**Comment by j-lakeman** [comment]
Cheers for the support!
Thing is in my case I only want to exclude a single `.gitignore`, but keep the individual ones in subfolders and the global `git` as well as `fd` one while also having hidden files enabled.

So what I'm doing atm as a workaround is calling `fd --hidden --no-ignore-vcs`.
I have also tried `fd -u --ignore-file .config/fd/ignore`.

But with both approaches, I would need to re-enable dozens of `.gitignore` files buried somewhere in the file system. Hope this helps to clarify!

**Comment by tmccombs** [comment]
I see.

That seems like a somewhat unusual use case to me, so I'm not sure it would be worth adding that functionality.

**Comment by tmccombs** [comment]
See #362

**Comment by j-lakeman** [comment]
Cheers!
Closing in favour of #362
