### ISSUE TITLE
[BUG]  Regex seems to not be working correctly with dashes

### ISSUE THREAD

**Issue by Norlock** [sharkdp/fd#1560]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

I have the following path:
```
Projects/impierce/impierce-mapper/
```

And the following regex:

```
fd --type directory  '(.*[Pp].*[Rr].*[Ii].*[Aa].*[Pp].*)'
````

And it will not find it:

```
Projects/sparticles/crates/sparticles_app/
Android/Sdk/sources/android-34/com/google/i18n/phonenumbers/prefixmapper/
Android/Sdk/sources/android-34/com/android/i18n/phonenumbers/prefixmapper/
bin/google-cloud-sdk/platform/bq/third_party/program_image_remapper/
```

I have also tested it on:  https://regex101.com/

Where it was matched.

I also tested another directory with - and it had the same problem

### Describe what you expected to happen:

Expect the regex to match correctly 

### What version of `fd` are you using?

fd 10.1.0

### Which operating system / distribution are you on?

```shell
Linux 6.8.9-arch1-2 x86_64

LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

**Comment by Norlock** [comment]
To follow up: 

```sh
 fd --type directory  '^[Pp].*[Rr].*[Ii].*[Aa].*[Pp]*$'
```

Gives me different results but also no match

**Comment by tmccombs** [comment]
By default fd only matches the final component. You need to use the --full-path option to match the full path
