### ISSUE TITLE
Allow for Files and Directories

### ISSUE THREAD

**Issue by rickalex21** [sharkdp/fd#1565]
Hello, thanks for all the great work with fd.

I have a use case in which I need to search multiple directories and a few files located elsewhere.

The find command allows for this:

```sh
find ~/dir1 ~/dir2 ~/file1 ~/file2
```

Fd does not allow this:

```text
[fd error]: Search path '~/file1l' is not a directory.
[fd error]: Search path '~/file2l' is not a directory.
[fd error]: No valid search paths given.
```

I understand that one can use ignore `-E` as a work around in some cases but it does become complicated
in other cases. A work around could be a glob to include `-g. However, I think it would me much easier
if this was implemented out of the box like the find command.

I have also tried combining different flags:

```sh
 fd --search-path  ~ -g "file*" --search-path  ~/other/path/ -g "file3*" 
error: the argument '--search-path <search-path>' cannot be used with '[path]...'
```

Thanks

**Comment by danielzgtg** [comment]
Version 9.0.0 has a helpful message. The first arg is a pattern, not a path like find. Just do `fd . ~/dir1 ~/dir2 ; readlink -e ~/file1 ~/file2` .

```console
$ touch file1 file2
$ mkdir dir1 dir2
$ touch dir1/hi
$ fd . ~/dir1 ~/dir2 ; readlink -e ~/file1 ~/file2 ~/file3
/home/home/dir1/hi
/home/home/file1
/home/home/file2
```

<details>
<summary>Original</summary>

```console
$ fd ~/dir1 ~/dir2 ~/file1 ~/file2
[fd error]: Search path '/home/home/file1' is not a directory.
[fd error]: Search path '/home/home/file2' is not a directory.
[fd error]: The search pattern '/home/home/dir1' contains a path-separation character ('/') and will not lead to any search results.

If you want to search for all files inside the '/home/home/dir1' directory, use a match-all pattern:

  fd . '/home/home/dir1'

Instead, if you want your pattern to match the full file path, use:

  fd --full-path '/home/home/dir1'
```
</details>

**Comment by rickalex21** [comment]
@danielzgtg  I don't think that would work with consult-fd since it's expecting directories but at that
point it becomes a consult question and I would not want to have anyone spend time implementing
this feature if it's something that can be resolved with readlink. If and when a better use case
comes up I will reopen the issue.

Thanks
