### ISSUE TITLE
Regexes for file extension

### ISSUE THREAD

**Issue by j-lakeman** [sharkdp/fd#1604]
I'd like to find all files with at least one underscore in the file extension. I haven't found any way to achieve this with regexes only.
Could the `--extension` flag allow regexes? E.g. `fd --extension '.*_.*'`

**Comment by tavianator** [comment]
`fd '\..*_.*' should work

**Comment by tmccombs** [comment]
Or use the --glob option and do `*.*_*`

**Comment by j-lakeman** [comment]
Cheers guys!
Both your approaches work, but they also find heaps of “unwanted” files e.g. `.gitignore_global` or `.bak_0.log` or `Application_Lite_18.1_download.pdf`.

**Comment by tavianator** [comment]
Perhaps `fd '[^.].*\.[^.]*_[^.]*$'`

**Comment by Ra2-IFV** [comment]
@tavianator At least with separators please
`-e a,b` matches `*.a` `*.b`
Reason for not using regex is regex is slow.

**Comment by Ra2-IFV** [comment]
Of course it can be done in scripts (brace expansion in shell, join array and `Invoke-Expression` in powershell), but it's much simpler with separators.
