### ISSUE TITLE
Search files with specific permission

### ISSUE THREAD

**Issue by GallaisPoutine** [sharkdp/fd#1637]
Hi, 

Is there any way to add the possibility to search for file by filtering permissions ?
I was search for all the files with 744 permission (for instance) and I found out there was no way to use this kind of search.
I volunteer to implement this feature if this acknowledged.

Regards, 
GallaisPoutine

**Comment by tavianator** [comment]
I suspect this falls outside of the 80/20 rule for `fd` (meaning, we want to support the most useful functionality from `find` while remaining considerably simpler).  You can use `find -perm 744`.

This was discussed before in https://github.com/sharkdp/fd/issues/523

**Comment by GallaisPoutine** [comment]
@tavianator thanks for redirecting to the original feature request. I will comment there if needed.
