### ISSUE TITLE
Directories named `target` not showing up in results

### ISSUE THREAD

**Issue by mirosval** [sharkdp/fd#170]
When I search for paths that contain `target` in them they don't show up:
```shell
# find
find . -name main -d
./server/target/scala-2.11/src_managed/main
./server/src/main
./client/target/scala-2.11/src_managed/main
./client/src/main

# fd
fd -t=d main .
client/src/main
server/src/main
```

Searching for `target`
```
find . -name target -d
./target
./server/target
./project/target
./project/project/target
./client/target

# fd
fd -t=d target .
# no results

fd target .
# no results

ls -la . | grep target
drwxr-xr-x   4 miroslav.zoricak  staff   128 Nov 14 13:10 target
```

There is nothing unusual about the directories as far as I can see. I'm on macOS High Sierra (10.13.1 (17B48)), but I experienced the same behavior on the most up to date macOS Sierra as well.

**Comment by tmccombs** [comment]
Do you have a .gitignore file that excludes directories named target?

**Comment by mirosval** [comment]
aaah I completely missed that one. Sorry! I love fd!
