### ISSUE TITLE
fd package for Ubuntu

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#174]
It would be great if we had an easy way to install *fd* on Ubuntu (or maybe even provide a package for all Debian-based distributions?).

I'm not familiar with creating own `.deb` packages and the ecosystem around PPAs, so any help would be greatly appreciated!

**Comment by danielpclark** [comment]
`.deb` packages are very involved.  Ubuntu supports a much easier to make lightweight package installation through [snap](https://docs.snapcraft.io/build-snaps/).

**Comment by tmccombs** [comment]
I could help out with this

**Comment by sharkdp** [comment]
@danielpclark Never heard of snap, but if that's something that's easily available (also on older Ubuntu versions?), that might be an alternative option.

@tmccombs Sounds great!

**Comment by sharkdp** [comment]
Just for reference, thanks to @tmccombs help, we have `*.deb` packages for the v6.1.0 release (and every forthcoming release).

What would be logical next steps to make this even more convenient for Ubuntu users?

Set up a PPA?

As a long term goal, [get into the official repositories](https://askubuntu.com/questions/16446/how-to-get-my-software-into-ubuntu)? :smile:

In any case, I should add a new "Ubuntu" section in the README install instructions.

**Comment by wsandin** [comment]
Would you be interested in a RPM, FreeBSD package or similar too?

**Comment by sharkdp** [comment]
> Would you be interested in a RPM, FreeBSD package or similar too?

- On FreeBSD, *fd* can be installed via portmaster already (see README) - is there something else that is needed?
- An RPM package would be great!

**Comment by matrixik** [comment]
Snaps are build automatically
https://docs.snapcraft.io/build-snaps/ci-integration
`ripgrep` config for it: https://github.com/BurntSushi/ripgrep/blob/master/snapcraft.yaml

**Comment by Kristinita** [comment]
**Type: Reply** 💬

It would be nice to be able to simply and without compilation install on Ubuntu the latest fd version like this:

```text
snap install fd-find
```

1. For Ubuntu Jammy Jellyfish ([**the latest Travis CI environment as of January 2024**](https://docs.travis-ci.com/user/reference/linux#overview)) [**the latest apt fd-find version is 8.3.1**](https://packages.ubuntu.com/jammy/fd-find), not 9.0.0.
1. When installing from binaries, the [**user must manually specify the version number and architecture**](https://github.com/sharkdp/fd#on-ubuntu).
1. Compilation from sources isn’t a “simply installation”.

Thanks.
