### ISSUE TITLE
hang with exec

### ISSUE THREAD

**Issue by aeosynth** [sharkdp/fd#178]
```
sudo touch foo
fd foo -x rm {}
```

attempting to remove a write-protected file hangs

**Comment by sharkdp** [comment]
Thank you for reporting this.

I believe this is due to `rm` waiting for input:
``` bash
▶ sudo touch foo

▶ rm foo
rm: remove write-protected regular empty file 'foo'? 
```

Indeed, if you enter `y`, *fd* terminates:
``` bash
▶ fd foo -x rm {}
y
rm: remove write-protected regular empty file 'foo'? %                                
```

Still, this is a bug because *fd* doesn't show the output of `rm`.

**Comment by ChengCat** [comment]
`rm` is waiting for inputs from stdin. We could resolve this issue, if stdin is closed before executing `rm`.
