### ISSUE TITLE
Fix build on Travis CI

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#183]
Something seems wrong with the Travis CI build in one particular setting. I tried resetting the caches, but that didn't help.

@matematikaadit Do you have any idea what's causing this?

**Comment by Doxterpepper** [comment]
For some reason it seems to be installing and updating rustfmt but then cargo isn't aware that rustfmt is installed, could it be a path thing?

**Comment by matematikaadit** [comment]
I assume it's this build
https://travis-ci.org/sharkdp/fd/jobs/309758165#L619

In particular, the output of `cargo install-update` is quite strange
```
$ cargo install-update rustfmt

    Updating registry `https://github.com/rust-lang/crates.io-index`

Package  Installed  Latest  Needs update

No packages need updating.
```

Compared to the [previous successful build](https://travis-ci.org/sharkdp/fd/jobs/306043483):
```
$ cargo install-update rustfmt

    Updating registry `https://github.com/rust-lang/crates.io-index`

Package  Installed  Latest  Needs update

rustfmt  v0.9.0     v0.9.0  No

No packages need updating.
```

The failed one has no mention of rustfmt package in it's output.

Currently investigaging...

**Comment by Doxterpepper** [comment]
I think I figured it out, for some reason cargo-update needs the -i flag to install the package that is not currently installed. Otherwise it just wants to update the package but since it's not installed it cant update it, so nothing happens.

**Comment by spk** [comment]
I think this can be closed thanks to https://github.com/sharkdp/fd/pull/185
