### ISSUE TITLE
Posibility to perform search with path and without pattern

### ISSUE THREAD

**Issue by dtcyganok** [sharkdp/fd#188]
If i want to quick overview any directory without changing current directory `find` allows this:

```bash
find /etc/systemd
```

Are there any alternatives with `fd`?

**Comment by sharkdp** [comment]
Yes, but for now you have to use one of the following
```
fd '' /etc/systemd
fd . /etc/systemd
fd ^ /etc/systemd
```

Basically, you have to provide a pattern that matches everything.

**Comment by fdcds** [comment]
Is there a plan to change this behaviour based on whether the argument is an existing directory or not?

**Comment by sharkdp** [comment]
There has been a detailed discussion in #312.

See also: #235 #315 #277 #385
