### ISSUE TITLE
Better integration with zsh

### ISSUE THREAD

**Issue by dtcyganok** [sharkdp/fd#189]
Currently autocomplete by `Tab` for `[<path>]` argument does not works.

**Comment by sharkdp** [comment]
Thank you for reporting this. Currently, autocompletion files are auto-generated. I'm not sure if this can be fixed by configuring `clap`. Any help would definitely be appreciated.

**Comment by sharkdp** [comment]
It looks like this is related to https://github.com/kbknapp/clap-rs/issues/568

**Comment by thernstig** [comment]
@sharkdp I just installed fd via `sudo dpkg -i fd_8.0.0_amd64.deb` but got no auto-completion items for the fish shell. Is this issue the same as this one, or a new issue?

**Comment by sharkdp** [comment]
That's something else. Could you please open a new ticket?

**Comment by smancill** [comment]
I have written a native Zsh completion script for personal use (actually, I had no idea there was an autogenerated completion script), and I have been thinking of sharing it with zsh-users/zsh-completions or here, and I found this issue. I took existing `_find` completion as example, so the completion offers the letters for `-t`, or commands and options for `x`, and directories for the second positional argument, for example.

Here it is working:

[![asciicast](https://asciinema.org/a/Tru8hppyuDNpGEGu6UP6cgTK0.svg)](https://asciinema.org/a/Tru8hppyuDNpGEGu6UP6cgTK0)

I can create a PR if you are interested.

**Comment by sharkdp** [comment]
> so the completion offers the letters for `-t`, or commands and options for `-x`, and directories for the second positional argument, for example.

That sounds fantastic!

> I can create a PR if you are interested. I have fd 7.5.0 installed though, I would need to check if there are missing options for newer versions, but shouldn't be a problem.

I'd be glad to replace the auto-generated file with the hand-written, if it's up to date. I guess a few changes will be necessary to the build/deployment system as well. See for example:

https://github.com/sharkdp/fd/blob/74c3431a2bf74ce78c26974f3cc07570e1d3baf3/ci/before_deploy.bash#L148

**Comment by sharkdp** [comment]
released in [v8.2.0](https://github.com/sharkdp/fd/releases/tag/v8.2.0).
