### ISSUE TITLE
New search options

### ISSUE THREAD

**Issue by dtcyganok** [sharkdp/fd#190]
* owner
* group
* permissions
* time
* file attributes (immutable, undeletable, and etc)

**Comment by sharkdp** [comment]
Thank you for your feedback.

A collection of keywords like this is not going to be very useful if we are considering to implement this. As far as I understand, this request overlaps with (at least) #165 and #177. Please comment in the respective tickets or open new tickets for specific features which you would like to see in *fd*. If possible, these feature requests should come with a description on how this is supposed to work and why you want this to be added.

**Comment by dtcyganok** [comment]
Most of the listed options are in `find`. The reason for which they are needed is the same for which they are needed in `find`.

For example
How can I find files in the home directory, which is not owned by me?
How can I find all executables in the home directory?
Etc.

Without them, I not see the opportunity to replace `find` with `fd`.
