### ISSUE TITLE
Getting incorrect results when using `-p, --full-path` option

### ISSUE THREAD

**Issue by laerus** [sharkdp/fd#192]
on current master 51aea57a6a13399d30d6883debc438498d012da4

this seems to be an issue when the current working directory and another directory in the tree 
have the same name

```
$ pwd
/home/kon/test-fd/projectname
$ tree
.
├── projectname
│   ├── source_0
│   ├── source_1
│   └── source_2
└── tests
    ├── test_0
    ├── test_1
    └── test_2

$ fd projectname/ -p
projectname
projectname/source_0
projectname/source_1
projectname/source_2
tests
tests/test_0
tests/test_1
tests/test_2
$ mv projectname/ not_the_same_name
$ fd not_the_same_name/ -p
not_the_same_name/source_0
not_the_same_name/source_1
not_the_same_name/source_2
```

**Comment by sharkdp** [comment]
What do you think would be the expected output? I don't see the problem.

The `-p` option instructs *fd* to match the pattern against the full (absolute) path. If your current working directory is called `/home/kon/test-fd/projectname`, then all those paths will have `projectname/` in them - and therefore, they should all match.

**Comment by tmccombs** [comment]
Maybe `-p` should imply `-a`, so that the match will always be in the printed result.

**Comment by sharkdp** [comment]
> Maybe -p should imply -a, so that the match will always be in the printed result.

That seems like a good idea to me. @laerus do you think this would have helped in your case?

**Comment by laerus** [comment]
I see what i misunderstood there, i was trying to reproduce the following `find` behavior,
can i do this with `fd` without changing the directory?

```
$ find projectname/
projectname/
projectname/source_0
projectname/source_2
projectname/source_1
```

i think an implied `-a` will make this more confusing

**Comment by tmccombs** [comment]
@laerus you can get that with `fd . projectname`
