### ISSUE TITLE
Request: update release

### ISSUE THREAD

**Issue by Alok** [sharkdp/fd#194]
This is really more a personal request, but I'm a bit limited at the moment.

I'd like the latest build of `fd`, which has the handy flag `--no-ignore-vcs`, to be added to the releases page so I can download the static binary onto a server I have to do work on. I don't have a rust toolchain set up on my local computer (running macOS) to cross-compile for Ubuntu 16.04.

Please and thank you.

**Comment by sharkdp** [comment]
Just released [v6.1.0](https://github.com/sharkdp/fd/releases/tag/v6.1.0). Debian packages are now also available
