### ISSUE TITLE
Bash completion not working with deb package

### ISSUE THREAD

**Issue by elcste** [sharkdp/fd#195]
I installed the new Debian package (fd-musl_6.1.0_amd64.deb) on Ubuntu 17.10 and bash completion is not working.

I'm *definitely* no expert in this, but based on other files on my system, what I tried and seems to work was to move the `/usr/share/bash_completion/completions/fd/fd.bash-completion` file to `/usr/share/bash-completion/completions/fd`.

(It also used to work for me when I manually moved the `fd.bash-completion` file to `/etc/bash_completion.d`.)

**Comment by tmccombs** [comment]
Ah, yeah that's just a typo
