### ISSUE TITLE
Feature request: library option

### ISSUE THREAD

**Issue by zekesonxx** [sharkdp/fd#203]
I'd really like to use fd's powerful finding in my Rust application, but it's only available as a binary.

I could call it as a subprocess, but that's really awkward and requires installing another binary and... having it as a library would be a lot simpler.

**Comment by sharkdp** [comment]
Thank you very much for your feedback!

To be honest, I'm not sure if this would currently be worth the effort.

What kind of functionality would you like to see from this library?

* If you need something to walk a directory tree recursively (with support for `.gitignore` files, etc.), you should take a look at the `ignore` crate which is used by *fd*.
* If you need pattern matching on file names in addition, it would probably still be quite easy to use the `ignore` and `regex` crates on your own.

**Comment by sharkdp** [comment]
Closing this for now, until there is any feedback from @zekesonxx
