### ISSUE TITLE
Question: How to search in the results?

### ISSUE THREAD

**Issue by geniusupgrader** [sharkdp/fd#219]
If I do for example: `fd test`

the output should be:

~~~
folder1/test.txt
folder1/test2.txt
folder2/test.txt
~~~

Now, how do I search in these result further with `fd`?
For example I want search in this list for folder2: `fd folder2`

the end result should be:

`folder2/test.txt`

How do I do that?
I would like to use only `fd` for that.

**Comment by sharkdp** [comment]
What exactly do you want to do?

  * Search for results in a particular subfolder?

    ```
    fd test folder2
    ```

  * Search the results for an arbitrary substring?

    If so, why don't you want to use a second tool for that?
    ```
    fd test | grep folder2
    ```

    If you absolutely don't want to use a second tool, you could use the `-p`/`--full-path` option to search the full file path and use a regex that searches for both `folder2` and `test`. However, you would have to choose a particular order:
    ```
    fd -p 'folder.*test'
    ```

**Comment by geniusupgrader** [comment]
Thanks @sharkdp the `--full-path` option gets me there.
And to pipe the results to grep (or ripgrep) should suffice, too.
