### ISSUE TITLE
Support for EXA_COLORS

### ISSUE THREAD

**Issue by notramo** [sharkdp/fd#222]
[`exa`](https://the.exa.website/) is a user-friendly alternative to `ls` and `tree`. (Similarly as `fd` → `find`, `rg` →`grep`)
The `EXA_COLORS` variable functions as the `LS_COLORS` variable, but contains additional coloring rules, such as coloring by
- permissions
- owner
- git modification status

See the `ENVIRONMENT_VARIABLES` section of the `exa` man page.

As `fd` has some of the features of `rg` (e.g. git support), it should support some features of `exa` to integrate into this ecosystem better.
These tools have similar aims, and if someone use a user friendly alternative to `find` and `grep`, he/she will likely use a modern alternative to `ls` and `tree`.

**Comment by sharkdp** [comment]
Thank you very much for your feedback.

I haven't completely thought this through, but I think I'm against this. My guess is that this would come at the cost of performance (additional file attributes have to be read, Git status needs to be queried).

Also, if you really wanted, you could already do something like this (obviously, you would create an alias):
``` bash
fd --exec exa --color=always
```

**Comment by notramo** [comment]
Running `exa` for each result wouldn't be a huge performance loss?

**Comment by sharkdp** [comment]
> Running exa for each result wouldn't be a huge performance loss?

Yes - it most probably would.

Still, I don't see any strong use case for this (plus, I'm afraid of the performance impact). I'm closing this for now - feel free to comment, if there is anything left to discuss.

**Comment by sharkdp** [comment]
For reference: In the meantime, we have `fd -X`, which would call `exa` just once.
