### ISSUE TITLE
Print usage like find

### ISSUE THREAD

**Issue by rleungx** [sharkdp/fd#230]
For now, fd without any args will recursively find all files in the current path.
Is it better to print usage instead?

**Comment by sharkdp** [comment]
Thank you very much for the feedback.

I find the default behavior very useful to get an overview of all files in a certain directory (similar to `tree`) while ignoring all hidden and VCS-ignored files. Actually, GNU find does the same thing (without ignoring hidden/VCS files).

Program usage can be displayed via `fd -h` (basic), `fd --help` (extended) or via the man page (`man fd`).
