### ISSUE TITLE
Suggest --fixed-strings on invalid regexps

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#234]
Inspired by https://github.com/BurntSushi/ripgrep/issues/709

**Comment by PramodBisht** [comment]
@sharkdp Can I take this one?

**Comment by sharkdp** [comment]
Sure! Let me know if you need any help.

**Comment by sharkdp** [comment]
This is part of [fd v7.0.0](https://github.com/sharkdp/fd/releases/tag/v7.0.0).
