### ISSUE TITLE
--type=symlink: Inconsistency between command line options and man page

### ISSUE THREAD

**Issue by kbd** [sharkdp/fd#240]
The [code](https://github.com/sharkdp/fd/blob/814d37030e2d27ed75d6598c9d6ec00d427f196d/src/app.rs#L83) and [help docs](https://github.com/sharkdp/fd/blob/814d37030e2d27ed75d6598c9d6ec00d427f196d/src/app.rs#L189) have `--type=l` mean symlinks, but the [man page lists the short flag as 's' instead of 'l'](https://github.com/sharkdp/fd/blob/master/doc/fd.1#L85).

Also, I didn't see it documented anywhere that the default type is file+directory but not symlink. It would be helpful if the docs and help had something like:

`Filter by type: f(ile), d(irectory), (sym)l(ink) (default: file + directory)`

Thanks for `fd` btw! I use it constantly (with `fzf` and standalone).

**Comment by sharkdp** [comment]
Thank you for the report! The man page looks outdated, yes.



> Also, I didn't see it documented anywhere that the default type is file+directory but not symlink.

That is not quite correct. The default is to not filter by file-type at all. Symlinks should be displayed as search results. However, note that symlinks are not *followed* by default.

So if you have this:
```
.
├── directory
│   └── file2
├── file
├── symlink_to_directory -> directory
└── symlink_to_file -> file
```

You should see both symlinks:
```
▶ fd
directory
directory/file2
file
symlink_to_directory
symlink_to_file
```

However, to see the nested file inside `symlink_to_directory`, you would have to add `--follow`/`-L`:
```
▶ fd -L
directory
directory/file2
file
symlink_to_directory
symlink_to_directory/file2
symlink_to_file
```

**Comment by kbd** [comment]
> The default is to not filter by file-type at all.

My mistake! Apologies, and thanks for the correction.

**Comment by sharkdp** [comment]
Fixed.
