### ISSUE TITLE
Negate extensions

### ISSUE THREAD

**Issue by kbknapp** [sharkdp/fd#242]
It would be awesome if we could specify `-e !jpg` which would do all files that are *not* a jpg. Similar to ripgrep's `--glob` option.

**Comment by sharkdp** [comment]
Thank you for the feedback!

You can use the `--exclude`/`-E` option (which is like the opposite of ripgrep's `--glob`):
```
fd -E '*.jpg'
```

**Comment by kbknapp** [comment]
Totally missed that :man_facepalming: 

Thanks!
