### ISSUE TITLE
Add Fedora install instructions

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#243]
It would be great if we could add install instructions for Fedora to the README. @ignatenkobrain If I understand correctly, you are packaging `fd` for Fedora (thank you!). Could you help me with the commands that a Fedora user would have to execute to install `fd`?

Ref: https://src.fedoraproject.org/rpms/rust-fd-find

**Comment by ignatenkobrain** [comment]
@sharkdp `$ sudo dnf install fd-find`, but unfortunately it's available only in F28+. If you feel that I should backport it to F27, I can spend some evenings ;)

**Comment by sharkdp** [comment]
I see - in this case, we'll just wait until F28 is officially released. I definitely wouldn't want you to spend even more time to backport it. Thank you very much!
