### ISSUE TITLE
Binary release for ARM (Raspberry Pi)

### ISSUE THREAD

**Issue by dan-santana** [sharkdp/fd#244]
It would be nice to have an ARM build, so we can use it on devices like Raspberry Pi.

**Comment by sharkdp** [comment]
Sounds great. I don't have a ARM system at hand, so any help would be appreciated.

**Comment by sharkdp** [comment]
I actually do have a ARM system at hand... 

Here is `fd` on my [rooted](https://github.com/dgiese/dustcloud) Xiaomi Mi vacuum cleaner :smile:

![image](https://user-images.githubusercontent.com/4209276/36606251-762b65b0-18c3-11e8-8b7c-b00ea590d4cd.png)

**Comment by sharkdp** [comment]
If someone wants to try it out, the ARMv7 (>= Raspberry Pi 2) binary is here: https://shark.fish/share/fd

**Comment by McKael** [comment]
@sharkdp Tested OK on both Raspberry Pi 3 and ODROID XU4.
Thanks!

**Comment by wedi** [comment]
Tested it on a Raspberry 2. Works like a charm! 👍

**Comment by sharkdp** [comment]
> Tested it on a Raspberry 2. Works like a charm! 

Nice!

> What kind of help do you need to provide fd as part of regular releases?

We probably have to do something very similar to ripgrep where ARM builds are now part of each release (see linked issue above and related pull request). If somebody would like to work on that, I'd be happy to mentor.

**Comment by sharkdp** [comment]
Starting with the [v7.1.0 release](https://github.com/sharkdp/fd/releases/tag/v7.1.0), we now provide pre-built ARMv7 binaries!

```
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.4.39 armv7l)

 * Documentation:  https://help.ubuntu.com/
Last login: Sun Aug 19 19:55:20 2018 from floyd

root@rockrobo:~# file ./fd
./fd: ELF 32-bit LSB  shared object, ARM, EABI5 version 1 (SYSV), dynamically linked
(uses shared libs), for GNU/Linux 2.6.32,
BuildID[sha1]=85cd5db8f67b8807df9ac260723a1896ecfb7b79, stripped

root@rockrobo:~# ./fd -V
fd 7.1.0
```

**Comment by issmirnov** [comment]
Thank you!! This is fantastic :)
