### ISSUE TITLE
Add 'executable' file type

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#246]
Add a new `executable`/`x` filetype for `--type`/`-t` filtering that only shows files with the executable bit.

For Windows, we could either disable this feature completely or search for files with `exe`/`bat`/`com`/`cmd`/`msi`.. file extensions.

**Comment by sharkdp** [comment]
Note: we already have an `is_executable` function in `output.rs` which could be re-used for this. Currently, it always returns `false` on Windows.

**Comment by PramodBisht** [comment]
@sharkdp I want to pick this up if nobody is working on that.

**Comment by sharkdp** [comment]
@PramodBisht Sounds great!

**Comment by PramodBisht** [comment]
@sharkdp in https://github.com/PramodBisht/fd/commit/8f796e3b9a735dd75611fb587f60dd4c99c0419f commit I have added changeset to show only `executable`, but its not working. Could you give me some pointer what I am doing wrong.

**Comment by sharkdp** [comment]
These changes look good to me. How did you test this? Which OS are you on?

**Comment by sharkdp** [comment]
I just got a closer look. There is indeed a logical error in that code. Let's take a look at these lines in `walk.rs`:
``` rust
if (entry_type.is_file() && !file_types.files)
    || (entry_type.is_dir() && !file_types.directories)
    || (entry_type.is_symlink() && !file_types.symlinks)
    || (output::is_executable(&entry.metadata().unwrap()) && !file_types.executables)
{
    return ignore::WalkState::Continue;
}
```

The way this works is that certain filesystem entries are *skipped* if one (or more) of the statements like `entry_type.is_file() && !file_types.files` are fulfilled.

If you specify `--type executable` (and no other `--type` arguments), then currently `file_types.executables = true` but all other `file_types.*` fields are set to `false`. This means that all files, directories and symlinks will be skipped (whether or not they are executable).

It looks like the `executable` flag should actually work a little different than the other three. What we want to see is files that are executable (directories typically also have the executable flag enabled, but we are probably not interested in that). So I think we should rename `file_types.executables` to `file_types.executables_only` and set both `files` and `executables_only` to true if `--type executable` has been specified. Then, we can modify the above to:
``` rust
if (entry_type.is_file() && !file_types.files)
    || (entry_type.is_dir() && !file_types.directories)
    || (entry_type.is_symlink() && !file_types.symlinks)
    || (!output::is_executable(&entry.metadata().unwrap()) && file_types.executables_only)
{
    return ignore::WalkState::Continue;
}
```

This would also allow us to specify `--type executable` in combination with `--type directory` and `--type symlink`.

**Comment by sharkdp** [comment]
This is part of [fd v7.0.0](https://github.com/sharkdp/fd/releases/tag/v7.0.0)
