### ISSUE TITLE
Support .ignore files using same format as rg and ag

### ISSUE THREAD

**Issue by erf** [sharkdp/fd#25]
Suggestion: Support .ignore files using same format as Ripgrep and The Silver Searcher ( rg and ag ).

**Comment by euphoria** [comment]
Given that this uses the same `ignore` crate as `ripgrep` (https://crates.io/crates/ignore) I would expect this to already be the case.  I haven't tried it yet, but is the functionality different for you in some way that you could clarify?

**Comment by erf** [comment]
I did not know that. Tested ok!

**Comment by adc17** [comment]
Hmm, FWIW a `.ignore` file in my home directory is picked up by ripgrep but not by fd. (It doesn't really bother me though as I can just create a symlink called `.fdignore` that works fine).

**Comment by tmccombs** [comment]
@adc17 
Probably because of this: https://github.com/sharkdp/fd/pull/241
