### ISSUE TITLE
Verbose flag to delete found matches

### ISSUE THREAD

**Issue by BrainMaestro** [sharkdp/fd#253]
Hi @sharkdp. Thanks for the awesome project. 

Some common uses of `find` is to delete files that match the pattern. This is so common that `find` has a `-delete` flag. I know it can be accomplished with `--exec rm {} \+`, but it would be nice to save some keystrokes. What do you think? I wouldn't mind trying to implement it if you point me in the right direction. I'm not yet very familiar with Rust though.

**Comment by BrainMaestro** [comment]
Oh. I forgot about the `-x` and it's nice that {} can be skipped. 

`+` basically makes exec behave like xargs.
man page
> -exec command {} +
    This variant of the -exec action runs the specified command on the selected files, but the command line is built by appending each selected file name at the end; the total number of invocations of the command will be much less than the number of matched files. The command line is built in much the same way that xargs builds its command lines. Only one instance of '{}' is allowed within the command. The command is executed in the starting directory. 

Maybe that's the more interesting feature to implement

**Comment by sharkdp** [comment]
Oh right, that was a `find` feature, not a `rm`-argument. Note that `fd` runs commands in parallel, so there is probably a little less need for that feature.

**Comment by lnicola** [comment]
:+1: for adding a `--delete` parameter.
