### ISSUE TITLE
Search without hidden folder but include specific ones?

### ISSUE THREAD

**Issue by Xixiao007** [sharkdp/fd#256]
Hi all,

This is a question rather than issue.
I perceive that `fd` accepts `-H` to search through all hidden files/folders. But my scenario is different:
I want to search in `$home` directory, excluding all hidden files/folders except one specific hidden folder and its sub folder/files.
A command like this `fd  --include-recursive one-hidden-folder $HOME`
Is this viable? I had a look at `man fd`, but didnt figure out.

Thanks,
Xi

**Comment by sharkdp** [comment]
Thank you very much for your feedback.

If you *only* want to search that specific hidden folder, you can simply say:
```
fd <pattern> path/to/.special-hidden-folder
```

If you want to search both your home folder and a specific hidden folder, you can specify multiple search paths:
```
fd <pattern> $HOME path/to/.special-hidden-folder
```

Does this work for you?

**Comment by Xixiao007** [comment]
Hi @sharkdp , thanks for replying!

It seems not resolving exactly.

With your solution, `fd` indexes `special-hidden-folder`, yet without hidden sub files/folders.

I'd like both normal and hidden files/folders are recursively searchable inside the `path/to/.special-hidden-folder`.

**Comment by sharkdp** [comment]
Closing this. Feel free to comment, if you think this has not been resolved.
