### ISSUE TITLE
Add a homebrew formula for fd

### ISSUE THREAD

**Issue by erf** [sharkdp/fd#26]
Add a [homebrew](https://brew.sh) formula for `fd`.

**Comment by sharkdp** [comment]
Thank you for the suggestion.

I don't have access to a MacOS system, so it's hard for me to test this. Also, I don't know how homebrew formulas work.

**Comment by erf** [comment]
I have a macOS, but i have not created a brew formula before and not sure how much time i can spend on this issue right now. I might be able to look into it later, or maybe someone else will have a go at it if you leave it open?

**Comment by sharkdp** [comment]
Sure, I will leave it open. Thank you.

**Comment by gsquire** [comment]
If you are worried about cargo installs falling out of date, you can use [this subcommand](https://github.com/nabijaczleweli/cargo-update) to check.

**Comment by douglascamata** [comment]
PR to add the homebrew formula open.

**Comment by sharkdp** [comment]
Thank you very much! I've just released v1.1.0, in case you still want to include this.

**Comment by douglascamata** [comment]
Updated the version there and fixed some issues commented by maintainers. Should be merged soon.

**Comment by douglascamata** [comment]
Formula was merged! o/

**Comment by sharkdp** [comment]
Cool, thank you very much!

I think we should add a note to the `README` (install instructions) that it is now possible to just run `brew install fd`, if I understand correctly(?).

**Comment by erf** [comment]
Thank you! I can confirm `brew install fd` works on macOS.

**Comment by chhschou** [comment]
@sharkdp I recently did `brew install fd`, it first tries to build rust from source then fd's dependencies. The entire install is around 30min (including compiling rust). Since there are already published packages for `fd` that does not require compiling, will you entertain a new homebrew formula that just install the compiled binary? `ripgrep` already does this here (via a custom homebrew tap that points to its github repo): https://github.com/BurntSushi/ripgrep/blob/master/pkg/brew/ripgrep-bin.rb

**Comment by sharkdp** [comment]
@chhschou I'm open to this idea, but I don't really have any experience with or knowledge about Homebrew. It's probably a good idea to open a new ticket to discuss this.

@douglascamata Do you have any thoughts on this? Could this potentially even be changed upstream?

**Comment by mcint** [comment]
Perhaps I should open a new issue, or support [zfwf's comment]https://github.com/sharkdp/fd/issues/26#issuecomment-408668494) of a binary distribution.  It is a fair bit heavier that I'd like for installing `fd`, to need `llvm`, I suppose depended on by `rust`, and also and especially `ca-certificates`, `openssl`, and `libssh2`. `mpdecimal` seems likely unnecessary too, but not to my knowledge large files, taking a long time to build, overall a slow chain of dependencies to build--where the `rust` brew-installation and its antecedents are.
![Screenshot_20241005_151557](https://github.com/user-attachments/assets/11599851-1e05-45ff-b802-955bc674923f).

It it fair, correct to assume that all of these I've listed are indirect dependencies of `fd` through `rust`?

`fd`
- `rust`
  - `llvm@18`
  - `openssl@3`
  - `libssh2`
  - `ca-certificates`
