### ISSUE TITLE
Integration with Ranger

### ISSUE THREAD

**Issue by 4goodapp** [sharkdp/fd#266]
Can fd be used as an ranger search/filter?

**Comment by sharkdp** [comment]
Could you please elaborate? What is Ranger?

**Comment by 4goodapp** [comment]
It's an CLI based file manager: https://github.com/ranger/ranger
I just find fd, try it and was blown away by its  speed. So the first thing that pop up on m mind is an integration with ranger

**Comment by sharkdp** [comment]
Unfortunately, I'm not familiar with ranger (and its internals). Maybe it would be better to open a ticket for ranger?

If there is anything we can do here, let us know.

**Comment by 4goodapp** [comment]
> Maybe it would be better to open a ticket for ranger?

Sure! that's a good idea. I will let you know.

**Comment by 4goodapp** [comment]
[Done!](https://github.com/ranger/ranger/issues/1118)
