### ISSUE TITLE
Suggestion: filter by executable bit

### ISSUE THREAD

**Issue by mqudsi** [sharkdp/fd#272]
Just a simple suggestion that won't clash with anything that's currently implemented nor obstruct the command line arguments namespace: an additional `-t/--type` filter `x` (`executable`) that restricts matches to executable files. Useful when searching for the binary associated with a package but you don't know its name and don't want a ton of false positives generated by various source, info, help, resource, etc. files.

Thanks for this awesome utility, btw :)

**Comment by sharkdp** [comment]
Hi, thank you for your feedback! 

Filtering by executable bit has already been implemented in fd 7.0: https://github.com/sharkdp/fd/releases/tag/v7.0.0

**Comment by mqudsi** [comment]
Well what do you know!

Thanks :)

**Comment by PeerzadaZeeshan** [comment]
About what??
