### ISSUE TITLE
add "smart ignore" option

### ISSUE THREAD

**Issue by vvuk** [sharkdp/fd#279]
I typically work on projects that have a `build` or `artifacts` dir inside the main source checkout.  These are in `.gitignore`, as they should be.  However, I often then want to find a file inside the build dir, leading to something like `cd build; fd foo.a; wtf where is foo.a; oh right; fd -I foo.a`.

I'd suggest an additional `--smart-ignore` option with the following semantics:
- if cwd is inside a directory that would otherwise be ignored, don't ignore that directory
- if an ignored path is explicitly specified (`fd foo.a build` above), pretend that path is not ignored

This would make `fd` in the toplevel do the right thing, but `fd` inside ignored dirs also do something expected.

**Comment by sharkdp** [comment]
Hi, thank you for the feedback!

> if cwd is inside a directory that would otherwise be ignored, don't ignore that directory

That should work already?

```
> mkdir build
> touch build/foo.a
> echo "/build" > .gitignore
> fd foo.a
> cd build 
> fd foo.a
foo.a
```

> if an ignored path is explicitly specified (fd foo.a build above), pretend that path is not ignored

That should also work out of the box:

```
> fd foo.a build
build/foo.a
```

**Comment by vvuk** [comment]
Hmmm. Indeed.  I dug more into my project's `.gitignore`, and the issue seems to be that I had both `build` and `CMakeFiles` ignored.  So even in the build directory, everything inside `CMakeFiles` dirs further down the tree was being ignored -- as it should be.  I didn't notice that other ignore dir, hence why neither of my examples worked for me... all objects, libraries, etc. are in a CMakeFiles dir.  Whoops.

Apologies for the spam, and thank you for an awesome tool!
