### ISSUE TITLE
Could you add `using fd with Emacs` section into README

### ISSUE THREAD

**Issue by redguardtoo** [sharkdp/fd#281]
See
https://github.com/technomancy/find-file-in-project#use-fd-a-simple-fast-and-user-friendly-alternative-to-find

Usage is simple,
Install `find-file-in-project`, add one line `(setq ffip-use-rust-fd t)` into `~/.emacs`.

Tested on Windows/Linux/Mac.

**Comment by sharkdp** [comment]
Thank you for your feedback.

Sounds good! Maybe we should add this (and the part about `fzf`) into a "Integration with other programs" section?

Would you like to open a PR for this?
