### ISSUE TITLE
Sometimes ignore-file fail on some binary files

### ISSUE THREAD

**Issue by Porkepix** [sharkdp/fd#287]
While trying to investigate another issue (fd completely stuck and doing nothing if running it on the top of the root volume), I ran into another issue.

```
fd --ignore-file /crypto_keyfile.bin ssh /
Error while parsing custom ignore file '/crypto_keyfile.bin': stream did not contain valid UTF-8.
```

File was generated with `dd bs=512 count=8 if=/dev/urandom of=/crypto_keyfile.bin`

**Comment by sharkdp** [comment]
Please not that `--ignore-file` specifies a file in `.gitignore` format:

```
> fd --help

..
        --ignore-file <path>...    
            Add a custom ignore-file in '.gitignore' format. These files have a low
            precedence.
```

To specifically ignore certain files, use the `-E`/`--exclude` option or use a custom `.fdignore` file.

**Comment by Porkepix** [comment]
Yeah, just realized that when I read about that `-E` on the other issue I opened. Read the manpage too quickly, sorry about the unnecessary noise :(

**Comment by sharkdp** [comment]
No worries :smiley:
