### ISSUE TITLE
The links for the deb releases are broken

### ISSUE THREAD

**Issue by mrbig033** [sharkdp/fd#294]
They point to:
* http://fd_7.0.0_i386.deb/
* http://fd_7.0.0_amd64.deb/
* http://fd-musl_7.0.0_i386.deb/
* http://fd-musl_7.0.0_amd64.deb/

**Comment by sharkdp** [comment]
The links on this page: https://github.com/sharkdp/fd/releases ?

They shouldn't be broken unless something was wrong with Github or your browser+extentions?

**Comment by mrbig033** [comment]
You're right. It was [this one](https://chrome.google.com/webstore/detail/mgamelhnfokapndfdodnmfiningckjia). I even tested it with wget, but the extension messed the links for copying too. Sorry about that. Closing.

**Comment by sharkdp** [comment]
No worries :smile:
