### ISSUE TITLE
Reverse symlink lookup

### ISSUE THREAD

**Issue by flip111** [sharkdp/fd#300]
I have a huge directory with many files and many symlinks (pointing to files in the same directory). Given a file i would like to get all the symlinks. I read [here](https://stackoverflow.com/a/4535344/1833322) GNU find can do it with the `-samefile` option. Could such an option be added to fd ?

**Comment by sharkdp** [comment]
Thank you for the feedback!

We could probably add such a feature, but I am not sure that we should. Our goal with `fd` is to handle 80% of the use-cases of `find` in a convenient way, but not all of them (see first section in README). This `find` feature sounds like a <1% use-case for me, to be honest.

**Comment by flip111** [comment]
I understand you. I think handling 80% of the use cases and following pareto's law are not the same. Because pareto's law also says you put 20% of the effort. I have no idea if at the moment the code is at 20% of all the possible code to have all features. Maybe in other words what i'm trying to say is that if you look at it that way it will be cheap to implement some things and not go over the 20% effort. Anyway i can not say if this is the case but i just wanted to mention it. This issue can be closed if you want.

**Comment by sharkdp** [comment]
Thank you for your feedback. I agree with your interpretation of the 20%/80% rule. However, the main reason why I want to stay at 80% of the use cases is *simplicity* - both for the code base and for the command-line interface. This also helps me to keep the future maintenance cost at a reasonable level.

I will close this for now but I'm happy to further discuss this if there should be a strong support for this (now or in the future).

**Comment by edshamis** [comment]
```
fd -H --type l -x zsh -c "[[ $file -ef {} ]] && echo {}"
```

**Comment by hadim** [comment]
I would also like to have that feature!
