### ISSUE TITLE
Find dead symlinks

### ISSUE THREAD

**Issue by flip111** [sharkdp/fd#301]
This command `/usr/bin/find -xtype l -delete` can be used to remove dead symlinks. How can this be done with `fd`?

**Comment by sharkdp** [comment]
Thank you for the feedback!

It can not be done with `fd`. We could probably add such a feature, but I am not sure that we should. Our goal with `fd` is to handle 80% of the use-cases of `find` in a convenient way, but not all of them (see first section in README). This `find` feature sounds like a <1% use-case for me, to be honest. 

It's probably also a once-in-a-while thing and not something you want to execute regularly(?).. which means that it won't hurt to use `find` with a slightly worse performance.

**Comment by flip111** [comment]
Maybe not have `-delete` but have something to find symlinks?

**Comment by sharkdp** [comment]
You can search for symlinks with `fd --type symlink` (or `fd -tl` as a short version). However, this will not specifically search for *dead* symlinks.

Instead of `-delete`, you can use `--exec rm`, or `-x rm` for short (be careful!). If you want to use a safer version, you can use `-x rm -i`.

**Comment by flip111** [comment]
Maybe someone knows something to put after `--exec` that implements `delete only if symlink is dead`. Anyway let's close this too for the moment.

**Comment by sharkdp** [comment]
@flip111 It is actually now possible to search for dead symlinks by running
```
fd --follow --type symlink
```
or short:
```
fd -L -tl
```
Note that this has not yet been release (only available on `master`).
