### ISSUE TITLE
fd doesn't return anything

### ISSUE THREAD

**Issue by keith24** [sharkdp/fd#302]
I dunno, just seems to come up empty every time.  

```sh
$ ls
audio  bin  books  code  Desktop  docs  images  man  msc  photos  resume  videos  vm
$ fd -V
fd 7.0.0
$ fd -h
fd 7.0.0

USAGE:
    fd [FLAGS/OPTIONS] [<pattern>] [<path>...]

FLAGS:
    -H, --hidden            Search hidden files and directories
    ...
$ fd
$ fd docs
$ fd resume
$ touch newfile
$ ls newfile
newfile
$ fd newf
$ fd newfile
```

**Comment by sharkdp** [comment]
`fd` will not show files which are ignored by `git`. Please check if you have any `.gitignore` files that could cause these files not to show up.

You can disable this feature by using `--no-ignore` or `-I`.

**Comment by keith24** [comment]
Without checking, I'm sure that's it.  I have a wildcard .gitignore in my home folder.
