### ISSUE TITLE
running fd in home directory only finds dotfiles

### ISSUE THREAD

**Issue by klassegeljakt** [sharkdp/fd#305]
I have installed fd version 7.0.0 on macOS High Sierra 10.13.3, and when I run the following command:

```
cd; fd
```

The only output I get is dotfiles. If I run it in other directories it is able to find regular files and directories. Is this intended behaviour?

**Comment by sharkdp** [comment]
Do you have any `.gitignore` files (in your home directory or above) that might affect the search? Maybe one with a catch-all `*` pattern?

**Comment by klassegeljakt** [comment]
Oh woops,I keep a gitignore for the dotfiles, it seems like `fd --no-ignore` solves it!
