### ISSUE TITLE
results for  -p '.{178,}'  includes paths that have fewer characters

### ISSUE THREAD

**Issue by 517qf** [sharkdp/fd#306]
I want to find all paths (combination of directories+filenames) that have more than 178 characters. 

For find (from GNU findutils 4.7.0 bundled with Debian9) I would use `find -regextype posix-extended -regex '.{178,}'` ([source](https://unix.stackexchange.com/a/61202)). 

The command `fd -p '.{178,}'` (-p = --full-path = Search full path) shows more hits: When I redirect the output into a file and view this file in my texteditor the editor shows me that many lines have a length of less than 177. I used fd from the release fd-v7.0.0-x86_64-unknown-linux-gnu.tar.gz. I tested on Debian 9.

I wonder which mistake I made? Do I misundersand the option -p? Is there a problem with my regex?

**Comment by sharkdp** [comment]
The `-p`/`--full-path` option searches the whole *absolute* path while `find` searches the relative path (if you don't specify an absolute path as argument). Could this explain the differences?

**Comment by 517qf** [comment]
That was it. Thank you very much for your answer. I should have seen this. Sorry for wasting your time.

**Comment by sharkdp** [comment]
thank you for your feedback
