### ISSUE TITLE
Command not found error under Windows 10 with `--exec`

### ISSUE THREAD

**Issue by HeapUnderfl0w** [sharkdp/fd#310]
OS: Windows 10 Pro x64 (Version 1803 / OS Build 17134.112)
rustc: rustc 1.28.0-nightly (e3bf634e0 2018-06-28)
fd: v7.0.0

I am unable to use the `--exec` / `-x` function under windows, as *any* command just gives me the error
`fd: execution error: command not found`. I tested this under both Powershell and cmd.exe, both give the same error.

Example:
![example_image](https://user-images.githubusercontent.com/28512568/42285253-46cd60ea-7faf-11e8-9653-3adb5ce2fc1f.png)

**Comment by sharkdp** [comment]
You need to use `fd -x echo` or `fd -x echo "{}"`. Otherwise, `fd` is searching for the command `echo {}`.

**Comment by HeapUnderfl0w** [comment]
It actually does not make a difference if i use either `"echo {}"`, `echo {}` or `echo "{}"`.
All generate the same error as described above.
![image](https://user-images.githubusercontent.com/28512568/42292416-a54b6036-7fd2-11e8-9d9c-77f981342a1d.png)
I also tried appending `;` or `\;`to all of those, none did work.

**Comment by sharkdp** [comment]
The problem seems to be that `echo` is a shell builtin on Windows and not a proper command. Could you please try this with an actual command (not a shell function)? As a workaround, you can create a `echo.bat` script which you can call via `fd -x ./echo.bat`.

On Linux, `echo` is typically also a shell builtin but there is also `/bin/echo` (from GNU coreutils), which is a proper executable.

**Comment by HeapUnderfl0w** [comment]
That seems to also be what i have read while researching this bug.

I have created a `echo.bat` file, with these contents:
```batch
@echo off
echo %*
```
Now there is some unexpected output.

if i execute the command `fd ".*" ..\fd\ -x .\echo.bat "{}"`
The output looks as expected (it is the same when i use `cmd /C echo "{}"` instead of `.\echo.bat "{}"`)
![image](https://user-images.githubusercontent.com/28512568/42342989-0564246a-8098-11e8-95e2-368a3cea9075.png)

But if i simply forgo the `""` around the `{}` then i get some wierd artifacts before the path:
![image](https://user-images.githubusercontent.com/28512568/42343064-32be00f2-8098-11e8-8990-d32152236396.png)

i do think that this can and will lead to severe confusion about unexpected behavior while using fd under windows.

**Comment by sharkdp** [comment]
Braces (`{`, `}`) are [part of PowerShell's syntax](https://mcpmag.com/articles/2014/01/21/syntax-part-3.aspx), so you always need to escape them if you want to pass them to any command (in their literal form). This is not a problem with `fd` but something you always have to take care of if you are using a shell. `echo {}` will also not do what you expect. If in doubt, always use quotes.

**Comment by HeapUnderfl0w** [comment]
oh ok, well i'll accept the workaround with as a solution.

Thank you for your patience.

**Comment by HeapUnderfl0w** [comment]
PS. Actually using the back-tics <code>&#96;</code> to escape <code>{}</code> does yield the expected results. (<code>&#96;{&#96;}</code>).

**Comment by hinogi** [comment]
Also an issue here
https://github.com/cljoly/telescope-repo.nvim/issues/43

**Comment by hinogi** [comment]
`fd --hidden --case-sensitive --absolute-path --exec powershell /C "echo {//}" ; ^\.git$` this seems to work on windows and powershell

**Comment by maaaaz** [comment]
This is incredibly misleading !
