### ISSUE TITLE
Optionally allow pattern elision

### ISSUE THREAD

**Issue by studoot** [sharkdp/fd#312]
This is related to #235 - maybe it's just me, but I search for files by just their extension often enough that when I see the warning below, I wish yet again that `fd` could fill in the match-all pattern for me...

```
Error: The search pattern '/mnt/e/code/vcpkg/' contains a path-separation character ('/') and will not lead to any search results.

If you want to search for all files inside the '/mnt/e/code/vcpkg/' directory, use a match-all pattern:

  fd . '/mnt/e/code/vcpkg/'

Instead, if you want to search for the pattern in the full path, use:

  fd --full-path '/mnt/e/code/vcpkg/'
```

Having an option to enable this feels beneficial (if only to me, I guess!). Maybe only in the case that a filtering option (such as `-e` or `-t`) has also been used?

**Comment by sharkdp** [comment]
Interesting idea. I have to admit that I also see this error from time to time :smile:.

What I definitely want to avoid is any sort of ambiguity (or confusion on the user side). I think it would be quite unfortunate that the following two commands would do completely different things:

```
fd -e txt docs/  # Search for "*.txt" in the "docs" folder
fd -e txt docs   # Search current directory for entries matching "docs" and "*.txt"
```

**Comment by sharkdp** [comment]
This is related to both #315 and #277.

**Comment by sharkdp** [comment]
The `--path-before-pattern` doesn't feel very natural for me. I'm going to close this as "won't fix" for now. If someone comes with a better idea, I'm happy to reconsider this.

**Comment by cup** [comment]
https://github.com/sharkdp/fd/issues/235
https://github.com/sharkdp/fd/issues/277
https://github.com/sharkdp/fd/issues/312
https://github.com/sharkdp/fd/issues/385
https://github.com/sharkdp/fd/pull/259
https://github.com/sharkdp/fd/pull/349

**Comment by dezza** [comment]
I think the error is really badly worded, overly long and confusing. It makes no sense to me that you should have the first arg for this functionality (_go back and put current dir (.) first, what?_)

```
[fd error]: The search pattern '/home/dza/src/' contains a path-separation character ('/') and will not lead to any search results.

If you want to search for all files inside the '/home/dza/src/' directory, use a match-all pattern:

  fd . '/home/dza/src/'

Instead, if you want your pattern to match the full file path, use:

  fd --full-path '/home/dza/src/'
```

This error shouldn't exist.

It should be

```
fd -type d /home/dza/src # find all dirs
```

Like find.

**Comment by tmccombs** [comment]
> go back and put current dir (.) first, what?

In this context, it isn't the current directory, it is a regex that matches any single character, and thus matches any file. An empty string would actually work just as well.

> It should be ... like find


fd is not find.

It assumes the first argument is a regex pattern to search for, and its syntax is more similar to grep (and ripgrep) than find.  Was that the best decision? I don't know. But at this point, I don't think it is viable to change it.

**Comment by dezza** [comment]
Some things can definetily be improved - especially regarding arguments, documentation, error messages, ordering or inferred arguments.

> fd is not find.

But this *is* how fd promotes itself. Faster, *better*, *more* intuitive.

[**README:**](https://github.com/sharkdp/fd?tab=readme-ov-file#features)

> Intuitive syntax: fd PATTERN instead of find -iname '*PATTERN*'

But `fd` in many *is not* intuitive for the simplest args from find. Often feels like its just being difficult and working against you as you battle its quirks as a new user;

```console
dza:~ $ fd --type f sampledir/
[fd error]: The search pattern 'sampledir/' contains a path-separation character ('/') and will not lead to any search results.

If you want to search for all files inside the 'sampledir/' directory, use a match-all pattern:

  fd . 'sampledir/'

Instead, if you want your pattern to match the full file path, use:

  fd --full-path 'sampledir/'
```

and the last command `fd --fullpath` suggested actually works in this case, but the former `fd . 'sampledir/'` doesn't - *without* highlighting the order of the arguments in the error-message, just repeating the usage message would be a great help in deciphering it, if the suggestions also leaned into that style:
`Usage: fd [OPTIONS] [pattern] [path]...`

```console
dza:~ $ fd . --type f 'sampledir/*'
[fd error]: Search path 'sampledir/*' is not a directory.
[fd error]: No valid search paths given.
```

```console
dza:~ $ fd . --type f sampledir/*
[fd error]: Search path 'sampledir/zerofile' is not a directory.
[fd error]: Search path 'sampledir/moo' is not a directory.
[fd error]: Search path 'sampledir/foo' is not a directory.
```

```console
dza:~ $ fd --type f --size=0 . sampledir/
error: invalid value '0' for '--size <size>': '0' is not a valid size constraint. See 'fd --help'.

For more information, try '--help'.
```

You go to the man-page, its not answering this issue - `size=0` common pattern in find;

```
       -S, --size size
              Limit results based on the size of files using the format <+-><NUM><UNIT>

              '+'    file size must be greater than or equal to this

              '-'    file size must be less than or equal to this

              If neither '+' nor '-' is specified, file size must be exactly equal to this.

              'NUM'  The numeric size (e.g. 500)

              'UNIT' The units for NUM. They are not case-sensitive.  Allowed unit values:

                     'b'    bytes

                     'k'    kilobytes (base ten, 10^3 = 1000 bytes)

                     'm'    megabytes

                     'g'    gigabytes

                     't'    terabytes

                     'ki'   kibibytes (base two, 2^10 = 1024 bytes)

                     'mi'   mebibytes

                     'gi'   gibibytes

                     'ti'   tebibytes
```

Mentioning it here or in the returned error-message that refers here not once, but twice over 3 lines which doesn't explain the issue.

```console
dza:~ $ find -type d . # wrong
find: paths must precede expression: `.'
find: possible unquoted pattern after predicate `-type'?
$ find . -type d # correct
.
./sampledir
dza:~ $ find . -type f -size 0 # works by default
./sampledir/zerofile
```

```console
dza:~ $ find sampledir/* -type f | wc -l # works
163
dza:~ $ find sampledir/* -type f | wc -l # works
163
```

> Was that the best decision? I don't know. But at this point, I don't think it is viable to change it.

I think these are logical quirks.

Finally, why not allow `-type` for backwards compat, old habits? I feel like if `fd` sells itself on improving `find` it can learn a lot from `findutils` crafted helpful usage / invalid argument feedback loop.
