### ISSUE TITLE
ARM static binary

### ISSUE THREAD

**Issue by babam86** [sharkdp/fd#320]
Please provide arm static binary.

Thanks.

**Comment by sharkdp** [comment]
Thank you for the feedback.

I believe this could be achieved by repeating/adapting what I did in 6fb5004b850f3bf898605d65cc44e94fb08691f8 for the `arm-unknown-linux-musleabihf` target (instead of `arm-unknown-linux-gnueabihf`).

Any help would be greatly appreciated.

**Comment by babam86** [comment]
TARGET=armv7-unknown-linux-musleabihf

I will use fd on my Android (armv7).

Thanks.

**Comment by sharkdp** [comment]
If I understand correctly, the `arm-unknown-*` targets support both armv7 and armv6.

**Comment by duncanfinney** [comment]
> If I understand correctly, the `arm-unknown-*` targets support both armv7 and armv6.

Yep! `arm-unknown-` builds armv5. The newer arm versions are all backwards compatible (I think even armv8 if it's running in 32-bit mode).

**Comment by sharkdp** [comment]
Closed via #320 by @duncanfinney. The next `fd` release will include a statically linked ARM binary.
