### ISSUE TITLE
FZF_CTRL_T_COMMAND not working with zsh and kitty.

### ISSUE THREAD

**Issue by aranmohyeddin** [sharkdp/fd#321]
My shell is zsh and my terminal is kitty.
Here is what I have in my .zshrc
```
export FZF_DEFAULT_OPTS="-m --inline-info --ansi --height 40% --reverse --bind 'ctrl-o:execute(rifle -- {} < /dev/tty)+abort,ctrl-y:execute-silent(echo -n {} | xclip -selection clipboard)+abort'"
export FZF_DEFAULT_COMMAND='fd --type f --color=always --follow --hidden'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```
I open a new kitty, I run:
```
$ echo $FZF_CTRL_T_COMMAND 
fd --type f --color=always --follow --hidden
```
So the environment variables are set. then I type vim and press ctrl+t and nothing happens. Did I misunderstand anything?

**Comment by sharkdp** [comment]
Does Ctrl-T work without `fd` in the command? Does it work with the default settings?

I doubt that this is an issue with `fd`?

**Comment by aranmohyeddin** [comment]
I don't understand your comment.
is ctrl-T ctrl+shift+t or ctrl+t because the former is my terminals shortcut for a new tab.
what doe you mean by work exactly? what I expected was that if I do type 'vim ' and then press ^t fzf will open with fd as default command and then I can chose what file I want to open with vim from there.
I don't understand what you mean by does without fd in the command do you mean without fd as FZF_DEFAULT_COMMAND?
I also don't think that this is an issue with fd but rather an issue with your readme.md because the only place I see and mention of FZF_CTRL_T_COMMAND is in your readme.md so I thought I'd ask here. Because I did as your instructions but it didn't do anything so I thought I'd ask if I have done anything wrong.

**Comment by sharkdp** [comment]
Well you first need to make sure that fzf works for you (without trying to combine fzf and fd). Please see fzf's instructions first: https://github.com/junegunn/fzf

**Comment by sharkdp** [comment]
I'm going to close this. Please feel free to comment here, if you feel that this has not been resolved.
