### ISSUE TITLE
About the chinese readme.md 😊

### ISSUE THREAD

**Issue by chinanf-boy** [sharkdp/fd#322]
## repo

https://github.com/chinanf-boy/fd-zh

**Comment by sharkdp** [comment]
Cool! :+1: :smile: 

Thank you very much!

**Comment by sharkdp** [comment]
I'm going to close this, as I don't really know what do do here. If the chinese README is up to date and you want to add a (small, discrete) link in the README here, feel free to open a PR.

Thank you!
