### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by tjvanpat** [sharkdp/fd#329]
`fd` is not able to find a file that `find` can.

```
~/code/chromium/src$ fd test.apl
test.apl

~/code/chromium/src$ find . -name test.apl
./out/Debug/test/test.apl
./out/Debug/test.apl
./out/test.apl
./test.apl
```

It seems that `fd` is not able to look any deeper than `out/`, which is just a normal directory.

```
~/code/chromium/src$ ls -ld out/
drwxr-xr-x 3 <user> primarygroup 4096 Sep 26 16:31 out/
```

`fd` is able to find files in other directories within this same path; it seems to be something unique to `out/`.   Once I `cd` into `out/`, `fd` is able to find everything.

```
~/code/chromium/src/out$ fd test.apl
Debug/test/test.apl
Debug/test.apl
test.apl
```

Let me know if there's something I'm doing wrong or what else I can include that would be helpful.

```
timvp@timvp:~/code/chromium/src$ fd --version
fd 7.1.0
```

**Comment by tmccombs** [comment]
Do you have a .gitignore that is ignoring the out directory? By default fd won't search any folders (or files) that are ignored by .gitignore.

**Comment by tjvanpat** [comment]
Ah, yup, that's it.   I'll need to do a better job of RTFM next time.   Adding the following alias should save me some trouble looking for generated binaries in the future:

```
alias fd="fd --no-ignore"
```

Thanks for the help.

**Comment by SuperSandro2000** [comment]
I would invert the ``--no-ignore`` flag.
