### ISSUE TITLE
Consider making the CLI arguments consistent with ripgrep

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#33]
For example: *fd*'s `-I/--no-ignore` vs *ripgrep*'s `-u/--unrestricted`.

(via DebuggingPanda on reddit)

**Comment by sharkdp** [comment]
Let's consider all of *fd*'s current command-line options:
* [x] `-a`/`--absolute-path` => not related to ripgrep
* [ ] `-s`, `--sensitive` => ripgrep uses `-s`, `--case-sensitive` => change to ripgreps format
* [x] `-f`, `--follow` => ripgrep also uses `--follow`, but uses `-L` for the short flag (like `find`). I find this rather unintuitive... => stay with current format for now
* [x] `-p`, `--full-path` => not related to ripgrep
* [x] `-H`, `--hidden` => ripgrep also uses `--hidden`, there is no short flag
* [ ] `-n`, `--no-color` => ripgrep uses `--color never` because there are more options => we would need to implement `--color always` and `--color auto` (*fd*s default) first.
* [x] `-I`, `--no-ignore` => ripgrep also uses `--no-ignore`, there is no short flag

Considering *ripgrep*'s options, there is
* [ ] `-u`, `--unrestricted`: an alias for `--no-ignore` => could be implemented
* [ ] two occurences of `-u`/`--unrestricted`: an alias for `--no-ignore --hidden` => could be implemented
* [x] three occurences ...: not relevant for *fd*

**Comment by epipping** [comment]
@sharkdp Using -L for following/dereferencing (i.e., treating a symlink like the object that it points to) is rather common. And it's not uncommon that the single-letter option does not use the first letter of the option name: 

- GNU **ls** has `-L, --dereference` and BSD **ls** also uses `-L` for this purpose
- GNU and BSD **find** both have `-L` and `-follow` (the latter is deprecated)
- GNU **cp** has `-L, --dereference` and BSD **cp** also uses `-L`.
- **rsync** has `-L, --copy-links` which behave in a similar fashion.

I would thus like to suggest sticking with `-L, --follow`.

(it's a bit of a stretch but one could even argue that **curl**'s `-L, --location` fits the pattern if you view redirects as symlinks).

**Comment by sharkdp** [comment]
@epipping Fair points, you convinced me. Changed the action above.

**Comment by sharkdp** [comment]
`-L` is now the short-option for `--follow`. `--dereference` can be used as an alias.

**Comment by unhammer** [comment]
I'd also love to have the `-u` / `-uu` as in ripgrep – it's annoying enough the first time you don't find something because it's in .gitignore, so it'd be nice if the UI to turn it off were consistent with other "modern unix tools" you're likely to have :-)

**Comment by sharkdp** [comment]
I would like to keep the command-line interface as clean and simple as possible (i.e., I don't want the `-h` text to be several pages long), but adding `-u` seems like a good idea. We could possible hide it from the standard `-h` text and add it as a hidden option that would only be mentioned in a man page. It would be great if you could open a new ticket to track this.
