### ISSUE TITLE
Disable filesystem errors by default

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#348]
We recently introduced error messages for things like wrong permissions (on `master`, not released yet). I think we should actually disable them again (by default), but add a new command-line option to enable them. I don't want to `2> /dev/null` all the time.

**Comment by majecty** [comment]
I want to handle this issue.

Could we add `--verbose` option to print errors?

**Comment by DTibbs** [comment]
I started taking a crack at this. It's a bit more challenging than expected to redirect the current process's stderr io within Rust. Would using a custom panic! that is conditionally set be acceptable? This would mean actual panics, without specifying the command-line option, would also be suppressed.

**Comment by sharkdp** [comment]
> Could we add `--verbose` option to print errors?

Yeah, something like `--show-errors` or `--verbose`.

@DTibbs 
> I started taking a crack at this.

I think @majecty is already working on this: #350 

> It's a bit more challenging than expected to redirect the current process's stderr io within Rust.

We don't want to do this.

> Would using a custom panic! that is conditionally set be acceptable? This would mean actual panics, without specifying the command-line option, would also be suppressed.

I'd prefer an actual error handling without relying on such tricks.

**Comment by sharkdp** [comment]
Closed via #350
