### ISSUE TITLE
Question: Find file and grep content - on stdout print just file name

### ISSUE THREAD

**Issue by waldauf** [sharkdp/fd#352]
Hello,

is there option how to use fd with grep but don't print content of grepped lines just print file name?
```
fd -e md -x grep -q STRING 
```

Example of find where is used _-print_ option: 
```
find . -type f -name "*.md" -exec grep -q STRING '{}' \; -print
```

**Comment by sharkdp** [comment]
There are several options:

* Use ripgrep (maybe `ag` or `grep` would work too). This is exactly what it is made for (search in files):
  ```
  rg -T md -l STRING
  ```
  The `-l` option tells it to only print the file name.

**Comment by sharkdp** [comment]
There are several options:

* Use ripgrep (maybe `ag` or `grep` would work too). This is exactly what it is made for (search in files):
  ```
  rg -T md -l STRING
  ```
  The `-l` option tells it to only print the file name.
* Use `grep`s `-l` option:
  ```
  fd -e md -x grep -l STRING
  ```

**Comment by waldauf** [comment]
Great! Many thx for your exhaustive answer. :]
