### ISSUE TITLE
Documentation and differentiation of `--no-ignore-vcs` and `--no-ignore`

### ISSUE THREAD

**Issue by HaleTom** [sharkdp/fd#354]
The man page says:

```
       -I, --no-ignore
              Do not respect files like .gitignore and .fdignore and include ignored files in the search results.

       --no-ignore-vcs
              Do not respect version control ignore files like .gitignore and include the respective entries in the search results.
```

1. Where is the list of `files like...` that are normally respected?  (The wording makes me wonder if there are other files ending in `ignore` which are usually looked at)
2. Is `-I` a strict superset of `--no-ignore-vcs`?

**Comment by sharkdp** [comment]
Thank you very much for your feedback. This topic definitely needs some clarification.

> * Where is the list of `files like...` that are normally respected?  (The wording makes me wonder if there are other files ending in `ignore` which are usually looked at)

There are six sources for ignore patterns:
1. `.gitignore` files
2. `.git/info/exclude` files (these are like user-specific `.gitignore` files that are not shared with the rest of the world)
3. The global `gitignore` configuration (`core.excludesFile` git setting, defaults to `$HOME/.config/git/ignore`)
4. `.ignore` files (things you would like to ignore across tools like `fd`, `ripgrep`, `ag`, etc. that are not part of your `.gitignore`)
5. `.fdignore` files (things you would only like to be ignored by `fd`)
6. Manually added ignore patterns via `--exclude <pattern>` or `--ignore-file <path>` (things you would only like to be ignored in this specific run of `fd`)

The `--no-ignore` option switches off 1-5.
The `--no-ignore-vcs` option switches off 1-4.

> 2\. Is `-I` a strict superset of `--no-ignore-vcs`?

Yes.

---

Sources:
- https://docs.rs/ignore/0.4.4/ignore/struct.WalkBuilder.html#ignore-rules
- https://git-scm.com/docs/gitignore

**Comment by calebcordry** [comment]
I am not sure how common of a use case it is, but personally I would like the ability to turn on `1.` and turn off `2.`. (I want to respect my projects .gitignore, but I have my own scratchpad type files I would like to index, but never commit).

Is this possible with the current API? Is there something like an `--include` that I am missing?

**Comment by calebcordry** [comment]
I found the `--no-ignore` flag, but it "no ignores" everything, it would be cool to be able to specify certain paths to `--no-ignore` like you can with the `--ignore-path` flag.

BTW: Thanks for the awesome tool!!! 😁

**Comment by tmccombs** [comment]
Not a perfect solution. But as a workaround, you could use an ignore file (either .fdignore or with --ignore-path) that explicitly includes your scratchpad files.
