### ISSUE TITLE
Doesn't work on specific directory

### ISSUE THREAD

**Issue by AhmedKamal20** [sharkdp/fd#356]
in what condition `fd` doesn't work ?
I have this situation :

`ls -lah data`
```
total 72M
drwxrwxr-x 4 akamal akamal 4.0K Nov  5 16:21 .
drwxrwxr-x 5 akamal akamal 4.0K Nov  5 13:04 ..
drwxrwxr-x 5 akamal akamal 4.0K Oct 14 16:55 flight-data
drwxr-xr-x 2 root   root   4.0K Nov  5 16:21 retail-data
```
`fd data`
```
data
```
`fd flight-data`
```

```

it isn't even a sym/hard link ?
any explanation ?

Thank You.

**Comment by sharkdp** [comment]
Is there a `.gitignore` file that could affect the search results? `fd` ignores results `.gitignore`-d results, by default. You could try `fd -I`/`fd --no-ignore` to check if this is the case.

**Comment by AhmedKamal20** [comment]
Actually, i have it in `.gitignore` indeed, sorry for not reading the README carefully.
However, i feel it's a bit confusing.

Thank You.
