### ISSUE TITLE
Reproducible benchmarks

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#36]
For example:
- Generate a lot of dummy files / directories in a controlled way by a shell script and run specific benchmarks within this test folder.
- Clone a certain (big) repository and run benchmarks within this repository (this is not 100% reproducible).

**Comment by jrobeson** [comment]
As per https://github.com/sharkdp/fd/issues/30 you might also want to bench against network  filesystems like NFS and SMB. And also against sshfs and other FUSE filesystems.

**Comment by lnicola** [comment]
One thing I noticed is that `fd` calls `stat` three times for each file.

**Comment by sharkdp** [comment]
> One thing I noticed is that fd calls stat three times (and lstat once) for each file.

Good catch!! This should be fixed on master (via adaf4f6d73aa6935d381a4eb9be647815aeb46cd), i.e. `fd` should perform only one `lstat` and one `stat` call.

Note: those syscalls are only necessary when colored output is active (in order to check if the entries are symlinks, directories, executables or normal files).

**Comment by lnicola** [comment]
I think it does a `lstat` via `walkdir` and one `stat` per path component in `print_entry`.

But I'm not sure that's a good idea. Don't we care only about the leaf component? Presumably, non-leaf ones are directories and we only want to check the type of the file.

**Comment by sharkdp** [comment]
> Don't we care only about the leaf component?

Well, currently `fd` can do this (i.e. colorize "symlink1" as a symlink):

![image](https://user-images.githubusercontent.com/4209276/30557324-309464c0-9cae-11e7-8124-7cf9a79bf6bf.png)

**Comment by lnicola** [comment]
Yeah, that might be useful, I suppose. I wasn't sure what `fd` is supposed to do with symlinks:

```
 grayshade@ubik  ~/foo  ll
total 1.0K
drwxr-xr-x 2 grayshade grayshade 2 Sep 18 22:32 bar
lrwxrwxrwx 1 grayshade grayshade 3 Sep 18 22:32 baz -> bar
 grayshade@ubik  ~/foo  fd . baz
bar
```

**Comment by sharkdp** [comment]
If somebody has any ideas on how to proceed on this, I'd love to hear them!

Here are the two benchmark scripts that I have so far:

https://gist.github.com/sharkdp/4bc3e5f5ea9df2f29c02ede50634b16a

**Comment by avently** [comment]
On my system fd is slower than find. After multiple starts:
fd -HI -c never zsh         //2.3-2.4 sec 
find . -name "*zsh*"       //1.9 sec

**Comment by sharkdp** [comment]
@avently Thank you for the feedback! Could you please give a little bit of background information?

- Which version of fd are you using (`fd -V`)?
- How many cores does your system have (`nproc`)?
- Which OS?
- Anything specific about the directory that you perform the search in (e.g.: what kind of physical device is it placed on)?

**Comment by avently** [comment]
@sharkdp 
4.0.0
2 cores and 4 threads (Intel i3)
Manjaro (Arch-based)
home directory (~/), ext4 mounted from the same HDD as the system,  630000 files

**Comment by sharkdp** [comment]
@avently Thanks!

I just now looked at your command more closely. Note that these two commands do something quite different:

`find . -name "zsh"` will look for files whose name is exactly "zsh" (case-sensitive)

`fd -HI -c never zsh` will look for files whose filename matches the regular expression "zsh" (anywhere, case-insensitive).

To have a fair comparison, you should consider running either `find . -iregex '.*zsh.*'` or `fd -HI -s -c never '^zsh$'`.

If you are interested, you could try experimenting with different numbers of threads via the `-j n`/`--threads n` option. Default should be 4 for you.

**Comment by avently** [comment]
@sharkdp the command i used for test was
find . -name "*zsh*"
I just wrote here the wrong one. 
As i understand it's the same as 
fd -HI -c never zsh
but case-sensitive

**Comment by sharkdp** [comment]
Oh I see, Markdown was interpreting `*zsh*` as italic *zsh* :smile:

In this case, they are the same (except for case-sensitivity). But note that *fd* does regex-by-default.

**Comment by avently** [comment]
@sharkdp fd use  344% cpu, find use 96% cpu for those queries.
But if i use regex search:
find . -iregex '.*zsh.*'
system 99% cpu 5,436 total

fd is winner in the regex search.

**Comment by sharkdp** [comment]
I'm going to close this, as we have this now: https://github.com/sharkdp/fd-benchmarks
