### ISSUE TITLE
fd doesn't show substituted drive on Windows

### ISSUE THREAD

**Issue by thorstenkampe** [sharkdp/fd#365]
fd on Windows shows the real path on a substituted drive, not the substituted one:
```
pwsh> subst
F:\: => C:\data\flash drive

pwsh> cd \
pwsh> pwd

Path
----
F:\

pwsh> fd.exe --absolute-path
C:\data\flash drive\ARCHIVE
[...]
```

**Comment by sharkdp** [comment]
Thank you for the feedback. I'm not a Windows user myself, so I cannot judge the significance of this. How do other tools behave? How big of a problem is this?

**Comment by thorstenkampe** [comment]
Say you would bind mount `/usr/local/bin` to `~/bin`. Then you do an `absolute-path` search in `~/bin` but all the results are prefixed with `/usr/local/bin` instead of `/home/user/bin`. Highly irritating.

**Comment by thorstenkampe** [comment]
Cygwin `readlink` uses the substituted drive:
```
> cd /cygdrive/f
> readlink.exe -f Autorun.inf
/cygdrive/f/Autorun.inf
```

**Comment by sharkdp** [comment]
Does this work if the CWD is `F:\`?

**Comment by thorstenkampe** [comment]
It does not work when I'm on F:\. As described in my first note:
```
[...]
pwsh> pwd

Path
----
F:\
[...]
```

**Comment by sharkdp** [comment]
Ok, thank you.

I'm not going to work on this myself as I don't have a Windows machine to develop on. Also, I don't have an idea on how to fix this.

**Comment by sharkdp** [comment]
I believe this might be fixed by #811. Please feel free to re-open this, if it still exists.

A build from the #811 branch:
[fd-v8.2.1-x86_64-pc-windows-msvc.zip(1).zip](https://github.com/sharkdp/fd/files/6950727/fd-v8.2.1-x86_64-pc-windows-msvc.zip.1.zip)

**Comment by thorstenkampe** [comment]
fixed

**Comment by sharkdp** [comment]
Awesome. Thank you for the feedback!
