### ISSUE TITLE
Add `mdfind` Benchmark for macOS.

### ISSUE THREAD

**Issue by wangjiejacques** [sharkdp/fd#367]

**Comment by sharkdp** [comment]
If you are requesting actions like this without even bothering to add a description to the ticket, you are not very likely to get a helpful response. I will try anyway.

I'm not a macOS user myself, so I had to search for `mdfind`. I guess you are refering to [this tool](https://www.unix.com/man-page/all/1/mdfind/)? If so, it looks like it is using a central metadata storage as a backend.

In this case, `mdfind` would be comparable to `locate`/`updatedb`, but not really to `find` or `fd`. I would assume that `mdfind` is much faster if it's backed by a cache, but it would also come with all the downsides.

Even if it is a tool which is comparable to `find` and `fd`, I don't feel "obliged" to add it to the benchmarks but if someone is interested in that, I'm very open to adding links or integrating more benchmarks in the README.

**Comment by wangjiejacques** [comment]
Hi, @sharkdp my apologies, I didn't think carefully about this issue.
Thanks for you patient explanation.

**Comment by sharkdp** [comment]
Ok, thank you for the feedback.
