### ISSUE TITLE
Exclude System entries with Windows

### ISSUE THREAD

**Issue by cup** [sharkdp/fd#372]
Compare FD:

~~~
C:\> fd -d 1
$Recycle.Bin
Documents and Settings
PerfLogs
Program Files
Program Files (x86)
ProgramData
Recovery
Users
Windows
pagefile.sys
~~~

With Command Prompt:

~~~
C:\> dir /A:-S
2009-07-13  09:20 PM    <DIR>          PerfLogs
2018-12-15  06:05 PM    <DIR>          Program Files
2018-12-15  05:21 PM    <DIR>          Program Files (x86)
2018-10-31  06:07 PM    <DIR>          ProgramData
2018-11-18  01:10 AM    <DIR>          Users
2018-11-09  08:18 AM    <DIR>          Windows
~~~

as can be seen, Command Prompt has a way to exclude System items. Does FD have
some way to do this?

**Comment by sharkdp** [comment]
Thank you for the feedback.

There is no direct way to do this with `fd`, no. It looks like we could - in principle - implement this by using the Windows-specific [`file_attributes` function](https://doc.rust-lang.org/stable/std/os/windows/fs/trait.MetadataExt.html#tymethod.file_attributes), filtering by [`FILE_ATTRIBUTE_SYSTEM`](https://docs.microsoft.com/de-de/windows/desktop/FileIO/file-attribute-constants) (?)

On the other hand, I'm not very keen on adding (more) operating-specific features to `fd`. We would probably also have to add a new command-line option for this (or somehow use `--type`). All in all, it doesn't really look like a feature that is part of the *"80% of the use-cases"* (see README).

One way to achieve the same goal could be to create a custom `.fdignore` file that would be enabled by default or via `--ignore-file <path>`.

**Comment by sirikid** [comment]
Dot files are not a Linux specific feature, they are widely used in Unix(-like) systems.

**Comment by cup** [comment]
@sirikid thats a semantic argument.

**Comment by sharkdp** [comment]
> @sharkdp I think what you mean to say is "adding (more) Windows-specific"
> features.

No. I meant to say OS-specific.

> however on Windows, `fd` goes ahead and shows everything, hidden or not:

I didn't know that Windows has an additional meaning of "hidden" file. If you think this is something we should fix, please open a new ticket. We would have to discuss whether or not to treat *both* leading-dot-files and Windows-hidden files as "hidden".

> and `fd` has neglected the **Windows-specific** feature of signaling hidden and
> system items via file attributes.

Why the negative language? This was never discussed and was certainly not done on purpose. As I said, if you think that this should change, please open a new ticket concerning hidden files on Windows.


Coming back to this specific feature request: I don't see any strong reason to add a new command line option for filtering out system-related files (on Windows). `fd` does not aim to provide filters/functionality for each and every use case (see README). If there is a nice way to integrate/combine this with exiting functionality (such as the `--type` option or the requested `--user`/`--owner` option in #307), let me know.

**Comment by cup** [comment]
https://github.com/sharkdp/fd/issues/379

**Comment by cup** [comment]
https://github.com/BurntSushi/ripgrep/issues/1154
https://github.com/sharkdp/fd/issues/372
https://github.com/sharkdp/fd/issues/379

**Comment by sharkdp** [comment]
Closing this in favor of #379
