### ISSUE TITLE
fd fails to find files named .DS_Store

### ISSUE THREAD

**Issue by terrycojones** [sharkdp/fd#376]
Running brew-installed `fd` (version `7.2.0` on OS X `10.13.6`) I can't figure out how to convince it to find files named `.DS_Store`. `find` finds them no problem:

```sh
$ find . -name .DS_Store
./.DS_Store
./data/.DS_Store
./data/trees/.DS_Store
./data/alignments/.DS_Store
```

I've tried many combinations of args to `fd` (including `-H`, `-I`, `-F`, `-L`) and have tried giving it partial file name patterns (e.g., `tore`),  but it never prints any file names.  It's as though it doesn't even see the `.DS_Store` files in its traversal so can never print their names, regardless of arguments.

BTW, the `-H` option could be a bit better documented, as "hidden files" is quite vague. Does this mean files/dirs whose names start with `.`?

Thanks for `fd`!

**Comment by sharkdp** [comment]
> I've tried many combinations of args to `fd` (including `-H`, `-I`, `-F`, `-L`) and have tried giving it partial file name patterns (e.g., `tore`), but it never prints any file names

Have you tried the combination of *both* `-H` and `-I`? `fd -HI` should be equivalent to `find`.

> BTW, the `-H` option could be a bit better documented, as "hidden files" is quite vague. Does this mean files/dirs whose names start with `.`?

Yes, currently it does. Good point about the documentation improvement.

**Comment by terrycojones** [comment]
Huh... now I'm really confused :-)  First off though, using `-IH` does indeed find all the files, thanks.

But what does this mean about the semantics of those two args? It seems the `.DS_Store` files are not considered either hidden or ignored but are both!  In that case the `-I` actually only shows ignored files IF they're not also hidden, and `-H` only shows hidden files if they're not also ignored?

Anyway, thanks!

**Comment by sharkdp** [comment]
> But what does this mean about the semantics of those two args? It seems the `.DS_Store` files are not considered either hidden or ignored but are both!

Exactly. You probably have a `.gitignore` (or `.ignore`/`.fdignore`) somewhere which declares `.DS_Store` files as ignored. They are also considered to be "hidden files" due to the leading dot. For files like this, you need to disable both filters (git-ignored files and hidden files) and pass both `-I` and `-H`.

**Comment by terrycojones** [comment]
Yes, I found the parent `.gitignore` and now it all makes sense. Stand by & I'll send you a pr on the README.
