### ISSUE TITLE
respect hidden file attribute

### ISSUE THREAD

**Issue by cup** [sharkdp/fd#379]
currently FD considers a hidden file something starting with `.`, which is a
long time Linux convention

However the Windows convention of the hidden file attribute is not recognized by
FD. So if you have some files on Windows with the hidden file attribute, FD will
always show them regardless of `-H` option, unless they also happen to start
with `.`

**Comment by cup** [comment]
https://github.com/sharkdp/fd/issues/372

**Comment by colinwahl** [comment]
After briefly looking into this, it appears that `fd` uses [ignore](https://docs.rs/ignore/0.4.6/ignore/) to walk the directory tree.  It looks like the behavior you are describing stems from https://github.com/BurntSushi/ripgrep/blob/master/ignore/src/pathutil.rs#L20.  Perhaps this issue should be raised there?

**Comment by cup** [comment]
https://github.com/BurntSushi/ripgrep/issues/1154

**Comment by cup** [comment]
https://github.com/BurntSushi/ripgrep/issues/1154
https://github.com/sharkdp/fd/issues/372
https://github.com/sharkdp/fd/issues/379

**Comment by sharkdp** [comment]
Thank you for the notice. We are going to include this as soon as the next `ignore` release is published.

**Comment by cup** [comment]
@sharkdp I notice two `ignore` releases have been made since your comment:

- https://github.com/BurntSushi/ripgrep/releases/tag/ignore-0.4.8
- https://github.com/BurntSushi/ripgrep/releases/tag/ignore-0.4.7

**Comment by sharkdp** [comment]
Thank you for the reminder. Happy to include this into `fd`. We should probably also add a (Windows-only) test. I didn't look into how `ignore` implements this, but I think it would be reasonable to say that files starting with a dot would also be counted as "hidden" on Windows.

**Comment by cup** [comment]
@sharkdp thats an interesting comment

i think its a difference between "hidden" and "dont show by default"

strictly speaking, dotfiles are *not* hidden by default on Windows. However most users probably dont care whats in them and dont want them showing up in search results, in the general case. so if that means lumping dotfiles with true hidden files on windows, i am cool with that. but i think its an important distinction to make.

**Comment by sharkdp** [comment]
Handling of hidden files is now supported in [v7.4.0](https://github.com/sharkdp/fd/releases/tag/v7.4.0).
