### ISSUE TITLE
ditch Windows GNU builds

### ISSUE THREAD

**Issue by cup** [sharkdp/fd#380]
currently 4 windows versions are offered:

- fd-v7.2.0-i686-pc-windows-gnu.zip
- fd-v7.2.0-i686-pc-windows-msvc.zip
- fd-v7.2.0-x86_64-pc-windows-gnu.zip
- fd-v7.2.0-x86_64-pc-windows-msvc.zip

i get the `x86_64` vs `i686`, but i dont see a reason to distribute both
`gnu` and `msvc` versions.

this makes sense for rust itself - because rust is going to use a different
linker depending on which version of rust you installed. however with FD it
doesnt make sense because we arent linking anything. FD is not a compiler, it
was linked with rust and thats it.

my vote would be the MSVC versions because they are smaller.

**Comment by cup** [comment]
correcting myself - the MSVC version is smaller, but it requires Visual C++ 2015, which some users might not have installed - so maybe it makes sense to keep both

**Comment by sharkdp** [comment]
> but it requires Visual C++ 2015

wait... really? I would think that it requires VS for compiling, but not for running..?

**Comment by cup** [comment]
@sharkdp yep, for example if you get Win7 from here:

https://developer.microsoft.com/microsoft-edge/tools/vms

and try to use this:

fd-v7.2.0-i686-pc-windows-msvc.zip

you get this:

~~~
---------------------------
fd.exe - System Error
---------------------------
The program can't start because VCRUNTIME140.dll is missing from your computer.
Try reinstalling the program to fix this problem.
---------------------------
OK   
---------------------------
~~~

its not a huge deal as you can get it from here:

https://blogs.technet.microsoft.com/jagbal/2017/09/04/where-can-i-download

but might be worth documenting.

**Comment by cup** [comment]
@sharkdp its a matter of opinion really - to keep everyone happy you would just continue as is.

but i am of the opinion it would be simpler just just have ONE 64-bit windows and ONE 32-bit windows

so the question becomes GNU or MSVC? again this is opinion - but i would say go with MSVC and ditch GNU - some might disagree with this as it introduces the runtime requirement - but enough programs are requiring it that many users will already have it installed. up to you.

**Comment by sharkdp** [comment]
If there is a significant difference in both options, it seems reasonable to me to just keep both variants. If somebody has a different opinion, please comment here or write a short explanation in the corresponding README section.

**Comment by cup** [comment]
https://github.com/rust-lang/rustup.rs/issues/1851

**Comment by rbtcollins** [comment]
FWIW static CRT linkage should let you use MSVC builds that will on older windows without the c++ runtime installed

**Comment by cup** [comment]
@rbtcollins can you describe in detail how thats accomplished

**Comment by retep998** [comment]
Add this to your `.cargo/config`
```toml
[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
```
