### ISSUE TITLE
No good way to use a regex that starts with a hyphen (-)

### ISSUE THREAD

**Issue by tmccombs** [sharkdp/fd#386]
grep provides the `-e` flag, partly so that you can protect patterns that start with "-". afaict, fd doesn't have such a mechanism, and the best way I can think of to search for such a pattern would be to search for something like `.?-<whatever>`. At the very least there should be documentation on how to deal with this scenario.

**Comment by ghuls** [comment]
Doesn't this work?

```bash
fd -- '-yourpattern'
```

To avoid all leading `-` to be interpreted as arguments, most unix tools support `--` (stop interpreting `-` arguments as flags):

```
$ mkdir /tmp/test_fd_leading_hypen
$ cd /tmp/test_fd_leading_hypen

# Create some files.
$ echo bla1 > -file1
$ echo bla2 > another-file2
$ echo bla3 > file3

# List files.
$ fd
-file1
another-file2
file3

# Find files.
$ fd -- -f
-file1
another-file2

# Remove files ("--" to avoid "-file1" be processed as flags).
$ rm -- -file1 another-file2 file3
```

**Comment by tavianator** [comment]
There's also `fd '[-]whatever'` and `fd '\-whatever'`
