### ISSUE TITLE
fd returns absolute paths in Fish shell

### ISSUE THREAD

**Issue by micouy** [sharkdp/fd#392]
Setting --absolute-path doesn't change anything.

**Comment by sharkdp** [comment]
Please provide a little bit more information.

Which version of `fd` do you use?

How do you call `fd`? What is the output? What would be the expected output?

What does `which fd` say? Did you alias it to something?

**Comment by micouy** [comment]
I'm using fd 7.2.0. `which fd` returns `/Users/me/.cargo/bin//fd`. I have not aliased it to anything.

If I call fd with `fd . ~/test`, the output contains absolute paths:

```
/Users/me/test/file1.txt
/Users/me/test/file2.txt
/Users/me/test/file3.txt
/Users/me/test/folder
/Users/me/test/folder/file4.txt
```

But I've just noticed that when I call `fd . .` while being in `Users/me/test` dir, fd returns different (expected) output:
```
file1.txt
file2.txt
file3.txt
folder
folder/file4.txt
```

`fd . . --absolute-path` called in `test` dir also works properly:
```
/Users/me/test/file1.txt
/Users/me/test/file2.txt
/Users/me/test/file3.txt
/Users/me/test/folder
/Users/me/test/folder/file4.txt
```

**Comment by tmccombs** [comment]
I think that's expected behaviour. 

Notice that if you are in your home directory running `fd . test` will output something like:

```
test/file1.txt
test/file2.txt
test/file3.txt
test/folder
test/folder/file4.txt
```

I believe it just starts with the path that you are searching (if you supply a path)

**Comment by micouy** [comment]
Oh okay, my bad then. It just didn't make sense to me and I thought that's a bug. What should I do to make it not show the path prefix? `(cd dir && fd . .)`?

**Comment by sharkdp** [comment]
> Oh okay, my bad then. It just didn't make sense to me and I thought that's a bug. What should I do to make it not show the path prefix? `(cd dir && fd . .)`?

`fd` shows absolute paths if:
* you use the `--absolute-path` option, or
* the supplied search path is an absolute path

Note that your shell will replace `~` by the *absolute path* to your home directory, so when you call `fd . ~/test`, you are actually running `fd . /Users/me/test` (you can test this by running `echo fd . ~/test`). This is why `fd` is showing absolute paths in this case. If you want to prevent this, use a relative path to your home directory, for example:
```
cd ~
fd . test

cd /Users
fd . me/test

cd ~/test
fd .
```

**Comment by micouy** [comment]
Thank you for your response, I didn't realise that was the expected behavior.
