### ISSUE TITLE
Support for atime and ctime in --changed-within/--changed-before

### ISSUE THREAD

**Issue by Ruin0x11** [sharkdp/fd#393]
I came across a situation where I specifically needed to find files with a recent `ctime`, but the `--changed-within` option implemented in #339 only supports `mtime`. It would be nice if there were an option for specifying which type of time to compare against. Implementation would probably entail adding a branch around https://github.com/kimsnj/fd/blob/master/src/walk.rs#L309 with a call to `Metadata::accessed()` or `Metadata::created()`.

**Comment by tavianator** [comment]
Note that `ctime` is not creation time, it is "change time," i.e. the last time the file's metadata was changed.

**Comment by sharkdp** [comment]
@Ruin0x11 Thank you for the feedback. There are no plans to implement this in `fd` (see discussion in #165).

**Comment by seangenabe** [comment]
> [@Ruin0x11](https://github.com/Ruin0x11) Thank you for the feedback. There are no plans to implement this in `fd` (see discussion in [#165](https://github.com/sharkdp/fd/issues/165)).

I read #165 but there was no discussion specifically why atime and (I guess) ctime weren't implemented. Did I miss something?
