### ISSUE TITLE
fd shows less files than find

### ISSUE THREAD

**Issue by mg979** [sharkdp/fd#394]
I ran `fd` looking for a file, knowing it was there somewhere, but it couldn't find it. `find` did instead.

I run a comparison between:
```
find . -iname *dmenu* > find.test
fd --hidden dmenu > fd.test
```

[fd.test.txt](https://github.com/sharkdp/fd/files/2774028/fd.test.txt)
[find.test.txt](https://github.com/sharkdp/fd/files/2774029/find.test.txt)

Files have been sorted and in `find.test` I remved the first `./` to make diff easier.

**Comment by sharkdp** [comment]
please see https://github.com/sharkdp/fd#fd-does-not-find-my-file

**Comment by mg979** [comment]
Thanks, that clarifies it :+1:
