### ISSUE TITLE
Possible to exec in non-parallel?

### ISSUE THREAD

**Issue by remy** [sharkdp/fd#395]
I used `fd` to do a mass `git mv` command, and it's perfect for the job, syntax-wise:

```
fd -e js -x git mv {} {.}.js
```

The problem is that git starts throwing errors about lock files. I suspect it's because the exec jobs are being run in parallel and some are being caught in git's file locking (there was only 35 files, but about 4 or 5 didn't get moved due to this error).

I wondered if it was possible to run the exec commands in sequence rather than parallel via some flag. Looking at the `man` page I couldn't see that it exists, but wanted to ask. And if not, wonder if there's a strong enough use case to add support?

**Comment by tmccombs** [comment]
You could use `-j1` to only use one thread, but that would also search for files in series instead of in parallel.

**Comment by remy** [comment]
Thanks. For the relatively small directory I think that would be fine.

**Comment by sharkdp** [comment]
Just FYI: this has nothing to do with `fd`, but for your particular use case you could also run `mv {} {.}.js` in parallel (instead of `git mv`) and use `git add` afterwards to stage all changes.

In my understanding, `mv` + `git add` is always equivalent to `git mv`.
