### ISSUE TITLE
Support for .hgignore ?

### ISSUE THREAD

**Issue by ahh** [sharkdp/fd#397]
It doesn't appear that fd respects .hgignore files.  As much as I like git, I do have to use Mercurial sometimes, and it'd be great if it natively supported it.  --ignore-file works but is very inconvenient (in particular, we have to use a $(hg root) stanza to  find it, which is frustrating.)  I'm also not sure that's going to do the right thing from subdirectories when the hgignore pattern specifies specific files in subdirectories, though I haven't tested it extensively.

How difficult would it be for you to support this?

Thanks!

**Comment by alexmaco** [comment]
It looks like reading `.hgignore` files by default would be fairly simple. However, always interpreting them correctly is not. `fd` uses the [ignore](https://docs.rs/ignore) crate to do file system walking, which includes filtering out files excluded via `ignore` files, but it seems that `ignore` currently only supports `.gitignore` format, and thus may yield incorrect results for some `.hgignore` files, for instance when they switch to `syntax: regex`.

If `ignore` would add mercurial support then multiple tools, including `fd`, and ignore's parent `ripgrep` would benefit. Perhaps filing an issue there could help things along and make the feature request more visible.

**Comment by sharkdp** [comment]
Thank you for your request.

Unfortunately, we are probably not going to support this due to the reasons mentioned by @alexmaco. Filing a bug upstream with `ignore`/`ripgrep` will not help either, as they are rather clear about *not* adding support for `.hgignore`, see: https://github.com/BurntSushi/ripgrep/issues/6#issuecomment-406812551
