### ISSUE TITLE
Support PCRE (look behind)

### ISSUE THREAD

**Issue by ar1a** [sharkdp/fd#399]
with the addition of --pcre2 flag into BurntSushi/ripgrep , lookbehind is something i've been pining for. It'd be great if PCRE2 support could be added

**Comment by sharkdp** [comment]
Thank you for the feedback.

Could you please provide a few examples where advanced regex features like lookbehind could be useful in a realistic `fd` use case?

**Comment by ar1a** [comment]
I can't think of any examples off the top of my head but the use case I was going for was the negative lookaheads/behinds. They are pretty awkward to express without lookbehinds.

**Comment by sharkdp** [comment]
I think I am going to have to decline (for now).

`fd` is trying to stay simple and is only targeting "80% of the use cases" (see README), so I am not going to implement a feature without any use case at all.

**Comment by jrraymond** [comment]
A use case is finding all file which don't match an extension, ei: `^.+\.(?!py$)[^.]+$`. `?!` requires look-around.

**Comment by sharkdp** [comment]
@jrraymond 

This use case can also be solved with `fd`s `-E, --exclude <pattern>...` option:
```
fd pattern -X '*.py'
```
For example: search for all files matching the `README` pattern that do not have an `md` extension:
```
fd README -X '*.md'
```

That's (arguably) also more readable than the lookbehind.

**Comment by Aouchinx** [comment]
@sharkdp 
a use case is to find out files with both 'mutation' and 'asset' in their names
option: `^(?=.*mutation)(?=.*asset).*$`

**Comment by unusualevent** [comment]
the -E exclude thing definitely slipped past me on the first few tries to solve this. Compared to wishing I had a negative lookbehind... having a quick "exclude" glob seems so much nicer. it's possible this could be phrased better in the readme as "find all files not matching x" is a use case of it, not just "ignore" :)

**Comment by sharkdp** [comment]
@unusualevent A small PR with a documentation update would be very much appreciated.

**Comment by unusualevent** [comment]
@sharkdp I'd probably butcher the readme :/
