### ISSUE TITLE
How to make the output of `fd` print only once for each file it finded?

### ISSUE THREAD

**Issue by explainlikeimfive** [sharkdp/fd#405]
E.g. for files that respect [pattern] in current directory, `$ fd [pattern] . . .` will print each of them 3 times. How to make it print only once?

**Comment by sharkdp** [comment]
There is currently no way to do this directly in `fd`, but you can simply pipe into `sort -u`:
```
fd [pattern] some/ search/ paths/ | sort -u
```

If you want to keep the colored output, you need to use `--color=always`:
```
fd --color=always [pattern] some/ search/ paths/ | sort -u
```
