### ISSUE TITLE
Man page doesn't explain search patterns

### ISSUE THREAD

**Issue by ntc2** [sharkdp/fd#408]
The man page doesn't say what form search patterns should take. The README here on GitHub says they are regular expressions, but not what kind of REs (I guess they are not PCREs, because there's an issue for adding that).

Suggestion: document in man page that the pattern argument is a regular expression, and say what kind of regular expression ops are supported.

**Comment by sharkdp** [comment]
Thank you for the feedback. We should add that to the documentation (man page and maybe README) - yes.



> I guess they are not PCREs, because there's an issue for adding that

You are right. `fd` uses the regular expressions specified by the `regex` crate (Rust library). Its syntax is documented here: https://docs.rs/regex/1.1.0/regex/#syntax

**Comment by sergeevabc** [comment]
FD lacks a basic description as well. And it’s important to have one if this app is used infrequently. Compare:
```
ripgrep 0.10.0
Andrew Gallant <jamslam@gmail.com>

ripgrep (rg) recursively searches your current directory for a regex pattern.
By default, ripgrep will respect your .gitignore and automatically skip hidden
files/directories and binary files.
```

**Comment by rootbid** [comment]
Hey @sharkdp
I would like to get my feet wet with this, as my first contribution.
- [ ]  Add syntax patterns for RE.
- [ ]  Add examples with RE syntax.

**Comment by sharkdp** [comment]
@rootbid Sounds great!
