### ISSUE TITLE
show number of ignored matches

### ISSUE THREAD

**Issue by milianw** [sharkdp/fd#409]
Hey there,

thanks a lot for fd, I use it a lot and am very happy with it! One regular annoyance I run into is that I sometimes want to find a file that is ignored by my `.gitignore`. I e.g. don't want to include `perf.data` files in my git repository, yet I do want to find them. When I run `fd perf` I see no matches, until I realize that they simply where excluded. It would be very helpful if `fd` could print a short line at the end, telling the user how many entries it ignored.

Expected results:
```
$ fd perf
ignored matches: 1
$
```

Actual results:
```
$ fd perf
$ # no output at all
```

This could be hidden behind a command line switch, which I could include in an `fd` alias. And the output could be written to `stderr`, to not break existing tools when piping the `fd` output.

Thanks!

**Comment by antonholmberg** [comment]
This is somewhat easy to do with a shell script

Try something like

`diff <(fd perf) <(fd --no-ignore perf) | wc -l`

It should give you the number of ignored matches.

**Comment by milianw** [comment]
@antonholmberg that suggestion will make searching at least 2x slower, 3x with your approach, since one also has to search normally to get the real output...

**Comment by antonholmberg** [comment]
@milianw The fd commands will run in parallel with this approach so it will be slower for sure but hopefully not 2x or 3x

**Comment by sharkdp** [comment]
> thanks a lot for fd, I use it a lot and am very happy with it!

Thank you for the feedback!

> One regular annoyance I run into is that I sometimes want to find a file that is ignored by my `.gitignore`. I e.g. don't want to include `perf.data` files in my git repository, yet I do want to find them.

You can use `.ignore` or `.fdignore` files for this (either in the repo or in your home folder). Just add `!perf.data` to those files and you will see them without using `-I`/`--no-ignore`.

> When I run `fd perf` I see no matches, until I realize that they simply where excluded. It would be very helpful if `fd` could print a short line at the end, telling the user how many entries it ignored.

> This could be hidden behind a command line switch, which I could include in an `fd` alias. And the output could be written to `stderr`, to not break existing tools when piping the `fd` output.

Well, I agree that this would be useful. It has been requested a few times. However, note that this would mean that we would have to traverse *all ignored directories*. This can lead to significant slowdowns.

**Comment by sharkdp** [comment]
Closing this for the reasons given above.
