### ISSUE TITLE
Indexing / Caching Drives

### ISSUE THREAD

**Issue by Schizo** [sharkdp/fd#415]
I was wondering if there was already discussion on creating a database like locate does. Or how hard would it be to implement a directory structure that is cached?

**Comment by hungptit** [comment]
I do not think there is a lot of shared code between fd and fd-locate (make up name) except fd-locate uses fd to build the cache file information. You can take a look at mlocate command (https://github.com/hungptit/tools.git) for a GNU locate alternative solution.

**Comment by sharkdp** [comment]
There is no discussion about this, so far, but I'm not inclined to add caching functionality into `fd`.

(Personally, I haven't felt the need for `locate` in a long time, as `fd` searches my whole hard drive in ~1 sec - but there are larger file systems out there of course :smile:)

**Comment by hungptit** [comment]
The locate command is very handy in the large scale software develop workflow or Linux/Unix administration tasks. If your folder has millions of files and they are in the network drive or spin disks then it will save you a lot of time. For example it only takes mlocate (https://github.com/hungptit/tools) around <50ms to find for a file from a list of 200K paths, however, it will take fd/find >20s. And if we pipe the output of the mlocate command to fzf then we can open/access a file interactively in no time.

**Comment by sharkdp** [comment]
> The locate command is very handy in the large scale software develop workflow or Linux/Unix administration tasks. If your folder has millions of files and they are in the network drive or spin disks then it will save you a lot of time. For example it only takes mlocate (https://github.com/hungptit/tools) around <50ms to find for a file from a list of 200K paths, however, it will take fd/find >20s.

Sure, but how long does it take to build the index? How do you know when you have to update your index, especially on network drives?

Look, I'm not questioning the usefulness of `updatedb`/`locate`, the comment in parenthesis was just a personal remark. But I *do* think that `find`-like tools and `locate`-like tools are separate classes of programs and I currently don't see any benefit from a mixed/combined version, however that would look like.

> And if we pipe the output of the mlocate command to fzf then we can open/access a file interactively in no time.

I don't see how that is related to the topic. Combining with `fzf` works with both `locate` and `find`/`fd`.

**Comment by Schizo** [comment]
As caching is nowaday's a thing that you can "turn on" like redis, I thought that someone might have had a usecase for it. In my case, we are storing versioned data, which mean's those path's never get changed, we just keep adding new ones. For that we would basically just push the new path, when they are created.

But yeah, caching might not be desirable if your whole disk is searched in 1 sek, but our data is around 10 Million files in average, per project.

**Comment by sharkdp** [comment]
Again, I'm not questioning the usefulness of caching. I just don't see how that fits into `fd`. If there is no additional ideas/feedback, I'd like to close this.

**Comment by 07416** [comment]
> There is no discussion about this, so far, but I'm not inclined to add caching functionality into `fd`.
> 
> (Personally, I haven't felt the need for `locate` in a long time, as `fd` searches my whole hard drive in ~1 sec - but there are larger file systems out there of course )

I assume that it can take over a minute for `fd` to search through large HDD drive (≥20 TB) — a very rough and casual estimate based on my use. Cache support sure would be of appreciated by users.

On a related note, can `fd` searches be indexed with some other tool? I redirect some `fd` runs into a text file (in cron) which I filter with `fzf`, but haven't yet come up with other out-of-the-box solutions.
