### ISSUE TITLE
gitignore not honored

### ISSUE THREAD

**Issue by dbingham** [sharkdp/fd#418]
`fd` seems to no longer honor gitignore files by default?  To test this, I setup a basic file structure for testing:

```
$ tree -a .
.
|-- .gitignore
|-- a/
|   `-- file1.txt
|-- b/
|   `-- file2.txt
`-- c/
    `-- file3.txt

3 directories, 4 files
```

The `.gitignore` just contains:
```
a/
```

Then when I run `fd` I get this:

```
$ fd
a
a/file1.txt
b
b/file2.txt
c
c/file3.txt
```

But if I explicitly add the `.gitignore` as an `ignore-file` it works:

```
$ fd --ignore-file .gitignore
b
b/file2.txt
c
c/file3.txt
```

Also, renaming it to `.ignore` works:

```
$ mv .gitignore .ignore
$ fd
b
b/file2.txt
c
c/file3.txt
```

The README still talks about `.gitignore` being honored by default and the options on the app seem to indicate that it will be used unless disabled.  However, that doesn't seem to be the case.

```
$ fd --version
fd 7.3.0
```

**Comment by sharkdp** [comment]
Thank you for the feedback!

As of recently, `.gitignore` files are only honored if the folder is actually a Git repository. Hope that resolves your question.

**Comment by dbingham** [comment]
Thank you for clarifying.  I was going to complain that this isn't clarified in the docs, but I just looked again and saw this:

> If we work in a directory that is a Git repository (or includes Git repositories), fd does not search folders (and does not show files) that match one of the .gitignore patterns.

So apparently I just can't read.  Appreciate you pointing me in the right direction.  Will close now.

**Comment by trollfred** [comment]
@sharkdp is there any alternative file for directories which are not a git repository?

**Comment by goto-engineering** [comment]
Argh, this just cost me like 15 minutes of trying to "debug" fzf and wildignores and fd. Had made a new project, just opened it to test, so it wasn't a git repo yet.

Is there a reason for this? Are people commonly putting `.gitignore` files into non-git folders and then getting confused?

**Comment by sharkdp** [comment]
If I remember correctly, this was an upstream change in the `ignore` crate which is also used in ripgrep. I think it makes sense to maintain compatibility with ripgrep here. Maybe there is a deeper reason to be found in the ripgrep/ignore changelogs.

**Comment by quinncomendant** [comment]
I just bumped into this issue as well. I've been using [degit](https://github.com/Rich-Harris/degit) to quickly clone git repos, which results in a local copy without a `.git` directory, thus fd doesn't respect `.gitignore`. As a workaround, I've added a `fdi` function to `~/.bashrc` that explicitly uses `.gitignore` if it exists and isn't overridden by other options:

```bash
function fdi() {
    local ignore_file_arg;
    if [[ ! "$*" =~ -I && ! "$*" =~ --ignore-file && -f .gitignore ]]; then
        ignore_file_arg='--ignore-file .gitignore'
    fi
    fd $ignore_file_arg "$@";
}
```

**Comment by bryango** [comment]
I also bumped into this issue, let me document my findings here in case it's useful to others. I have a tree like this:
```
parent_repo
├── .git
├── .gitignore
└── child_mounted
    ├── ...
    └── .gitignore
```
where `parent_repo` is a git repo with a `.git` directory, while `child_mounted` is a mounted drive without a `.git`, and it is itself git-ignored by `parent_repo`. In this case, `fd` treats `child_mounted` as an active git repo and `.gitignore` is honored.

However, when `child_mounted` is mounted at some other place where the parent is not a git repo, then `fd` treats it as a non-active repo so `.gitignore` is not honored. This is correct behavior so there is no bug, but it got me confused for a looooong time.

**Comment by tavianator** [comment]
@bryango This matches the behaviour of git itself, which is the goal
