### ISSUE TITLE
Upload to crates.io

### ISSUE THREAD

**Issue by dead10ck** [sharkdp/fd#42]
Title is self-explanatory.

**Comment by sharkdp** [comment]
Thank you for the suggestion.

Unfortunately, the name `fd` is already taken by @stemjail's https://github.com/stemjail/fd-rs - https://crates.io/crates/fd

Any suggestions on how to proceed? 

Are there any other advantages, apart from being able to run `cargo install <crate-name>`?

**Comment by tmccombs** [comment]
does the cargo/crate name need to be the same as the executable? If not you could name the crate something like `fd-command` or `fd-finder` or even `better-find`

**Comment by dead10ck** [comment]
The crate name really doesn't matter. Any of @tmccombs ' suggestions would work. @sharkdp there's that, and also storing every old version that gets published without having to resort to something like git tags. Also, it's just a pain for users to have to look up the github URL every time.

**Comment by sharkdp** [comment]
I quite like the `fd-finder` idea, but also +1 for the remark about finding an expanded name in order for this to be more memorable (and search-engine friendly).

I tried my best in expanding the `fd` acronym. Here are a few ideas (not to be taken too seriously):
* `find-deluxe` - maybe a little bit too pretentious :smile: 
* `file-detector`
* `find-data`
* `finding-dory`

Something like *ag - the silver searcher* would be cool, but *Fd* is not a chemical element :frowning_face:.

**Comment by erf** [comment]
Suggestion: 
'find direct' or 'file direct(or)' or 'fd - find with rust'

**Comment by sharkdp** [comment]
`fd` is now on crates.io: https://crates.io/crates/fd-find and therefore can be installed via
```
cargo install fd-find
```

Thanks!
