### ISSUE TITLE
[Exclude pattern] strange behavior with "!()"

### ISSUE THREAD

**Issue by rockandska** [sharkdp/fd#425]
Hi

Just tried to negate a glob pattern to say "only catch those files" since -E is for exclusion and didn't see another option for filtering with globs.

It seems to partially works and doesn't return the same results as bash does
```
$ shopt -s extglob                                                          
$ mkdir testfd
$ cd testfd
$ touch just.mp3
$ mkdir {a,b}
$ touch {a,b}/README.md
$ touch a/a.mp3
$ touch b/b.mp3
$ fd
a
a/README.md
a/a.mp3
b
b/README.md
b/b.mp3
just.mp3
$ fd -E !(*.@([ao]|so|mp3))
b
b/b.mp3
```
bash:
```
$ shopt -s extglob   
$ shopt -s globstar
$ printf "%s\n" **/!(!(*.@([ao]|so|mp3)))
a/a.mp3
b/b.mp3
just.mp3
```

**Comment by tavianator** [comment]
Since you're not quoting the glob pattern, it is your shell expanding it, not `fd`.  I.e. the command will be like

    $ fd -E match1 match2 match3...

and `-E` will only look at `match1`.

**Comment by rockandska** [comment]
I had leave the glob pattern unquoted because when i've quoted it, it didn't work at all
```
$ fd -E '*.@([ao]|so|mp3)' 
a
a/README.md
a/a.mp3
b
b/README.md
b/b.mp3
just.mp3
```
Found no details about it, but which form of globing is allowed here ?
glob ? extglob ?
@() , ?(), +(), !() ?

Regards,

**Comment by tavianator** [comment]
It doesn't seem to be documented, but the code uses `OverrideBuilder` from the `ignore` crate which ultimately falls back to [`globset` syntax](https://docs.rs/globset/0.4.2/globset/#syntax).

**Comment by sharkdp** [comment]
You can not use negation with the `--exclude` option to *include* something.

Searching with glob patterns is currently not possible, but there is an open feature request to implement it: #284 

However, you can use a regular expression to do what you want (capture all `.a`, `.o`. `.so` and `.mp3` files):
```
fd '\.([ao]|so|mp3)$'
```

If you are searching for file extensions in particular, you can also use `fd`s `--extension`/`-e` option:
```
fd -e a -e o -e so -e mp3
```

**Comment by rockandska** [comment]
thanks for the explanations but my concern was to reuse "extglob" patterns coming from "bash_completion" and don't find yet a way to convert them to regex ( the pattern `!()` to be exact is the one i'm missing )

Original ( `^!...` will be convert to `^!(...)` by the functions who used them )
```
$ printf "%s\n" ${_xspecs[@]} | tail -n5 | head
!*.@(okular|@(?(e|x)ps|?(E|X)PS|[pf]df|[PF]DF|dvi|DVI|cb[rz]|CB[RZ]|djv?(u)|DJV?(U)|dvi|DVI|gif|jp?(e)g|miff|tif?(f)|pn[gm]|p[bgp]m|bmp|xpm|ico|xwd|tga|pcx|GIF|JP?(E)G|MIFF|TIF?(F)|PN[GM]|P[BGP]M|BMP|XPM|ICO|XWD|TGA|PCX|epub|EPUB|odt|ODT|fb?(2)|FB?(2)|mobi|MOBI|g3|G3|chm|CHM)?(.?(gz|GZ|bz2|BZ2)))
!*.@(?(la)tex|texi|dtx|ins|ltx|dbj)
!*.@(?(t)xz|tlz|lzma)
!*.@(mid?(i)|rmi|rcp|[gr]36|g18|mod|xm|it|x3m|s[3t]m|kar)
!*.dvi
$ 
```

Sorry, I assumed that `-E glob pattern` implicitly mean 'extglob'

**Comment by sharkdp** [comment]
Can you please tell us what you are trying to achieve, exactly (without using any code)?

**Comment by rockandska** [comment]
To resume, i'm looking for a find alternative who is able to filter files based on a extglob pattern.

Extglob pattern could be used directly in bash, but do not allow to have colourized output , or only files, and other options available in tools like fd.

I first tried to do a "extglob->regex" converter, but had hard times with `!()` and `!()` nested, so i give up for now.

There is only a few libraries i'm aware of who implemented the `extglob` logic :
- [micromatch](https://github.com/micromatch/extglob)
- [wcmatch](https://github.com/facelessuser/wcmatch/)

**Comment by sharkdp** [comment]
> To resume, i'm looking for a find alternative who is able to filter files based on a extglob pattern.

`fd` is not the right tool, then.

If you are looking to solve a particular problem that could potentially be solved without extglob syntax, let us know. That's why I asked for a "without any code" description of what you are trying to achieve. I don't really know the extglob syntax, so you would have to describe it in words.

But I think this ticket should be closed. `fd` does not (claim to) support `extglob` syntax.
