### ISSUE TITLE
(Oh-my)Zsh defines fd as find alias

### ISSUE THREAD

**Issue by rugk** [sharkdp/fd#426]
I wanted to try out this tool, but (after some confusing tries) noticed this:
```zsh
which fd
fd='find . -type d -name'
	/usr/bin/find
```

So one may say this is kinda related to https://github.com/sharkdp/fd/issues/189.

Does someone has the same issue? If so, can someone tell me, which plugin/what known (oh-my-)zsh thing defines it?
I am totally lost here… :stuck_out_tongue_winking_eye:

**Comment by sharkdp** [comment]
see #104.
