### ISSUE TITLE
Support ripgrep's --path-separator option

### ISSUE THREAD

**Issue by mookid** [sharkdp/fd#428]
On windows (both cygwin and cmd.exe shells) the output is with backslashes as path separator. However, one sometimes would want to interop with windows port of unix tools and get slash-separated paths.

When using ripgrep, one can override the path separator with the `--path-separator` option. I think it would be great to support it in fd as well.

This should also allow working around issues like #153.

reference: the ripgrep discussion https://github.com/BurntSushi/ripgrep/issues/275

**Comment by vvuk** [comment]
What happened to this in #429?  I see that PR got closed without comment.

**Comment by mookid** [comment]
I did not see a great interest for it. I would be happy to see this merged, but I don't want to keep pinging.

When I need the feature, I use my fork.

**Comment by sharkdp** [comment]
I think there is some interest for it (see also the discussion in #153).

If you closed the PR because there was no response from my side, let me assure you that it was only a lack of time, not lack of interest 😄

**Comment by sharkdp** [comment]
Fixed in #429 by @mookid

**Comment by rajeshduggal** [comment]
Great! When can we expect to see a windows release which includes this? https://github.com/sharkdp/fd/releases

**Comment by sharkdp** [comment]
Released in [v7.4.0](https://github.com/sharkdp/fd/releases/tag/v7.4.0).
