### ISSUE TITLE
Auto use a pager like git

### ISSUE THREAD

**Issue by bofh69** [sharkdp/fd#430]
It would be nice if fd used a pager when stdout is a terminal, just like git does.

A workaround is to make a script/function that does it. With bash I use:
```bash
function fd()
{
  if [ -t 1 ]; then
    env fd -c always $* | less -XRF
  else
    env fd $*
  fi
}
```

**Comment by sharkdp** [comment]
Thank you for the feedback.

I'm not inclined to add paging support to `fd`.

One reason is that I want `fd` to always immediately print search results as soon as they are available. `less -XRF` waits for a full page of search results (or for the full search to be finished), as can be demonstrated via:
``` bash
(echo 1; sleep 1; echo 2; sleep 1; echo 3) | less -XRF
```

If we do not use `-F`/`--quit-if-one-screen`, users always have to exit the pager when using `fd`.

**Comment by bofh69** [comment]
Hi @sharkdp !

I understand if you don't want to keep fd leen and not add more logic. The feature can be implemented just as well with a wrapper function like I did.

However... :-) 

more from util-linux 2.31.1 and less 487 on Ubuntu 18.04 both shows the lines immediately. I remember less worked like you describe a long time ago, but I looked at less' release notes back to 2011 and didn't find any changes regarding this. Could it be a LESSOPEN filter that doesn't pass through the lines immediately (like using lessfile instead of lesspipe)? -L removes it.

There is a crate, pager, for automatically adding a pager. It can use the normal environment variable to choose the pager as well as defaults. I've not used it so can't say anything about its problems though. 

Having a --paginate or --no-pager option would be needed for such a feature though.

**Comment by tavianator** [comment]
> One reason is that I want `fd` to always immediately print search results as soon as they are available. `less -XRF` waits for a full page of search results (or for the full search to be finished), as can be demonstrated via:
> 
> ```shell
> (echo 1; sleep 1; echo 2; sleep 1; echo 3) | less -XRF
> ```

For the record, I reported this as a bug to `less`.  `less -F` was changed recently to behave like `-XF` if it gets less than a screen of input, but to do this it has to wait for a whole screen of input before starting to print anything.  The fact that it still waits even if `-XF` is specified explicitly seems like an oversight.

**Comment by sharkdp** [comment]
> more from util-linux 2.31.1 and less 487 on Ubuntu 18.04 both shows the lines immediately.

It's present for me in `less 530` on Arch Linux.

> For the record, I reported this as a bug to `less`.

Thanks.

**Comment by tavianator** [comment]
Turns out it was already fixed a while ago: https://github.com/gwsw/less/commit/bc231ee311f6e473620c29b27c901bcb3048d908

**Comment by sharkdp** [comment]
I'd like to close this. There are no plans to add paging support to `fd`. Thank you for your feedback though.
