### ISSUE TITLE
Does fd support full regular expression syntax?

### ISSUE THREAD

**Issue by hungptit** [sharkdp/fd#433]
I see fd miss a file during my tests. Is this expected? 

> MacOS:ioutils hdang$ fd "zstd/.*doc/README[.]md$" ../3p/src/

> MacOS:ioutils hdang$ fast-find -e "zstd/.*doc/README[.]md$" ../3p/src/
> ../3p/src/zstd/doc/README.md

**Comment by sharkdp** [comment]
`fd` supports [this regex syntax](https://docs.rs/regex/1/regex/#syntax).

It looks like you want to match on a full path (instead of just the basename). In this case, you need to use the `--full-path`/`-p` option.

**Comment by hungptit** [comment]
Thanks.

**Comment by hungptit** [comment]
--full-path option works for me.
