### ISSUE TITLE
combine --changed-within and --changed-before into a single short argument

### ISSUE THREAD

**Issue by njthomas** [sharkdp/fd#435]
I really like how --changed-within and --changed-before takes short deltas like 3w, 2d, 1h, etc. But these arguments are too long to type.

**Proposal: Combine `--changed-within` and `--changed-before` into a single short argument. We can distinguish "before" and "within" times by using a "+" sign. This would similar to how standard find does it: `-mtime -4`.**

Unfortunately, `-t` is taken, so maybe `-T` could be used instead?

This is how it would work:

```
    # a minus sign or absence of sign means --changed-within
    # the following three are equivalent
    -T 3h
    -T -3h
    --changed-within 3h

    # a plus sign means --changed-before
    # the following two are equivalent
    -T +2d
    --changed-before 2d
```

**Comment by sharkdp** [comment]
Thank you for your feedback.

I'm not a big fan of the `±value` syntax of `find`, but we didn't come up with something better for `fd`s `--size`/`-S` argument either. So I guess it is reasonable to do something similar for time-based searches.

Are you suggesting to deprecate `--changed-within`, `--changed-before`, … in favor of the new `-T` option? Or would you keep both of them?

**Comment by njthomas** [comment]
> Are you suggesting to deprecate `--changed-within`, `--changed-before`, … in favor of the new `-T` option? Or would you keep both of them?

At this point, I would guess some non-finite and probably significant amount of users people are used to to the old switches, so I would suggest keeping them both for now.

Perhaps you could deprecated --changed-* at some later date.

**Comment by sharkdp** [comment]
To be honest, I'd rather not implement this. The syntax is not completely obvious when times are involved (in my opinon). I want `fd` to have an easy-to-use, concise command-line interface, but `-T +2d` feels rather cryptic.
