### ISSUE TITLE
Test shell script doesn't work in macOS

### ISSUE THREAD

**Issue by douglascamata** [sharkdp/fd#44]
I tried to run the test shell script in macOS and it returns this:

```
⋊> ~/c/r/fd on master ⨯ sh tests/test.sh                                                                                         14:25:13
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
```

**Comment by sharkdp** [comment]
I believe this might be fixed by replacing `mktemp --directory` by `mktemp -d`. Unfortunately, I don't have a macOS system to test...

**Comment by sharkdp** [comment]
I've just updated the `test.sh` script. I'd be great if somebody could test this.

**Comment by douglascamata** [comment]
@sharkdp I'll test it.

**Comment by douglascamata** [comment]
Still failing:

![image](https://user-images.githubusercontent.com/159076/27107043-6044497e-5096-11e7-9193-8f3a0d7d39c7.png)

**Comment by sharkdp** [comment]
This should hopefully be fixed now, tested on El Capitan.
