### ISSUE TITLE
OpenBSD install instructions don't work

### ISSUE THREAD

**Issue by egtann** [sharkdp/fd#442]
Appears epbsd.org no longer exists. Is there another host for this?

```
$ curl epbsd.org
curl: (6) Could not resolve host: epbsd.org
```

**Comment by sharkdp** [comment]
Maybe @evitalis can help?

**Comment by evitalis** [comment]
Hello @egtann sorry about that. I had to pull down the web server temporarily. I will be working to get this back up during the week. I apologize for the inconvenience. I will update this thread again once it is back online.

**Comment by evitalis** [comment]
@egtann Can you please test the repo again, it should be working. If everything is in order for you feel free to close this issue.

**Comment by egtann** [comment]
Yup, it's back up for me. Thank you, all!
