### ISSUE TITLE
There is an armhf version?

### ISSUE THREAD

**Issue by baruchiro** [sharkdp/fd#443]
For Ubuntu (touch)

**Comment by sharkdp** [comment]
No.

If someone wants to work on this, take a look at the [bat repository](https://github.com/sharkdp/bat) where `armhf` (deb) packages are probided (the deployment infrastructure is very similar between `fd` and `bat`).

**Comment by baruchiro** [comment]
Where the `armhf` deployment configured on `bat` repository?

**Comment by sharkdp** [comment]
`ci/before_install.bash` and `ci/before_deploy.bash`. It might also be necessary to adapt `ci/script.bash`.
