### ISSUE TITLE
How to search all folders (including /var and so on)

### ISSUE THREAD

**Issue by qazip** [sharkdp/fd#444]
Hey there,

I know about `--no-ignore`, but it doesn't seem to work for my case. I want to search/find a file called `pacman.log`, which is in `/var/log`. If I do `fd --no-ignore pacman.log` while in my home folder, it doesn't find the file. If I however cd into `/var` and do the same search, it finds it.

So my question is: 
- How can I search all folders from anywhere?

Thanks for this amazing software!

**Comment by qazip** [comment]
I guess doing `fd pacman.log /` solves this lol. I will close this, but if there is an easier way, please let me know.

**Comment by sharkdp** [comment]
that's the way to do it. Either go into the directory you want to search or specify the directory (directories) as additional arguments:
```
fd pacman.log /var/log /maybe/some/other/directory
```
