### ISSUE TITLE
Add a `-quit` option, like `find`?

### ISSUE THREAD

**Issue by gabebw** [sharkdp/fd#446]
Hi,

I use `find`'s `-quit` option to determine if there's at least 1 file that matches my criteria. I like `-quit` because it quits early, without listing every file, and so is faster. 

What do you think of adding a `--quit` option to `fd`? As a small improvement on `find`'s option, it'd be great if `fd` also exited with 0 (if it found any files) or 1 (if it found none). `find` exits with a 0 code regardless.

Thanks for fd!

**Comment by sharkdp** [comment]
Please see #303 and #106.

**Comment by gabebw** [comment]
Thank you! `fd --max-buffer-time 0 ... | head -n 1` solves this issue for me.
