### ISSUE TITLE
Centos version

### ISSUE THREAD

**Issue by ariecattan** [sharkdp/fd#447]
Is there a Lentos version ?

**Comment by sharkdp** [comment]
The generic linux version should work. Just download the correct tarball for your architecture from the [release page](https://github.com/sharkdp/fd/releases), for example `fd-v7.3.0-x86_64-unknown-linux-gnu.tar.gz` for a `x86_64` system.

If you have problems with dynamically linked libraries, choose a statically linked version (the ones with `musl` in the name`), e.g. `fd-v7.3.0-x86_64-unknown-linux-musl.tar.gz`.

**Comment by sharkdp** [comment]
Can you confirm this?

**Comment by amitlevy21** [comment]
I confirm that statically linked version `fd-v7.3.0-x86_64-unknown-linux-musl.tar.gz` works on RHEL 7.6.
The dynamically linked version `fd-v7.3.0-x86_64-unknown-linux-gnu.tar.gz` complained about GLIBC version 2.18 not found (I have 2.17).

**Comment by owenstake** [comment]
> I confirm that statically linked version `fd-v7.3.0-x86_64-unknown-linux-musl.tar.gz` works on RHEL 7.6. The dynamically linked version `fd-v7.3.0-x86_64-unknown-linux-gnu.tar.gz` complained about GLIBC version 2.18 not found (I have 2.17).

same fact here

**Comment by liyang85** [comment]
I can run the `fd-v10.2.0-x86_64-unknown-linux-musl.tar.gz` version on `CentOS 7.6`. Thanks.
