### ISSUE TITLE
How to adjust the job pool size for parallel execution is unclear

### ISSUE THREAD

**Issue by detly** [sharkdp/fd#450]
I would like to increase the job pool for parallel execution of my `-x` command beyond the number of cores to take advantage of my job being IO bound.

The [documentation](https://github.com/sharkdp/fd/blob/master/README.md) says:

> If the `-x/--exec` option is specified alongside a command template, a job pool will be created for executing commands in parallel for each discovered path as the input.

The man page says:

```text
       -j, --threads num
              Number of threads to use for searching (default: number of available CPUs).
```

It's not clear whether the two are related.

**Comment by sharkdp** [comment]
Thank you for reporting this. The documentation should be improved.

Currently, `-j, --threads num` sets both: the number of threads used for searching AND the number of threads used for execution. So you can definitely use it to increase the job pool size.

**Comment by sharkdp** [comment]
This was added in #454 by @detly.
