### ISSUE TITLE
"fd" don't show results, but "find" does

### ISSUE THREAD

**Issue by xtavras** [sharkdp/fd#458]
Hello,

I'm not sure if it's bug or I miss something. I was searching for "admin.conf", "**fd**" shows empty result, **"find"** show everything right, the directory or files are not hidden (i've tried -H as well) 

```
% cd somedir
% fd admin.conf
```
```
% find -iname admin.conf
./inventory/mycluster/artifacts/admin.conf
```
```
% fd admin.conf
```

version 7.3.0

**Comment by sharkdp** [comment]
Please see: https://github.com/sharkdp/fd#troubleshooting

**Comment by xtavras** [comment]
@sharkdp thanks, the file was defined in ".gitignore"
