### ISSUE TITLE
Option to output basenames only

### ISSUE THREAD

**Issue by jswny** [sharkdp/fd#460]
Hello, I am using `fd` as a `find` replacement for the purposes of piping into `fzf` and some other things. Is there any way to output only the basename of each result when searching in a specific path? For example, if I have a directory `~/foo` and I run an `fd` search like this:
```sh
$ fd . ~/foo
/Users/joe/foo/bar
/Users/joe/foo/bar/qux
/Users/joe/foo/baz
```
I would like to know if there's a way to only output the basenames for the results in `fd`. Like this:
```sh
bar
qux
baz
```

The use case for this is basically emulating `ls ~/foo` without including the full path. My personal use case is using `fd` to quickly output the contents of directories that I have selected via `fzf` into a preview window.

GNU `find` has a feature for this in the form of `-printf` like so: `find ~/foo -type f -printf '%f\n'`. 

I know this is possible by piping into `basename` via `xargs` or something similar but that is slow because to maintain colors you have to use `unbuffer` or something similar (this is all according to my testing in which which I could easily be doing something wrong):
```sh
$ time bash -c "fd . ~/github | xargs basename > /dev/null"
        0.14 real         0.33 user         0.62 sys
```
```sh
$ time bash -c "unbuffer fd . ~/github | xargs basename > /dev/null"
        1.00 real         0.78 user         1.65 sys
```
In addition, `basename` can only handle so much which means you sometimes get things like this with larger searches:
```sh
$ time bash -c "fd . ~/github | xargs basename > /dev/null"
xargs: basename: Argument list too long
```
Doing this with `fd --exec` is also very slow because you have to call the `basename` executable:
```
$ time bash -c "fd --exec basename {} \; . ~/github > /dev/null"
        5.29 real         5.92 user        13.01 sys
```

Apologies if this feature exists, if there is a way to do it I couldn't seem to figure it out from the documentation. Thanks for the help!

**Comment by tavianator** [comment]
`fd --color=always` is likely faster than unbuffer.  I'm not sure what platform you're on, but "argument list too long" from `xargs` seems like a bug.  POSIX [specifies](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/xargs.html) that it should always work within `ARG_MAX`.

Anyway, the following works for me:

```sh
$ fd --color=always | sed 's|.*/||'
```

**Comment by jswny** [comment]
@tavianator Ah I see, I didn't realize I could preserve the coloring through a pipe with `--color` but that works well enough for me! I benchmarked it and its just as fast as vanilla `fd` so no problems there. Thanks for you help! I'm not sure about the `xargs` thing but it definitely seems to be an issue with `xargs` itself or elsewhere.
