### ISSUE TITLE
Any idea "fd failed to install, please install it again" on Ubuntu 16.04.6 LTS

### ISSUE THREAD

**Issue by butterl** [sharkdp/fd#462]
install with
```
sudo dpkg -i fd_7.3.0_amd64.deb
```
call fd and return
``` 
fd failed to install, please install it again
```

**Comment by sharkdp** [comment]
I can't help without having more information. What OS/distribution are you on? Have you installed `fd` previously? Is there any other output (maybe run with a "verbose" option)?

**Comment by butterl** [comment]
I updated the system to 18.04.2 LTS,  the install error in 16.04 disappeared ， on 16.04  `fd failed to install, please install it again` was the only returned error log
