### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by shadowrylander** [sharkdp/fd#465]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; So I have a massive list of around `8200` or so absolute file paths in my `.fdignore` file, which I am specifying using `--ignore-file /path/to/.fdignore`; I assumed `fd` would have found everything else not in the `.fdignore` file that is in the source directory, but it finds nothing, and I know for a fact that not everything in the source is in the ignore file, as I compared the line numbers in the file with the contents of the source directory in its properties. I'm using `--absolute-path`, `--full-path`, `--follow`, `--hidden`, and `--no-ignore-vcs`, but `fd` still can't find the files. I'm suspecting `fnmatch` may be at fault here. <br>
&nbsp;&nbsp;&nbsp;&nbsp; The command is:
```bash
fd . --hidden --no-ignore-vcs --absolute-path --follow --full-path  --ignore-file "/s/borg/test/surface/test/ignore/.fdignore" "/s/borg/test/source"
```
&nbsp;&nbsp;&nbsp;&nbsp; Any help would be greatly appreciated!

**Comment by sharkdp** [comment]
Thank you for the report.

This is hard to debug without further information on how to reproduce this.

Could you try to find the names of some files which you would expect to see? You could run `fd -HI | sort` and compare the result to `cat /path/to/.fdignore | sort`.




> So I have a massive list of around `8200` or so absolute file paths in my `.fdignore` file

Note that entries in the `.fdignore` file are treated as glob patterns, not as absolute file paths. so something like `/path/to/a.c` would also prevent `/path/to/abc` from showing up in the search results.

**Comment by shadowrylander** [comment]
Ah; the second point might be the issue. Is there any way to get `fd` to treat them as absolute file paths? My program requires a list of included files from a set of inclusion rules, rather than a set exclusion rules. So I'm trying a roundabout method instead.

**Comment by tmccombs** [comment]
> Note that entries in the .fdignore file are treated as glob patterns, not as absolute file paths. so something like /path/to/a.c would also prevent /path/to/abc from showing up in the search results.

Wait, I thought .fdignore used the same syntax as gitignore, in which case a "." is just treated as a literal ".". The same argument would be true for characters like "*" and "?" but those are much less  common in filenames.

**Comment by shadowrylander** [comment]
@tmccombs Where could I get a list of these charaters, if possible?

**Comment by sharkdp** [comment]
> Wait, I thought .fdignore used the same syntax as gitignore, in which case a "." is just treated as a literal ".". The same argument would be true for characters like "*" and "?" but those are much less common in filenames.

You are absolutely right, I was confused there for a second.

> @tmccombs Where could I get a list of these charaters, if possible?

See, for example, https://git-scm.com/docs/gitignore#_pattern_format

But as @tmccombs said, most of them are unlikely to appear in filenames. Could you try to compare the two sorted lists, as I suggested above?

**Comment by shadowrylander** [comment]
@sharkdp Ah, right; sorry about that! Completely slipped my mind. Yes, all the files I wanted to include are not in the `.fdignore` file.

**Comment by shadowrylander** [comment]
Of course, my code might be too complicated; does the `.fdignore` follow this particular inclusion rule for the `.gitignore`: https://github.com/git/git/commit/d589a67eceacd1cc171bbe94906ca7c9a0edd8c5#diff-7fea460d44f92f185e7add8aa5620305R144

**Comment by sharkdp** [comment]
I'm sorry, it is getting harder and harder to follow along.

> Although that's interesting: only one folder's entire `.git` and `.hg` contents are being included as well... I don't want _those_...

What do you mean by included? Included in the `.fdignore` file by your automatic generation?

> The original exclusion and inclusion rules, from which I generated the `.fdigore`, are like this:
> [...]

What kind of file is this?

Is it possible that you could show us the full `.fdignore` file (maybe upload to https://gist.github.com/)? And possibly some file paths which you would expect to see in `fd`s output`?



> does the `.fdignore` follow this particular inclusion rule for the `.gitignore`: [git/git@d589a67#diff-7fea460d44f92f185e7add8aa5620305R144](https://github.com/git/git/commit/d589a67eceacd1cc171bbe94906ca7c9a0edd8c5#diff-7fea460d44f92f185e7add8aa5620305R144)

I don't know for sure (`.gitignore` matching is done by the `ignore` crate), but I would guess so. It should be easy to check in a minimal example.

**Comment by shadowrylander** [comment]
In a nutshell, I basically need a list of included files in a directory, and a list of excluded files in a directory. Is there a way to pass `fd` a file of inclusion rules, similar to passing it the `.fdignore` file using `--ignore-file`? I know you can use the `regex` pattern right after `fd` to include files, i.e. `fd [regex_pattern] [directory]`, but can you pass in a list of those?

> It should be easy to check in a minimal example.

Apparently `.fdignore` does not follow that inclusion method.

**Comment by sharkdp** [comment]
Your example also wouldn't work in git. Please read up on how `.gitignore` files work. For example: https://stackoverflow.com/questions/5533050/gitignore-exclude-folder-but-include-specific-subfolder

I'd like to close this issue. If there is reproducible example where `fd` misbehaves (i.e. different from Git), please feel free to re-open this ticket or to post a new one.

**Comment by shadowrylander** [comment]
Ah, of course; that makes sense. Thanks!
