### ISSUE TITLE
Does exclude option really works?

### ISSUE THREAD

**Issue by vkuznet** [sharkdp/fd#467]
Hi,
I'm trying to understand how exclude option works and having hard time with it. I'm working on macOS where usually we have plenty of stuff in $HOME/LIbrary and I want to exclude my Dropbox, and other paths, but regardless from provided option fd seems to scan these areas anyway, e.g.

```
fd --exclude /Users/vk/Library --type f --color never ics
or
fd --exclude Library --type f --color never ics
```
I still get output with plenty of files from Library area, e.g.
```
Library/Caches/GeoServices/Resources/default-genericshields-small-7.genericshieldstyles
```
So from my point of view exclude option does not really work on Mac, but may be I'm doing something wrong.

**Comment by n8henrie** [comment]
Seems to work okay for me. What directory are you running this from?

```shell_session
$ fd --type f '\.ics$' | wc -l
25776
$ fd --exclude Library --type f '\.ics$' | wc -l
42
$ fd --version
fd 7.3.0
$ uname -a
Darwin macbook.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64 i386 MacBookAir7,1 Darwin
```

**Comment by n8henrie** [comment]
A few more examples.

Using your exact command:

```console
$ fd --type f --color never ics | wc -l
27282
$ fd --exclude Library --type f --color never ics | wc -l
1177
```

Some results still have the word `library` in them, either because it's part of another word (e.g. `Photos Library`) or because it's lowercase:
```console
$ fd --exclude Library --type f --color never ics | grep -i library | wc -l
71
```

Adding some wildcard globs excludes all cases of `Library` anywhere in the result:
```console
$ fd --exclude '*Library*' --type f --color never ics | grep -i library | wc -l
10
```

And accounting for case sensitivity in the first letter excludes the rest of the results:
```console
$ fd --exclude '*[Ll]ibrary*' --type f --color never ics | grep -i library | wc -l
0
```

**Comment by vkuznet** [comment]
ok, thanks for clarification.

**Comment by sharkdp** [comment]
@n8henrie Thank you for helping out here!
