### ISSUE TITLE
Is Globbing supported like /disk/movie*/*/

### ISSUE THREAD

**Issue by Schizo** [sharkdp/fd#468]
I'm not sure if this is breaking `fd`, but was wondering if `fd` can use glob style search patterns. I'm using fd to list directories/files especiallay with the --changed-within command but would like to use glob to search on a drive only within specific paths.

Is that doable?

**Comment by sharkdp** [comment]
Not yet, please see #284

**Comment by sharkdp** [comment]
This is now supported.
