### ISSUE TITLE
--changed-within/--changed-before not working with directories

### ISSUE THREAD

**Issue by mrzool** [sharkdp/fd#470]
Took me a while to figure out… these options work fine when searching files, they don’t currently work when searching directories (thus when `-t d` is given).

Grateful for pointers.

Thanks for this amazing little tool.

**Comment by sharkdp** [comment]
Thank you for reporting this!

I hope this could be fixed really easily by removing this condition:
https://github.com/sharkdp/fd/blob/a0505bd4df82dc2203195d4f651a5ab7227987d0/src/walk.rs#L358

I'm not sure why it is there. It could be a copy&paste error from the size-constraints block above (where is_file is actually needed).

**Comment by sharkdp** [comment]
Fixed in [v7.4.0](https://github.com/sharkdp/fd/releases/tag/v7.4.0).

**Comment by thisguychris** [comment]
Hi, @sharkdp. Thank you for the fix. 🤝🏻 I've also got bitten by this, 😅, Like @mrzool, it took me a while to figure out that it wasn't working in directories. Ubuntu's still at v7.2. When I've updated it to v7.4.0 seems the problem went away.

I'm not sure if we should add in the README to use the latest version for the latest bugfixes. I wouldn't want people to get the same experience as me, especially if their time is really precious.

**Comment by sharkdp** [comment]
@thisguychris Thank you for the feedback.

> Ubuntu's still at v7.2. When I've updated it to v7.4.0 seems the problem went away.
> 
> I'm not sure if we should add in the README to use the latest version for the latest bugfixes

To be honest, I don't think so. That's a very general problem that appears with any kind of software. If you are using outdated versions, you might not have the latest bugfixes. This is not a critical bug, so I don't think any further action is required.
