### ISSUE TITLE
How to execute command properly

### ISSUE THREAD

**Issue by xasx** [sharkdp/fd#473]
Hi there,

I need support since it seems that I am unable to figure out the correct command line.

Is…
```bash
fd -tx -x'{} -version;' "^java\$" / 
```
…supposed to work? I only get errors like

```
[fd error]: Command not found: "/usr/lib/jvm/zulu-8/bin/java -version;"
[fd error]: Command not found: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.fc30.x86_64/bin/java -version;"
[fd error]: Command not found: "/usr/lib/jvm/zulu-12/bin/java -version;"
[fd error]: Command not found: "/usr/lib/jvm/java-11-openjdk-11.0.4.11-0.fc30.x86_64/bin/java -version;"
```

What am I missing?

**Comment by ilyapopov** [comment]
Just don't use quotes around your command, this requires moving `-x` to the end of the command line:

```
fd -tx "^java\$" / -x {} -version 
```

Be careful, though, executing unexpected files may be dangerous.

**Comment by xasx** [comment]
Thank you @ilyapopov 

I already considered doing some rough check on the executable, but unless my command was not working at all, I had to ask first.

Many thanks again.
