### ISSUE TITLE
Output to find format?

### ISSUE THREAD

**Issue by brendonmackenzie** [sharkdp/fd#474]
I prefer to use `fd` over `find` but sometimes the default output doesn't seem to play nicely when piped to other programs (in my case `rmlint`). Is there a flag that I am missing to make this easier? 
(I really just mean the `./` before each file or directory)

e.g. the behaviour under find might be:

``` bash
$ find .
.
./file3.txt
./file2.txt
./file1.txt
./directory1
./directory1/file4.txt
```

With fd:

``` bash
$ fd
directory1
directory1/file4.txt
file1.txt
file2.txt
file3.txt
```

I am currently working around the issue by using `--exec echo` but this affects performance:

``` bash
$ fd --exec echo "./{}"
./file3.txt
./file2.txt
./file1.txt
./directory1
./directory1/file4.txt
```

Am I doing this right?

**Comment by sharkdp** [comment]
Would the `-a`/`--absolute-path` option work for you?

**Comment by brendonmackenzie** [comment]
Thanks. Yes, I managed to make that work and for it to perform rapidly.
