### ISSUE TITLE
flag to force color

### ISSUE THREAD

**Issue by CallumHoward** [sharkdp/fd#49]
Thanks for a great plugin!
`fd` doesn't use color when piping, however it can be useful. My usecase is for use with [lotabout/skim](https://github.com/lotabout/skim).
ripgrep provides this behaviour with: `rg --color=always`

**Comment by sharkdp** [comment]
Thank you for the suggestion. This is (more or less) already tracked here: #33

**Comment by Mic92** [comment]
This feature was not implemented. You can only disable colors now. The other tracking issue was closed.

**Comment by Mic92** [comment]
the current work-around is to use unbuffer from the expect package:

```console
$ unbuffer fd -t f '64*.c' | less
```

**Comment by sharkdp** [comment]
Good point. Let's reopen this.
