### ISSUE TITLE
Add a -l flag for listing more details about the files.

### ISSUE THREAD

**Issue by tewalds** [sharkdp/fd#491]
fd is great for listing the files that match some pattern, but if I want to know more details about those files (eg permissions, size, owner, modification date) I need to run them through `ls` or `exa`. `fd pattern -x ls -l` isn't such a great experience though: it isn't colored, the order is random, and the columns don't align if the file sizes aren't similar. Given that `-l` is the most common flag to `ls`, why not also support it in `fd`?

**Comment by sharkdp** [comment]
Thank you for your feedback.

> `fd pattern -x ls -l` isn't such a great experience though: it isn't colored, the order is random, and the columns don't align if the file sizes aren't similar.

All of this can be solved by using `--exec-batch`/`-X` instead of `--exec`/`-x` and telling `ls` to colorize the results:
```
fd … -X ls -l --color=auto
```

**Comment by tewalds** [comment]
I tried `-X`, but it didn't work, though maybe that's because I'm using the version in apt. Either way, `fd … -X ls -l --color=auto` doesn't exactly roll off the tongue. Could `fd -l ...` be a shortcut for that?

**Comment by sharkdp** [comment]
> I tried `-X`, but it didn't work, though maybe that's because I'm using the version in apt.

`-X` has been introduced in fd 7.3.0.

> Either way, `fd … -X ls -l --color=auto` doesn't exactly roll off the tongue. Could `fd -l ...` be a shortcut for that?

I certainly don't want to add `ls -l`-like functionality to `fd`, but I might be convinced to add something like this as an alias for `-X ls -l --color=auto`. This could also be a nice solution for #482.

However, I would first like to leave this for discussion.

A possible counter-argument is that we would have to choose a particular set of command-line options for `ls`. `ls -l --color=always` would be one choice, but others might prefer a different combination.

**Comment by tewalds** [comment]
If the argument against adding `ls -l` functionality to fd directly is the amount of extra work and code duplication, maybe `exa` can be used as a library? It's also in rust and already implements `ls -l` functionality, with colors.

As for `--color=auto` vs `always`, why not tie that to `fd`'s own `--color` flag? Just propagate it through to `ls`.

**Comment by sharkdp** [comment]
This has been implemented in #556.

**Comment by sharkdp** [comment]
This has now been released in [fd v8.0](https://github.com/sharkdp/fd/releases/tag/v8.0.0).
