### ISSUE TITLE
Installation on a chromebook with Linux (Beta)?

### ISSUE THREAD

**Issue by jmfayard** [sharkdp/fd#492]
Hello, I just started enabling Linux on my chromebook. 
https://support.google.com/chromebook/answer/9145439

The chromebook is a modified Ubuntu distribution, but I'm pretty new to this and I am not sure how to install it. 

`sudo apt install fd-find` or `sudo apt-get install fd-find` do not work

And I am not sure which `.deb` packet I should install from the release page

**Comment by sharkdp** [comment]
You need to find out what CPU architecture your Chromebook uses (by running `lscpu`, for example). Then, download the corresponding `.deb` file or tarball. Let us know if none of the provided binaries work for you.

**Comment by sharkdp** [comment]
@jmfayard it would be great to get some feedback if this worked for you.

**Comment by jmfayard** [comment]
@sharkdp it worked!

If anyone is interested, here is how I did it

- To know which architecture to use, I typed `uname -m`
- I went to https://github.com/sharkdp/fd/releases 
- I downloaded `fd_7.4.0_amd64.deb`
- I open the `Files` app and double clicked on the debian package and it installed correctly 

![Screenshot 2019-12-25 at 06 52 09](https://user-images.githubusercontent.com/459464/71434083-2184bb80-26e3-11ea-9102-2e6a5ea55aa4.png)

**Comment by sharkdp** [comment]
Thank you for the feedback.
