### ISSUE TITLE
is that possible to search file/folder in network ?

### ISSUE THREAD

**Issue by changchichung** [sharkdp/fd#493]
lets said I mount a share folder via gvfs , I can not change directory to that path , but I'm able to browse files/folders via nautilus .
since I do not know the real path , then I can not use fd to search files.
is there anyway to do so ?

**Comment by tmccombs** [comment]
I'm not an expert, but from my understanding, gvfs should mount a FUSE filesystem in ~/.gvfs that you could run fd from.

**Comment by changchichung** [comment]
yes, in ubuntu , that path will be stored in enveironment variable as $XDG_RUNTIME_DIR.
thanks for reply !
