### ISSUE TITLE
Optional second argument: starting directory

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#5]

**Comment by rfourquet** [comment]
Would be useful to allow specifying mutliple search path roots, i.e. `fd [pattern] [path [path ...]]`. 
PS: thanks for this tool, this allows me to get rid of my much less powerful python script for similar tasks. It also steals the name of another of my programs which Finds Dupes (a glorified fdupes), but that's fine, that last one is not needed nearly as often so I can rename it to a longer name!

**Comment by sharkdp** [comment]
Sounds good! Could you please open a new ticket for this?

**Comment by rfourquet** [comment]
Sure! cf. #166. I unfortunately don't know (yet) rust to provide a fix myself.
