### ISSUE TITLE
How to search glob like with regex?

### ISSUE THREAD

**Issue by Schizo** [sharkdp/fd#500]
This thread is based on a suggestion on issue https://github.com/sharkdp/fd/issues/284 to use regex if you want to achieve a glob like search.

So let's say I have a folder

```
/disk/movie/a030
/disk/movie/a040
/disk/movie/b030
/disk/movie/b040
```

And If I were to capture only the ones starting with an `a` would do `glob("/disk/movie/a*")` Is this possible with **fd** and regex patterns? And if yes can I get some help?

Thanks

**Comment by tmccombs** [comment]
the regex pattern for that would be `/disk/movie/a.*`

**Comment by Schizo** [comment]
Could you give me an example of how I would use this with `fd` searching in the directory `/disk/movie/ for the files `a*`

Thanks

**Comment by tmccombs** [comment]
if you are in the `/disk/movie` directory, you could use `fd 'a.*'`

**Comment by sharkdp** [comment]
With the latest version of `fd`, you can also just use globs:
```
fd -g 'a*' /disk/movie
```

**Comment by rnwolf** [comment]
I found in MS-Windows that using the quotes does not work.

```
C:\Users\rnwol\OneDrive>fd ^2019-10.*
Documents\2019\2019-10-29 test
Documents\2019\2019-10-29 test\2019-10-29 This is some file.pdf
Documents\2019-10-24T16.56.30 Annotation 2019-10-24 165627 -- test Hello.png
Documents\2019-10-29T08.09.59 New Text Document Test info.txt
Family\2019-10-27 Hello -- Test.txt
Family\2019-10-27 Hello again -- Test.txt

C:\Users\rnwol\OneDrive>fd ^2019-10.*png$
Documents\2019-10-24T16.56.30 Annotation 2019-10-24 165627 -- test Hello.png

C:\Users\rnwol\OneDrive>fd ^2019-10.*again.* ./Family
Family\2019-10-27 Hello again -- Test.txt

C:\Users\rnwol\OneDrive>fd ^2019-10.*txt$ ./Family
Family\2019-10-27 Hello -- Test.txt
Family\2019-10-27 Hello again -- Test.txt
```

**Comment by sharkdp** [comment]
@Schizo Any update on this? Do the suggested options work for your?

@rnwolf is this a question or a comment?

**Comment by rnwolf** [comment]
Comment for the next person who is wondering why quotes don't work.

**Comment by sharkdp** [comment]
Closing this, as there is no further feedback from @Schizo
