### ISSUE TITLE
Is it possible to implement -lname?

### ISSUE THREAD

**Issue by macrohard** [sharkdp/fd#505]
Using the find command with the -lname parameter makes it easy to find all matching symbolic links.

for example:
find . -lname '*libarchive*'

I can find all the symbolic links from the *libarchive* directory.

**Comment by sharkdp** [comment]
I don't think this is currently possible with `fd`. It's unlikely, that we are going to provide this functionality in the future.

> I can find all the symbolic links from the _libarchive_ directory.

... symbolic links *to* the `libarchive` directory, right?

**Comment by sharkdp** [comment]
closing this for now (as there is no further feedback).
