### ISSUE TITLE
No option to limit search to one file system

### ISSUE THREAD

**Issue by FallenWarrior2k** [sharkdp/fd#507]
Many tools surrounding file system traversal include an option to disable crossing file system boundaries. find includes the `-xdev` option, which accomplishes this. fd, however, seems to lack such a feature at the present time. I've looked through the man page and the issue list and was unable to find anything relating to this.

Looking at the docs of the ignore crate, implementation should be quite simple as well: it only requires adding a call to `.same_file_system(config.same_file_system)` to the [`WalkBuilder`](https://github.com/sharkdp/fd/blob/master/src/walk.rs#L72), assuming a corresponding option `same_file_system: bool` is added to `FdOptions`, with corresponding changes in `build_app()` and `main()`.

**Comment by sharkdp** [comment]
see also: #227 #74 #89 

Didn't know about the `.same_file_system` option, though.

**Comment by FallenWarrior2k** [comment]
Oh, sorry. Seems my search terms weren't precise enough.

However, since this uses an existing feature of the ignore crate, there _shouldn't_ be any performance degradation if the option is not used, since the ignore crate defaults it to false anyway. Since it is basically just adding a public API for a feature that already existed, albeit unused, I wonder if you'd consider adding it.

If not, feel free to close this and the corresponding PR.

**Comment by sharkdp** [comment]
> However, since this uses an existing feature of the ignore crate, there _shouldn't_ be any performance degradation if the option is not used, since the ignore crate defaults it to false anyway. Since it is basically just adding a public API for a feature that already existed, albeit unused, I wonder if you'd consider adding it.

Ok, that sounds reasonable. I'll take a look at the PR soon, thank you.

**Comment by sharkdp** [comment]
Released in [fd 7.5.0](https://github.com/sharkdp/fd/releases/tag/v7.5.0)
