### ISSUE TITLE
Option -H, breaking VCS ignore behaviour

### ISSUE THREAD

**Issue by kurkale6ka** [sharkdp/fd#510]
Hi,

Using version `fd 7.4.0` via brew (on Mac OS Catalina) and I notice that using `-H` disables the default VCS ignore behaviour. In my case .git/files are found with `fd -tf -H` in addition to 'normal' dot files. I would expect this to happen if also providing the `-I` switch

Regards

**Comment by sharkdp** [comment]
The `.git` folder is not "git ignored". Matches within the `.git` folder are thus expected to show up if you use `--hidden`/`-H`. Take a look at the `--exclude` option, if you want to exclude certain matches.

**Comment by kurkale6ka** [comment]
Got it. Thanks.
