### ISSUE TITLE
Show entries "exec" is operating on

### ISSUE THREAD

**Issue by cup** [sharkdp/fd#514]
If I want to find text files, I can do this:

~~~
fd txt
~~~

If I want to print all text files, I can do this:

~~~
fd txt -x cat
~~~

but can I do both? As a workaround, I can use Find:

~~~sh
find . -name '*.txt' -print -exec cat {} ';'
~~~

or Grep:

~~~sh
grep -r --include '*.txt' .
~~~

or Silver Searcher:

~~~
ag -G txt .
~~~

**Comment by sharkdp** [comment]
Thank you for the feedback. I think this is a duplicate of #406?

**Comment by cup** [comment]
@sharkdp yes, it is a duplicate, thank you
