### ISSUE TITLE
Incorrect behavior with --ignore-file and recursive wildcard

### ISSUE THREAD

**Issue by ijacquez** [sharkdp/fd#516]
**Steps to reproduce**
1. Create custom ignore file `.my-ignore`:
```gitignore
/Assets/Bundles/**
!/Assets/Bundles/**/*.json
```
2. Add many `.json` files within `Assets/Bundles/`, as well within subdirectories.
3. Call `fdfind`:
```bash
fdfind . \
    --color=never \
    --type f \
    -H \
    -E .git \
    -E .my-gitignore \
    --ignore-file .my-gitignore | grep 'Bundle'
```

**Results**
Only the `.json` file in `Assets/Bundles/` is listed, but not any `.json` from the subdirectories.

**Expected results**
_All_ `.json` files within `Assets/Bundles` should be listed.

**Versions tested**
- 7.2.0
- 7.4.0

**Comment by sharkdp** [comment]
If you use the same two patterns in a `.gitignore` file, does it work as expected?

**Comment by ijacquez** [comment]
Good idea. I'll verify...

**Comment by ijacquez** [comment]
I'm a bit surprised (in a good way) of the results.

What I had written in the OP doesn't work as I've expected with `git`.

The following works:
```gitignore
/Assets/Bundles/**/*
!/Assets/Bundles/**/*/
!/Assets/Bundles/**/*.json
```

You have to ignore all with the first line, following by excluding directories from being ignored (second line). I don't 100% understand exactly why, but doing so would allow the third line to work.

I tested this, and it works with `fd`.

**Comment by sharkdp** [comment]
Thank you for the feedback!
