### ISSUE TITLE
Why is the search with --full-path so slow

### ISSUE THREAD

**Issue by kontrafiktion** [sharkdp/fd#518]
Search with --full-path:

    fd --full-path workspaces/cc -e py  9.62s user 36.87s system 644% cpu 7.215 total

Search from $PWD:
```
cd workspaces/cc
fd -e py  0.20s user 0.40s system 677% cpu 0.089 total
```

**Comment by tmccombs** [comment]
`--full-path` is matching every file in the current tree against "workspaces/cc". I'm guess what you actually want is something like `fd -e py  . workspaces/cc`

**Comment by kontrafiktion** [comment]
ah yes, you are right, I have totally not seen the optional `[<path>...]` at the end of the command. Too much used to `find`
