### ISSUE TITLE
Provide binary downloads with every release for easy installation

### ISSUE THREAD

**Issue by jnachtigall** [sharkdp/fd#52]
I'm a ripgrep user on windows (git bash) and ripgrep makes it really easy to install: https://github.com/BurntSushi/ripgrep#installation. In my case I just did `$ choco install ripgrep`

Would be great if fd would also provide binary downloads with every release:

> ripgrep has first class support on Windows, Mac and Linux, with binary downloads available for every release.

I guess ripgrep has some automatic build tooling for this.

**Comment by sharkdp** [comment]
That would be great, I agree (especially if it would be automated)!

So far, I haven't figured out how to set up AppVeyor properly. Any help would be appreciated.

**Comment by sharkdp** [comment]
For the new release v4.0.0, there is at least a binary package available via the release page: https://github.com/sharkdp/fd/releases/tag/v4.0.0

**Comment by sharkdp** [comment]
@jnachtigall I'm closing this for now, as we now auto-generate Windows executables for every release. If you are interested in Chocolatey, in particular, please feel free to open a new ticket.

**Comment by jnachtigall** [comment]
Cool. @sharkdp btw, congrats for being on top of HN ;) You deserved it, very useful tool!

**Comment by sharkdp** [comment]
Thank you for the feedback!
