### ISSUE TITLE
Cannot build with cargo

### ISSUE THREAD

**Issue by unphased** [sharkdp/fd#521]
```
❯❯❯ cargo install fd-find  
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading fd-find v7.4.0
error: failed to parse manifest at `/home/slu/.cargo/registry/src/github.com-1ecc6299db9ec823/fd-find-7.4.0/Cargo.toml`

Caused by:
  editions are unstable

Caused by:
  feature `edition` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["edition"]` to enable this feature
```
I'm sure I'm just missing something basic, but the google is failing me currently.

**Comment by sharkdp** [comment]
It looks like the version of your Rust compiler is too old.

Please note that Rust 1.31 is required: https://github.com/sharkdp/fd#from-source

**Comment by unphased** [comment]
Thank you. I am certain that you're right. I actually saw a 1.31 requirement but decided to think it was 1.3.1 when I saw that the cargo version was 1.27...
