### ISSUE TITLE
Request: Remove version strings from release artifact naming

### ISSUE THREAD

**Issue by bbenne10** [sharkdp/fd#529]
Firstly, amazing project! Thanks for it!
Secondly, would it be too much to ask to remove the version strings from the release artifacts filenames? I am currently looking to incorporate automatic downloading and installing of some non-core utilities in my shell setup. For docker-compose, it looks a lot like this (in my `~/.bashrc` at the moment):

```sh
which docker-compose 1>/dev/null || curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)"
 -o ~/.local/bin/docker-compose && chmod +x ~/.local/bin/docker-compose
```

This is possible because docker-compose doesn't have the release number as a substring of the file name, which makes it relatively reliable to guess where I'll be able to download it from (if used alongside the `/latest/` release alias). This is SUPER convenient and REALLY nice! It allows me to grab up to date tooling without having to worry about installing it from an upstream. I use a somewhat out of date linux distro at work, which is unavoidable and unfortunate.

If you're unwilling to make this work, I 100% understand but would ask you to consider what value the version in the artifact's downloaded filename provides. Thanks again for the time and effort in this tool! I find it invaluable in my daily usage :)

**Comment by sharkdp** [comment]
Thank you for your feedback.

Ye, I think there is some value in having the version in the release artifacts, if only for a clean overview in a `Download` folder with many `fd-…` tarballs.

You can use the GitHub API to find the latest release version. For example:
```bash
curl https://api.github.com/repos/sharkdp/fd/releases/latest | jq .tag_name
```

Would that work for you? (if you don't have `jq` installed, a `grep`/`sed`/… combination would probably also work).

You could even list all download URLs via
```
curl -s https://api.github.com/repos/sharkdp/fd/releases/latest | jq '.assets[].browser_download_url'
```
and select (`grep` for) the one you need.

**Comment by bbenne10** [comment]
This was similarly mentioned in another repository. Seeing as jq is similarly non-standard, we appear to be at a bit of an impasse (`grep`, `sed` and the like will...work, but the solution is inelegant at best and wildly brittle at worst). 

The answer I found was that, seeing as `jq` has releases without numeric addendums, I can grab the latest release of `jq` and then use it to parse numeric releases. While not my preferred solution, it works. 

The real problem lies in the fact that github knows NOTHING about releases. For instance, my `grep` line would need to be quite a bit different on my raspberry pi ("armv7"...or was it just "arm") than on my desktop ("x86_64"...or "amd64"...or un-suffixed, because it's the most common target!). Version strings are only a part of the problem, but one that's solvable by a convincing enough argument :)

I'm going to close this, as there's a solution (though not a great one) and the problem should be solved by github (adding metadata with fixed schema to releases would be incredible for this use case). Thanks for the consideration and for taking the time to reply!

**Comment by sharkdp** [comment]
Thank you for the response.

Your problems pretty much sound like they should be solved by an actual package manager. What OS / distro are you on? There are official packages for quite a few package managers: https://github.com/sharkdp/fd#installation

**Comment by bbenne10** [comment]
Herein is the problem: im om multiple distros + OSX. I am required to spin up on new boxes more frequently than i would like, and id like to insulate myself from thr rigamarole of package version differences, package naming differences and from the explicit set up step as much as is feasible

![Zplugin (now zinit, i guess)](https://github.com/zdharma/zinit) offers this (by allowing `ice` declarations which grab from multiple sources, notably Github Releases, and unpack into one's `fpath`), but i was recently ALSO forced to use bash as a login shell for...reasons :unamused:.

This request is borne out of my attempts to replicate this setup in bash without overcomplicating it. It's a hard problem to solve, as it turns out.

:shrug:
