### ISSUE TITLE
Powershell and exec issues

### ISSUE THREAD

**Issue by SonOfDiablo** [sharkdp/fd#538]
There seems to be an issue with fd and executing powershell cmdlets/aliases.

Here is an example of the issue:

```
# fd can find the file no problem.
> fd install
install.json

# fd can't run rm...
> fd install -x rm
[fd error]: Command not found: "rm" "install.json"

# rm is an alias, so fair enough lets use the original cmdlet.
> which rm
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           rm -> Remove-Item

# Remove-Item is indeed a Powershell cmdlet
> which Remove-Item

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Remove-Item                                        3.1.0.0    Microsoft.PowerShell.Management

# fd can't run the cmdlet either...
> fd install -x Remove-Item
[fd error]: Command not found: "Remove-Item" "install.json"

# Now lets try with a binary instead.. That seems to work.
> fd install -x bat
{
    "bucket": "main",
    "architecture": "64bit"
}

# bat was installed with Scoop so the binary is ran via the Powershell shim Scoop creates.
> which bat
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
ExternalScript  bat.ps1                                                       D:\scoop\shims\bat.ps1

# Also works fine if calling bat directly (as expected, but thought I would include it none the less).
> fd install -x D:\scoop\apps\bat\current\bat.exe
{
    "bucket": "main",
    "architecture": "64bit"
}
```

Is this an actual issue or am I just missing something obvious?

**Comment by sharkdp** [comment]
Thank you for the feedback.

This is not an actual issue and is actually expected. `fd` does *not* spawn a shell in which it runs your commands. It runs an actual executable (with a number of arguments). Aliases and Powershell commands are not actual executables. You would need to have a `del.exe` file or similar in order to make this work. I'm not sure if Windows provides something like this.

You can also run PowerShell explicitly via something like `fd -x powershell /C "shell command"`, but you need to be VERY careful with proper escaping etc.

**Comment by SonOfDiablo** [comment]
Right that was what I thought, I was just wondering mostly if you had any plans on addressing the "issue" (though I understand that it isn't something that is reasonable to include in fd).

As far as I know there is no .exe for the Powershell commands... Best I can think of is trying to collect the ports of the linux equivalents (or some other alternatives).

Also I just want to add that I made a mistake in my original post stating that fd was executing the .ps1 shim of bat, in fact it's using the .exe shim that Scoop creates.

**Comment by sharkdp** [comment]
We explicitly decided against using an intermediate shell. I think there are multiple reasons (see #84):

- We are not vulnerable to shell injection bugs where someone forgets to properly escape the filepaths, suddenly executing commands they never wanted to run.
- It can be much faster. Spawning a shell takes ~2ms for every command, which can be a significant overhead if the command itself is fast (like `rm`).
- We don't have to worry about availability of different shells on different platforms. We would have to make a choice: `sh` on Linux? `cmd.exe` on Windows, …?

**Comment by SonOfDiablo** [comment]
Right, I fully understand. It does seem like the best approach.

I guess I will have to make do with piping from fd if I need to use basic functions then.

Thanks for the explanation though! Really appreciate it! Keep up the good work :)

**Comment by sharkdp** [comment]
Hm. This would have been an argument pro #387
