### ISSUE TITLE
How to execute a sequence of commands ?

### ISSUE THREAD

**Issue by ngirard** [sharkdp/fd#539]
A common scenario is to be able to execute, not only one but a sequence of commands, for every path of a search result.

For instance, the following command unpacks every zip file:
```sh
fd -e zip -x unzip
```

But how to remove the zip file after unpacking it successfully ?
The syntax I found to work, after some trial & errors, is:
```sh
fd -e zip -exec sh -c 'unzip "{}" && rm "{}"'
```

Is there a more intuitive way ?
In any case, I'd suggest to include a similar example to README file.

**Comment by sharkdp** [comment]
Unfortunately, that's not (yet) possible. See also: https://github.com/sharkdp/fd/issues/406#issuecomment-462070251

**Comment by sharkdp** [comment]
I'm closing this in favor of #406
