### ISSUE TITLE
fd release v7.5.0

### ISSUE THREAD

**Issue by laur89** [sharkdp/fd#541]
Hia,
could you please release new ver of `fd`? It's been a few months and am waiting for some fixes that have long been implemented.

**Comment by sharkdp** [comment]
I am planning to do that soon, yes. If someone wants to help with the process (see https://dev.to/sharkdp/my-release-checklist-for-rust-programs-1m33), we can start compiling the changelog here in this ticket

* ChangeLog format: https://github.com/sharkdp/fd/releases/tag/v7.4.0
* Changes since v7.4.0: https://github.com/sharkdp/fd/compare/v7.4.0...master

**Comment by ImportTaste** [comment]
In the meantime, would you consider letting AppVeyor publish the artifacts it's compiling instead of discarding them?

**Comment by sharkdp** [comment]
> would you consider letting AppVeyor publish the artifacts it's compiling instead of discarding them?

I'm not sure how that would work and where these artifacts would end up

**Comment by Ordoviz** [comment]
You can use that as a draft for the changelog. I release my work under the [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/) license:

```
# Bug Fixes

- Fixed 'command not found' error when using zsh completion, see #487
  (@barskern).

# Features

- Added `--one-file-system` (aliases: `--mount`, `--xdev`) to not cross file
  system boundaries on Unix and Windows, see #507 (@FallenWarrior2k).
- Added `--base-directory` to change the working directory in which `fd` is
  run, see #509 and #475 (@hajdamak).
- Added `-u` and `-uu` aliases for no-ignore and no-ignore+hidden to match
  behaviour of ripgrep, see #92 and #98 (@unsignedint).
- `fd` will not use colored output if the `NO_COLOR` environment variable
  is set, see #550 and #551 (@metadave).

# Changes

- A flag can now be passed multiple times without producing an error, see
  #488 and #496 (@rootbid).
- Search results are sorted when using the `-X` option to match the behaviour
  of xargs, see #441 and #524 (@Marcoleni @crash-g).
```

**Comment by sharkdp** [comment]
@ignatenkobrain FYI

**Comment by ignatenkobrain** [comment]
LGTM from Fedora POV... Just don't forget to drop references to Fedora 28 and such... Latest non-EOL version is now F30 :)

**Comment by sharkdp** [comment]
@Ordoviz thank  you very much!

@ignatenkobrain Thanks for the reminder.

**Comment by sharkdp** [comment]
v7.5.0 is out: https://github.com/sharkdp/fd/releases/tag/v7.5.0
