### ISSUE TITLE
Proposal: add support for `git` information

### ISSUE THREAD

**Issue by bigH** [sharkdp/fd#543]
It'd be nice to have `git status` information as an option. I (and I'm sure many others) often use `fd` with `fzf` and turning on `git` information can be super useful in those instances.

(I should add that I use the hell out of `fd` in my personal setup. Thanks for all the hard work!)

**Comment by sharkdp** [comment]
Thank you for your feedback.

This has been shortly discussed in #222. Querying `git status` informatioin would incur a large performance penalty.

**Comment by bigH** [comment]
@sharkdp it's probably fine as long as it's optional. I agree that _everyone_ paying this penalty would be bad, but being able to choose whether or not to turn it on/off is super-handy. `exa` uses a `--git` option

**Comment by sharkdp** [comment]
I'd rather not implement this, to be honest. It would also add a dependency to `git` and possibly add a large amount of code and possible future maintenance work.

Note that there is a reasonable workaround in #222.

**Comment by bigH** [comment]
the suggestion in #222 is solid. thanks.
