### ISSUE TITLE
Add short option for --same-file-system

### ISSUE THREAD

**Issue by HaleTom** [sharkdp/fd#544]
I commonly use `-xdev` in `find`.

`--same-file-system` is a bit of a mouthful.  Would you consider adding `-X` or some other short form for this (currently longest) long option?

Related: #507 #536

**Comment by sharkdp** [comment]
`-x` and `-X` are already taken. However, we have `--xdev` and `--mount` as hidden aliases for `--same-file-system`.

**Comment by HaleTom** [comment]
Oooh, sweet!  

I couldn't see these in https://github.com/FallenWarrior2k/fd/commit/825c0b377ddd9529c7c2fb1344a531ac96b4c22d.

Hidden as in not documented in the man-page?

**Comment by sharkdp** [comment]
> Hidden as in not documented in the man-page?

Well, not shown in the `--help` text. But we should add them to the man page.
