### ISSUE TITLE
NO_COLOR support

### ISSUE THREAD

**Issue by rektide** [sharkdp/fd#550]
Hello. Lovely tool. 

I find myself doing a bunch of `fd whatever | cat` to strip out colors.

Would be lovely to have support for [NO_COLOR](https://no-color.org/)! Would give users are more consistent way to control this behavior.

Lovely tool. Played with it briefly a while back but after a [recent mention](https://mobile.twitter.com/dimfeld/status/1232468670367948800) from @dimfeld I've been using it quite consistently. It alleviated my specific gripe, which was ripgrep being ridiculously faster than find & needing less filtering after. Thanks ever much.

**Comment by sharkdp** [comment]
Thank you for the feedback!

> I find myself doing a bunch of fd whatever | cat to strip out colors.

Why? Simply because you don't like the colorized output? Note that the ANSI escape codes auto-disable when you pipe to another process.

Also, have you seen that colors can be deactivated using `--color=never`?

> Would be lovely to have support for [NO_COLOR](https://no-color.org/)! Would give users are more consistent way to control this behavior.

Sounds good to me.

**Comment by sharkdp** [comment]
closed in #551 by @metadave

**Comment by sharkdp** [comment]
Released in [fd 7.5.0](https://github.com/sharkdp/fd/releases/tag/v7.5.0)
