### ISSUE TITLE
fd interprets LS_COLORS quite differently

### ISSUE THREAD

**Issue by ri-aje** [sharkdp/fd#552]
I am on ubuntu 18.04 and my `fd` is 7.2.0. I customize LS_COLORS in my bashrc, e.g., `export LS_COLORS=$LS_COLORS:"*.pdf=06;35"`, then I noticed `fd` displays quite different color from the builtin `ls` or `exa` commands. `exa` gives identical color to `ls`, which is the expected behavior. how do I make `fd` to behave as `ls` and `exa`? I observed this discrepancy on multiple terminals. I checked history issues on LS_COLORS but didn't find a solution for my case. thanks.

see screenshot below for effects.
![image](https://user-images.githubusercontent.com/321429/78075994-6bbcaf00-735a-11ea-8d01-b7fc5804a515.png)

**Comment by sharkdp** [comment]
Thank you for reporting this.

First, `fd` 7.2.0 is quite old. We did a major update  on `LS_COLORS` support in [v7.3.0](https://github.com/sharkdp/fd/releases/tag/v7.3.0). True color support is one thing that is not supported in 7.2.0, for example (but that is not really relevant for this ticket).

The main problem here is the `06;35` ANSI style. `06` is short for "blinking", which is currently not supported by `lscolors` (the library `fd` uses for parsing `LS_COLORS`): https://github.com/sharkdp/lscolors/issues/2 Your example should work fine if you use a different font style ("normal", "bold": `01`, or "italic": `03`):
```bash
export LS_COLORS=$LS_COLORS:"*.pdf=01;35"
```

For unsupported font styles (faint, slow blink, rapid blink, dimmed, hidden, …), the library currently ignores the color (`35`) which comes after that. That's certainly not ideal and should be fixed. I will keep this ticket open until https://github.com/sharkdp/lscolors/issues/2 has been resolved.

**Comment by sharkdp** [comment]
Fixed via https://github.com/sharkdp/lscolors/pull/22, https://github.com/sharkdp/lscolors/pull/23 and #553 

we can now have blinking pdf files :tada:  :smile:

**Comment by ri-aje** [comment]
@sharkdp thanks. v7.3.0 made it look much better. when will https://github.com/sharkdp/fd/pull/553 be released?

**Comment by sharkdp** [comment]
Now: [fd v8.0](https://github.com/sharkdp/fd/releases/tag/v8.0.0).
