### ISSUE TITLE
Add -1 option as an alias for --max-results=1

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#561]
see #476

**Comment by tpiekarski** [comment]
Did anyone started already? Would like to offer a PR and implement that tomorrow.

**Comment by SimplyDanny** [comment]
I did. See #563.

**Comment by tpiekarski** [comment]
Thanks, so guess I move along and search for other good first issues to get into Rust. :disappointed:

**Comment by sharkdp** [comment]
closed in #563 by @SimplyDanny.

@tpiekarski There are a few more "good first issues" in `fd`s issue tracker. Some of these tickets are [staged for the upcoming v8.0 release](https://github.com/sharkdp/fd/issues?q=is%3Aopen+is%3Aissue+milestone%3Av8.0+label%3A%22good+first+issue%22).

Ordered by increasing complexity:
* #469 (in v8.0 milestone)
* #562  (in v8.0 milestone)
* #485 
* #511 (in v8.0 milestone)

**Comment by tpiekarski** [comment]
@sharkdp Thanks, I'll take a closer look at those issues 😊

**Comment by sharkdp** [comment]
This has now been released in [fd v8.0](https://github.com/sharkdp/fd/releases/tag/v8.0.0).
