### ISSUE TITLE
Find items by exact name, no glob, no regex

### ISSUE THREAD

**Issue by anahata0108** [sharkdp/fd#566]
It would be nice if I could use fd to find files by the exact name I specify. Not an implied glob of `*ARG*`, not an implied regex of `.*ARG.*`. Just `ARG`.

**Comment by sharkdp** [comment]
For globs, `*ARG*` is *not* implied. So you can use the glob option to get exact matches.

There is also `--fixed-strings`, but that has an implied `.*xxx.*`.

**Comment by anahata0108** [comment]
Oh! I must have misunderstood something along the way. I see that if I specify `-g` then I do get the exact matching I was looking for. I think I'll want to set an alias to use `-g` since that tends to be what I actually want.

Thank you for the fast reply!
