### ISSUE TITLE
--hidden overrides --ignore-file

### ISSUE THREAD

**Issue by texastoland** [sharkdp/fd#574]
**Describe the bug you encountered:**

`fd -E=node_modules ignore` returns no results.
`fd -HE=node_modules ignore` returns hidden results without `node_modules`.
`fd -H --ignore-file node_modules.ignore` returns hidden results with `node_modules`.

**Describe what you expected to happen:**

I expected the ignore file to return the same results as excluding the patterns individually. I don't Rust but [your implementation](https://sourcegraph.com/github.com/sharkdp/fd@04bcd546b2446a188bb098455817228381d195df/-/blob/src/walk.rs#L85:32&tab=references) looks comparable to [ripgrep's implementation](https://sourcegraph.com/github.com/BurntSushi/ripgrep@e772a95b58b77604e9a4657e949431539ec15b08/-/blob/crates/core/args.rs#L866:30&tab=references).

It seems counterintuitive to me that the _ignore_ crate treats them differently. @BurntSushi Is it a bug or by design?

**What version of `fd` are you using?**

`8.0.0`

**Which operating system / distribution are you on?**

`Darwin 19.4.0 x86_64`
`Mac OS X 10.15.4 19E287`

**Comment by sharkdp** [comment]
Thank you for the bug report.

I'm not sure I understand. Why are you adding `ignore` to your first two `fd` calls? Are you searching for filesystem entries containing the word "ignore"?

The following behavior seems fine for me:
``` bash
❯ tree -a
.
├── .foo
├── foo
└── node_modules
    ├── .foo
    └── foo

1 directory, 4 files

❯ fd # show all matches, except hidden files
foo
node_modules
node_modules/foo

❯ fd -E=node_modules # ignore node_modules
foo

❯ fd -HE=node_modules # ignore node_modules, but show hidden files
.foo
foo

❯ echo "node_modules" > node_modules.ignore # create a custom ignore file
❯ fd -H --ignore-file=node_modules.ignore # use it
.foo
foo
node_modules.ignore
```

**Comment by texastoland** [comment]
> Are you searching for filesystem entries containing the word "ignore"?

It took an hour to realize I left out the query from my last command 🤦🏽‍♂️ I spent the last day trying to figure out why `fd` wasn't playing nice with `fzf`. Now it just works. Thanks for your example!
