### ISSUE TITLE
Windows binaries for newest release have an old version instead (7.3.0 instead of 8.0.0)

### ISSUE THREAD

**Issue by zed-g** [sharkdp/fd#576]
**Describe the bug you encountered:**

The Windows binaries included with the new release of version 8.0.0 available at <https://github.com/sharkdp/fd/releases/tag/v8.0.0> are actually version 7.3.0:

```
$ fd --version
fd 7.3.0
```

(I found out by trying the new flag `-l`/`--list-details`, which naturally did not work.)

As far as I can tell the chocolatery package available at <https://chocolatey.org/packages/fd> also includes the wrong binary .

**Describe what you expected to happen:**

I expected the binaries available from the release page to include the actual version the release has in its name.

**Which operating system / distribution are you on?**
I tried this out for the Windows binaries:

- fd-v8.0.0-i686-pc-windows-gnu.zip
- fd-v8.0.0-i686-pc-windows-msvc.zip
- fd-v8.0.0-x86_64-pc-windows-gnu.zip
- fd-v8.0.0-x86_64-pc-windows-msvc.zip

**Comment by sharkdp** [comment]
I can not reproduce this:

![image](https://user-images.githubusercontent.com/4209276/80114718-2cae0200-8584-11ea-9223-474cbaa9460e.png)


Please make sure that you do not have an old version of `fd` installed somewhere else.

**Comment by zed-g** [comment]
Oh man, I tried again and you are totally right! I mixed up my paths and had an older version already installed. I deleted the older version from PATH and now everything is as it should be. Thanks for your great tools and sorry for the noise!

**Comment by sharkdp** [comment]
no worries :smile:
