### ISSUE TITLE
Disable color when not supported

### ISSUE THREAD

**Issue by muv1** [sharkdp/fd#577]
When I run `fd`, I get this:

~~~
[1;34mext\ [0mphp_mbstring.dll
php7embed.lib
~~~

I think `fd` should automatically detect when the user has a terminal without
ANSI support, and disable colors.

**Comment by sharkdp** [comment]
Which OS are you on? Which terminal emulator? Which version of `fd`?

**Comment by muv1** [comment]
> Which OS are you on? Which version of fd?

~~~
fd-v8.0.0-i686-pc-windows-msvc.zip
~~~

> Which terminal emulator?

<https://en.wikipedia.org/wiki/Cmd.exe>

**Comment by sharkdp** [comment]
Are you on Windows 8 or older?

Have you seen the entry in the release notes: https://github.com/sharkdp/fd/releases/tag/v8.0.0

> Colored output will now be enabled by default on older Windows versions.
This allows the use of colored output if the terminal supports it (e.g.
MinTTY, Git Bash). On the other hand, this will be a regression for users
on older Windows versions with terminals that do not support ANSI escape
sequences. Affected users can use an alias fd="fd --color=never" to
continue using fd without colors. There is no change of behavior for
Windows 10. See #469.

**Comment by muv1** [comment]
Ok, so it seems I am a member of that group. In my opinion, the best way to handle this problem in general is like this:

SOLUTION A: detect users terminal capability. If ANSI supported, use color

SOLUTION B: If not possible to detect ANSI, detect OS. If not Windows 10, no color

**Comment by sharkdp** [comment]
Sure, that sounds great. However, I think it was deemed impossible to detect these terminal capabilities. If someone know how to do this, I'm happy to change the behavior in `fd` accordingly.



> Ok, so it seems I am a member of that group.

So just to confirm: you are on Windows 8 or older, and you use `cmd.exe` as your terminal emulator? (..and you don't care about having colorized output)?

**Comment by muv1** [comment]
I am on Windows older than 10, and I use `cmd.exe`. I do care about having colorized output, but its not important enough to worry about some alternate terminal. I plan on upgrading to Windows 10 in the next year.

However all that above isnt really the important detail. The important detail is: for all Windows versions before 2016 (including Windows 10), ANSI is not supported:

https://en.wikipedia.org/wiki/ANSI_escape_code#DOS_and_Windows

So it makes sense to turn the color off, by default. Otherwise if you giving an unpleasant experience to these users.

**Comment by sharkdp** [comment]
> So it makes sense to turn the color off, by default. Otherwise you are giving an unpleasant experience to these users.

But what about users on recent versions of Windows (see https://github.com/sharkdp/fd/issues/469)? Shouldn't we rather choose a good default for them?

**Comment by muv1** [comment]
@sharkdp pseudocode:

~~~php
if ($os == 'Windows 10') {
   $color = true;
} else {
   $color = false;
}
~~~

**Comment by sharkdp** [comment]
Ok, sounds good to me if someone can turn that into actual code :smile:. It's a bit more complicated though. We have three color modes (`--color`):
* `never`: never ever emit color codes
* `always`: always emit color codes, don't care about OS, terminal emulator etc.
* `auto`:
  * if the output of `fd` goes to a pipe, do *not* emit color codes
  * if the output goes to an interactive terminal, use `$default`

where `$default` would be "use color" on supported operating systems and "do not use color" otherwise.

**Comment by sharkdp** [comment]
I will need support from someone that has access to Windows 10 and older Windows versions in order to properly test this.

**Comment by muv1** [comment]
I can do older, and probably newer too. I have Virtualbox and I have virtualized Windows 10 before, but I would like to try to find an ISO thats not 6 GB if thats possible.

**Comment by bagage** [comment]
I do have the same issue (from #585), using pwsh under W7. I've colors in terminal but fd 8.0.0 colors are not displayed properly:

![image](https://user-images.githubusercontent.com/1451988/81790258-734ca780-9505-11ea-950d-7b4acfbc68c9.png)

Can help with both old (W7) and recent (W10) versions if needed.

**Comment by sharkdp** [comment]
I reverted my "fix" from 8.0 and published [fd 8.1](https://github.com/sharkdp/fd/releases/tag/v8.1.0). Could somebody please confirm that this issue has been resolved?

**Comment by muv1** [comment]
I mean its better... buts its even black and white if I use a terminal that
supports color. I think the logic I used before should be updated to this
pseudocode:

~~~php
if ($opt == '-c always' || $os == 'Windows 10') {
   $color = true;
} else {
   $color = false;
}
~~~

Mintty and other terminals for Windows support color, even with older Windows
versions. So in this case you dont have to use any heuristic, if someone
explicitly says they want color, give it to them, even if its not supported.

**Comment by sharkdp** [comment]
> buts its even black and white if I use a terminal that
> supports color.

which terminal?

> the logic I used before should be updated to this
> pseudocode:

this is probably what #469 is all about, which I have just re-opened. Note that it's not that easy. There are Windows 10 versions that do not support ANSI escape sequences.

**Comment by muv1** [comment]
@sharkdp you should be able to get exactly what you need like this:

~~~rust
#[link(name = "ntdll")]
extern {
   fn RtlGetNtVersionNumbers(major: *mut u32, minor: *mut u32, build: *mut u32);
}
fn main() {
   let mut n1 = 0u32;
   let mut n2 = 0u32;
   let mut n3 = 0u32;
   unsafe {
      RtlGetNtVersionNumbers(&mut n1, &mut n2, &mut n3);
   }
   let n_loword = n3 & 0xFFFF;
   dbg!(n1, n2, n_loword);
}
~~~

With my Windows 7 computer, I get `6 1 7601`, which exactly matches `ver.exe`:

~~~
Microsoft Windows [Version 6.1.7601]
~~~

and on my Windows 10 computer, I get `10 0 18363`.

**Comment by sharkdp** [comment]
Thank you. Can we move the discussion to #469 please? (unless you think that your issue is not related to that)

**Comment by muv1** [comment]
If you mean close issue, sure. or do you need some other information?

**Comment by sharkdp** [comment]
I think we don't need the check for the Windows version. The result of `ansi_term::enable_ansi_support().is_ok()` will tell us if ANSI sequences are supported or not. The question is: what do we do if that returns `false`? I agree with you that we should still enable colors if `--color=always` is set. This is the first suggestion in https://github.com/sharkdp/fd/issues/469#issuecomment-532314748
