### ISSUE TITLE
Install fails on Ubuntu 20.04 LTS: failed to run custom build command for jemalloc-sys v0.3.2

### ISSUE THREAD

**Issue by nachoguru** [sharkdp/fd#578]
**Describe what you expected to happen:**
**Describe the bug you encountered:**

I'm not a Rust or C++ programmer, I just use a few awesome tools written in Rust, including `fd`.

I spun up a new Ubuntu 20.04 LTS droplet at Digital Ocean, ran `apt install rustc` and when I tried to add favourite command line tools including `fd`:

```
cargo install exa fd-find rage ripgrep tokei
```

...everything installed except fd-find, which died here:

```
error: failed to run custom build command for `jemalloc-sys v0.3.2`
```

So I have just reported that to the jemalloc project at https://github.com/gnzlbg/jemallocator/issues/148

I don't think the issue is with fd specifically, and I don't mean to spam by posting this here too, but I just thought you should know about it in case you get other reports. (I have posted more in-depth details at that other issue since I think they can use them to fix it.)

**What version of `fd` are you using?**
Tried to install 8.0.0, failed.

**Which operating system / distribution are you on?**

```
uname -a
Linux u20do 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

rustc -V
rustc 1.41.0

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

**Comment by nachoguru** [comment]
Ah it turns out **make** was not on that VM by default. @sfackler suggested I run `apt install make` and retry, and that did the trick.

`cargo install fd-find` ran fine after that.

Hopefully someone else finds this useful down the line so I didn't just waste his time!

**Comment by sharkdp** [comment]
No worries. Thanks for clearing it up.
