### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by QiBaobin** [sharkdp/fd#588]
**Describe the bug you encountered:**
zsh: segmentation fault  fd 

**Describe what you expected to happen:**
execute successfully or give meaningful error output

**What version of `fd` are you using?**

v8.0.0 installed by cargo install fd-find
**Which operating system / distribution are you on?**

Darwin 19.3.0 x86_64

**Comment by tmccombs** [comment]
Do you have a core dump, or have steps to reproduce?

**Comment by QiBaobin** [comment]
Just run the fd after cargo install fd-find.

Using brew install works.

Can you tell me how to get the core dump?

**Comment by sharkdp** [comment]
> Just run the fd after cargo install fd-find.
> 
> Using brew install works.

This sounds like #498 which is patched when installing via `brew`.

**Comment by QiBaobin** [comment]
Thanks, close this now!
