### ISSUE TITLE
Why fd does not search files in git subdirectories? How to make it do?

### ISSUE THREAD

**Issue by kuvaldini** [sharkdp/fd#591]
**What version of `fd` are you using?**

    fd 8.0.0 

Having one git repo and another one inside. When searching in outer repo `fd` does not show files which are inside inner0-repo.

This is an official OpenWRT repo. Subfolder _feeds/packages_ appears after `./scripts/feeds update`, it clones git repo to _feeds/packages_
```
/V/l/openwrt ❯❯❯ fd blue
target/linux/brcm63xx/dts/livebox-blue-5g.dts
/V/l/openwrt ❯❯❯ cd feeds/packages
/V/l/o/f/packages ❯❯❯ fd blue
lang/python/python/patches/005-fix-bluetooth-support.patch
utils/bluelog
utils/bluelog/files/bluelog.init
utils/bluez
utils/bluez/files/bluetoothd.init
```

Why `fd` does so and how to change this behaviour?

**Comment by sharkdp** [comment]
I would guess that the `feeds/packages` folder is `.gitignore`d in the outer repo?

See https://github.com/sharkdp/fd#fd-does-not-find-my-file

**Comment by kuvaldini** [comment]
Thank you. Works fine.
