### ISSUE TITLE
-E does not seem to work correctly

### ISSUE THREAD

**Issue by GuoXu-GX** [sharkdp/fd#598]
I'm using 'fd -E pattern' to ignore some file with specified pattern.

The version of fd is fd-find 8.1.0 installed with 'cargo install fd-find' on ubuntu 18.04. 

I have a directory which contains a lot of pdf and epub files, so I try to use " fd -E 'pdf$|epub$' " to filter out pdf and epub files and have a look at other file types, but it does not work as expected.
It looks like fd completely ignores the pattern specified by -E and returns all the files contained in the directory.

The previous version I'm using is 7.3.0, it does not work either.

**Comment by sharkdp** [comment]
Please note that `-E` takes a *glob* pattern, not a regex. You can use it multiple times to achieve what you want:
``` bash
fd -E '*.pdf' -E '*.epub'
```

If you think that the documentation could be improved, please let us know.

**Comment by GuoXu-GX** [comment]
Thanks, it seems I did not understand the doc correctly.
