### ISSUE TITLE
How to hide files name in the output

### ISSUE THREAD

**Issue by aborruso** [sharkdp/fd#603]
**What version of `fd` are you using?**

I'm using fd 7.3.0.

If I run `fd -e csv -x bash -c 'wc -l "{}"'` I have both wc output command and the CSV files name.

How to have only the wc output?

Thank you

**Comment by sharkdp** [comment]
> If I run `fd -e csv -x bash -c 'wc -l "{}"'` I have both wc output command and the CSV files name.

That file name is printed by `wc`, not by `fd` :smile: 

You don't have to wrap everything in a `bash` call. You can also leave out the final `{}`. I suggest you use this instead:
``` bash
fd -e csv -x wc -l
```

If you want to get rid of the file names, you could use something like `cut`:
``` bash
fd -e csv -x wc -l | cut -d' ' -f1
```

**Comment by aborruso** [comment]
@sharkdp thank you very much.

I have pasted a simple example. I use bash call, because I concatenate more than one command, and I'm not able to run it simply using a fd `-x`.

Now I run `fd -e csv -x bash -c 'echo -n "{/}|" && wc -l "{}"` to obtain something like `filename|number of lines`

Best regards
