### ISSUE TITLE
--full-relative-path

### ISSUE THREAD

**Issue by rafcamlet** [sharkdp/fd#609]
Can you add additional option to search in full **relative** path? Something what will work like `find -regex`?  

Currently, I am including PWD in my full path search, but additional flag (maybe capital `-P`?)  will be great.

```
fd -p "$PWD.*what_i_am_looking_for"
```

**Comment by sharkdp** [comment]
Thank you for your request.

Why do you include the `$PWD.*` part? It should also work with `fd -p "what_i_am_looking_for"`. `fd` adds implicit `.*` parts on both sides of the regex pattern.

**Comment by rafcamlet** [comment]
Because i do not want to match my search against upper directories.
For example: I have a project related to the real estate market, and I am looking for all files which have "home" in path. I am in `~/my_projects/real_estate` directory.

So calling `fd -p "home.*emily"` wild find also files like `/home/my_user_name/pictures/my_photo_with_emily`
but `fd -p" $ pwd.*home.*emily` which is `fd -p "/home/my_user_name/my_projects/real_estate.*home.*emily "will find only files like `/home/my_user_name/my_projects/real_estate/home_for_emily/offer.doc` which i am looking for.

**Comment by sharkdp** [comment]
Thank you for the explanation. That's a valid use case of course.

However, given that there is an easy workaround with `-p "$PWD/…"` or `-p "$HOME/…"`, I'm not sure if we should really add a new command line option for this. The proposed option would be rather complicated to explain to users when combined with explicit search path arguments and/or `--base-directory=<dir>`.

**Comment by sharkdp** [comment]
Closing for now.
