### ISSUE TITLE
fd mkimage failed?

### ISSUE THREAD

**Issue by iysheng** [sharkdp/fd#610]
**What version of `fd` are you using?**
[paste the output of `fd --version` here]

fd 8.1.0

when i want to local the execute file named mkimage in tools dir,i do the command
```
fd mkimage tools/
```
what i can see is just the source file *mkimage.c* and *mkimage.h*,but the mkimage file and mkimage.o file is really exist. when i do **ll tools/mkimage***
```
.rwxrwxr-x yangyongsheng yangyongsheng 60.3 KB Tue Jun  2 13:23:58 2020 mkimage
.rw-r--r-- yangyongsheng yangyongsheng 14.5 KB Sun Jun  1 10:34:58 2014 mkimage.c
.rw-r--r-- yangyongsheng yangyongsheng  1.4 KB Sun Jun  1 10:34:58 2014 mkimage.h
.rw-rw-r-- yangyongsheng yangyongsheng 57.8 KB Tue Jun  2 13:23:57 2020 mkimage.o
```
i get confused why this happen?

**Comment by sharkdp** [comment]
Did you read https://github.com/sharkdp/fd#fd-does-not-find-my-file ?

**Comment by iysheng** [comment]
@sharkdp thanks, i get it.
