### ISSUE TITLE
running fd on a symlink fails

### ISSUE THREAD

**Issue by EvanTheB** [sharkdp/fd#611]
**Describe the bug you encountered:**

**Describe what you expected to happen:**
i expect fd to follow the symlink and search there

**What version of `fd` are you using?**
fd 8.1.1

**Which operating system / distribution are you on?**
Linux 5.2.17 x86_64

```
> mkdir /tmp/fdtest
> ln -s /tmp/fdtest/ /tmp/fdtest_link
> fd . /tmp/fdtest/
> fd . /tmp/fdtest_link/
[fd error]: Search path '/tmp/fdtest_link/' is not a directory.
[fd error]: No valid search paths given.
```

**Comment by sharkdp** [comment]
Thank you for reporting this. 

That should definitely be fixed.

**Comment by maxtriano** [comment]
If anyone's not already working on a fix for this, I'd like to pick it up

**Comment by maxtriano** [comment]
I can't get the given example to reproduce the bug on my machine, but I am on kernel 5.6.15. Any reason why kernel updates between 5.2 and 5.6 would have changed handling of symlinks to cause this break?

**Comment by sharkdp** [comment]
I actually cannot reproduce this either. I would be *very* surprised if this would depend on the kernel version.

@EvanTheB Is there anything else about your setup that might be worth mentioning? Is `/tmp` on a special file system? Is `fd` an alias for `fd --some-option`?

**Comment by joshuarli** [comment]
Can't reproduce on `4.19.0-8-cloud-amd64` (google cloud vanilla Debian 10) with `fd 8.1.1`.

**Comment by sharkdp** [comment]
@EvanTheB Any update on this?

**Comment by EvanTheB** [comment]
Apologies I am slow, I see this on my work setup which is a debian derivative. I will compile HEAD again today and have a look.

**Comment by EvanTheB** [comment]
Aha, yes sharkdp, I have realised why my alias is stuffing this up.
I only get the issue when I run fd via `sudo`, AND on the `/tmp` dir. `sudo ls` also fails on the same link (but not on the target). So this is not a fd issue, but something else to do with this setup. 
Thanks

**Comment by sharkdp** [comment]
Thank you for the update
