### ISSUE TITLE
Discussion: Stabilization phase?

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#613]
I personally feel like we reached a point in the development of `fd` where we could take a longer break from introducing new features (especially breaking changes) and focus on stabilization instead. I would like to know what others think about this idea.

There are a few things which I would like to get finished before we start this phase (in particular: #612).

Once we enter the stabilization phase, I would like to focus on three major things:
- Bug fixing
- Documentation improvements
- Performance improvements

I would not put a super-strict ban on new features, but I would probably reject larger-scale changes for a while. Especially those that are likely to introduce new bugs.

What do you think? If you think this is a good idea, what kind of feature requests / breaking changes would you like to see implemented before we would start such a phase? If not, what do you propose instead?

**Comment by joshuarli** [comment]
+1 for stabilization phase. Long-time fd user here, zero complaints and I think the UX is absolutely first class (takes a tiny bit getting used to if you come from GNU find). Regarding https://github.com/sharkdp/fd/issues/612 I've had `fdh: aliased to fd --no-ignore-vcs -H -E '.git/'` for a long time, and think it's a good resource-saving default, but also wouldn't mind if I had to do the inverse.

**Comment by saifali-ch** [comment]
fd is an awesome tool without any doubt. I would like to see one more feature (search stat). Like ripgrep does.

**Comment by saifali-ch** [comment]
**Salam!** @sharkdp

I wish, if you could please add **stats** feature in **fd** like **ripgrep** does. 
I can contribute, but the problem is I never coded in Rust.

**Following three features as --stats**
Total matched searches. (although it is possible via piping fd's output to wc but....)
Total time taken. (also possible via time(2) but...)
Total searches (including unmatched ones)

Regardless, **fd is** && **will** always be a **great** tool.

**Comment by sharkdp** [comment]
As everyone seems to agree, my plan is to start the stabilization phase with the release of [fd 9.x](https://github.com/sharkdp/fd/milestone/9). It might be a while before this gets released, though.
