### ISSUE TITLE
Does not find everything it should find. 

### ISSUE THREAD

**Issue by jonathan-s** [sharkdp/fd#614]
**Describe the bug you encountered:**

I'm running the following command `fd 'node_modules' . -t d`. 

I get a bunch of outputs, all good. But when I try to search for folders in that output I know should exist it doesn't exist in the output from fd. 

I cross-referenced this with 
```
# this should remove any folders that starts with a dot. 
find projects -name node_modules -type d -not -path '*/\.*' -prune
```
Let me know how I can help debug this.

The folders I'm missing are folders such as 
```
projects/growthgrid/node_modules
projects/hello-app/node_modules
projects/bookstat/node_modules
```

fd found some folders in projects, but not all.

**Describe what you expected to happen:**
I would have expected fd to find all folders. 

**What version of `fd` are you using?**
fd 8.1.1

**Which operating system / distribution are you on?**
Darwin 18.7.0 x86_64

**Comment by jonathan-s** [comment]
The flag -I solved the problem. To be honest, I'm not sure that should be a default. It makes somewhat sense to have hidden files as a default though.

**Comment by sharkdp** [comment]
see the Troubleshooting section in the README and #612
