### ISSUE TITLE
Ubuntu: apt-get not working

### ISSUE THREAD

**Issue by Beramos** [sharkdp/fd#618]
**Describe the bug you encountered:**
When installing df-find. the official package does not exist

**Describe what you expected to happen:**
`sudo apt-get install df-find`
> Unable to locate package fd-find

**Which operating system / distribution are you on?**

Unix:   Linux 4.13.0-32-generic x86_64

**Comment by sharkdp** [comment]
Which version of Ubuntu are you on? `fd` is only available since 19.04: https://github.com/sharkdp/fd#on-ubuntu

>  `sudo apt-get install df-find`

the package is called `fd-find`, but I guess you used the correct name, like indicated in the error message.

**Comment by Beramos** [comment]
My bad, I'm currently on 18.3. I've misread the requirements. Thanks

**Comment by sharkdp** [comment]
Note that you can still manually install appropriate `.deb` packages from the release page in this repo.

**Comment by Beramos** [comment]
Yes, thank you! I was a bit lazy :flushed:
