### ISSUE TITLE
Document regex syntax

### ISSUE THREAD

**Issue by nu8** [sharkdp/fd#622]
I was looking to do a word boundary search, so I started with something like
this:

~~~
\<Sunday\>
~~~

as that is how Vim does it. That did not work, so I was inclined to open an FD
issue about it. It turns out that FD uses the Regex crate:

https://docs.rs/regex

which does support word boundary via this syntax:

~~~
\bSunday\b
~~~

my issue is that I feel the FD regex could be better documented. I dont believe
this repo even has any links to the Regex crate, but I could be mistaken.

**Comment by sharkdp** [comment]
from the man page:
```
PATTERN SYNTAX
       The regular expression syntax used by fd is documented here:

       ⟨https://docs.rs/regex/1.0.0/regex/#syntax⟩

       The glob syntax is documented here:

       ⟨https://docs.rs/globset/#syntax⟩
```

But documentation can always be improved. I'm  happy for any suggestions!

**Comment by nu8** [comment]
I mean, just adding a link here would be helpful:

https://github.com/sharkdp/fd#fd-doesnt-seem-to-interpret-my-regex-pattern-correctly

**Comment by tmccombs** [comment]
> as that is how Vim does it.

vim's regex syntax is actually quite different from the more prevalent  "perl-compatible regular ecpressions" (PCRE), and I believe rust's regex syntax, which fd uses, is mostly a subset of PCRE.
