### ISSUE TITLE
WinGet-based installation

### ISSUE THREAD

**Issue by zkat** [sharkdp/fd#625]
It would be really great to be able to install `fd` on Windows through the [windows package manager, `winget`](https://docs.microsoft.com/en-us/windows/package-manager/winget/).

**Comment by sharkdp** [comment]
see my comment here: https://github.com/sharkdp/bat/issues/1102

**Comment by sharkdp** [comment]
I'm going to close this, as I don't really see any value in tracking this here. Let me know if someone thinks otherwise.

**Comment by sitiom** [comment]
PR: https://github.com/microsoft/winget-pkgs/pull/94714. Please see https://github.com/sharkdp/bat/issues/1102#issuecomment-1404962018
