### ISSUE TITLE
'--fixed-strings=$STRING' is a substring match. Therefore a '--exact' option is necessary to not always match everything containing the STRING

### ISSUE THREAD

**Issue by KuroKensei** [sharkdp/fd#627]
When using '--fixed-strings=$STRING" fd treats the literal string as a substring.
Please provide a '--exact' or '--line' or '--word' option to actually only match the provided STRING and not more.

Especially for short literal strings this currently heavily pollutes the output up to complete and utter uselessness.
Since the filename contains special characters, it'd be nice to be able to use the '--fixed-strings' option instead of manually having to escape the regex characters in the filename using 'sed'.

**Comment by sharkdp** [comment]
Have you seen `--glob`?

**Comment by ShadiZade** [comment]
> Have you seen `--glob`?

@sharkdp `--glob` is not a good substitute for a hypothetical `--fixed-strings --exact` option. For example, I have a script that deals with files that often have `[...]` in their names wherein `...` is a random string that can contain `-`. `--glob` interprets that as a range and throws an error.
