### ISSUE TITLE
Provide more detailed '--help' output

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#63]
clap has an option to show a more detailed help message if `fd --help` is called (as compared to `fd -h`):

* https://docs.rs/clap/2.26.2/clap/struct.Arg.html#method.long_help
* https://docs.rs/clap/2.26.2/clap/struct.App.html#method.long_about

We could use this to provide a more detailed help text for `fd`.

**Comment by abaez** [comment]
Hey, 

I would like to take a stab at this. Probably get this one done later tonight.

**Comment by sharkdp** [comment]
Closed via #71
