### ISSUE TITLE
Exclude second level below directory

### ISSUE THREAD

**Issue by weeman1337** [sharkdp/fd#633]
**What version of `fd` are you using?**  
8.1.1

I have the question if it is possible to ignore the second level below a directory. The specific use case is `node_modules` (npm packages). I want to find the directories and files directly placed one level below `node_modules` but not deeper ones.

Should be found (e.g.):
* `node_modules/eslint`

Should not be found (e.g.):
* `node_modules/eslint/lib/`
* `node_modules/eslint/lib/linter.js`

**Comment by sharkdp** [comment]
```
    -d, --max-depth <depth>
            Limit the directory traversal to a given depth. By default,
            there is no limit on the search depth.
```

**Comment by weeman1337** [comment]
Thanks for the response. I think that is not what I am actually looking for ;)

I want to find unlimit depth but I want to exclude the sub-sub directories inside `node_modules`.

I tried `--exclude node_modules/*/*` without success :/

**Comment by sharkdp** [comment]
> Thanks for the response. I think that is not what I am actually looking for ;)
> 
> I want to find unlimit depth but I want to exclude the sub-sub directories inside `node_modules`.

Oh, I see.



> I tried `--exclude node_modules/*/*` without success :/

I think this should do the trick:
```bash
--exclude '**/node_modules/*/*'
```

**Comment by weeman1337** [comment]
This works, thank you ✓

How can I add multiple excludes? Adding multiple `--exclude` params?

**Comment by sharkdp** [comment]
Yes. Or you could write a custom `.fdignore` file
