### ISSUE TITLE
How to exclude .gitignore in home directory?

### ISSUE THREAD

**Issue by asolopovas** [sharkdp/fd#635]
**What version of `fd` are you using?**
 `fd --version:`   8.1.1

Hi,
I am syncing my dotfile in GitHub and in order not to get all the files uploaded to git, I have created the following .gitignore file it has more entries but for sake of example, this is how I use it.
```
/**
!Readme.md
!.bashrc
```
The problem is that `fd` takes into account .gitignore and only searches my dotfiles, is there a way to exclude single .gitignore file for `fd` to search the rest of the folders?

**Comment by mpollow** [comment]
Got the same issue. It took me a while to realize that the .gitignore in my home folder is causing no output at all from fd.

**Comment by asolopovas** [comment]
There should be some sort of flag to turn off certain .gitignores as otherwise, you may want to find certain files in `node_modules` for testing or debugging purposes but you won't be able to do that if `fd`  ignores this directory by default and you can't switch it off even temporary.

**Comment by tmccombs** [comment]
So you want some .gitignores to be respected but not others? How would you indicate which ones shouldn't be included? And I'm not sure I understand the usecase.

**Comment by tmccombs** [comment]
You may already be aware of this, but you can disable all .gitignore files with the `--no-ignore-vcs` option, and then add .gitignore files you want with the `--ignore-file` option.

**Comment by asolopovas** [comment]
Disabling all .gitignore does not make sense if you only want to ignore the file that is in your home directory. It would be great if I could specify `--ignore-file ~/.gitignore` and only that .gitignore file would be ignored by fd while the rest respected.

**Comment by asolopovas** [comment]
> You may already be aware of this, but you can disable all .gitignore files with the `--no-ignore-vcs` option, and then add .gitignore files you want with the `--ignore-file` option.

If I understand correctly that's the opposite of what I am trying to do. Is to ignore all .gitignore file and exclude only one of them.

**Comment by sharkdp** [comment]
>  The problem is that my [dotfiles](https://raw.githubusercontent.com/asolopovas/dotfiles/master/.gitignore) are stored on github, and the fd doesn't work with my setup because it ignores most of the folder apart from my dotfiles.

May I suggest that this setup is not ideal? I'm sure it would cause problems in other programs as well.

An alternative way to do this (which is much cleaner, IMO), is to have a dedicated `dotfiles` folder somewhere which includes everything that should be tracked via Git. And your actual dotfiles are simple symlinks into the `dotfiles` repository.

**Comment by asolopovas** [comment]
@sharkdp I could do it this way but then I would have write a separate script that would automatically to create symbolic links automatically and edit that script each time when I have to update or use new configuration, I guess there is no win win in here and I do get that you can't please all the use-cases. Thanks anyway for responding, you can close the issue if there is nothing to be done.

**Comment by tmccombs** [comment]
> but then I would have write a separate script that would automatically to create symbolic links 

that is what I do. It's not that bad.

> and edit that script each time when I have to update or use new configuration

not necessarily. the way I have it set up, is I have a folder that contains the source files, and my script just creates a symlink for everything in that directory, so I just have to create the file inside that directory then run the symlink script.

**Comment by sharkdp** [comment]
Closing this for now. I don't really want to add a new option to exclude certain ignore files.
