### ISSUE TITLE
can not use fd with wsl1 ubuntu20.04

### ISSUE THREAD

**Issue by umaYnit** [sharkdp/fd#637]
**Describe the bug you encountered:**
it is not work on wsl1 ubuntu20.04

**Describe what you expected to happen:**

**What version of `fd` are you using?**
8.1.1

**Which operating system / distribution are you on?**
Linux 4.4.0-18362-Microsoft x86_64

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

there is the error log:

```
thread 'thread '<unnamed>thread 'thread '<unnamed>' panicked at 'thread '<unnamed><unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`<unnamed>' panicked at 'thread '' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`thread '', thread 'thread 'thread '' panicked at 'thread 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`<unnamed>assertion failed: `(left == right)`
  left: `22`,
 right: `4`', <unnamed>src/libstd/sys/unix/thread.rs<unnamed><unnamed><unnamed>assertion failed: `(left == right)`
  left: `22`,
 right: `4`<unnamed>', ' panicked at '', src/libstd/sys/unix/thread.rs' panicked at ':' panicked at '' panicked at '' panicked at '', ' panicked at 'src/libstd/sys/unix/thread.rsassertion failed: `(left == right)`
  left: `22`,
 right: `4`src/libstd/sys/unix/thread.rs:assertion failed: `(left == right)`
  left: `22`,
 right: `4`179assertion failed: `(left == right)`
  left: `22`,
 right: `4`assertion failed: `(left == right)`
  left: `22`,
 right: `4`assertion failed: `(left == right)`
  left: `22`,
 right: `4`src/libstd/sys/unix/thread.rsassertion failed: `(left == right)`
  left: `22`,
 right: `4`:', :179', :', ', ', :', 179src/libstd/sys/unix/thread.rs179:src/libstd/sys/unix/thread.rs21src/libstd/sys/unix/thread.rssrc/libstd/sys/unix/thread.rssrc/libstd/sys/unix/thread.rs179src/libstd/sys/unix/thread.rs:::21:
:::::2117921
179note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
17917917921179
:
::thread '::
:212121main212121


' panicked at '


called `Result::unwrap()` on an `Err` value: Any', /root/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ignore-0.4.15/src/walk.rs:1294:17
```

full log file
[full_error.log](https://github.com/sharkdp/fd/files/5015615/full_error.log)

**Comment by sharkdp** [comment]
Thank you for reporting this. How did you run `fd`?

**Comment by umaYnit** [comment]
direct input `fd` . i try other input like `fd Cargo.toml` is the same error.
and `fd --version` is ok.

**Comment by sharkdp** [comment]
> thd fd is building in local wsl with stable rust 1.45.1

is this a debug build? if not, could you try to do that? `cargo build`, and then use the binary from the `target/debug` folder.



> direct input `fd` . i try other input like `fd Cargo.toml` is the same error.

Could you also try to run `fd --threads=1`?

**Comment by umaYnit** [comment]
> is this a debug build? if not, could you try to do that? cargo build, and then use the binary from the target/debug folder.

the same error message like arelease mode.

> Could you also try to run `fd --threads=1`?

it can work by ` --threads=1`.

**Comment by sharkdp** [comment]
Looks similar to this  https://github.com/rust-lang/rustup/issues/2245

If it is the same, I don't think there is anything we can do here.

**Comment by sharkdp** [comment]
@umaYnit Do you have access to WSL2? Could you check if it works?

**Comment by umaYnit** [comment]
in WSL2, it's ok.

**Comment by sharkdp** [comment]
Ok, I think I'd like to close this then. I'm really not sure what could be done here. Let me know if you think otherwise.
