### ISSUE TITLE
getting last modified file

### ISSUE THREAD

**Issue by idkjs** [sharkdp/fd#640]
**What version of `fd` are you using?**
[fd 8.1.1]

How would I get the last modified file in a directory and it sub-directories with fd?

This is the script I have now: `ls -t **/*.re | head -n1`. It search for files by an extension recursively and returns the last modified file. 

I can't get this to run in `fd`. This is as close as I am: 

```sh
> fd -e re --exec stat | sort -nr | cut -d: -f2- | head -1
06:29 2020" "Aug 10 10:06:29 2020" "Aug 10 10:06:29 2020" "Aug  9 18:12:28 2020" 4096 8 0 src/Router.re
```

Great Project.

Thank you.

**Comment by tmccombs** [comment]
How about:
```
fd -e go --exec stat --printf='%Y\t%n\n' | sort -nr | head -1 | cut -f2 
```

**Comment by idkjs** [comment]
I think that I forgot to mention that I am trying this on fishshell. Just started using it. Syntax might be a bit different.

Getting:

```sh
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- -
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
stat: illegal option -- -
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
```

**Comment by tmccombs** [comment]
What OS are you on? Your stat options look very different than mine (on linux). I'd read the manpage for your stat, and see how you can use a format that has the timestamp as a single number (unix epoch) and filename.

**Comment by idkjs** [comment]
mac

**Comment by idkjs** [comment]
You read the man page for mac? That is a nice reflex. Thank you for sharing that with me. This man page has some good info it. I will come back and post once i have figured it out. Peace/Love @tmccombs

**Comment by tmccombs** [comment]
I think it would be `stat -f "%m%t%N"` or possibly `stat -f "%Sm%t%N" -t %s`

**Comment by idkjs** [comment]
`fd -e re --exec stat -f "%m%t%N" | sort -nr | head -1 | cut -f2` is correct. You are the lucky winner of my gratitude. Seriously, you are very generous.

I am still going to take time to study that man page.

Peace/Love

**Comment by abitrolly** [comment]
Somewhat related. If somebody needs all files modified within two days, it can be done with this.
```bash
fd . --changed-within=2d ~
```

**Comment by idkjs** [comment]
@abitrolly looks like that search the entire drive instead of the pwd.

**Comment by abitrolly** [comment]
There is an invisible `~` at the end, so it looks in home dir.

**Comment by carpetscheme** [comment]
Another approach in case it's useful to anyone:
```
fd --type f . --exec-batch ls -lt
```
where 'ls -t' orders by last modification time.
