### ISSUE TITLE
PowerShell 7.0.3 vs CMD and `fd`

### ISSUE THREAD

**Issue by g0blin-NN** [sharkdp/fd#646]
**What version of `fd` are you using?**
[fd 8.1.1](https://github.com/sharkdp/fd/releases/download/v8.1.1/fd-v8.1.1-x86_64-pc-windows-msvc.zip)
[cwebp 1.1.0](https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html)
I do not know much English. it's easier for me to explain in Russian. excuse me.
what am I doing wrong? we have. [PowerShell 7](https://github.com/PowerShell/PowerShell/releases/tag/v7.0.3) and CMD from Windows 10.  Do they process the same command differently? how to teach PowerShell to correctly process the command?

`fd -e jpg -x cwebp -q 80 {} -o {.}.webp`

![PowerShell vs cmd](https://user-images.githubusercontent.com/66860852/92360749-008bbb80-f0f6-11ea-917b-662254136b53.png)

**Comment by tmccombs** [comment]
I'm not an expert in either powershell or cmd.exe, but I think you might need to quote or escape the "{.}" And possibly other special characters in powershell

**Comment by g0blin-NN** [comment]
> I'm not an expert in either powershell or cmd.exe, but I think you might need to quote or escape the "{.}" And possibly other special characters in powershell

yes. `fd -e jpg -x cwebp q 80 "{}" -o "{.}.webp"` - so there are no errors. thank. such a trifle, and so spoils everything.
