### ISSUE TITLE
./fd: fork: Resource temporarily unavailable

### ISSUE THREAD

**Issue by tigger04** [sharkdp/fd#649]
**Describe the bug you encountered:**

fd returns an error about 80% of the time, randomly and inconsistently
I have not yet encountered this error with any other command

```
~/bin$ fd dark-plus -uu
./fd: fork: Resource temporarily unavailable
🔴~/bin$ fd -v dark-plus -uu
./fd: fork: Resource temporarily unavailable
🔴~/bin$ fd --version
./fd: fork: Resource temporarily unavailable
```

**Describe what you expected to happen:**

To see results, or the version number

**What version of `fd` are you using?**

Difficult to say given fd --version doesn't work
but according to Homebrew:

```
~/bin$ brew list --versions | grep fd
fd 8.1.1

```

**Which operating system / distribution are you on?**
 

```
~/bin$ uname -srm
Darwin 19.6.0 x86_64
~/bin$ lsb_release -aF
-bash: lsb_release: command not found
🔴~/bin$

```

Not sure if this is a problem with my system or fd - couldn't find anything similar in the issues

**Comment by sharkdp** [comment]
I would suspect that this is due to a system resource limit, see e.g. https://unix.stackexchange.com/a/205063/229308

**Comment by tigger04** [comment]
So, this is what I get for ulimit -a:

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2784
virtual memory          (kbytes, -v) unlimited
```

These would appear to be typical for a 2020 MacBook Pro running Catalina.
Then I went down a rabbit-hole of how to change resource limits on the Mac  There is conflicting information out there, but it seems that changing the number for max processes is either hard-coded in the kernel and therefore impossible, or maybe possible via a non-trivial process that would put it in to server mode and kill any hope of this laptop having use of its battery by the sounds of it.

Interestingly though I only seem to experience the issue in one particular directory ~/code/bin, where I have discovered a workaround: search from its parent directory (~/code) and the results are almost instant. Something is not right as this would have a far greater scan area than within ~/code/bin itself.
```

~/code$ SECONDS=0; fd autogit; echo $SECONDS
bin/autogit
bin/autogit.launchd.plist
1
~/code$ cd bin
/Users/tadhg.obrien/code/bin
~/code/bin$ SECONDS=0; fd autogit; echo $SECONDS
./fd: fork: Resource temporarily unavailable
36
~/code/bin$
```

**Comment by sharkdp** [comment]
> Interestingly though I only seem to experience the issue in one particular directory `~/code/bin`, where I have discovered a workaround: search from its parent directory `~/code` and the results are almost instant.

Maybe the `bin` folder is in `.gitignore` and won't get searched?


But something definitely doesn't seem right. Is there anything peculiar about the directory/file structure in `bin`? Does it work if you use `--threads=1`/`-j1`?

**Comment by tigger04** [comment]
> Maybe the `bin` folder is in `.gitignore` and won't get searched?

if that was so, then this from my earlier snippet would return nothing:

```
~/code$ SECONDS=0; fd autogit; echo $SECONDS
bin/autogit
bin/autogit.launchd.plist
1
```

`~/code` is not and is not part of a git repo. `~/code/bin` is the root of own git repo.

 > But something definitely doesn't seem right. Is there anything peculiar about the directory/file structure in `bin`? Does it work if you use `--threads=1`/`-j1`?

I don't think there's anything unusual, few symlinks but mostly bash scripts and a few binaries. I can send a full tree structure if that helps? here's `du -hd1`

```
4.0K	./caffeinating
1.0G	./temp
664K	./archive
4.2M	./countdown
 20K	./bitbar-plugins
 24K	./tugnotes
412K	./useful_stuff
448K	./.history
216K	./todo
 48M	./sounds
 88M	./scratch
124K	./keypress
1.8M	./btt
 12K	./examples
4.1M	./inventory
624K	./carpark
 88K	./gen_kk
752K	./pomodoro
117M	./.git
8.0K	./.vscode
 56K	./testsh
8.0K	./shots
2.1M	./purgatory
1.3G	.

```
and
```
~/code/bin$ dir-summary
 511 dirs
5653 files
  65 hardlinks
 160 symlinks
```

as for setting threads=1

```
~/code/bin$ fd --threads=1 autogit
./fd: fork: Resource temporarily unavailable

```

Before running I thought I'd check what `-j `does, is it just an alias for threads or something else, but it doesn't like `--help` either in this directory!

<img width="529" alt="image" src="https://user-images.githubusercontent.com/43514058/93749470-deb02f80-fbf1-11ea-9fb1-c21664841f8a.png">


<img width="631" alt="image" src="https://user-images.githubusercontent.com/43514058/93749424-d0faaa00-fbf1-11ea-80a6-e1c54b85a762.png">

**Comment by sharkdp** [comment]
Thank you for the update. Could you please run `fd` with strace to see what's going on right before the error? Maybe just with `fd --help`:
```bash
strace -f fd --help
```

**Comment by tmccombs** [comment]
I suspect this might have to do with the low open files limit (256). Whenever you start a new process it has to make three open files for stdin, stdout, and stderr. So you might be hitting that limit. But I don't know why it would only happen for fd, or only in the bin directory. Is your fd an alias to something?

**Comment by sharkdp** [comment]
@tigger04 Any update on this?

**Comment by tigger04** [comment]
Indeed,  I have some more information that may help explain this one.

In ~/code/bin I have a script called fd. These scripts get replicated across all of the devies I use, some MacOS, some Linux. For some reason the command for fd is `fdfind` in Linux, but '`fd`' on the Mac.

A further little bit of context - my ~/code/bin directory gets cloned from github to exacly there ~/code/bin. This diectory ia also symlinked to ~/bin for convenience / convention. Bothe ~/code/bin and ~/bin are in my path, this ensures these scripts are always available to use wherever you are (otherwise you need to get in to clunky ./progream.sh invocations depending on context).

In the past I was finding ap roblem with using fd in my scripts - the command naming difference seemed to introduce some inexplicable compleixyt, so I created a script in ~/bin:

```
#!/bin/bash
if command -v fdfind >/dev/null 2>&1; then
  fdfind "$@"
elif command -v fd >/dev/null 2>&1; then
  fd "$@"
else
 return 1
fi
```

This has served me well for some time. or so I thought.
Renaming my fd script to fd.sh gives me a temporary workaround, for now.

What still remains a mystery to me is, why does fd behave so differently / fail when invoked from a script?

cheers and thanks for your help!

**Comment by tmccombs** [comment]
So your script is named `fd`? I think you have run into infinite recursion. When you run `fd` it runs the `fd` script, which then checks if the `fd` command exists, which does, so it calls `fd` which starts the same script over again, and continues doing so until you run out of processes. 

You could solve this by changing the `fd "$@"` to use an absolute path to the original fd executable. Something like `/usr/bin/fd "$@"`.

Since this isn't an issue with fd itself, I'm going to close this issue.

**Comment by tigger04** [comment]
Its a good point, and would explain it quite neatly in fact.
I had been using this blissfully unaware, as it has been working flawlessly in my scripts  and interactive shell sessions (on the Linux boxes anyway). The reason bieng the order it finds them in the $PATH variable - a vaguery I wouldn't want to rely on,

Referencing the absolute path isn't really an option , since  the respective package managers on each machine wiil place the binaries in different locations. Instead, renaming the script to fd.sh (and all scripts which reference it) seems to be the answer, for the time being.

I agree it is not an fd bug, but my own, and  I do apologies for tanking up your time on this. Thanks so much for your help.

**Comment by tigger04** [comment]
PS bonus question if you don't mind, why does fd get a different command on linux (fdfind) versus Mac/BSD? (fd)? I am  a big fan of this little utility, and tell anyone who will listen to switch to it!

**Comment by sharkdp** [comment]
> PS bonus question if you don't mind, why does fd get a different command on linux (fdfind) versus Mac/BSD? (fd)?

This is not specific to Linux, but rather specific to Debian/Ubuntu where another package was already shipping a binary called `fd`. This is why they had to rename it, unfortunately. The official name of the project is `fd`.

This is also explained in the README: https://github.com/sharkdp/fd#on-ubuntu

**Comment by tigger04** [comment]
Thanks for sending the literature. It's worth pointing out - and may I suggest as a correction to the doc, that setting an alias as suggested here:

> Note that the binary is called fdfind as the binary name fd is already used by another package. It is recommended that you add an alias fd=fdfind to your shells initialization file, in order to use fd in the same way as in this documentation.

This approach works for interactive sessions only, use of an alias will fail in any script. There are ways to make it work in a script (e.g. with shopt expand_aliases defined within the script) - but I would caution against such an approach it can cause all sorts of unintended consequences that are difficult to debug.
According to the Bash manual, functions are preferred over aliases in any case.

https://www.gnu.org/software/bash/manual/html_node/Aliases.html

There's no perfect solution if you've got conflicting names, but I'd suggest either 
-warn people of the problem and let them figure it out
-advise them to write a function to handle it (not alias)
-better yet, write a function that can be downloaded from a gist or whatever

This may not be the top of your priorities as I"m sure you have enough to do with maintaining such a pivotal tool, but if you want any help putting it together (submit a PR?) I'm happy to put something together (with my above error corrected / tested of course).

**Comment by sharkdp** [comment]
The Ubuntu (and Debian?) package actually provides a symlink in
```
/usr/lib/cargo/bin/fd
```
that points to `/usr/bin/fdfind` (see https://packages.ubuntu.com/de/focal/amd64/fd-find/filelist).

So we could actually advise users to add `/usr/lib/cargo/bin/` to their path if they want to use `fd` instead of `fdfind`.
