### ISSUE TITLE
Re-write integration tests in Rust

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#65]
If there is a nice way to write the current integration tests (`tests/test.sh`) in Rust, this would be really beneficial:

* the tests would be platform-independent. Currently, the integration tests (naturally) do not run on Windows.
* `cargo test` would run both unit tests and integration tests

**Comment by reima** [comment]
Had the same thought yesterday and just wanted to open an issue for it 😃 

I'll take a stab at this and will report back with a prototype later today.

**Comment by sharkdp** [comment]
Closed via #67
