### ISSUE TITLE
Add `--and` to add patterns that should also be present

### ISSUE THREAD

**Issue by NightMachinary** [sharkdp/fd#650]
Since `fd` doesn't support lookahead, the only way to AND patterns is to pipe the output to an external program.

Related: https://github.com/sharkdp/fd/issues/414

**Comment by sharkdp** [comment]
Thank you for your feedback. Could you please go into a bit more detail what your exact use case is?

Often when searching for two patterns at once (`A` and `B`), you know that `A` comes before `B` (or vice versa). In this case, you can use
```
fd 'A.*B'
```
If you do not know the order, you could still run
```
fd 'A.*B|B.*A'
```
which is not really ideal, I agree.

In a lot of these cases for me, one of the patterns is actually a file extension (e.g.: look for all `.csv` files that match pattern `A`). In this case, you can use the `-e`/`--extension` option of `fd`:
```
fd A -e csv
```

**Comment by NightMachinary** [comment]
[**@sharkdp**](https://github.com/sharkdp) commented on [Oct 5, 2020, 11:47 PM GMT+3:30](https://github.com/sharkdp/fd/issues/650#issuecomment-703865224 "2020-10-05T20:17:33Z - Replied by Github Reply Comments"):

> Often when searching for two patterns at once (`A` and `B`), you know that `A` comes before `B` (or vice versa). 

1. I embed tags into filenames, e.g.:
![image](https://user-images.githubusercontent.com/36224762/95133276-ecc38b80-076d-11eb-8ba3-251653e3122c.png)

When I want to search for a file that has multiple tags, I can't know the order the tags were inserted into the filename.

2. I organize my notes via hierarchical directories, and it's not always easy to remember which category comes first. E.g., was it `/anime/recommendations` or `recommendations/anime`.

**Comment by jack99999** [comment]
i have the same problem of sometimes wanting to look for multiple strings. 

my normal solution is to use` locate -all`

usually, i could use the slightly clunky `fd 'A.*B|B.*A'` but it doesn't really flow from the fingers. on the rare occasions i want three strings i'd have to resort to grep.

**Comment by sharkdp** [comment]
Let's close this and continue the discussion in #315. Hope that's okay with everyone.
