### ISSUE TITLE
Excludes file defined in includeIf block is not honored 

### ISSUE THREAD

**Issue by denizevrenci-paypay** [sharkdp/fd#651]
**Describe the bug you encountered:**
I have a git configuration where certain settings including the `excludesfile` is set per some directory structure using the `includeIf` directive of git configuration.

```
`~/.config/git/config`:

[includeIf "gitdir:<somedir>"]
	path = <somedir>/.gitconfig

`<somedir>/.gitconfig`:

[core]
	excludesFile = ./.gitignore
```

fd does not honor this configuration and lists the files that are ignored by `<somedir>/.gitignore`.

**Describe what you expected to happen:**
The ignore pattern described through the `includeIf` mechanism to work.

**What version of `fd` are you using?**
fd 8.1.1

**Which operating system / distribution are you on?**
Darwin 19.6.0 x86_64

**Comment by tmccombs** [comment]
Afaik, the ignore crate only looks at gitignore files, not git configuration. This should probably be a feature request to the ignore crate (part of the ripgrep project)

**Comment by denizevrenci-paypay** [comment]
It checks git configuration. The following successfully ignores the patterns in `~/foo`.

```
`~/.config/git/config`:

[core]
	excludesFile = ~/foo
```

That being said, it might still be a missing feature of the ignore crate.

**Comment by sharkdp** [comment]
Thank you for your feedback and request. As we are most likely not going to solve this here, I'm going to close this for now.
