### ISSUE TITLE
How to do a "reverse match" with regex?

### ISSUE THREAD

**Issue by mathomp4** [sharkdp/fd#652]
**What version of `fd` are you using?**
fd 8.1.1

All, a simple question. Is there a way to do a "reverse match"? That is I can do this:
```
fd geos_moist | rg -v '\d{8}_\d{4}z.nc4'
```
which finds all files with `geos_moist` that *don't* match the regex. But part of me keeps thinking there might be a way to do this within `fd` without a pipe. I know of `--exclude` but of course that takes a glob.

**Comment by sharkdp** [comment]
Thank you for your question.

There is no way to do this in `fd` currently. I also use `… | rg -v` for this, to be honest - if `--exclude` doesn't work. I think it's a rather niche use case, so I'd rather lean towards not implementing this as a new feature.

**Comment by mathomp4** [comment]
@sharkdp I figured as much, but I wanted to be sure I wasn't missing some unknown feature/option. I know `find` has a `not` uh...operator(?), but didn't know if `fd` did.
