### ISSUE TITLE
Howto "find . -type f -name "*.c" -exec fgrep PatternInFile {} \; -print " ?

### ISSUE THREAD

**Issue by nicolasboulay** [sharkdp/fd#653]
I use often the following command, that could be very slow :
$ find . -type f -name "*.c" -exec fgrep PatternInFile {} \; -print 

I try :
fd .c -t f -x fgrep PatternInFile {}

Which is faster, but it's not usable without the name of the file.

**Comment by tmccombs** [comment]
would the `-l` (or `--files-with-matches`) option of grep/fgrep work?

**Comment by nicolasboulay** [comment]
-l return only the filename. It's not exactly the same use case.

**Comment by sharkdp** [comment]
This will hopefully be supported soon, see #406 

In the meantime, a few comments:
* `fd .c` is *not the same* as `find -name "*.c"`. `.c` is a regex that matches filenames with any character (`.`) followed by a `c`. If you want to search for C source files, try `fd -e c` or `fd -g "*.c"`.
* The `{}` is not necessary, if it's the last argument. So you can do: `fd -e c -t f -x fgrep PatternInFile`

In general, for this kind of thing, I recommend using [ripgrep](https://github.com/BurntSushi/ripgrep), which can filter by file type:
```
rg -t c PatternInFile
```

**Comment by nicolasboulay** [comment]
Thanks for ripgrep. It's the tools i need.
