### ISSUE TITLE
Sort order without external command

### ISSUE THREAD

**Issue by nu8** [sharkdp/fd#656]
With RipGrep, you can do something like this:

~~~
rg --sort=path May
~~~

https://github.com/BurntSushi/ripgrep/blob/master/FAQ.md#how-can-i-get-results-in-a-consistent-order

This doesnt call any external tools, it just simply disables parallelism and
allows the search to continue in a linear fashion. I was surprised to see that
Fd does not offer a similar option. I see this:

~~~
-l, --list-details
~~~

but as I am on Windows, it does not work:

~~~
'fd --list-details' is not supported on Windows unless GNU 'ls' is installed.
~~~

It is possible to have result in sort order, without calling an
external tool. I know this because many tools of the past already do this. See
`find`, `ls`, even Command Prompt `dir` or PowerShell `Get-ChildItem`. Is it
not possible for Fd to output ordered results, because of some Rust limitation?
Or is it a design decision?

**Comment by sharkdp** [comment]
Please see #196, #324 and #159.

> It is possible to have result in deterministic order, without calling an
> external tool.

Yes, you can use `-j 1` (or `--threads=1`). It's deterministic, but not sorted.

>  Or is it a design decision?

We *do*, in fact, sort search results - if the search has finished in a very short time. And if it's only a small number of search results. Otherwise, we do not sort results, because we want to stream them as they are found. We would need to wait until the end of the search to actually sort them. See tickets above for more details.

**Comment by nu8** [comment]
> Yes, you can use `-j 1` (or `--threads=1`). It's deterministic, but not sorted.

Thanks. I did a search using `fd --help`, but when I search `sort`, I only saw the the entry under
`-l, --list-details`. I see that option doesnt mention that use case:

> Set number of threads to use for searching & executing (default: number of available CPU cores)

but to be fair, neither does RipGrep:

> The approximate number of threads to use. A value of 0 (which is the default) causes ripgrep to 
> choose the thread count using heuristics.

**Comment by nu8** [comment]
> Yes, you can use `-j 1` (or `--threads=1`). It's deterministic, but not sorted.

Thanks. I did a search using `fd --help`, but when I search `sort`, I only saw the the entry under
`-l, --list-details`. I see that option doesnt mention that use case:

> Set number of threads to use for searching & executing (default: number of available CPU cores)

but to be fair, neither does RipGrep:

> The approximate number of threads to use. A value of 0 (which is the default) causes ripgrep to 
> choose the thread count using heuristics.

Actually upon further checking, at seems `fd -j 1` is not useful for my needs, as the order is still essentially "order created on the hard drive".

**Comment by sharkdp** [comment]
So why don't you want to use another program to do the sorting? For example, either GNU ls `gls` or a `sort` equivalent on Windows? I don't think there are any significant performance drawbacks.

**Comment by sharkdp** [comment]
> Thanks. I did a search using `fd --help`, but when I search `sort`, I only saw the the entry under
> `-l, --list-details`. I see that option doesnt mention that use case:

True, we should probably add this to the documentation.

**Comment by nu8** [comment]
PowerShell has `Sort-Object`:

https://docs.microsoft.com/powershell/module/microsoft.powershell.utility/sort-object

so I could use that. My thinking was that if sorting is already offered via `--list-details`, in an ideal setting Fd would be able to cross platform sort without calling an external tool, like RipGrep. However if you dont want to support that functionality I understand.

**Comment by sharkdp** [comment]
I'd rather not, to be honest. Comparisons with ripgrep are fine, to a certain degree. But it's a tool for a different job.. We don't have to support everything that ripgrep supports.

Thank you very much for your request anyways.
