### ISSUE TITLE
fd could  not find files in subfolders (2 levels done) while find can -

### ISSUE THREAD

**Issue by ipstone** [sharkdp/fd#657]
**Describe the bug you encountered:**  

Notice that fd could not find my files, but find can -

**Describe what you expected to happen:**
such as
```
$fd hgnc
<-- nothing happens -->


$find ./ -name "*hgnc*"
 .//input/gene_lists/hgnc_ensembl_gene_names.txt
.//input/gene_lists/hgnc_ensembl_gene_names.csv

```

**What version of `fd` are you using?**
fd 7.4.0

**Which operating system / distribution are you on?**
mac os 10.14.6
(it happens to me on centOS7 as well for fd 7.1.0

**Comment by sharkdp** [comment]
https://github.com/sharkdp/fd#fd-does-not-find-my-file

**Comment by ipstone** [comment]
thanks @sharkdp ! It's exactly the cause in the list you linked - the subfolder was included in .gitignore. Thanks and I am closing this issue.
