### ISSUE TITLE
exact values in file size filter

### ISSUE THREAD

**Issue by Rogach** [sharkdp/fd#669]
Currently `fd --size 0b` gives an error: `[fd error]: '0b' is not a valid size constraint.`

Documentation seems to require `+` or `-` prefixes (greater than or less than). Maybe we should handle cases without prefix as meaning "this exact size"? `find` does it this way - `--size 0` will find files with size of zero bytes.

(if such change is acceptable, I would be willing to provide a pull request)

**Comment by sharkdp** [comment]
That sounds great, yes! Thank you.

**Comment by sharkdp** [comment]
released in [v8.2.0](https://github.com/sharkdp/fd/releases/tag/v8.2.0).

**Comment by dezza** [comment]
Why not just allow `--size=0` ? It makes no sense.
