### ISSUE TITLE
how to disable recursive and search dot files

### ISSUE THREAD

**Issue by sudipta1g** [sharkdp/fd#670]
**What version of `fd` are you using?**
[fd 8.1.1]

1. fd always find files recursively. How to disable it

2. how I can search only dot files (example .bashrc, .bash_alias)

Thanks

**Comment by tmccombs** [comment]
1. Use the `-d 1` option to lilmit to a depth of 1.
2. `fd --hidden -g .* ...`

**Comment by sudipta1g** [comment]
always getting bellow error
[fd error]: Search path '.bash_logout' is not a directory.

**Comment by sharkdp** [comment]
Always quote special characters:
```
fd --hidden -g '.*'
```
