### ISSUE TITLE
Bug: fixed string '- -' interpreted as flag/option

### ISSUE THREAD

**Issue by trin94** [sharkdp/fd#684]
**Describe the bug you encountered:**
```bash
➤ fd --fixed-strings "- -"
error: Found argument '- ' which wasn't expected, or isn't valid in this context

USAGE:
    fd [FLAGS/OPTIONS] [<pattern>] [<path>...]

For more information try --help
```

**Describe what you expected to happen:**
`fd` prints out all the files that have the `- -` sequence in their names

**What version of `fd` are you using?**
```
fd 8.1.1
```

**Which operating system / distribution are you on?**

```
Linux 5.9.2-arch1-1 x86_64
```

```
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

```
Fish Shell
```

**Comment by sharkdp** [comment]
Thank you for reporting this. That is a limitation that is not specific to `--fixed-strings`. It's also not specific to `fd`. You will have similar problems in a lot of command-line applications when starting a value with a dash (`-`).

The solution is to escape with an additional `--` which tells the command-line option parser that no other options will follow:
```
fd --fixed-strings -- "- -"
```

**Comment by trin94** [comment]
Just checked it with `grep` and you're right! :see_no_evil: 
Sorry, for reporting this.

Thank you for the tip with the additional dashes :smiley:

**Comment by sharkdp** [comment]
No worries. Maybe this should be explained in the help text and/or the man page.
