### ISSUE TITLE
--glob doesn't work as expected?

### ISSUE THREAD

**Issue by alexxbb** [sharkdp/fd#685]
**What version of `fd` are you using?**
fd 8.1.1

`find -iname '*.pyc'`  lists a bunch of .pyc files in subfolders
`fd -g '*.pyc'` lists nothing

Am I using it wrong?

Thank you.

**Comment by tmccombs** [comment]
Have you already checked this: https://github.com/sharkdp/fd#fd-does-not-find-my-file

**Comment by alexxbb** [comment]
Oh I totally forgot about the `.gitignore` file! Thanks @tmccombs
