### ISSUE TITLE
fd does not find a file if it is more than 2 levels deep.

### ISSUE THREAD

**Issue by curioustolearn** [sharkdp/fd#686]
**What version of `fd` are you using?**

`fd 8.1.1`

**What are you trying** 
I have a file called `figures_for_class.pdf` with full path, say, `~/a/b/c/d/e/figures_for_class.pdf`

If I go to folder `e` and type `fd figures_for`, `fd` lists the file for me. The output is:
`figures_for_class.pdf`

Then, if I go to folder `d` and type `fd figures_for`, `fd` lists the file for me. The output is:
`e/figures_for_class.pdf`

Then, if I go to folder `c` and type `fd figures_for`, `fd` does not show any output. 

I even tried specifying the --max-depth explicitly to 5. But I get no output when I search from folder `c`. 

Am I doing something wrong?

**Thanks**
This tool is so much easier to use. I hope this works. Thank you for creating it.

**Comment by sharkdp** [comment]
Please check out https://github.com/sharkdp/fd#fd-does-not-find-my-file

**Comment by curioustolearn** [comment]
@sharkdp Thank you very much. As indicated at the link`-HI` worked great. However, neither the directory is hidden nor is it specified in any gitignore. Just wanted to mention that. I will keep using `-HI`.

**Comment by sharkdp** [comment]
> However, neither the directory is hidden nor is it specified in any gitignore

If you are sure about this, that would be a bug. Could you make sure with [`git check-ignore`](https://git-scm.com/docs/git-check-ignore)?

If the file is definitely not ignored, could you please give us a bit more information about the specific setup and your system?

**Comment by curioustolearn** [comment]
@sharkdp so sorry about this. That command shows that file as an ignored file. I suppose somewhere I have added `pdf` files in my gitignore. I need to find where. Thanks for your answer and help. This is an awesome tool. I never remember how to use `find`. `fd` is a great alternative.

**Comment by sharkdp** [comment]
No worries, thank you for the reply.

git check-ignore can help you find that .gitignore entry
