### ISSUE TITLE
`man fd` is incomplete on macOS

### ISSUE THREAD

**Issue by carlocab** [sharkdp/fd#687]
**Describe the bug you encountered:**

`man fd` is incomplete. The section `PATTERN SYNTAX` reads:

>          The regular expression syntax used by fd is documented here:
>
>
>          The glob syntax is documented here:

**Describe what you expected to happen:**

The `PATTERN SYNTAX` section should include where the regex and glob syntaxes are documented.

**What version of `fd` are you using?**

`fd 8.1.1`

**Which operating system / distribution are you on?**

macOS 10.15.7. `uname -srm` returns `Darwin 19.6.0 x86_64`. My system has no `lsb_release` command. `fd` was installed using `brew install fd`. (Could this be a problem with the Homebrew `fd` formula?)

**Comment by sharkdp** [comment]
Thank you for reporting htis. See #688 for further discussion.

**Comment by carlocab** [comment]
Thanks for getting a fix merged so quickly.

**Comment by sharkdp** [comment]
Thanks goes to @Liberatys.

**Comment by carlocab** [comment]
For reference, in case someone stumbles upon this and wonders why the URLs didn't render correctly on macOS: macs ship with an old (and presumably less forgiving) version of `groff`:
```
GNU groff version 1.19.2
Copyright (C) 2004 Free Software Foundation, Inc.
```

Using a newer version (e.g. `brew install groff`) and updating `/etc/man.conf` to use the newer version also fixes the problem.
