### ISSUE TITLE
 How to search for files based on a "whole-word" name

### ISSUE THREAD

**Issue by longcp** [sharkdp/fd#692]
I just want to find sepolicy files like the image, not others, can  fd do this ?
![image](https://user-images.githubusercontent.com/10282683/99968906-b94bc780-2dd4-11eb-92cf-467ce0dc445e.png)

**Comment by tavianator** [comment]
`fd '^selinux$'`

**Comment by sharkdp** [comment]
... or use a glob-based search:
```
fd -g selinux
```

**Comment by sharkdp** [comment]
I think it would be a good idea to add this example to the README. https://github.com/sharkdp/fd#tutorial
