### ISSUE TITLE
Inconsistency between -g and -e

### ISSUE THREAD

**Issue by CmdQ** [sharkdp/fd#694]
**Describe the bug you encountered:**

I think, `-e` and `-g` are not consistent in use. Assume I want to search all Python files up one directory. I can correctly do

    fd -g "*.py" ..

but I get different output with the expected equivalent

    fd -e py ..

The second version seems to silently ignore/misinterpret the `..`

To get the same output in the second case I need to include a dummy pattern:

    fd -e py . ..

**Describe what you expected to happen:**

I expect both `fd -g` and `fd -e` to not require a pattern anymore and thus treat the last argument as a path.

**What version of `fd` are you using?**
fd 7.4.0

**Which operating system / distribution are you on?**

Linux 4.19.128-microsoft-standard x86_64

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

**Comment by tmccombs** [comment]
That is the way it is supposed to work. the `-g` and `-e` flags work differently. The`-g` flag doesn't take an argument simply tells fd to interpret the pattern as a glob pattern rather than a regular expression pattern. The `-e` flag on the other hand takes an argument and  limits results by the file extension _in addition to_ filtering by the pattern.

**Comment by CmdQ** [comment]
Ok, I see. Obviously that was confusing for me. But with your reasoning I get it.

Then I have a follow-up question: I thought I could repair my command line like this

    fd -e py -p ..

Since that didn't work, my understanding of the `-p` parameter is wrong, too. Is there a flag to force interpretation as path?

**Comment by sharkdp** [comment]
```
fd -e py -p ..
```

As described by @tmccombs, `-e` takes an argument: `-e <ext>`. So `<ext>= py`. On the other hand, `-p` is a flag which does not take an argument. `fd`s usage is:
```
fd [FLAGS/OPTIONS] [<pattern>] [<path>...]
```

So in your case, `..` is used as the `<pattern>`, not as the `<path>`.

Here on the other hand:
```
fd -g "*.py" ..
```
the `-g` option is a flag (without an argument). So `<pattern> = "*.py"` and `<path> = ..`.
