### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#695]
It's always a good idea to work on documentation. I think it would also be good to restructure the README:

- [x] Add a quick link section at the top of the readme (see https://github.com/sharkdp/bat)
- [x] Extend the tutorial (rename "How to use"?)
- [x] Move the "Parallel command execution" section inside the "How to use" section). See also: #605 
- [x] Move "Installation" section below the "How to use" section

There are a few open issues [labeled with `documentation`](https://github.com/sharkdp/fd/labels/documentation):

- [ ] #692 
- [x] #684
- [x] #673
- [x] #661
- [x] #627
- [x] #605
- [ ] #374 
- [ ] #354 
- [x] #645

**Comment by tstewart-writer** [comment]
I'd be happy to work on the documentation. I can start with the changes to the README, then see what else I can do.

**Comment by sharkdp** [comment]
Sounds great. Several smaller PRs would be appreciated!

**Comment by tstewart-writer** [comment]
Probably a good idea to do this in small PR. I'm pretty new to git/GitHub, so it will be easier for me as well.

**Comment by sharkdp** [comment]
I think this can be closed. All major points have been addressed. We should - however - continue to work on the open `documentation` tickets. I have added all of them to the "fd 9" milestone.
