### ISSUE TITLE
--exec option doesn't honor --path-separator in Git Bash

### ISSUE THREAD

**Issue by LoopinFool** [sharkdp/fd#697]
In Git Bash, I use the alias `fd='MSYS_NO_PATHCONV=1 fd --path-separator=/'` so that everything is generally done with bash-style path names. This doesn't work with the --exec feature. This makes the output of "grep -H" annoying. The good news is that it functions - grep must accept either file separator. The bad news is that I get a path string I can't  usefully copy/paste in the shell to pass to programs like vim.

Examples:
`fd --type f ^filename.ext$`
Prints the full path of filename.ext with forward slashes

`fd --type f ^filename.ext$ --exec echo {}`
Prints the full path of filename.ext with backward slashes

I would expect --path-separator to apply everywhere, including paths passed to programs launched via the --exec argument.

Using fd version 8.1.1 - installed via chocolatey

Using the Git Bash that comes with Git for Windows version 2.28.0.windows.1

**Comment by sharkdp** [comment]
Thank you for reporting this.
