### ISSUE TITLE
Proper support for Windows

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#70]
There are a few things that need to be updated:

- [x] Proper handling of absolute paths (such as `C:\users\...`)
- [x] Ability to specify a search path.
- [x] Colored output

If the first two are fixed, we should be able to activate all tests that are currently disabled on Windows: https://github.com/sharkdp/fd/blob/2403ac350a8a0771f24a1a7eaf2cbe4f43419ab7/tests/tests.rs#L42-L43

Concerning point 3:
- I guess there is no analog to `LS_COLORS`, so we can only fall back to the defaults (see `Default` implementation of `LsColors`). This should work already.
- Apparently, PowerShell is able to interpret ANSI escape sequences. However, I'm not sure how to configure it to do so.
- If this is not possible, a solution would be to use [termcolor](https://github.com/BurntSushi/ripgrep/tree/master/termcolor). Currently, there is no support for 256 colors, so I'd like to keep using `ansi_term` on Linux/OSX - at least until there is progress on [this PR](https://github.com/BurntSushi/ripgrep/pull/452). If this turns out to be too complicated, we could also disable colored output by default (on Windows).

**Comment by sharkdp** [comment]
Colors actually work fine on Windows 10 / Powershell:

![image](https://user-images.githubusercontent.com/4209276/31307947-d073ab9a-ab6d-11e7-9d3a-a139b14c2f07.png)

**Comment by Detegr** [comment]
Powershell works fine, cmd.exe does not. I think we should either disable the coloring when the output is windows console or use `termcolor` to color the output if it is going to the windows console.

**Comment by sharkdp** [comment]
> I'm not sure if it is possible to detect whether the output is going to powershell or cmd

that would be one option. Maybe there is some kind of environment variable that is only set in PowerShell/cmd.exe.

> so one option would be just use termcolor on Windows as you suggested earlier.

This way, we would actually loose support for 256 colors on Windows/PowerShell, which I would think is the default for people that are actually using the command line on Windows (?)

**Comment by Detegr** [comment]
> This way, we would actually loose support for 256 colors on Windows/PowerShell

True, but I would like to think `termcolor` will eventually support 256 colors and this would no longer be an issue. I think it also would be better to support some colors on both consoles on Windows than to support no colors at all.

**Comment by sharkdp** [comment]
Somehow, I would like to get a feeling on how many people there are that actually do serious work in `cmd.exe` (serious in the sense that they are willing to install something like *fd* to improve their command line experience).

If there is such a user base, I'd be willing to work on that. Feel free to open a new ticket concerning `termcolor` support.

**Comment by sharkdp** [comment]
Actually, there seems to be some work on this here: https://docs.rs/clicolors-control/0.1.0/clicolors_control/

**Comment by ofek** [comment]
@sharkdp Will \#1 be in the next release? I currently get 2 extra path separators after the drive e.g. `C:\\\Users\Ofek\Desktop\...`.

**Comment by sharkdp** [comment]
Ok, in this case it looks like a bug. It would be great if you could open a new ticket to discuss this.

**Comment by ofek** [comment]
@sharkdp Here or https://github.com/rust-lang/rust?
