### ISSUE TITLE
How to find . -type f \( -name \*laravel\*.log -o -name \*node\*.log -o -name \*supervisor\*.log \) -exec rm -rf {} \;

### ISSUE THREAD

**Issue by vesper8** [sharkdp/fd#700]
This script was used to locate log files recursively and delete them

It would match files such as 
```
laravel-2020-12-04.log
laravel.log
node-2020-12-04.log
node.log
supervisor-2020-12-04.log
supervisor.log
```

It's very slow of course given it needs to traverse thousands of directories

Can anyone help me write this using `fd` please?

**Comment by tmccombs** [comment]
I think this could be done with somethig like:

```
fd -e log 'laravel|node|supervisor' --exec rm -rf {}
```

**Comment by sharkdp** [comment]
You can also use `--exec-batch` to call `rm` just once. Also, a trailing `{}` is optional:
I think this could be done with somethig like:

```
fd -e log 'laravel|node|supervisor' --exec-batch rm -rf
```

**Comment by vesper8** [comment]
Thank you! That works very nice

I had to add `--no-ignore --exclude node_modules --exclude vendor` since these logs files are found in folders that are ignored by .gitignore
