### ISSUE TITLE
'deployment-dummy' string in release tarballs

### ISSUE THREAD

**Issue by runiq** [sharkdp/fd#702]
Since 8.2.0, the naming scheme of the directory in the release tarballs isn't the same anymore—it now contains the string `deployment-dummy-` in between the version and arch. For example, the Linux x86_64 GNU tarball has the directory `fd-v8.2.0-deployment-dummy-x86_64-unknown-linux-gnu`.

This [broke my workflow](https://xkcd.com/1172), in which I unpack the tarballs using Ansible.

(Honestly, this is as minor as they come, I just thought I'd mention it. :) )

**Comment by sharkdp** [comment]
Thank you for the report. Yes, that was my mistake.

There was a bug in the automated deployment which was introduced via #659 (@reima: Just FYI - apparently we are still using an older version of the Travis release software `dpl` which does not support `cleanup: false`. Not sure why Travis shows that warning. No worries - Just FYI. In the future, I should always run a deployment test first when we change CI/CD stuff).

I fixed that bug after I noticed that the v8.2.0 release did not contain any Linux/macOS assets (c7cf2d110438eb42bf58fbf059190a00f8111cf5). I then pushed a `v8.2.0-deployment-dummy` tag to generate the artifacts, but didn't think about the suffix being visible in the Debian packages.

I now pushed a new 8.2.1 release. Let's hope the deployment works fine.

**Comment by reima** [comment]
@sharkdp Oh shoot! Sorry for causing this. I must admit that I didn't test the changes as thoroughly as I should have. I'm glad you could fix it.

**Comment by sharkdp** [comment]
> Oh shoot! Sorry for causing this. I must admit that I didn't test the changes as thoroughly as I should have

As I said: no worries :smile:. By the way, it looks like we will have to migrate away from Travis CI soon (https://news.ycombinator.com/item?id=25338983).
