### ISSUE TITLE
convert all files from CRLF to LF

### ISSUE THREAD

**Issue by blueray453** [sharkdp/fd#705]
**What version of `fd` are you using?**
fd 8.1.1

I found a [solution](https://stackoverflow.com/a/7533652/1772898) to convert CRLF to LF in linux mint. The command is:

`find . -type f -exec grep -qIP '\r$' {} ';' -exec perl -pi -e 's/\r$/\n/g' {} '+'`

It is using `-exec` twice. How to do that?

What is the given command's `fd` equivalent?

**Comment by sharkdp** [comment]
Multiple `--exec` commands are not supported right now, see #406.

Wouldn't this work?
```
fd -tf -x dos2unix
```

**Comment by blueray453** [comment]
Thank you very much.
