### ISSUE TITLE
Can I use '$(command)' in --exec ?

### ISSUE THREAD

**Issue by xaljer** [sharkdp/fd#706]
When do a batch rename, I can do this:

`fd 'pattern' | while read f; do mv $f $(echo $f | sd 'from' 'to'); done`

so that I can use sed or other tools to do more complex replace operation. Otherwise, template '{}' in --exec can only do limited replace.
Can fd support this kind of thing directly by in --exec?

**Comment by tmccombs** [comment]
I think this possible y wrapping the command in an invocation of shell, for example:

```sh
fd 'pattern' --exec bash -c "mv {} $(echo {}  | sd 'from' 'to')"
```

**Comment by sharkdp** [comment]
Also consider using `rename` (note that there are two incompatible versions out there):
```
fd 'pattern' -X rename from to
fd 'pattern' -X rename 's/from/to'
```
