### ISSUE TITLE
Can you upload fd version 8 on Ubuntu 20.04 repository?

### ISSUE THREAD

**Issue by pldg** [sharkdp/fd#707]
`sudo apt install fd-find` on Ubuntu 20.04 (WSL2) install the outdated `fd` version 7.4.0:

![image](https://user-images.githubusercontent.com/24630716/102939105-e4960500-44ad-11eb-9531-aa1a6bfe9e5e.png)

As you can also see in the [official maintained package](https://packages.ubuntu.com/search?keywords=fd-find):

![image](https://user-images.githubusercontent.com/24630716/102938935-9254e400-44ad-11eb-9918-c4b6769684ae.png)

Can you upload the last release (version 8.x.x)?

**Comment by tmccombs** [comment]
That is an issue to bring up with the Ubuntu package maintainer.
