### ISSUE TITLE
Add way to show only ignored files

### ISSUE THREAD

**Issue by wren** [sharkdp/fd#708]
Hi! First off, I just wanted to say thank you for fd. I use it constantly, and am always finding new uses for a vcs-aware find tool.

One of the many uses for me is using fd to find git-ignored files in order to generate a list of files to exclude from my backups. In order to accomplish this currently, I run fd twice (once with `-I` and once without), then take the difference. Like so:

```sh
sort <( cat <(fd -Ht f . $dir) <(fd -HIt f . $dir) ) | uniq -u
```

This works but fd has to run twice, and there's a considerable slow down using sort and uniq (as one would expect).

So, my feature request is to add a way for fd to search among just the vcs-ignored files (leaving out normal files).

For implementation, anything that works is fine with me, but I was thinking of some possible options.

There is, of course, the option to add a new flag (something like `--only-ignored` or whatever). This if the first that comes to mind, and it's user-friendly, but might have some weird edge cases around what happens if a user does something like `fd --hidden --only-ignored`. Does `--only-ignored` show hidden files? Does it require `--hidden` to be included? Does it automatically invoke the `-I` flag?

Another option (that I like better) is a new type (something like `fd --type ignored` or `fd -t i`). I personally like this the best, and think it fits the most with the current fd interface. This could have some unexpected results if a user tries to filter for ignored files without using the `-I` flag on the search, but could probably be mitigated with an explanation in man.

Also, as I write this all out, it occurs to me that a similar addition for hidden files would probably also be pretty useful.

**Comment by tmccombs** [comment]
I think the `--type ignored` option is inconsistent with the existing values that can be used with `--type`.

**Comment by wren** [comment]
@tmccombs That's completely fair. Honestly, any implementation is completely fine with me, as long as there's a command I can run to find just the ignored files.

**Comment by sharkdp** [comment]
I think this is a use case that should rather be handled by `git` itself, i.e. via `git status --ignored` or `git ls-files …`. See https://stackoverflow.com/questions/466764/git-command-to-show-which-specific-files-are-ignored-by-gitignore for more information.

**Comment by wren** [comment]
@sharkdp I think that makes a lot of sense for a single repo. It starts getting a bit clunky when traversing a tree that contains multiple repos, though, and even more with a tree that contains normal directories mixed in with those repos. 

Finding files that are ignored, and also meet certain criteria that fd already finds (like being hidden or executable) would be very useful for me. I already do this on a regular basis (looking for lock files in node_modules folders, compiled binaries, checking that minifiers worked as intended, etc), but have to manually filter through the noise of non-ignored files in the output.

And in the original use case from this issue, even with my clunky workaround, I found it very useful to be able to generate a list of ignored files in order to exclude those files from backups. Most backup software doesn't know how to interact with git, and most of that same software only provides robust ways to exclude files rather than include them.

Ultimately, fd is your project and I completely understand if you decide this doesn't belong here. But I do think it would be very useful for certain use cases that aren't covered by git and/or various backup software.

**Comment by sharkdp** [comment]
> @sharkdp I think that makes a lot of sense for a single repo. It starts getting a bit clunky when traversing a tree that contains multiple repos, though, and even more with a tree that contains normal directories mixed in with those repos.

Well, ignored files can only be in Git repositories. So you could `fd -H -td -g .git` to find all Git repositories and then use `-x` to run a Git command that shows all ignored files. Use `git`s `-C` option to specify the base path to the directory. Something like:
```bash
fd -H -td -g .git -x git -C '{//}' ls-files --others -i --exclude-standard
```

Would that work?

**Comment by wren** [comment]
@sharkdp That is pretty close, but my comment above about repos mixed was referring to `fd`'s ignore files. This sollution is pretty close, but it doesn't factor in `fd`'s global ignore file, or passing one in using the `--ignore-file` flag.

**Comment by sharkdp** [comment]
I understand your use case, but it doesn't really feel like there should be a simple-to-access feature in `fd` that supports it. It seems too peculiar for that.

I'd like to close this for now, but happy to reopen if you or others feel like it should be.

**Comment by wren** [comment]
@sharkdp No worries. I would find it useful, but completely understand if it's not a good fit for your project. Thanks for considering it!
