### ISSUE TITLE
How fd behave with --threads 0 and --threads 1?

### ISSUE THREAD

**Issue by stephane-archer** [sharkdp/fd#712]
I don't want my `-x command` to be executed in parallel but **sequentially**.
I saw the option `--threads` but what number shoud I put?
is 0 and 1 the same? or 0 has a different meaning? is it "additional thead" in addition to the main thread?

**Comment by tmccombs** [comment]
1 uses a single thread. 

From [this line](https://github.com/sharkdp/fd/blob/6a3aae52fdc60c6bc4b08d4122c7d91b2578c648/src/main.rs#L352), it appears that 0 is not a valid argument for the `--threads` option.

**Comment by sharkdp** [comment]
Exactly. `-j 1` will launch one search thread and one thread for command execution. It ensures sequential execution (but note that the order is not deterministic).

You can test this with a script like
``` bash
#!/bin/bash

(
    flock -n 9 || (echo FAILED && exit 1)

    echo "sequential: $*"
    sleep 0.1
) 9> /tmp/sequential.lock
```

It will show a lot of "FAILED" messages is you run it with j > 1, but run fine with j == 1.

**Comment by sharkdp** [comment]
Please let us know how the documentation could be improved. I guess we could expand the help text for `-j / --threads`?

**Comment by stephane-archer** [comment]
Thanks a lot for your replies,
I was using `fd 8.1.1` and I was able to launch `fd . --threads 0 --extension JPG ./MyFolder -x echo {}`
without any error witch really confused me.
I just upgraded to `8.2.1` and I got the error message `[fd error]: Number of threads must be positive.` which is clearly the behavior I was expected in the first place.
I was using this feature for the first time and in the current version, I think it's really clear.
I didn't realize I was outdated and this issue was already fixed.
My apologies.

**Comment by sharkdp** [comment]
>  I was using `fd 8.1.1` and I was able to launch `fd . --threads 0 --extension JPG ./MyFolder -x echo {}`
> without any error witch really confused me.

Ah, yes. That was only fixed recently.

>  I didn't realize I was outdated and this issue was already fixed.
> My apologies.

No worries. I think we could still improve the documentation. Both for the `--exec` option as well as for the `--threads` option. Running commands sequentially is probably a rather common use case. Let's leave it open until then.

**Comment by stephane-archer** [comment]
I didn't expect the first time I use -x to be in parallel.
I think just adding this detail in the doc will be great because coming from `find` your script and you maybe didn't prepare for that case (I was not).

```
-x, --exec command
              Execute command for each search result in parallel (see --thread 1 for sequential order). The following placeholders are substituted by a path derived from the current search result:
```
