### ISSUE TITLE
Is fd . MyFolder -x mv -i {} AnotherFolder/ safe?

### ISSUE THREAD

**Issue by stephane-archer** [sharkdp/fd#713]
if MyFolder contains two files with the same name even with the -i option or -n of the mv command I can get overwrite because of the parralle execution of the command. is it correct?

**Comment by sharkdp** [comment]
Yes, absolutely. I'm pretty sure this is NOT safe. Even if there are no files with the same names, your search could match a directory, in which case the directory would be moved first. This could lead to weird behavior. See also: https://github.com/sharkdp/fd#deleting-files.

What is it that you want to do? Can you describe your use-case?

**Comment by stephane-archer** [comment]
I have photos in folders from SD card I have backup and I want to organize them by date.
so I have:
```
MyFolder/
     sd1
     sd2
     sd3
     ....
```
and I want
```
AnotherFolder/
    2021-01-01
    2021-01-02
    ....
````
This organization is done by a python script but I used fd to search for jpeg.
I do the following:
`fd . --extension JPG MyFolder/ -x python3 MyScript.py {}`

but in the python script, I create the folders with the date name and move the different jpeg around.
I actually don't know how to avoid multiple programs (sharing the same code) to not step on each other foot.
for example:
```
if not os.path.exists(modificationtime):
		os.mkdir(modificationtime)
```
`os.mkdir` can be executed at the same time using `fd -x`

I know this is not a python forum but I would like to know how I can modify my script to avoid using the option `--thread 1`

**Comment by tmccombs** [comment]
On linux at least `os.mkdir` is an atomic operation. If two processes try to do it at the same time, one will succeed, and the other will fail (raising an exception in python). Depending on what you are doing in your script you might be able to use that information to determine the next step.

**Comment by stephane-archer** [comment]
Thanks for your answer, I didn't know `os.mkdir` was atomic (it's not written in the doc right? [https://docs.python.org/3/library/os.html](https://docs.python.org/3/library/os.html)) .
the main problem will be probably:
```
assert not os.path.exists(newpath), "file already exist:" + str(newpath)
shutil.move(file, newpath)
```
with `shutil.move(file, newpath)` multiple files can be move at the same place even if I just checked before with parallel execution.
I imagine `shutil.move` will not be atomic?
I don't want any overwrites.

**Comment by aswild** [comment]
You don't really need synchronization for the operation of "create a directory if it doesn't exist" - just try to create it (os.mkdir). If it exists, you'll get FileNotFoundError (C errno is EEXIST) which you can catch and ignore.

However, if you might have overlapping final filenames in the target directory, then there's no way to avoid filesystem races between parallel processes.

Maybe consider modifying your script to take a list of filenames as multiple arguments, and use fd's `-X` (`--exec-batch`) option to run the script once with all of the results.

**Comment by tmccombs** [comment]
> However, if you might have overlapping final filenames in the target directory, then there's no way to avoid filesystem races between parallel processes.

That isn't entirely true. You just need some kind of locking mechanism. The easiest way to do that would be to have a shared lock file between the processes and before performing the move operation acquire  a lock on that file (`fcntl.flock` on unix systems).  There are other inter-processing mechanisms as well, such as a semaphore in shared memory, but those are probably more complicated. 

Another option is rather than using `shutil.rename` to move the file you open the destination with the `'x'` mode (exclusive create). If it fails, a file with that name already exists. Then copy the bytes over from the old file, and delete the old file. 

Another option is to just add a random suffix onto the destination file to avoid collisions. 

Linux also has a `renameat2` syscall that has a `RENAME_NOREPLACE` option, but that's probably more involved than you want.

**Comment by stephane-archer** [comment]
Thanks a lot @tmccombs.
I was able to use `fcntl.flock` see bellow:
```
with open(newpath.parent / 'lockfile.lock', 'w') as lockfile:
            import fcntl
            fcntl.flock(lockfile, fcntl.LOCK_EX)
            assert not os.path.exists(newpath), "file already exist:" + str(newpath)
            shutil.move(file, newpath)
            fcntl.flock(lockfile, fcntl.LOCK_UN)
```
Is `open(myFile, 'x')` atomic and be used for locking mechanism?
What do you think about this? do you think it's better?
```
try:
    with open(newpath + '.lock', 'x') as lockfile:
            assert not os.path.exists(newpath), "file already exist:" + str(newpath)
            shutil.move(file, newpath)
except:
      print("someone is trying to copy a file with the same file name I should do something else"
```

The first one is using a syscall dedicated to that purpose so I feel confident using it but it creates a lock file I cannot delete because it's maybe used by another process.
The second creates a lock for every files but after the copy, I can delete the lock file

**Comment by tmccombs** [comment]
I think either of those approaches would work.

**Comment by stephane-archer** [comment]
Thank you so much @tmccombs , @aswild and @sharkdp for your help 👍
