### ISSUE TITLE
Folder names with spaces not working (argument parsing)

### ISSUE THREAD

**Issue by torbjo** [sharkdp/fd#716]
I'm sorry if I am mistaken; I find this kind of hard to belive.

**Describe the bug you encountered:**

    $ mkdir "folder name" ; fd . "folder name"
    [fd error]: Search path 'folder' is not a directory.
    [fd error]: Search path 'name' is not a directory.
    [fd error]: No valid search paths given.

**Describe what you expected to happen:**

    $ mkdir "folder name" ; fd . "folder name"

I expect no error message. (And empty output).

**What version of `fd` are you using?**

fd 8.2.1

**Which operating system / distribution are you on?**

Linux 4.19.0-10-amd64 x86_64

Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

**Comment by sharkdp** [comment]
Thank you for reporting this. I can not reproduce it:

```
▶ mkdir "folder name" ; fd . "folder name"
```
shows no output for me, as it should.

Is `fd` some kind of shell alias or shell function?

**Comment by sharkdp** [comment]
closing as "can not reproduce" for now. Happy to reopen if there is any feedback
