### ISSUE TITLE
`fd` doesn't use the same ansi sequence in terminal and X11 with Emacs

### ISSUE THREAD

**Issue by thierryvolpiatto** [sharkdp/fd#725]
**Describe the bug you encountered:**

When I run Emacs from the window manager menu(i.e. the Emacs.desktop), the ansi sequence is:
    `[38;5;81m.config/`
whereas when starting emacs from a console (here the xfce console) the ansi sequence is:
    `[1;34m.config/`
As a result Emacs is unable to colorize  `[38;5;81m.config/` whereas it is able to colorize `[1;34m.config/`
This is with 8.2.1, I have not this problem with 8.1.1, ansi sequences are the same.

Note that from a basic terminal in emacs, output is colorized but not from an async process.

**Describe what you expected to happen:**
Colors in fd output with fd 8.2.1.

**What version of `fd` are you using?**
fd 8.2.1

**Which operating system / distribution are you on?**

OS: Linux Mint 19.3 Tricia x86_64
Host: 81NB Lenovo IdeaPad S340-14API
Kernel: 5.4.0-65-generic
Shell: bash 4.4.20
Resolution: 1920x1080
DE: Xfce
WM: Xfwm4
WM Theme: Mint-Y
Theme: Mint-Y [GTK2/3]
Icons: Mint-Y [GTK2/3]
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz
GPU: AMD Picasso
Memory: 2045MiB / 5946MiB

**Comment by thierryvolpiatto** [comment]
Screenshots with 8.1.1 and 8.2.1:

![Capture d’écran_2021-02-04_09-36-58](https://user-images.githubusercontent.com/1533939/106866696-0e596300-66cd-11eb-8357-4c8769ff8d4d.png)

![Capture d’écran_2021-02-04_09-39-34](https://user-images.githubusercontent.com/1533939/106866745-1f09d900-66cd-11eb-856f-a7ed674b4883.png)

**Comment by thierryvolpiatto** [comment]
Debug logs from 8.1.1 and 8.2.1

![Capture d’écran_2021-02-04_09-50-47](https://user-images.githubusercontent.com/1533939/106868128-b1f74300-66ce-11eb-99fc-9396b01f0fa3.png)

![Capture d’écran_2021-02-04_09-48-21](https://user-images.githubusercontent.com/1533939/106868181-c20f2280-66ce-11eb-991c-968917fd13d6.png)

**Comment by thierryvolpiatto** [comment]
I don't know what is different from version 8.1.1, but I have fixed the problem by setting the env var `LS_COLORS` in my `~/.profile` file by adding `eval $(dircolors)`.  Hope this will help people having the same problem.

**Comment by sharkdp** [comment]
Thank you for reporting this.

That's unfortunate. We added a new default value for `LS_COLORS` in v8.2.0 in case it has not been set by the user. Your environment apparently doesn't support 8 bit / 256 color ANSI codes :-/. Maybe we should provide a backwards compatible version of `LS_COLORS` that only uses 16 colors. Or try to detect terminal support.

**Comment by sharkdp** [comment]
This has not yet appeared for other users and seems to be a very peculiar environment. I hope it's ok if we close this for now.

Everyone: Feel free to comment if this affects you.
