### ISSUE TITLE
What's the difference between windows-gnu and windows-msvc release?

### ISSUE THREAD

**Issue by saifali-ch** [sharkdp/fd#726]
**fd-v8.2.1-x86_64-pc-windows-gnu**
**fd-v8.2.1-x86_64-pc-windows-msvc**

Are both releases same?  If not which one should I prefer?

**Comment by tmccombs** [comment]
Which ABI it uses. windows-gnu is compatible with the GCC/MinGW ABI and windows-msvc is compattible with the Microsoft Visual Sutdio compiler ABI.  For an application like `fd` that isn't dynamically linked to anything besides libc, it probably doesn't matter too much.  There may be other small differences, such as small differences in performance or size of the executable, but I think either one would work fine.

**Comment by saifali-ch** [comment]
I perfromed benchmarking on windows with **sharkdp/hyperfine** and it turns out be that **windows-gnu** is a bit faster then **msvc**. 
On the other hand, **windows-msvc** binary size is smaller.

Thanks a lot!
**Jazzak Allah**

**Comment by sharkdp** [comment]
I think the MSVC version also has a dependency on some MSVC runtime support DLLs, right?

In any case, it would probably be good to document this somewhere for Windows users.

**Comment by plutonium-239** [comment]
Wrong repo but since it's already discussed here: I see the hyperfine `windows-gnu` release was disabled in https://github.com/sharkdp/hyperfine/commit/24a0d5da1bff11567bbf307315d11cb0e10733ec, citing a build error.
Any plans to get that back?
