### ISSUE TITLE
`-H` does not respect specific requests from `--prune` when used with `--type file`

### ISSUE THREAD

**Issue by HoffsMH** [sharkdp/fd#727]
Background:
I would like to search my dotfiles directory by piping output from `fd` to `fzf`. Being a dotfiles repository, there are many different hidden files that I would like to search through. At the same time I would like to ignore all files in the `.git` directory

**Describe the bug you encountered:**

I use `fd` with the `-H` flag and `--prune=".git"` and `--type file`

```sh
$ /usr/bin/fd --version
fd 8.2.1

$ pwd
<...>/personal/dotfiles

$ /usr/bin/fd -H --prune=".git" --type file | ag .git
<...>
.git/index
.git/info/exclude
.git/logs/HEAD
.git/logs/refs/heads/master
.git/logs/refs/remotes/origin/HEAD
.git/logs/refs/remotes/origin/master
.git/objects/00/a04afa8c3f579727a6b6cc6c083d87d7e758c8
.git/objects/01/052816a315855df577176672659e3b8900f8dc
.git/objects/01/388138e41dd66651a8ad6eaa9da67c215b908f
<...>

```

**Describe what you expected to happen:**

I expect all hidden files to be shown except those that exist in a folder that I expressly tell `fd` not to traverse.

**What version of `fd` are you using?**
`fd 8.2.1`

**Which operating system / distribution are you on?**

uname: `Linux 5.4.89-1-MANJARO x86_64`

lsb_release:
```
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	20.2.1
Codename:	Nibia
```
--- 

I apologize if this is a duplicate or the intended behavior.

**Comment by tavianator** [comment]
I don't think `fd` actually looks at the value in `--prune=value` -- I'm surprised it accepts it at all.  `--prune` is just a flag that tells `fd` to prune *every* matching directory.  Since you have `--type file` no directories will match and nothing is pruned.

`fd -H --exclude=".git"` works fine.

**Comment by HoffsMH** [comment]
@tavianator Thank you, didn't understand the difference between `exclude` and `prune`. My thinking was that it would somehow be more performant if it never had to look in my `git` folder to begin with.

Sorry for the trouble! feel free to close. :smile:

**Comment by sharkdp** [comment]
@HoffsMH Thank you for reporting this.

> I don't think `fd` actually looks at the value in `--prune=value` -- I'm surprised it accepts it at all. `--prune` is just a flag that tells `fd` to prune _every_ matching directory

Yes. It's unfortunate that `--prune` accepts a `=value`. It's a bug in the command-line argument parser that we use: https://github.com/clap-rs/clap/issues/1543

@HoffsMH Do you think we could improve the documentation here? Maybe we should refer to `--exclude` from the `--prune` help text? Or add some examples for `--prune`?

**Comment by HoffsMH** [comment]
@sharkdp, my understanding is that `--prune` cannot have a single effect on the output when used with `--type file`. From a user experience point of view, I think I would've had less total head-scratching time if instead it threw an error like 

```
--prune cannot be combined with --type file, try -exclude or --type directory instead
```
I realize that would be a pretty bespoke ask. Barring that, my process was to open up the man page and when I saw the words  for `--prune`

```
Do not traverse into matching directories
```
I then mentally added the words "while in search of my files" to the end of that sentence then thought, "Oh cool that sounds like it would make it even faster than `--exclude`". So my intuition would be to add some wording around the `prune` section since that's what I focused on.

**Comment by sharkdp** [comment]
> my understanding is that `--prune` cannot have a single effect on the output when used with `--type file`.

Correct.



> From a user experience point of view, I think I would've had less total head-scratching time if instead it threw an error like

We actually discussed this in https://github.com/sharkdp/fd/pull/658#issuecomment-706458229 and decided to allow/ignore it. @reima, what do you think? Should we print an error in that case? I can certainly see why it could be confusing otherwise. 

> I realize that would be a pretty bespoke ask.

No, I appreciate it!



> Barring that, my process was to open up the man page and when I saw the words for `--prune`

Ok, so let's work on the documentation for both `--prune` and `--exclude`. If you `--exclude foo`, `fd` will not descend into `foo` directories. So it `--prune` wouldn't be faster than `--exclude`.

> So my intuition would be to add some wording around the `prune` section since that's what I seemed to focus on.

:+1:
