### ISSUE TITLE
Ctrl-T not working on bash in Ubuntu

### ISSUE THREAD

**Issue by chhajedji** [sharkdp/fd#728]
`fd --version`: `fd 8.1.1`

One suggestion:

Adding `FZF_DEFAULT_COMMAND='fd --type f` does not help in Debian even if aliased, as the package name is `fdfind`. Rather, `export FZF_DEFAULT_COMMAND='fdfind --type f` helped me. Maybe you want to update README with this.

Original query:

As suggested in the [tips](https://github.com/junegunn/fzf#tips), I wanted to map my ctrl-t in bash shell to do fuzzy search but exporting the variables `FZF_CTRL_T_COMMAND` and `FZF_DEFAULT_COMMAND` didn't help. But when ctrl-t is pressed, it only swaps last and second last letters and not what it's expected to do. What could I be missing?

![rec-2021-02-11_19 20 17](https://user-images.githubusercontent.com/42715380/107645465-b909ec80-6c9e-11eb-8313-263a5ae5a389.gif)

**Comment by tmccombs** [comment]
That is because Debian calls the command `fdfind` instead of `fd`, on other distributions, or if you build it yourself, the command is `fd`.

**Comment by chhajedji** [comment]
Yeah, got that. It is better to soft link `fd` rather than making an alias.
```sh
ln -s $(which fdfind) ~/.local/bin/
```
After this I can use `FZF_DEFAULT_COMMAND='fd --type f` on Debian also. If using an alias, I have to use `fdfind` instead of `fd`.

Also got the ctrl-t and other completions wokring by [sourcing key-bindings.bash from fzf](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.bash)

**Comment by tmccombs** [comment]
ah, yes. an alias won't work in thinks like `FZF_DEFAULT_COMMAND` because that command won't be run in a context that has access to bash aliases.
