### ISSUE TITLE
Use real-world examples in the tutorial

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#73]
The tutorial in the README contains the common use cases of `fd`, but it would be nice if we could find real-world examples for each of these use cases (as opposed to searches in a test-environment).

Some random ideas:
* Find specific log files in `/var/log`
* Find configuration files in `/etc`
* Use the *fd*-repository as an actual real world example
    * Use a plain `fd` call to get an overview of all files
    * `fd -e yml` to show all `*.yml` files. Notice that `.travis.yml` is not present => `fd -H -e yml`.
    * `fd -H sample` to show the `.git/hooks/` files.
    * ...
* Find all Python files in the current directory: `fd -e py`.

**Comment by TitiAlone** [comment]
I take this.

**Comment by sharkdp** [comment]
@TitiAlone Sounds great! Let me know if you have anything to share (even single examples).

**Comment by TitiAlone** [comment]
Not much time for now, unfortunately, beacause of events I can't control...
Here's where I stopped, if someone wants to work on it before:

`
## Tutorial

First, to see all command line options, you can get `fd`'s help text by running:
```
fd --help
```

`fd` can be called with no arguments, it'll then show the content of the actual directory
recursively (like `ls -R`):
```
> cd fd
> fd
appveyor.yml
build.rs
Cargo.lock
Cargo.toml
LICENSE
README.md
src
src/app.rs
src/fshelper
src/fshelper/mod.rs
src/lscolors
src/lscolors/mod.rs
src/main.rs
tests
tests/testenv
tests/testenv/mod.rs
tests/tests.rs
```

If we work in a directory that is a Git repository (or includes several Git repositories), `fd`
does not search folders (and does not show files) that match the `.gitignore` pattern. For instance,
see above example, and note that .gitignore is the following:
```
target/
**/*.rs.bk
```

To disable this behavior, we can use the `-I` (or `--ignore`) option:
```
> fd -I
Cargo.lock
Cargo.toml
LICENSE
README.md
appveyor.yml
build.rs
src
src\app.rs
src\fshelper
src\fshelper\mod.rs
src\lscolors
src\lscolors\mod.rs
src\main.rs
target
target\debug
target\debug\build
target\debug\build\fd-find-11fb469ceafee9ce
target\debug\build\fd-find-11fb469ceafee9ce\out
target\debug\build\fd-find-11fb469ceafee9ce\out\_fd
target\debug\build\fd-find-11fb469ceafee9ce\out\_fd.ps1
target\debug\build\fd-find-11fb469ceafee9ce\out\fd.bash-completion
target\debug\build\fd-find-11fb469ceafee9ce\out\fd.fish
target\debug\build\fd-find-11fb469ceafee9ce\output
target\debug\build\fd-find-8682b98943903a5b
target\debug\build\fd-find-8682b98943903a5b\build-script-build.exe
target\debug\build\fd-find-8682b98943903a5b\build_script_build-8682b98943903a5b.exe
target\debug\build\fd-find-8682b98943903a5b\build_script_build-8682b98943903a5b.pdb
target\debug\build\kernel32-sys-7568a971f6718c45
target\debug\build\kernel32-sys-7568a971f6718c45\out
target\debug\build\kernel32-sys-7568a971f6718c45\output
target\debug\build\kernel32-sys-d715e52d58016295
target\debug\build\kernel32-sys-d715e52d58016295\build-script-build.exe
target\debug\build\kernel32-sys-d715e52d58016295\build_script_build-d715e52d58016295.exe
target\debug\build\kernel32-sys-d715e52d58016295\build_script_build-d715e52d58016295.pdb
target\debug\deps
(some content omitted...)
target\debug\examples
target\debug\fd.exe
target\debug\incremental
target\debug\native
tests
tests\testenv
tests\testenv\mod.rs
tests\tests.rs
```

If `fd` is called with a single argument (the search pattern), it will perform a recursive search
through the current directory. To search for all files that include the string "access" in the
/var/log directory, we can simply run:
```
> cd /var/log
> fd access
cups/access_log
cups/access_log.1
cups/access_log.2
some_program/user_access
```

The search pattern is treated as a regular expression. To show only entries that start with "access",
we can simply run:
```
> fd '^access'
cups/access_log
cups/access_log.1
cups/access_log.2
```

Note that `fd` does not show hidden files (like `.access_control`) by default. To change this, we can use
the `-H` (or `--hidden`) option:
```
> fd -H access
cups/access_log
cups/access_log.1
cups/access_log.2
some_program/user_access
.access_control
```

If we are interested in showing the results from a particular directory, we can specify the root of
the search as a second argument:
```
> cd /etc
> fd firewall iptables
simple_firewall.rules
// TODO: review this with router content
```

If we work in a directory that is a Git repository (or includes several Git repositories), `fd`
does not search folders (and does not show files) that match the `.gitignore` pattern. For example,
imagine we had a `.gitignore` file with the following content:
```
*.sh
```
In this case, `fd` would not show any files that end in `.sh`. To disable this behavior, we can
use the `-I` (or `--ignore`) option:
```
> fd -I me
sub_dir/more_dir/even_further_down/not_me.sh
```

To really search *all* files and directories, we can combine the hidden and ignore features to show
everything (`-HI`):
```
fd -HI 'not|here'
not_file
sub_dir/.here_be_tests
sub_dir/more_dir/.not_here
sub_dir/more_dir/even_further_down/not_me.sh
sub_dir/more_dir/not_file
```

Searching for a file extension is easy too, using the `-e` (or `--file-extensions`) switch for file
extensions:
```
> fd -e sh
sub_dir/more_dir/even_further_down/not_me.sh
```

Next, we can even use a pattern in combination with `-e` to search for a regex pattern over the
files that end in the specified extension.
```
> fd -e txt test
fd_examples/desub_dir/old_test.txt
fd_examples/sub_dir/new_test.txt
```

What if we wanted to run a command for each of the search results? We can use `xargs` to do that:
`fd -0 'test' | xargs -0 -I {} cp {} {}.new`

In this example there are a couple things to take note:
  - First we are telling `fd` we want a null character to seperate the files `-0`, this is
    important when passing to `xargs`.
  - Second, we are piping the output to `xargs` and telling this program to expect input null
    terminated with `-0` (the same syntax that `fd` was built with).
  - Then for fun we are using `-I` to replace a string `{}` and lauching `cp` to copy the file `{}`
    to a file ending in `{}.new`.

`fd` can also show us the absolute path vs. the full path with `-a` (`--absolute-path`):
```
> fd -a new
/Users/fd_user/fd_examples/sub_dir/more_dir/even_further_down/test_seven.new
/Users/fd_user/fd_examples/sub_dir/more_dir/even_further_down/testing_eight.new
/Users/fd_user/fd_examples/sub_dir/more_dir/test_file_six.new
/Users/fd_user/fd_examples/sub_dir/test_file_five.new
/Users/fd_user/fd_examples/sub_dir/test_file_four.new
/Users/fd_user/fd_examples/sub_dir/test_file_three.new
/Users/fd_user/fd_examples/test_file_one.new
/Users/fd_user/fd_examples/test_file_two.new
/Users/fd_user/fd_examples/test_one.new
/Users/fd_user/fd_examples/this_is_a_test.new
```
`

**Comment by sharkdp** [comment]
> Here's where I stopped, if someone wants to work on it before

This is great, thank you very much. I've put this into a pull request (see #122) so others can review and improve it.

(if you would have rather liked to open a PR on your own, let me know)

> Not much time for now, unfortunately, beacause of events I can't control...

No worries.

**Comment by pickfire** [comment]
Is there some examples like:

    find . -perm /100

**Comment by sharkdp** [comment]
What do you mean, exactly? `-perm` is not supported by `fd`. But we have an `xargs` example in #122.

**Comment by pickfire** [comment]
@sharkdp Shouldn`t `-perm` considered one of the most used features of `find`?
