### ISSUE TITLE
Search in parent directories instead of in subdirectories

### ISSUE THREAD

**Issue by mingyli** [sharkdp/fd#731]
Sometimes I'll want to search for a `.editorconfig` or Bazel `BUILD` file up the file tree instead of in subdirectories.
The shell script in <https://unix.stackexchange.com/questions/6463/find-searching-in-parent-directories-instead-of-subdirectories> works and I'm wondering if would be worth adding as a feature to `fd`. Apologies if this has been raised before.

**Comment by sharkdp** [comment]
That has not been raised before, IIRC. Thank you for the request.

Interesting idea. I'm not sure if that's something that should be builtin to `fd`, to be honest. But for what it's worth, here is an adapted script that works with `fd`:
```bash
#!/bin/bash

set -e

path="$PWD"

while [[ $(realpath "$path") != / ]]; do
    fd \
        --search-path="$path" \
        --absolute-path \
        --exact-depth=1 \
        "$@"

    path="$(realpath --relative-to="$PWD" "$path"/..)"
done
```

The `--absolute-path` option can be removed if someone likes to see search result paths like `../../../../../../.git`.

The script can be used like this to find the enclosing `.git` repo root, for example:
```
fd_up -H -h .git
```
