### ISSUE TITLE
Introducing a new type for git repos

### ISSUE THREAD

**Issue by EmilSodergren** [sharkdp/fd#732]
Hi,

I use fd a lot and I love it. I find myself using the following construct quite a lot:
`fd -uu --type d '\.git$' -x git -C {//} <git command to run>`
to run a certain command in all git repositories found under the current directory.

My suggestion/question would be if it would be possible to introduce a new type, '--type g', for git repositories to be able to write something like:
`fd --type g -x git -C {} <git command to run>`

Best Regards!
Emil

**Comment by sharkdp** [comment]
Thank you for reporting this.

I'd rather not add a special feature for that. I think it's something that could be easily stored in a shell function:
```
recursive_git() { fd -uu --type directory -g '.git' --exec  git -C {//} "$@" }
```
and then, for example:
```
recursive_git diff --shortstat
```

Slightly related: https://github.com/sharkdp/fd/issues/708#issuecomment-756905829

**Comment by EmilSodergren** [comment]
Yeah, it was a bit of a long shot. Useful though, but creating a function for it will do just fine. Thanks!
