### ISSUE TITLE
Use an environment variable for default options

### ISSUE THREAD

**Issue by chhajedji** [sharkdp/fd#739]
Is there any environmental variable which can be set to use with `fd`? I didn't find anything related in documentation hence filing a feature request.

Something similar to how we have it for `fzf`
```sh
export FZF_DEFAULT_COMMAND='fd --type file'
```
Happens many times that I forget what's in `.gitignore` and assume that result of `fd` is not present. Then after long session of debugging the inefficient sibling `find` helps me out !

I would like to add `-I`, `-H` and some other options to be used by default everytime I use `fd`.

**Comment by tmccombs** [comment]
This may be related to https://github.com/sharkdp/fd/issues/612.

**Comment by chhajedji** [comment]
Thanks @tmccombs, the discussion is exactly my point. Although I didn't follow complete thread as it's pretty lengthy one. Should I vote somewhere or contribute to the discussion in some other way?

**Comment by sharkdp** [comment]
See also: "Is there a global configuration file?" (https://github.com/sharkdp/fd/issues/362)

@chhajedji  For now, I think it's best to use an alias:
```bash
alias fd="fd -HI"
```

If you would like to see this as a general default in `fd`, please follow/comment on #612, as @tmccombs pointed out.
