### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by MrYakobo** [sharkdp/fd#740]
Hello

Thank you for an amazing tool. It really outplays GNU `find` and `parallell` by a lot.

Today, I found myself converting a lot of mp3s

```bash
fd -j4 . ../some_dir -e mp3 -x lame -b 256
```

which works marvellously, but without any easy way to tell how many files `fd` has left to process. A progress bar option (`--progress-bar/-#`?) would be nice.
Have a nice day!

**Comment by sharkdp** [comment]
Thank you for your request.

That's an interesting idea. Two problems/questions:

* It's not really possible to show a progress bar (in all `--exec` cases). Consider this: someone might be running a very fast `--exec` command on a couple of search results in a huge directory. In this scenario, the time is largely determined by *searching* the files, not by process execution. Conversely, in your use case, the filesystem search is probably much faster than the process execution. But there is no way to tell how long each of these commands will take. Estimating it by keeping track of a running average or similar can be misleading if there are files of vastly different size.
* What about the process output? Would we show that in addition (above/below the progress bar)? Or would `--progress-bar` switch off the process output?

**Comment by MrYakobo** [comment]
I fully agree with the difficulty of estimating the total time accurately, but isn't it always hard to estimate the total time? Progress bars have been wonky since always. The same argument applies to gnu parallel, yet they have the option. It doesn't have to be a perfect estimate :smile:

For process output, yeah that's definitely also a tricky one. Maybe do what parallel does with it's `--bar`?

```bash
$ mkdir test && cd test
$ touch $(seq 1 10)
$ echo 'import sys;import random;import time;time.sleep(random.random()*2);print("STDERR", file=sys.stderr);print("STDOUT")' > stderr_stdout.py
$ find -print0 | parallel --bar -0 -P 4 python stderr_stdout.py
```
![gnu](https://user-images.githubusercontent.com/11942597/111616163-de2fd480-87e1-11eb-926a-5dd9d24cf3bb.png)

i.e. copy both streams. And then maybe have some option for muting the subprocess output for a clean progress bar.

Or, don't show a bar at all, but rather show a fraction (file 42/100 done). Maybe that's less [lying](https://web.eecs.utk.edu/~azh/blog/fixprogressbars.html) than doing a bar and ETAs :thinking:

**Comment by meandmymind** [comment]
I would better not estimate total time, just show % of files processed and current time spent. It would be enough for user to satisfactorily estimate progress himself.

Thumbs up for feature!

**Comment by sharkdp** [comment]
Maybe we should leave this to a separate tool. You can use GNU parallel with `fd`, for example:
```sh
fd … | parallel --bar cmd
```

In principle, using `fd -x` can be faster than piping to `parallel`. But only if the filesystem search is the limiting factor. Which is not the case here.

I hope it's okay if we close this, but please feel free to comment.

**Comment by meandmymind** [comment]
@sharkdp 

I like @MrYakobo's idea of showing number of files currently processed. We won't lie about time, we have this information, it's really easy to render. Why not?

**Comment by sharkdp** [comment]
> Why not?

what about my second question above: https://github.com/sharkdp/fd/issues/740#issuecomment-798979678

**Comment by meandmymind** [comment]
@sharkdp 
---
## First case: many operations with logs
I guess I generally don't want my terminal to be cluttered with 10k+ lines of individual operations' logs so I want it to be disabled by default. As two ways to get this logs I would either:
* write them to file and look/search from there
* or do it the way `docker build` does: show progress bar or (file count + spent time) at the top and show last N lines of logs below

https://user-images.githubusercontent.com/24773652/128672830-df370bc9-1254-4e70-8c2b-8d1f8e3e82d2.mp4

---
## Second case: not many logs
It's ok to show logs for not a lot of files.

It's hard to define what is `many` for different cases so I would just make some behaviour default and the other not default.

**Comment by sharkdp** [comment]
Ok. I think I'd be okay with integrating this if it doesn't add a huge amount of new code.

**Comment by Anangaya** [comment]
Hey there,

I really think having a progress bar would be a fantastic addition to sd.

I recently had a task to delete over 600,000 HTML files from a HDD and chose to use sd as some smaller hyperfine tests showed it was faster than combining it with rush. Even though it was faster, the entire process still took around 2 hours!

What would have made it a smoother experience is if I could have tracked the progress live on sd itself, similar to rush --eta. I ended up resorting to voidtools everything to monitor the progress, but it would have been great to have that functionality within sd.

**Comment by Anangaya** [comment]
> by "sd" do you mean fd?
yeah my bad. I corrected it.

> How did you actually delete the files? Hopefully `-X rm`, not `-x rm`?

Well I did use `-x rm` in this case because I didn't come to my mind to test it out with `-X rm` which definitely seems faster for cases like this.
