### ISSUE TITLE
[SOLVED] fd doesn't work when using options.

### ISSUE THREAD

**Issue by rafamadriz** [sharkdp/fd#741]
**What version of `fd` are you using?**
[8.2.1-1]

If I just type `fd` it works fine *(it shows all files and directories in the current directory)*, but when I start passing options it doesn't show anything. Example: `fd --type f --hidden` doing that doesn't list anything. What am I doing wrong ? 

Also, is it normal that `fd` uses `fzf` ? I just installed `fd` and by default when I type `fd` it starts using `fzf` to list all the contents of the directory *(it's basically as I just type `fzf`)*. From what I saw on the GitHub page that's not the default behavior. Don't know why mine is doing that.

**Comment by sourlemon207** [comment]
What OS are you using and how did you install it?

**Comment by rafamadriz** [comment]
> What OS are you using and how did you install fd?
> 
> You might want to try checking where fd is located by running
> `which fd`
> and then
> `file $(which fd)`
> to make sure its not a symlink to something else

So the problem was that I had a function in my .zshrc called fd, when I typed fd it was calling the function instead of the program... 🙃 stupid me...
