### ISSUE TITLE
Search for files where parent directory has a specific name

### ISSUE THREAD

**Issue by joshy** [sharkdp/fd#744]
**What version of `fd` are you using?**
fd 8.1.1

I was wondering if it is possible to search for file named foo.txt and find all occurrences where the parent directory is bar. Is this possible with fd?

Example:
```
a/b/bar/foo.txt 
a/b/cold/foo.txt
a/d/bar/foo.txt
```
The command should match 1 and 3. 

Thanks for fd and your support. (I can run grep but I want to use fd only because the I want to use `-X`command. )

**Comment by sharkdp** [comment]
Would `-p` work for you?
```bash
fd -p 'bar/foo.txt$'
```

**Comment by joshy** [comment]
Perfect that works. Thanks a lot!
