### ISSUE TITLE
Don't show directories who also have children items

### ISSUE THREAD

**Issue by ClementNerma** [sharkdp/fd#745]
**What version of `fd` are you using?** `fd 8.2.1`

Hi there!

I've used `fd` for a bit now, and I find it to be an amazing tool. I'm currently trying to use it to generate a list of files to backup based on a list of patterns, but I'm blocked at one point.

By default, `fd` lists directories as well as their content, such as:

```shell
fd --search-path="..." Volt
```

```
Volt/
Volt/empty/
Volt/src/
Volt/src/front/
Volt/src/front/index.ts
Volt/src/main.ts
Volt/package.json
```

But when I write filters, the whole directories' names become a problem, because I don't want to backup the whole folders, only their filtered files. What I'd like to get is:

```
Volt/empty/
Volt/src/front/index.ts
Volt/src/main.ts
Volt/package.json
```

Problem being that there I can't find a way to do this. If I write a `--type file` I only get:

```
Volt/src/front/index.ts
Volt/src/main.ts
Volt/package.json
```

Note the missing `Volt/empty/` directory. Also, if I use a regular expression to match a directory name, I won't get its sub-files:

```
fd --search-path="..." Volt "^src$"
```

```
Volt/src/
```

While I'd like to get:

```
Volt/src/front/index.ts
Volt/src/main.ts
```

Is there any way to achieve this?

**EDIT:** To be clearer, what I'd like to achieve is to hide directories who are both non-empty and have children items listed.

**Comment by sharkdp** [comment]
Thank you for your request. To be honest, that sounds very specific.

> if I use a regular expression to match a directory name, I won't get its sub-files:

Have you seen the `--full-path` option?

**Comment by ClementNerma** [comment]
> Thank you for your request. To be honest, that sounds very specific.
I think too, but at the same time I think there should be a way to not have "duplicate" items in the list (as in files and their parent directories).

> Have you seen the `--full-path` option?
I don't know why but I thought to read it was to search inside a fixed directory string, but it actually solves the second problem :)

**Comment by sharkdp** [comment]
I hope it's fine if I close this. Let me know if you think otherwise.

**Comment by ClementNerma** [comment]
Well I think it could be interesting to either solve this issue or #742 (which I closed in favor of this one), as even though that's kind of a corner case it's still a bit weird to list directories _and_ their content just after. What do you think?

**Comment by sharkdp** [comment]
Does `find` have an option for this? I really think this should be handled by a separate tool (maybe the backup tool itself?).

**Comment by ClementNerma** [comment]
> Does `find` have an option for this? I really think this should be handled by a separate tool (maybe the backup tool itself?).

The thing is it would have been very convenient to have this feature built-in for such a (niche) case. What I do for now is list all files, then all directories (with `--type xxx`) and then filter out the ones who already appear in the first output (meaning they have children items). Which works fine but is not an optimal solution.

**Comment by sharkdp** [comment]
I understand, but I really don't see a way to (easily) integrate this in `fd`.

**Comment by ClementNerma** [comment]
> I understand, but I really don't see a way to (easily) integrate this in `fd`.

Oh, if this is na integration problem, then it's another thing. I was only talking about how this could be an interesting feature, but if it's hard to implement it's probably not worth it considering the very small use case.
I suggested this feature as I thought it would be trivial to implement given 'fd' shows the list of files after the directories that contain them, but if it's not the case then don't bother with it ;)
