### ISSUE TITLE
Only list text files (i.e., exclude binaries)

### ISSUE THREAD

**Issue by NightMachinary** [sharkdp/fd#749]
I want an option to only list text files (i.e., exclude binaries).

**Comment by tmccombs** [comment]
How do you define a text file? A file that only contains  ASCII characters? Only valid UTF-8 sequences? It has a text/* MIME type?  All of those would be kind of expensive to calculate. And determining the MIME type would be tricky to do in a portable way.

**Comment by NightMachinary** [comment]
[**@tmccombs**](https://github.com/tmccombs) commented on [Mar 23, 2021, 11:31 PM GMT+4:30](https://github.com/sharkdp/fd/issues/749#issuecomment-805155085 "2021-03-23T19:01:00Z - Replied by Github Reply Comments"):
> How do you define a text file? A file that only contains ASCII characters? Only valid UTF-8 sequences? It has a text/\* MIME type? All of those would be kind of expensive to calculate. And determining the MIME type would be tricky to do in a portable way.

The heuristic commonly employed is to scan for NUL characters. It can fail (e.g., when I was storing NUL-separated strings in a text file in git), but it's good enough.

**Comment by furkanusta** [comment]
I needed this functionality recently to pipe to output to fzf (with previews enabled)
I used the "file" command to filter. It seems to perform multiple checks (magic numbers, encoding, and mime type I suppose)

`fd -t f -x file | awk -F: '/ASCII text/ {print $1}'`

Though it has a significant performance overhead

**Comment by sourlemon207** [comment]
> I needed this functionality recently to pipe to output to fzf (with previews enabled)
> I used the "file" command to filter. It seems to perform multiple checks (magic numbers, encoding, and mime type I suppose)
> 
> `fd -t f -x file | awk -F: '/ASCII text/ {print $1}'`
> 
> Though it has a significant performance overhead

you might want to try using rg (ripgrep) instead such as
```rg -lU '^[\x00-\x7F]*$'```
I don't know if you can pipe a file list to rg but this approach is many times faster

**Comment by sharkdp** [comment]
> How do you define a text file? A file that only contains ASCII characters? Only valid UTF-8 sequences? It has a text/* MIME type? All of those would be kind of expensive to calculate. And determining the MIME type would be tricky to do in a portable way.

> The heuristic commonly employed is to scan for NUL characters. It can fail (e.g., when I was storing NUL-separated strings in a text file in git), but it's good enough.

I wrote a [blog post](https://dev.to/sharkdp/what-is-a-binary-file-2cf5) on this topic once :smile. I also implemented the NUL-heuristic in a [Rust library](https://github.com/sharkdp/content_inspector). It's extremely lightweight, so we could actually consider adding `text`/`binary` filters for `--type`. But I'm not 100% sold on that idea. And I haven't thought through all of the implications this would have for combinations with other (`--type`) filters.

**Comment by sharkdp** [comment]
I think this should be relatively easy to implement, if someone wants to try this.

But please note that I'm not 100% sure that we want to add this to `fd`. I'm inclined to say yes, though. Reasons for a rejection might be if this ends up being rather complicated to implement or if it conflicts with other `fd` features.

**Comment by tsoutsman** [comment]
I'd like to give this a crack. I'm fairly new to Rust and open source in general, so I have a few questions:
1. From @sharkdp s comment, I'd assume it should be implemented using `content_inspector`. Should the entire file be read in and checked or just the first n-number of bytes? I haven't worked with files or any programs where performance **actually** matters, so I genuinely have no clue about the performance implications.
2. Is the default for the `--type` option all filetypes? The default for `FileTypes` seems to suggest that the default is nothing but running `fd` without any type parameters obviously prints out results.
3. The current test setup doesn't seem to support file contents. If I were to try and add this feature, how should I go about testing it?

If this is implemented using the `--type` option, then there will be 2 more types, `binary` and `text` (obviously). Below is my proposed behaviour:

If the `file` option is added, it automatically overwrites the other two, and the results include both `binary` and `text` files regardless of whether or not they were enabled by the option. If only one of them is enabled, and `file` isn't enabled, then, obviously, it will display either `binary` or `text` based on the provided configuration. Finally, if both of them are enabled, the program behaves as if the `file` option was passed, regardless of whether the `file` option was actually given.

To implement this behaviour, I think the `files` field from `FileTypes` should be replaced with `binaries` and `text`. If `files` is passed to the program, it should just enable both fields.

---
I'm not that well versed in Rust, and definitely not familiar with this crate, so I quite possibly have missed something or made some incorrect assumptions.

**Comment by tmccombs** [comment]
>Should the entire file be read in and checked or just the first n-number of bytes

Probably the first n bytes, so that it isn't really slow if there are large files.

**Comment by sharkdp** [comment]
> From @sharkdp s comment, I'd assume it should be implemented using `content_inspector`. Should the entire file be read in and checked or just the first n-number of bytes? I haven't worked with files or any programs where performance **actually** matters, so I genuinely have no clue about the performance implications.

I agree with @tmccombs. We should probably do something similar to `diff`, reading the first 1024 bytes I think. And yes, this will nevertheless slow down a search *significantly*.

> Is the default for the `--type` option all filetypes? The default for `FileTypes` seems to suggest that the default is nothing but running `fd` without any type parameters obviously prints out results.

Hm, yes. But note this section: https://github.com/sharkdp/fd/blob/42dce35dd705d362465bbae95740374b37a79d4f/src/options.rs#L69-L71

> The current test setup doesn't seem to support file contents. If I were to try and add this feature, how should I go about testing it?

I think we could open one of the generated test files and either write some text to it, or some "binary" content (i.e. something with `\0`).

> If the `file` option is added, it automatically overwrites the other two, and the results include both `binary` and `text` files regardless of whether or not they were enabled by the option. If only one of them is enabled, and `file` isn't enabled, then, obviously, it will display either `binary` or `text` based on the provided configuration. Finally, if both of them are enabled, the program behaves as if the `file` option was passed, regardless of whether the `file` option was actually given.

Okay. And we definitely want to make sure to only run the binary-check if either `binary` or `text` is specified.

**Comment by sharkdp** [comment]
Before you invest too much time into this, maybe we should reconsider if we REALLY want to integrate this in `fd`. @NightMachinary and @furkanusta could you tell us a bit more about your use case?

**Comment by tavianator** [comment]
If you're okay with `grep`'s binary file detection, you can do something like

```shell
$ fd -t f -X grep -lI .
```

which will print the names of all non-binary, non-empty files.  I hoped that a zero-length pattern like `^` would allow it to match empty files but it stubbornly refuses.  And #410 may be an issue.

**Comment by furkanusta** [comment]
Initially, I had 
```bash
export FZF_DEFAULT_OPTS='--preview "bat --style=numbers --color=always --line-range :500 {}"'
export FZF_DEFAULT_COMMAND='fd --type f'
```
in my config file and whenever I use fzf, I would get some binary files in the list (which were not a big problem but just an inconvenience). However, as I get comfortable with both fzf and fd I decided to skip the binary file check. Because most of the time I have a rough idea of what I am searching for and quickly filtering the files is better.
Maybe others have a different use cases, but nowadays I need this functionality rarely. (Maybe rather than adding this functionality, a way to do this manually can be added to wiki or README)

**Comment by sharkdp** [comment]
@furkanusta If you are using (a recent version of) `bat` as a previewer, you should actually not have a problem with binary files. `bat` should show something like:

> [bat warning]: Binary content from file 'rg' will not be printed to the terminal (but will be present if the output of 'bat' is piped). You can use 'bat -A' to show the binary file contents.

**Comment by furkanusta** [comment]
I know, that is why I said it was more of an inconvenience rather than a problem. Since I am rarely interested in binary files I didn't want to see even the warning.
However,  the delay from the type checking was creating a significant delay. That is why I stopped that binary check and got used to the warning.

**Comment by 1n40** [comment]
How about we use `file` command to detect ascii files instead?

**Comment by sharkdp** [comment]
Ok, we haven't seen any real use case except for the minor "inconvenience". Closing this for now.

**Comment by scottchiefbaker** [comment]
I would definitely use this feature if it were available. My use case for this would be: "find all the text (code) files in this directory and it's children and pipe that to `tar` for a backup." I want to backup all my code (because that may have changed) but not my big binary files.

My code directory might have some `.jpg` files in it. Maybe an `.iso` down the road. I could use a complex extension filter I suppose but then I have to remember to update it if I add a new `.bin` type to my directory.

**Comment by rickalex21** [comment]
Might be worth a shot to see how they deal with binary files in [ripgrep](https://github.com/BurntSushi/ripgrep).

My use case is looking though code files with telescope, when using telescope in neovim I have
no need for binary files to come up when looking though a code based.

This use case can also be applied to emacs using consult to search though a code base.

**Comment by tmccombs** [comment]
Ripgrep is a little different than fd though. It has to read the entire file anyway for its main functionality. So while doing that, it can also use some heuristic to determine if a file is binary or not (such as looking for a nul byte, or a byte sequence that isn't utf8). 

However, fd doesn't currently open the file at all, because it is primarily for inspecting the filename and metadat of the file.

I suppose one option could be an option to filter files based on the extension. But then which way do you default if you don't recognize the extension, or the file doesn't have an extension.

**Comment by NightMachinery** [comment]
Using extensions is a bad idea. The file content must be checked. An extension-based solution could already be coded using `--extension` or a trivial perl filter.

**Comment by apcamargo** [comment]
I'd also welcome this suggestion. `grep` wouldn't do it for me because it can't tell if a file is executable or not (also, I assume `fd` would be much faster, since it doesn't have to read the whole file).

I couldn't find anything about how `file --mime` distinguishes between text and binary files, but maybe that's something that could be useful? Right now I'm using something similar to @furkanusta solution to find executable binaries:

```bash
fd -t x -X file --mime . | awk '$2 !~ /inode\/directory/ && $3 ~ /charset=binary/ {sub(/:$/, "", $1); print $1}'
```

**Comment by tmccombs** [comment]
@apcamargo you could do:

```
fd -t x -X grep -lI . 
```
to use fd to find executable files, then use grep to filter to those that are text files. 

Or 
```
fd -t x -X grep -LI .
```
to get binary executables.
