### ISSUE TITLE
--samefile option

### ISSUE THREAD

**Issue by gerases** [sharkdp/fd#751]
**What version of `fd` are you using?**
[paste the output of `fd --version` here]
7.0.0

Is there a way to duplicate `-samefile` option of `find`? From find's man page:

      -samefile name
              File refers to the same inode as name.

**Comment by sharkdp** [comment]
Thank you for your feedback.

There is currently no way to do this with `fd`, see https://github.com/sharkdp/fd/issues/300.

**Comment by edshamis** [comment]
```
fd -H --type l -x zsh -c "[[ $file -ef {} ]] && echo {}"
```
