### ISSUE TITLE
GUI for fd ?

### ISSUE THREAD

**Issue by Golddouble** [sharkdp/fd#753]
Is there a GUI for fd-search somewhere on the internet?
I have not found any.

Thank you.

**Comment by sergmister** [comment]
I doubt a GUI would be of much benefit to the average user. If that is something your looking, for look for other applications such as kFind.

**Comment by wolfisberg** [comment]
I am using `fd` a lot in conjunction with `rofi`, basically the gui version of piping `fd` into `fzf`.

Just pipe the `fd` output into `rofi`'s dmenu mode (or have a look at dmenu itself) and create whatever searches and lists you might need, your imagination is the limit. What I am using frequently is a PDF search:

      fd --type f -e pdf . ~ | rofi -monitor primary -keep-right -dmenu -i -p PDFS -multi-select | xargs -I {} xdg-open {}

I bound that to a shortcut. Hope this provides some inspiration.

**Comment by sharkdp** [comment]
@wolfisberg I'm also using rofi, but I hadn't thought of this `fd`-`rofi` combination so far. I think it would make a great addition to the ["Integration with other programs"](https://github.com/sharkdp/fd#integration-with-other-programs) list.

**Comment by wolfisberg** [comment]
@sharkdp Should I open a pull request with an added section to the "integration with other programs" list and provide a couple examples?

**Comment by Golddouble** [comment]
Thank you @wolfisberg.

No support for regex?
I have tried this command:
`fd --type f -HI --regex  . ~ | rofi -monitor -5 -keep-right -dmenu -i -p PDFS -multi-select | xargs -I {} xdg-open {}
`

![FD](https://user-images.githubusercontent.com/13977359/114700977-845bf500-9d22-11eb-9405-45b370206d3e.gif)

**Comment by sharkdp** [comment]
@wolfisberg That would be great!

@Golddouble If you want your search *in rofi* to support regexes, you need to enable regex search in rofi (with `-matching regex`), not in `fd`. In these examples, `fd` is basically just used to list all files.

**Comment by Golddouble** [comment]
Unfortunately exactly the same behaviour with:
`fd --type f -H  . ~ | rofi -monitor -5 -matching regex -keep-right -dmenu -i -p PDFS -multi-select | xargs -I {} xdg-open {}`

**Comment by wolfisberg** [comment]
@Golddouble Well, the `^book` regex would have to match against a **path** that starts with *book*, which can't exist. In this example, the matching is done against the entire path, that's why you don't get results.

**Comment by Golddouble** [comment]
Thank you. Yes I see. ("$" works.)
My latest command:
`fd --type d -H  --search-path / | rofi -monitor -5 -matching regex -keep-right -dmenu -i -p PDFS -multi-select -width 95 -lines 35 | xargs -I {} xdg-open {}`

**Comment by wolfisberg** [comment]
@Golddouble FYI, the `rofi -p` is the *prompt* argument, as in the message in front of the search box that rofi displays. so `-p PDFS` does not seem appropriate for your search :).

**Comment by Golddouble** [comment]
> Just pipe the `fd` output into `rofi`'s dmenu mode (or have a look at dmenu itself) and create whatever searches and lists you might need, your imagination is the limit. What I am using frequently is a PDF search:
> 
> ```
>   fd --type f -e pdf . ~ | rofi -monitor primary -keep-right -dmenu -i -p PDFS -multi-select | xargs -I {} xdg-open {}
> ```

This works great, when I start the command within a terminal. But when I create a starter, then the terminal starts for a short time and is closed immediately.

Any solution for this?

Thank you.

**Comment by wolfisberg** [comment]
What is that **starter** you mention?
Does the command run from terminal actually open the pdf in your desired reader?
What pdf reader is configured registered with xdg?

Or start deconstructing the command to fd only, then fd piped into rofi etc. and inspect the output.

**Comment by Golddouble** [comment]
This is my starter:
![Starter symbol](https://user-images.githubusercontent.com/13977359/115768275-62a9e000-a3aa-11eb-94ea-733515a0bc53.jpg)

And the command in the starter propperties:
![fd starter](https://user-images.githubusercontent.com/13977359/115768327-748b8300-a3aa-11eb-98db-b33936cf6b96.jpg)

OK. Maybe it does not start the terminal for a short time. It looks just like nothing happens, if I double click this starter.

**Comment by sharkdp** [comment]
@Golddouble This is more of a problem with your desktop environment. I don't think this issue tracker is the best place to solve the problem.

closing this as #758 has been merged.

**Comment by Golddouble** [comment]
In the meantime I have found the solution:

1. Create a new file "/home/Golddouble/.bin/Fd-Find.sh"
2. The content of this file should be:
`fd --type f -H --search-path / | rofi -monitor -5 -matching regex -keep-right -dmenu -i -p Datei -multi-select -width 95 -lines 35 | xargs -I {} xdg-open {}`
3. Make "Fd-Find.sh" executable
4. Replace the "command" in the "starter" through:
`/home/Golddouble/.bin/Fd-Find.sh`

-> Works now.

**Comment by stellarpower** [comment]
Anyone looking for a GUI, catfish is pretty good.
