### ISSUE TITLE
Fd - not locating one file

### ISSUE THREAD

**Issue by xircon** [sharkdp/fd#755]
fd 8.2.1

I have a weird problem.  I am having an issue with emacs and thought I would use fd to find all occurrences of a file called places.  But it doesn't find one instance:
```
ls -la pl*
.rw-r--r-- xircon xircon 9.7 KB Mon Apr  5 12:02:59 2021 places
.rw-r--r-- xircon xircon 9.7 KB Mon Apr  5 09:23:52 2021 places-old
.rw-r--r-- xircon xircon   0 B  Mon Apr  5 11:55:35 2021 placesp

fd places
places-old
placesp

locate places | grep emacs-term
/home/xircon/dotfiles/emacs-term/places
/home/xircon/dotfiles/emacs-term/places-old
/home/xircon/dotfiles/emacs-term/placesp
```
Just can't understand it, `~/dotfiles/emacs-term/places` does not show up.  What am I doing wrong?

**Comment by sourlemon207** [comment]
I was unable to reproduce this issue
this is what i get

```
/usr/bin/ls -la pl*
-rw-r----- 1 jack jack 0 Apr  5 13:44 places
-rw-r----- 1 jack jack 0 Apr  5 13:44 places-old
-rw-r----- 1 jack jack 0 Apr  5 13:44 placesp

fd places
places
places-old
placesp
```

**Comment by xircon** [comment]
Apologies for the late reply, been a busy week.  If I create the files in another directory fd finds them.  If I copy the directory to another directory it cannot, I am starting to suspect some sort of btrfs corruption.  Am still working on it.

**Comment by tavianator** [comment]
Any chance `fd -HI places` finds it?  https://github.com/sharkdp/fd#fd-does-not-find-my-file
