### ISSUE TITLE
Not possible to combine file extension filter with a search path

### ISSUE THREAD

**Issue by terjr** [sharkdp/fd#756]
**Describe the bug you encountered:**
I have a build folder (named `_build`) that is gitignored. Quite often I want to do a file extension search like this:
```
$ fd -e hubba
visible/file.hubba
```
...and sometimes I want to include files in my build folder too:
```
$ fd -e hubba -I
_build/file.hubba
visible/file.hubba
```

This is all good. However, if I want to pick just one of them, this does not work:
```
$ fd -e hubba visible
<nothing>
$ fd -e hubba _build
<nothing>
```

Doing the same trick with a normal regex works:
```
$ fd -I '.*\.hubba' visible
visible/file.hubba

$ fd -I '.*\.hubba' _build
_build/file.hubba
```

**Describe what you expected to happen:**
I expect the following two commands to list one file each:
```
$ fd -e hubba -I _build
_build/file.hubba

$ fd -e hubba -I visible
visible/file.hubba
```

**What version of `fd` are you using?**
fd 8.2.1

**Which operating system / distribution are you on?**
```
$ uname -srm
Linux 5.10.0-2005-oem x86_64
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Comment by lespea** [comment]
I believe you need to include the search term as well... so like `fd . -e hubba visible`

**Comment by terjr** [comment]
Right. That works, and even makes the `-I` argument superfluous.
