### ISSUE TITLE
.gitignore exclusion is not processed

### ISSUE THREAD

**Issue by abstractlyZach** [sharkdp/fd#757]
**Describe the bug you encountered:**
`.gitignore` files allow users to ignore large globs and then specify exclusions from those globs: https://stackoverflow.com/questions/987142/make-gitignore-ignore-everything-except-a-few-files

`fd` respects the large glob, but doesn't respect the exclusion. For example, if this is the gitignore:
```
# .gitignore

# Ignore everything
*

# But not these files...
!abc.txt
```
`fd` does NOT return `abc.txt`

**Describe what you expected to happen:**
`fd` should return `abc.txt`

**What version of `fd` are you using?**
```fd 8.2.1```

**Which operating system / distribution are you on?**

```
~
➜ uname -srm
Linux 5.10.23-1-MANJARO x86_64

~
➜ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.0
Codename:	Ornara
```

**Comment by sharkdp** [comment]
Thank you for reporting this. I can not confirm this:

```bash
▶ mkdir issue-757; cd issue-757
▶ git init
▶ touch abc.txt        
▶ fd
abc.txt
▶ echo '*' > .gitignore                         
▶ fd
▶ echo '!abc.txt' >> .gitignore 
▶ fd
abc.txt
```

**Comment by sharkdp** [comment]
Closing this for now to get the inbox clean. Let me know if there is somethign we can do.
