### ISSUE TITLE
Set up Travis to upload binaries for every release

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#76]
This already works for Windows builds (via Appveyor, see `appveyor.yml`). It would be great if we could also upload Linux and macOS tarballs, as well.

**Comment by sharkdp** [comment]
ripgrep and tokei seem to do something like this:

* https://github.com/BurntSushi/ripgrep/blob/master/.travis.yml
* https://github.com/Aaronepower/tokei/blob/master/.travis.yml

**Comment by matematikaadit** [comment]
I'm interested in submitting PR for this. Will try to working it out first in a fork and submit it later.

**Comment by sharkdp** [comment]
> I'm interested in submitting PR for this. Will try to working it out first in a fork and submit it later.

Sounds great!

**Comment by matematikaadit** [comment]
Sorry for the slow progress. I've been experimenting and figuring stuff out on building rust project on travis. And I think I found an issue regarding the current `.travis.yml` setting. Opening issue #132 and planning working on that first.
