### ISSUE TITLE
fd cant find symbolic links to directories

### ISSUE THREAD

**Issue by 06kellyjac** [sharkdp/fd#761]
**Describe the bug you encountered:**

```
λ fd
LICENSE
README.md
ci.nix
default.nix
flake-compat.nix
flake.lock
flake.nix
λ fd -t d
λ fd -t e
λ fd -t f
LICENSE
README.md
ci.nix
default.nix
flake-compat.nix
flake.lock
flake.nix
λ fd -t l
λ fd -t p
λ fd -t s
λ fd -t x
λ fd -t d -t l
λ ls -l result*
lrwxrwxrwx jk users 53 B Wed Apr 21 09:41:09 2021  result ⇒ /nix/store/ggfbxx26mnv3mmxhqi277g8l2lnqgm8j-dmenu-5.0
lrwxrwxrwx jk users 60 B Wed Apr 21 09:41:09 2021  result-2 ⇒ /nix/store/scn64qml01s0vmla0vp9yvisfa2wj05z-dwm-git-20210329
lrwxrwxrwx jk users 59 B Wed Apr 21 09:41:09 2021  result-3 ⇒ /nix/store/yrlr08ja4r8p3ik8s8dw04hhqjcs41ps-st-git-20210319
```

I want to find all the `result*` symlink dirs on my machine

**Describe what you expected to happen:**

I expect one of the file types to be able to find symbolic links to directories

Maybe it should be added as a new type?

Maybe it is supported already and I'm doing something dumb

**What version of `fd` are you using?**

```
λ fd --version
fd 8.2.1
```

**Which operating system / distribution are you on?**

```
[nix-shell:~]$ uname -srm; lsb_release -a
Linux 5.11.13 x86_64
No LSB modules are available.
Distributor ID:	NixOS
Description:	NixOS 21.05 (Okapi)
Release:	21.05.20210419.0a5f5ba
Codename:	okapi
```

**Comment by sharkdp** [comment]
Have you seen this section in the README? https://github.com/sharkdp/fd#fd-does-not-find-my-file

**Comment by 06kellyjac** [comment]
That did it. Sorry I should have looked harder

**Comment by sharkdp** [comment]
No worries, glad it was resolved.
