### ISSUE TITLE
Greedy/Non-greedy issue

### ISSUE THREAD

**Issue by ngirard** [sharkdp/fd#762]
Using latest precompiled binary on Ubuntu 20.04.

Using
```sh
cat > f <<EOF
Dummy line
Key: Value
EOF
```
I'm sumbling upon this weird behaviour: 
```sd '^([^:]+):' '`$1`:' < f```
gives
```
`Dummy line
Key`: Value
```

while I expected
```
Dummy line
`Key`: Value
```

The desired output is obtained by adding '\n' to the exclusion set:
```sd '^([^:\n]+):' '`$1`:' < f```

but the `\n` shouldn't be needed here.
I'm suspecting it's the same bug that other people have reported [here](https://github.com/dalance/amber/issues/75) and [there](https://github.com/nevdelap/ned/issues/55) with various tools written in Rust.

@sergeevabc, if you don't mind me asking, would you please confirm that the problem I'm reporting has the same origin as the others, in your opinion?

If that's the case, that's not reassuring *at all*, since I'm heavily depending on the reliability of my regex-related tools.

Notably, Ripgrep doesn't seem to be affected:

```sh
rg '^([^:]+):' -r '`$1`:' f
2:`Key`: Value
```

**Comment by ngirard** [comment]
@sharkdp Oh jeez... what a mess... sorry about that. 
I've copied the text source of the issue, perhaps you could delete it ? In that case, feel free to do so.

**Comment by sharkdp** [comment]
No worries 🙂
