### ISSUE TITLE
Double star globbing

### ISSUE THREAD

**Issue by shyun3** [sharkdp/fd#764]
Hello, I noticed that the `-g` option doesn't seem to support globbing with `**` like with `git grep` or the `-g` option for `rg`. Could you add something like this?

Examples:
```
git grep -l . "**/dir/file*"
rg --files -g "**/dir/file*"
```

**Comment by sharkdp** [comment]
It does, but you need to use `-p`, `--full-path`:
```
    -p, --full-path
            By default, the search pattern is only
            matched against the filename (or directory
            name). Using this flag, the pattern is
            matched against the full path.
```

But be aware that you might need to use `**/` in the beginning because it will try to match on absolute paths.

**Comment by sharkdp** [comment]
Please let us know if you think the documentation can be improved.

**Comment by shyun3** [comment]
Oh, I didn't know that about `-p`. I think it would be helpful if there was an example of using this option with `**` somewhere in the documentation.
