### ISSUE TITLE
How to display a leading ./ (dot slash) in search results?

### ISSUE THREAD

**Issue by mamiu** [sharkdp/fd#765]
**What version of `fd` are you using?**
`fd --version`: fd 7.4.0

How to show a leading `./` (dot slash) in search results?

Find does it by default but is also able to omit the leading `./` by using an asterisk (`*`) as search pattern.

**Comment by sharkdp** [comment]
> How to show a leading `./` (dot slash) in search results?

It's not possibly currently. What do you need this for? Would `--absolute-path` also satisfy your needs?

> Find does it by default but is also able to omit the leading `./` by using an asterisk (`*`) as search pattern.

I don't think so. It always shows a trailing slash. Are you maybe calling `find *`? That is probably not what you want. Your shell will expand the `*` to all files/directories in the current directory. Causing `find` to start a search at every given argument.

**Comment by sharkdp** [comment]
Closing this for now as we're probably not implementing this.

**Comment by sharkdp** [comment]
well.. maybe we will. I suggest you follow #760
