### ISSUE TITLE
support for longer argument lists with `-X`?

### ISSUE THREAD

**Issue by githorse** [sharkdp/fd#766]
When I try to use `-X` on a giant argument list, it fails:

```
$ fd /giant/directory --type f -X stat 
[fd error]: Problem while executing command: Argument list too long (os error 7)
```

Ok, makes sense, since my argument list is 100k files long. But `find -exec` actually works here:

```
$ find . -type f -exec stat {} +
# seems to work
```

AFAIK the `+` means that all results are passed to `stat`, so it seems that `stat` actually supports argument lists that long. Or maybe `find` is batching them up somehow? Using `find -exec +` is way faster than `find -exec \;`, which passes them one-by-one, so it's doing something different for sure. 

Would it be possible for `fd` to support (ridiculously) long argument lists as well?

**Comment by sharkdp** [comment]
Thank you for reporting this. Please see #410.

**Comment by sharkdp** [comment]
> AFAIK the `+` means that all results are passed to `stat`, so it seems that `stat` actually supports argument lists that long. Or maybe `find` is batching them up somehow?

`find` is calling the external multiple times, if that is needed (if the argument list is too long). So yet, it's executing in batches. `fd` should do the same for `-X`.

> Using `find -exec +` is way faster than `find -exec \;`, which passes them one-by-one, so it's doing something different for sure.

Exactly. `-exec … +` is like `fd`s `-X`/`--exec-batch`. A normal `-exec` without the `+` is like `fd`s `-x`/`--exec`.
