### ISSUE TITLE
--glob does not find the file

### ISSUE THREAD

**Issue by balazser** [sharkdp/fd#769]
**Describe the bug you encountered:**
--glob does not find the file according to these scenarios:

## create test file env
```
mkdir -p a/b/; touch a/b/alma.txt
```

## use fd to find alma.txt
```
fd --glob --full-path 'a/b/*.txt';
fd --glob --full-path '**/*.txt'; # it works
a/b/alma.txt
fd --glob --full-path '*/*/*.txt';
fd --glob --full-path '*/*/alma.txt';
fd --glob --full-path '*.txt';
```

**Describe what you expected to happen:**
prints `a/b/alma.txt`
or can find some documentation about fd-find's glob valid patterns

**What version of `fd` are you using?**
fd 8.2.1

**Which operating system / distribution are you on?**
**uname -srm**
Linux 5.10.15-1-MANJARO x86_64
**lsb_release -a**
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.2.1
Codename:       Nibia

**Comment by balazser** [comment]
just found [this comment](https://github.com/sharkdp/fd/issues/764#issuecomment-835494645) which makes it work. maybe we could add it to the README.

> But be aware that you might need to use **/ in the beginning because it will try to match on absolute paths.

**Comment by sharkdp** [comment]
Thanks for figuring this out yourself! Yes. That should be included in the documentation (help text and possibly README). That's why the other ticket is still open. Any help is very much appreciated.

I'm going to close this ticket as a duplicate, hope that's fine.
