### ISSUE TITLE
Add option/flag to escape spaces in file names returned as results

### ISSUE THREAD

**Issue by CatalinPuscoci** [sharkdp/fd#774]
I noticed that if I have a file that contains spaces, and I want to use xargs, a folder with spaces is not escaped properly and it will try to pass each separate word to xargs. See the picture below
![image](https://user-images.githubusercontent.com/32127810/120904753-75286200-c656-11eb-812f-302ed4eeae8a.png)

I know folders with spaces are stupid, but maybe I think it could be potentially more useful than it seems.

I hope this isn't a duplicate, I tried searching the issues for similar stuff.

**Comment by CatalinPuscoci** [comment]
using -X works on files with spaces tho, so there's that. I guess there is an option.  Close this issue if you think that's good enough :p

**Comment by tmccombs** [comment]
There is also the `-0/--print0` option which uses the NUL character to delimit results. And many commands, including xargs have options to accept nul-delimited input. From your example you could do:

```
fd -0 ayy | xargs -0 du -sh
```

And if we really need the arguments to be shell-safe, you can do something like:

```
fd ayy -X printf "%q\n"
```

**Comment by sharkdp** [comment]
This is also described in the documentation: https://github.com/sharkdp/fd#using-fd-with-xargs-or-parallel

@CatalinPuscoci Feel free to suggest improvements to the docs.
