### ISSUE TITLE
.fdignore not working in Windows10 when installed using Chocolatey

### ISSUE THREAD

**Issue by echaya** [sharkdp/fd#776]
**Describe the bug you encountered:**

Per the readme.md,

> If you want fd to ignore these patterns globally, you can put them in fd's global ignore file. This is usually located in ~/.config/fd/ignore in macOS or Linux, and %APPDATA%\fd\ignore in Windows.

I've recently installed latest fd (8.2.1) with Chocolatey on windows 10, and fd binary is installed into the following path:

c:\ProgramData\chocolatey\lib\fd\tools\fd.exe

Since then I have tried to put .fdignore in the following folders but neither worked:

c:\Users\XXXXX\AppData\Local\fd\ignore\\.fdignore
c:\Users\XXXXX\AppData\Roaming\fd\ignore\\.fdignore
c:\ProgramData\chocolatey\lib\fd\tools\ignore\\.fdignore
c:\ProgramData\chocolatey\lib\fd\ignore\\.fdignore

within my .fdignore file i only have one line:

`*.md`

**Describe what you expected to happen:**

when using in PowerShell / nvim (work together with fzf.vim), `*.md` files are still in the output while the file type should be 'ignored'

**What version of `fd` are you using?**
fd 8.2.1

**Which operating system / distribution are you on?**
windows 10

**Comment by sharkdp** [comment]
As the documentation says, the file path should be:
```
%APPDATA%\fd\ignore
```
i.e.:
```
c:\Users\XXXXX\AppData\fd\ignore
```

That's the full path to the (text) file, not a directory name.

**Comment by echaya** [comment]
Thanks Sharkdp!  I've tried to put the `ignore` file in the following folders but still no luck:

c:\Users\XXXXX\AppData\fd\ignore
c:\Users\XXXXX\AppData\Roaming\fd\ignore
c:\Users\echay\AppData\Local\fd\ignore

**Comment by echaya** [comment]
Thanks Sharkdp!  it is working after putting the `ignore` file in the following path. all good now :D

c:\Users\XXXXX\AppData\Roaming\fd\ignore
