### ISSUE TITLE
fd ignores .github directory - include option available?

### ISSUE THREAD

**Issue by maheshsundaram** [sharkdp/fd#780]
**What version of `fd` are you using?**
fd 8.1.1

By default fd ignores hidden directories, however I would like it to not ignore the `.github` directory. If I use the `--hidden` option, then it also includes `.git` which I don't want. I haven't seen an option available to explicitly include a directory - is that possible? Or is there a combination of options that would mean `ignore vcs but include other hidden directories`? 

Thank you!

**Comment by sharkdp** [comment]
Hm. I think you could use `--hidden` but then `--exclude .git`, right?

**Comment by maheshsundaram** [comment]
@sharkdp Thanks for your reply! Yes I had thought of that but I don't want to include other hidden folders and files that are ignored by version control, so I thought there might be an easier way. No worries though if not

**Comment by sharkdp** [comment]
I think you could also list the .github folder as an additional search path. There is no other way, unfortunately.

**Comment by cpdean** [comment]
Requesting a feature, but would it be possible to have a file to add default CLI arguments to `fd` invocations? ripgrep supports a [file-based config](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file) for this in `~/.ripgreprc`.

That way a `~/.fdrc` could have

```
--hidden
--exclude .git
```

That are added to all invocations of `fd`.

**Comment by sharkdp** [comment]
please see #362
