### ISSUE TITLE
--owner does not recognize my username or group

### ISSUE THREAD

**Issue by eflyon** [sharkdp/fd#781]
**Describe the bug you encountered:**

I get errors about my user and group not being recognized when I try to use them in an --owner search.  Some users and groups are recognized, which appear to be only those described in `/etc/passwd` or `/etc/group` (root, service users).  My user and group come from Active Directory.
```
elyon$ fd -o root
foo/baz
elyon$ fd -o elyon
[fd error]: 'elyon' is not a recognized user name
elyon$ fd -o :foobar
[fd error]: 'foobar' is not a recognized group name
elyon$ fd -o sssd . /etc
/etc/sssd
elyon$ id
uid=14485(elyon) gid=14034(foobar)
```

**Describe what you expected to happen:**
Expected success, as with sssd in example above.

**What version of `fd` are you using?**

fd 8.2.1 (from fd-v8.2.1-x86_64-unknown-linux-musl.tar.gz in Releases)

**Which operating system / distribution are you on?**

Linux 3.10.0-1160.31.1.el7.x86_64 x86_64
Red Hat Enterprise Linux Workstation 7.9 (Maipo)

**Comment by tmccombs** [comment]
fd uses the [rust-users crate](https://github.com/ogham/rust-users) to lookup the user, and that in turn calls `getpwnam_r`. I'm not sure why that wouldn't return the uid for your user.

**Comment by eflyon** [comment]
As you suggest, it appears to be a musl/rust-users problem.  I did a build with glibc (couldn't use the released one because it required a newer glibc than the target system provided), and the problem went away.

https://github.com/ogham/exa/issues/671#issuecomment-869771928 has more detail.
