### ISSUE TITLE
fd cannot find a file with some extension

### ISSUE THREAD

**Issue by huapy** [sharkdp/fd#784]
**What version of `fd` are you using?**
fd 7.4.0

I used fd to find all wks extension files in Yocto poky path. I also git cloned meta-raspberrypi path in poky as a layer.

`fd -e wks` skipped meta-raspberrypi path.
But if I cd to meta-raspberrypi path and execute `fd -e wks`, fd will find the wks file in this path.

Is there any consumption that fd will skip some path?

**Comment by sharkdp** [comment]
yes: https://github.com/sharkdp/fd#fd-does-not-find-my-file

**Comment by huapy** [comment]
thanks a lot, this resolve my question.
