### ISSUE TITLE
cannot find files, fd thinks the file is a invalid directory

### ISSUE THREAD

**Issue by leoliu0** [sharkdp/fd#786]
fd fails to find certain files like pdfs in my case. 
"$ fd" returns nothing.
"$ fd *.pdf" 
returns [fd error]: Search path 'xxx.pdf' is not a directory.

output of "$ file xxx.pdf" : 
xxx.pdf: PDF document, version 1.7, 27 pages

output of the unix find "$ find" : 
./xxx.pdf

**Describe what you expected to happen:**
fd should return the pdf

**What version of `fd` are you using?**
fd 8.2.1

**Which operating system / distribution are you on?**
I am using Arch linux
Unix:    paste the output of `uname -srm` and `lsb_release -a` here.
Linux 5.12.13-arch1-2 x86_64

LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a

**Comment by tmccombs** [comment]
For the first problem (no output for `fd`) I'll refer you to https://github.com/sharkdp/fd#fd-does-not-find-my-file. My guess is your files are gitignored.

For the second problem, what is happening is your shell is expanding "*.pdf" to multiple files, and fd is interpreting the first as the pattern and the second as the directory to search in, but the pdf file isn't a directory so it gives you the error listed.  What you probably meant to do was `fd -g '*.pdf'`.

**Comment by leoliu0** [comment]
Oh, Thank you! I did not think fd would actually use the .gitignore, even it is in the parent directory (the folder I am searching in child directory of a git repo). Thank you for pointing this out!
