### ISSUE TITLE
Feature: Add a --sort flag so that output is ordered as if piped through `sort`

### ISSUE THREAD

**Issue by zachriggle** [sharkdp/fd#789]
`fd` is great and I use it on my day-to-day.

Unfortunately, by virtue of being heavily multi-threaded, its output is not sorted.

Piping through `sort` removes coloring (by default) and using `--color=always` is a small barrier.

It would be nice if there were a way to cause `fd` to traverse the directory tree in a sorted fashion (while still being multi-threaded) or otherwise sort its output.

**Comment by sharkdp** [comment]
Please see #324 and #196. We should probably document this better.

**Comment by tompazourek** [comment]
As noted above, the current recommended way to achieve sorted results is to use `--list-details` (or `-l` for short).

However, that seems to do more things than just sorting, and also does not work at all on Windows unless using Cygwin (which is a big limitation, at least for me).

I wish `fd` had flags like `--sort` or `--sortr` that [ripgrep](https://github.com/BurntSushi/ripgrep) has. I think that would be much cleaner solution to the issue. Also, ripgrep can do these things on Windows without needing Cygwin, and is written in Rust as well. Maybe there can be some inspiration as to how to achieve this in a multi-platform way?

As for me, I'm using this on Windows, and I don't plan to start using Cygwin, so I just pipe to `sort` and accept that the colors get lost...

**Comment by your-diary** [comment]
@tompazourek 

> I wish fd had flags like --sort or --sortr that [ripgrep](https://github.com/BurntSushi/ripgrep) has. I think that would be much cleaner solution to the issue.

As `ripgrep`'s `--sort` options forces `ripgrep` to work in a single thread, it's not a magic. So `-j 1` is essentially the same, I think.

> *Note that sorting results currently always forces ripgrep to abandon parallelism and run in a single thread.* (from `man rg`)
