### ISSUE TITLE
Command 'fd' not found - Ubuntu 20.04.2

### ISSUE THREAD

**Issue by hallmerle** [sharkdp/fd#791]
**Describe the bug you encountered:**

After installing fd-find either via apt on the command line or through Synaptic, I get:

Command 'fd' not found, but can be installed with:

sudo apt install fdclone

...which appears to be some other program entirely.

I did, also, try linking the fd command per the README file for installing on Ubuntu, but I get the same result.

**Describe what you expected to happen:**

Expected the 'fd' command to work after installing fd-find

**What version of `fd` are you using?**

Synaptic says, 7.4.0-2build1

**Which operating system / distribution are you on?**

Linux 5.11.0-7614-generic x86_64
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

**Comment by tmccombs** [comment]
On ubuntu and other debian based distros the executable is called `fdfind`. The reason being there was a preexisting package with an executable called fd. You can create an alias or symlink to get the "fd" name

**Comment by hallmerle** [comment]
Thank you!  But with regards to the link, that's what I thought this
expression from the README Installation notes was for:

ln -s $(which fdfind) ~/.local/bin/fd

And it did create the link, which appears to follow through correctly:

$ ls -l ~/.local/bin/fd
lrwxrwxrwx 1 family family 15 Jul 10 20:57 /home/family/.local/bin/fd ->
/usr/bin/fdfind
$ ls /usr/bin/fdfind
/usr/bin/fdfind
$ ls -l /usr/bin/fdfind
lrwxrwxrwx 1 root root 19 Mar 22  2020 /usr/bin/fdfind ->
../lib/cargo/bin/fd
$ ls -l /usr/lib/cargo/bin/fd
-rwxr-xr-x 1 root root 2406944 Mar 22  2020 /usr/lib/cargo/bin/fd

But I still get the "Command 'fd' not found..." result.

'fdfind' does work, of course, now that I know that, but still might be
helpful to know why 'fd' doesn't work.

**Comment by tmccombs** [comment]
Is `~/.local/bin/fd` in your PATH environment variable?

**Comment by hallmerle** [comment]
Wasn't.  But after an hour of trying to figure out how to do so properly, I
believe it is now:

$ echo "$PATH"
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/family/.local/bin/fd
$ fd wallpaper

Command 'fd' not found, but can be installed with:

sudo apt install fdclone

...but I get the same result.

And, just to be sure, I did test the 'fd' command using the full path to
make sure it works.  And it does.

$ .local/bin/fd wallpaper
Pictures/Wallpapers

**Comment by tmccombs** [comment]
Ah the path in PATH needs to be .local/bin noy .local/bin/fd. It is a folder to search for executables in, not the actual executable.

**Comment by hallmerle** [comment]
Hah!  Well, of course.  That should've occurred to me when I used the full
command path.

Should this PATH process be added to the README in addition to the link
information?  Just a thought.

Thanks much for your help!

**Comment by sharkdp** [comment]
Yes, thanks. Let's add something like "Make sure that `$HOME/.local/bin` is in your `$PATH`" to the README.

**Comment by Kristinita** [comment]
**Type: Additional information** ➕

For Travis CI Jammy (Ubuntu Jammy Jellyfish 22.04.3 LTS) [**the correct command to add a symbolic link is**](https://app.travis-ci.com/github/Kristinita/SashaTravis/builds/268175013#L217):

```text
sudo ln --symbolic $(which fdfind) /usr/local/bin/fd
```

Changes:

1. `sudo` required.
1. Path. `~/.local/bin/fd` is a non-existent path `/home/travis/.local/bin/fd` on Travis.

Thanks.

**Comment by yiqiangjizhang** [comment]
> ```
> sudo ln --symbolic $(which fdfind) /usr/local/bin/fd
> ```

This solved it for me as well on WSL Ubuntu 22.04
