### ISSUE TITLE
Feature: --changed-{newer, older}-than should support files

### ISSUE THREAD

**Issue by zachriggle** [sharkdp/fd#793]
One useful feature of GNU find that `fd` does not have is the `-newer` flag, which only emits files which are newer than the provided file.

It might require a new flag (since it's possible that a file may be named e.g. "2weeks") but I think it would be nice to have.

Note for anybody else looking for this, you can achieve the same effect with:

```
$ fd --change-newer-than "$(date -jnr $FILENAME '+%Y-%m-%d %H:%M:%S')"
```

Thanks!

**Comment by sharkdp** [comment]
Thank you for the request. I think I'm going to decline this, as I don't want to add a new command-line option for such a small use case, especially if there is a reasonable workaround. Maybe this could be added to the docs (https://github.com/sharkdp/fd#integration-with-other-programs)
