### ISSUE TITLE
How to use -x

### ISSUE THREAD

**Issue by Fujiwara-Chika** [sharkdp/fd#796]
**What version of `fd` are you using?**
fd 8.2.1

`fd -e png -x cjpeg -quality 95 {} > {.}.jpg`

this output only one picture named `{.}.jpg`

`fd -e png -x sh -c "cjpeg -quality 95 {} > {.}.jpg"`

this output only two then stopped.

what's wrong with it? how should I write?
> EXAMPLES

     This example compresses the PPM file foo.ppm with a  quality
     factor of 60 and saves the output as foo.jpg:

          cjpeg -quality 60 foo.ppm > foo.jpg

**Comment by tmccombs** [comment]
The > redirection is part of the shell not part of the command. So your first command is writing the output from fd to a file called "{.}.jpg" . The second one looks like it should work.

**Comment by Fujiwara-Chika** [comment]
> The > redirection is part of the shell not part of the command. So your first command is writing the output from fd to a file called "{.}.jpg" . The second one looks like it should work.

yes, it should work but didn't

**Comment by tmccombs** [comment]
Maybe try replacing "sh -c " with echo so you can see what commands it is trying to run

**Comment by Fujiwara-Chika** [comment]
<img width="714" alt="iShot2021-07-18 03 17 49" src="https://user-images.githubusercontent.com/44722787/126047426-3dbc3306-f59d-44ad-86ba-ca019085f168.png">
<img width="714" alt="iShot2021-07-18 03 18 26" src="https://user-images.githubusercontent.com/44722787/126047424-9dee878f-80e7-49b9-a444-9283f1e46153.png">
<img width="714" alt="iShot2021-07-18 03 18 08" src="https://user-images.githubusercontent.com/44722787/126047425-c33a4d7e-8091-480b-b936-516ebd537163.png">

then I renamed those to image+numer, it worked. maybe filename is to blame :(

**Comment by Fujiwara-Chika** [comment]
maybe space in filename is not allowed for cjpeg

**Comment by Fujiwara-Chika** [comment]
oh, I see, `fd -e png -x sh -c "cjpeg -quality 95 '{}' > '{.}.jpg'"`

**Comment by gingerbeardman** [comment]
Thanks for this discussion!

I think the documentation would benefit from this sort of example of a good way to execute more than one command using the matched filename.

**Comment by sharkdp** [comment]
The problem is that these type of commands are prone to fail. If a filename contains a `'` character, you will get "shell injection"-type errors. I don't think we want to recommend sth. like this in the official documentation. Note that there is a safe way to do this though, by passing the filename as an additional command to `sh`. Can't remember the exact syntax right now.
