### ISSUE TITLE
Add option for grouping directories at the top

### ISSUE THREAD

**Issue by henriquehbr** [sharkdp/fd#798]
`ls` already has something like this:

```
--group-directories-first
    group directories before files;
```

Basically what it would do is re-order `fd` output for displaying directories grouped at the top, before files, example below:

```
# before

a-file
b-folder-1
b-folder-2
c-file

# after (with -G)

b-folder-1
b-folder-2
a-file
c-file
```

> The flag for this could be `-G`, as `-g` is already being used as the `--glob` option, and the description on the docs

**Comment by sharkdp** [comment]
Thank you very much for your contribution!

This is similar to a `--sort` option that we decided not to implement for various reasons (see #324, for example). What you can do is to pipe to `ls -G`:
```
fd … -X ls -lhd --color=always --group-directories-first
```

**Comment by henriquehbr** [comment]
Many thanks @sharkdp, it worked!
