### ISSUE TITLE
mimicking "find" a bit more

### ISSUE THREAD

**Issue by mkrier** [sharkdp/fd#828]
fd syntax is like this:

fd passwd /etc

in standard "find" it would be:

find /etc -name "passwd"

So, in find the directory comes first, followed by the term; so you decided to do it backwards. 

I mean, I know you're not trying to be *identical* to find, but maybe try and mimic as much as possible. 

A (great) designer cited an old adage to me "'intuitive' is a synonym for 'familiar'".

Cool idea for a command tho, thanks, gl!

**Comment by sharkdp** [comment]
We *do* try to follow `find` where reasonable/possible. But this is one convention that I did not want to adopt. The main reason is that I often want to start my search in the current directory. I would say at least 80% of the time. `fd` allows me to simply type `fd pattern` whereas the `find` convention would require me to specify `.` for the current directory (`fd . pattern`).
