### ISSUE TITLE
Search xattrs

### ISSUE THREAD

**Issue by shakna-israel** [sharkdp/fd#830]
Several partition formats support extended attributes, like ext4 & NTFS.

The normal `find` ignores all of these tags, but could `fd` conditionally support searching over them, if the filesystem supports them?

**Comment by sharkdp** [comment]
Thank you for your request. What would be a usecase for this?

**Comment by sharkdp** [comment]
I think this should rather be left to an external tool. Thank you for your request.

**Comment by berney** [comment]
Different file systems (and operating systems) support different extended attributes. For linux the chattr man page lists a bunch.
https://man7.org/linux/man-pages/man1/chattr.1.html#ATTRIBUTES.
For Ext4 FS it supports these extended attributes https://man7.org/linux/man-pages/man5/ext4.5.html#FILE_ATTRIBUTES.

A file/directory could be marked as immutable, etc. Being able to use `fd` directly to find these would be nice.
Currently we have to do something like `fd -X lsattr -d | grep '^----i---------e------- '` to find files/directories with (only) Immutable and Extents xattrs.

**Comment by cgzones** [comment]
A special case for extended attributes is the SELinux security attribute (`security.selinux`). Similar to find(1)'s `--context` option this can be used to find files with a particular context, e.g. unlabeled files or files with a context mentioned in a SELinux denial message.

**Comment by Evidlo** [comment]
I'm surprised to find this closed, as I thought this is exactly the sort of thing that would belong in fd.

**Comment by rsmirnov90** [comment]
@sharkdp 

Just echoing some of the other sentiment here to hopefully reopen this... 

I feel the initial sample usecase provided might not have been the best illustration. The purpose of xattr's is **not** "yet another way to store arbitrary information about files"; this is a filesystem-level feature and is used for many different low-level operations, including critical functionality on some mainstream operating systems and SELinux on Linux.

I think it would be fantastic for `fd` to support it...

**Comment by blueforesticarus** [comment]
I think, and have thought ever since I was a kid, that xattrs should be used for alot more things than they are

**Comment by blueforesticarus** [comment]
Implementing this was fairly easy. 

@sharkdp I would appreciate if you would reconsider this. An xattr based workflow would supplement ignore file based search quite well. 

I even think it is worth considering if there should be a default here. Perhaps the freedesktop.org [recommendation](https://www.freedesktop.org/wiki/CommonExtendedAttributes/) of `user.xdg.robots.index=false`, or supporting an env variable like XATTR_IGNORE. My current patch does both.
