### ISSUE TITLE
how to use fd inside neovim.

### ISSUE THREAD

**Issue by Trid-collab** [sharkdp/fd#832]
I am using the latest nightly version of neovim and have installed fd using my package manager. However I am unable to use fd instead of "find" inside neovim.

Could you please help

**Comment by tmccombs** [comment]
Which os/distribution are you using? And how are you trying to use fd inside of neovim? My first guess would be your package manager installed it as fd-find (as is the case for debian based distros) and neovim doesn't use your shell aliases.

**Comment by Trid-collab** [comment]
@tmccombs I am using Ubuntu 20.04 on WSL. I have installed fd-find in Ubuntu and is working fine, when I type fd. I wanted to understand how do I get it to work in neovim -whether I need to install the fd-find from this repository using my neovim package manager like "packer" - the same process we use for ripgrep.

Also I have tried putting the following lines in my vimrc which came across in the samoshkin/vim-find-files plugin
This doesn't seem to work either
```
"Or Use sharkdp/fd as a backend
" let g:find_files_findprg = 'fd --hidden $* $d'
```

**Comment by tmccombs** [comment]
The name of the executable in the ubuntu package is `fdfind` not `fd`. See https://github.com/sharkdp/fd#on-ubuntu. If you want to use just `fd` from neovim, you will need to follow the instructions in that section on creating a symlink.

**Comment by Trid-collab** [comment]
Thank you have done the same. Now I am able to use fd inside neovim via ":!fd <>" 
Is there anyway to replace the neovim/vim "find" command using fd

**Comment by tmccombs** [comment]
I believe the `:find` program is built into vim, and you can't customize it with a program.There are however, several plugins that can make use of fd (such as telescope.nvim if you are using neovim), or you could write your own `:Find` command that uses `fd`.
