### ISSUE TITLE
Absolute path support in `--exec`

### ISSUE THREAD

**Issue by figsoda** [sharkdp/fd#859]
I feel like giving an example is the easiest way to elaborate
Here are some outputs of my WIP pull request

```ShellSession
$ cargo run -- . doc -x echo "{+}"
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/fd . doc -x echo '{+}'`
/home/figsoda/fd/doc/fd.1
/home/figsoda/fd/doc/screencast.sh
/home/figsoda/fd/doc/screencast.svg

$ cargo run -- . doc -x echo "{+.}"
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/fd . doc -x echo '{+.}'`
/home/figsoda/fd/doc/screencast
/home/figsoda/fd/doc/fd
/home/figsoda/fd/doc/screencast
```

**Comment by tavianator** [comment]
Is this any different than using `-a`/`--absolute-path`?

**Comment by figsoda** [comment]
`-a` makes `{}`, `{.}`, and `{//}` also output absolute paths

**Comment by tmccombs** [comment]
Do you have a usecase where you need to use both the relative and absolute paths in the same command?

**Comment by sharkdp** [comment]
Thank you for your request and for the implementation in #860. I'm inclined to reject this, as I think it can be easily worked around. And most use cases can be solved by using `--absolute-path` in combination with the existing placeholder syntax.

I'm closing both tickets for now, but please feel free to comment here if you think it should be reopened.

**Comment by figsoda** [comment]
I do still wish this to be implemented but I'm ok with this being closed since there are rather trivial workarounds
