### ISSUE TITLE
Combining fd and rg

### ISSUE THREAD

**Issue by vbd** [sharkdp/fd#862]
fd 8.2.1 on Windows 10

`fd --changed-within "2021-10-09" | rg -i xxx`
won't return an result.

`fd --changed-within "2021-10-09" --exec  rg -i xxx`
returns the lines macthing xxx but the output is missing the filename where xxx is found.
Any idea how to get the filename where xxx is found?

`rg -i xxx` 
alone returns machting lines including filename

**Comment by sharkdp** [comment]
If you use `fd`s `-x` option, it will call `rg` once for each search result. `rg` is thus called with a single file argument and does not see the need to show you the filename (although you can force it to, using `rg`s `-H`/`--with-filename` option).

What I suggest doing (and often do myself) is to use `fd`s capital `-X` option which calls `rg` *once*, with all search results as arguments. This way, it should show you the filenames by default:
```
fd --changed-within "2021-10-09" -X rg -i xxx
```

Please let us know if that worked for you and how we could improve the documentation for future users.

**Comment by vbd** [comment]
Just works for me! Thank you very much. 
Please keep your great work :)

**Comment by vbd** [comment]
Imho an example for the `-X` parameter with `rg ` and your explanation would be useful.

**Comment by tacoda** [comment]
I can take care of updating the documentation.
