### ISSUE TITLE
syntax error at -e line 1, near "*." && execution of -e aborted due to compilation errors.

### ISSUE THREAD

**Issue by gingerbeardman** [sharkdp/fd#869]
**Command**

`fd -e txt -x sh -c "cat \"{}\" | perl -ne 's/(\x00\x1F|\x00x\00)//g;print $_;' > \"../_new/{.}.txt\"" \;`

**Describe the bug you encountered:**

The above command sometimes fails as follows:
```
syntax error at -e line 1, near "*."
Execution of -e aborted due to compilation errors.
```

However, if I issue the command a second time immediately afterwards it will work without error!

**Describe what you expected to happen:**

Command should work without error every time.

**What version of `fd` are you using?**

fd 8.2.1

**Which operating system / distribution are you on?**

Darwin 20.6.0 x86_64
macOS 11.6 (20G165) Big Sur

**Comment by tmccombs** [comment]
I think that error is from perl, and means that there was an error parsing the regular expression (or maybe just the syntax in general?)

**Comment by gingerbeardman** [comment]
Interesting, thanks!

I wonder why it errors and then with me changing nothing works at the next invocation?

Anyway, closing.

**Comment by sharkdp** [comment]
Note that your command line is also vulnerable to shell injection. If there is a matching file with a `"` or `$` character (or any other shell special character) in the name, this will likely fail.

**Comment by gingerbeardman** [comment]
Thanks! I'll be sure to check the filenames (though they are all under my control and not accessible to anybody else)

**Comment by sharkdp** [comment]
I wasn't so much talking about a potential security vulnerability (which is also there), but more about a potential "shooting yourself in the foot" problem. All sorts of dangerous commands could be accidentally executed if the quoting is not correct. As mentioned in https://github.com/sharkdp/fd/issues/796#issuecomment-964844319, there is a way to do this properly. I'm pretty sure it has been mentioned somewhere on the issue tracker as well. Let me know if you can't find it and I can also try to search it.
