### ISSUE TITLE
Add how to delete examples

### ISSUE THREAD

**Issue by daniejstriata** [sharkdp/fd#879]
**What version of `fd` are you using?**
fd 8.2.1

**How do I delete files older than or newer than?**
Can you please add examples how to delete? I've tried a couple ways and have not been able to get fd to delete

```
→ fd --change-older-than 90days -exec "rm -rf {}"
[fd error]: regex parse error:
    rm -rf {}
            ^
error: repetition quantifier expects a valid decimal

Note: You can use the '--fixed-strings' option to search for a literal string instead of a regular expression. Alternatively, you can also use the '--glob' option to match on a glob pattern.
```
or:
```
→ fd --change-older-than 90days -exec rm -rf {}
error: Found argument '-r' which wasn't expected, or isn't valid in this context

USAGE:
    fd [FLAGS/OPTIONS] [<pattern>] [<path>...]

For more information try --help
```
It would be nice if  I can simply add --delete
```
→ fd --change-older-than 90days --delete
error: Found argument '--delete' which wasn't expected, or isn't valid in this context

USAGE:
    fd [FLAGS/OPTIONS] [<pattern>] [<path>...]

For more information try --help
```

**Comment by tmccombs** [comment]
the problem is you are using `-exec` instead of `--exec`, which `fd` interprets as adding a filter for files with the `.xec` extension. 

Regarding a `--delete` option, see #871 (I think there was another issue about it too, but I can't find it right now).

**Comment by daniejstriata** [comment]
@tmccombs Thank you!
