### ISSUE TITLE
Split up main.rs into separate modules.

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#88]
A possible split could look like this:

- `main.rs` just includes the `main` function and the command-line parsing / options.
- Split out `print_entry` into its own module (`output.rs`?). Possibly split up the `print_entry` function as well.
- Split out `scan` into its own module (`traversal.rs`, `walk.rs`, or sth. similar). Possibly split out receiver and transmitter code into their own functions.

**Comment by gsquire** [comment]
Can I claim this?

**Comment by sharkdp** [comment]
Sure! Let me know if you need any help.
