### ISSUE TITLE
Shell completions for FISH shell

### ISSUE THREAD

**Issue by lordlycastle** [sharkdp/fd#887]
It would be great to have completions for fish shell, it is quite popular.

It would be quite easy to create them. [Here is the documentation](https://fishshell.com/docs/current/cmds/complete.html) for `complete` command that is used for these.

If you agree, I could give it a start and make a PR.

**Comment by tmccombs** [comment]
There are completions for the fish shell.  They are generated [here](https://github.com/sharkdp/fd/blob/f32060b0de34b52c255027aea12ac5ce53e40d6e/build.rs#L28). 

In the debian package they are under /usr/share/fish/completions. In the tarballs and zips, I think they are in the fd.fish file in the autocompletion directory
