### ISSUE TITLE
Option to prepend ./ to relative paths

### ISSUE THREAD

**Issue by jzinn** [sharkdp/fd#888]
When finding paths with `find` and `fd`, I often pipe the results into a script I wrote called `pathsort` that groups files before directories.

The `pathsort` script depends on there being at least one `/` in every path.

When running `find . -foo -bar`, the output paths all start with `./`, so my `pathsort` script works out-of-the-box with `find`.

To work with `fd`, the script has to have a flag (`-fd`) that causes it to prepend `./` to every line before processing.  I can't blindly prepend `./` to every line because `fd` output can have a mix of relative and absolute paths, making it difficult to remove after sorting.

If `fd` had an option to prepend `./` to every relative path, then `pathsort` would collapse to a `sed | sort | sed` one-liner that would work with both `find` and `fd`.

This is `pathsort`:

```shell
#!/bin/sh
set -euo pipefail

# 1.  Replace the last `/` with `/ /`
# 2.  Sort
# 3.  Replace the `/ /` with `/`
pathsort()
{
        sed -E 's/(.*)\//\1\/ \//' | sort | sed -E 's/(.*)\/ \//\1\//'
}

case "${1-}" in
        -fd )
                # It would be nice if `fd` had an option
                # to prepend `./` to all relative paths,
                # so that all paths have at least one `/` in them.
                sed 's/^/.\//' | pathsort
                ;;
        * )
                pathsort
                ;;
esac
```

**Comment by tavianator** [comment]
See #760/#861

**Comment by jzinn** [comment]
Thanks.  I deserve a "let me google that for your".  And just after I responsibly searched the issues on another repo before opening an issue there, too.

**Comment by jzinn** [comment]
It looks like #760/#861 will make the default behavior to prepend `./` to relative paths when output is not to an interactive tty.  That's great!
