### ISSUE TITLE
Can you help me secure my binary like fd?

### ISSUE THREAD

**Issue by STashakkori** [sharkdp/fd#890]
Hello my friend. I am enjoying fd. I ran a checksec on the binary and noticed the following results:

RELRO: Full RELRO
STACK CANARY: Canary found
NX: NX enabled
PIE: PIE enabled
FORTIFY: Yes

The STACK CANARY and FORTIFY protections are not present in any of my binaries. Can you please help me to add these protections in my binaries? What flags or steps must I use to have these? Thank you so much for your help, it is clear that you are a very advanced Rustacean

**Comment by sharkdp** [comment]
To be honest, I have no idea what any of this means. But you can see how we build `fd` in https://github.com/sharkdp/fd/blob/master/.github/workflows/CICD.yml
