### ISSUE TITLE
Question: Delete all files except the latest one

### ISSUE THREAD

**Issue by mailsanchu** [sharkdp/fd#905]
Is it possible to delete all files except the latest file using fd

**Comment by tmccombs** [comment]
You could do something like:

```sh
fd <pattern> --exec-batch ls -td --zero | tail -n +2 --zero-terminated | xargs -0 rm
```

**Comment by mailsanchu** [comment]
ls: unrecognized option '--zero'
Try 'ls --help' for more information.

I am on ubuntu if that helps

**Comment by mailsanchu** [comment]
But I understand the concept. Thanks

**Comment by tmccombs** [comment]
sorry, I meant to mention that assumes you are using GNU coreutils. I don't think there is a POSIX equivalent of the `--zero` option.

**Comment by mailsanchu** [comment]
This is how find does it and am not sure how easy to implement 
`  find . -maxdepth 1 -type f ! -newer "$LATEST_SNAPSHOT" ! -name "$LATEST_SNAPSHOT" -delete
`

**Comment by sharkdp** [comment]
Closing this for now. This is a niche use-case that `fd` is not trying to provide a feature for.

**Comment by mailsanchu** [comment]
No problem. Thank you very much for replying. Happy to close
