### ISSUE TITLE
Specifying `--no-ignore-vcs` option also turns on `--no-ignore-parent` option

### ISSUE THREAD

**Issue by phongnh** [sharkdp/fd#907]
**What version of `fd` are you using?**
`fd 8.3.0`

Here is my use case, I don't use `.gitignore` at project but I use custom `.ignore` or `.fdignore` at project's parent repo.

```sh
$ tree -L 2 -a ~/projects
/home/phongnh/projects
├── repo
│   ├── changelog.md
│   ├── ...
│   ├── .git
│   └── .gitignore
└── .ignore
```

```sh
cd ~/projects/repo
fd --type file --no-ignore-vcs # ==> this does not respect ~/projects/.ignore
```

Based on my check, it seems this comes from this PR https://github.com/sharkdp/fd/pull/817.

Please help to check this, thanks.

**Comment by sharkdp** [comment]
Fixed in https://github.com/sharkdp/fd/releases/tag/v8.3.1
