### ISSUE TITLE
The SSL Certificate is invalid?

### ISSUE THREAD

**Issue by GabrielKast** [sharkdp/fd#91]
Hi,
I was trying to install fd via cargo. Here is the output
```
~/projects$ cargo install fd-find --verbose
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  [16/-17] The SSL certificate is invalid

```
Am i the only one?

**Comment by sharkdp** [comment]
I don't think it's related to `fd`. It seems like `cargo` cannot download the package index. Can you access `https://github.com/rust-lang/crates.io-index` from your console?
