### ISSUE TITLE
.deb package in release page has bat's description

### ISSUE THREAD

**Issue by pwalch** [sharkdp/fd#915]
Hi `fd` maintainers and thanks for the great work!

I usually installed `fd` by downloading the pre-compiled binary to my PATH, but today I tried to use the `.deb` provided in the [release page](https://github.com/sharkdp/fd/releases/tag/v8.3.0). When I read the package info, it seems to be showing the `bat` description (from [this GitHub repo](https://github.com/sharkdp/bat)) instead of the `fd` one. That being said, the package seems to be functional and installs `fd` as expected.

To reproduce on Ubuntu 20.04:
* `curl -sL -o fd.deb https://github.com/sharkdp/fd/releases/download/v8.3.0/fd_8.3.0_amd64.deb`
* `dpkg -I fd.deb`

You will get the description of `bat` instead of the description of `fd`:
```
 new Debian package, version 2.0.
 size 888280 bytes: control archive=424 bytes.
     300 bytes,    11 lines      control              
 Package: fd
 Version: 8.3.0
 Section: utils
 Priority: optional
 Maintainer: David Peter <mail@david-peter.de>
 Homepage: https://github.com/sharkdp/fd
 Architecture: amd64
 Provides: fd
 Conflicts: fd-musl
 Description: cat(1) clone with wings.
   A cat(1) clone with syntax highlighting and Git integration.
```

**Comment by tmccombs** [comment]
@sharkdp, is this just a mistake during packaging?

**Comment by sharkdp** [comment]
Thank you for reporting this. That was a copy&paste error on my behalf. Fixed.

**Comment by pwalch** [comment]
Thanks! :100:
