### ISSUE TITLE
Is `-tf -td -tl -ts -tp` always true?

### ISSUE THREAD

**Issue by x-yuri** [sharkdp/fd#917]
**What version of `fd` are you using?**
fd 8.3.0

I'm trying to exclude sockets so that `tar` wouldn't complain. And pipes since I don't need them. Should I use `-tf -td -tl`?

**Comment by tmccombs** [comment]
I think that `-tf -td`  alone would match everything, because it matches all files and all directories.

**Comment by x-yuri** [comment]
Actually no:

```
$ mkfifo p
$ touch a
$ ln -s ./a b
$ fd -tf
a
$ fd -tl
b
$ fd -tp
p
```

Here are the corresponding lines:

https://github.com/sharkdp/fd/blob/e5145ffb985ab1fdd72b680806dff4fc00c1877f/src/filetypes.rs#L19-L23

And the [`is_file`][a] description says:

> Tests whether this file type represents a regular file. The result is mutually exclusive to the results of `is_dir` and `is_symlink`; only zero or one of these tests may pass.

Then the following lines suggest that the options in the title aren't true for every entry:

https://github.com/sharkdp/fd/blob/e5145ffb985ab1fdd72b680806dff4fc00c1877f/src/filetypes.rs#L30-L34

So, what are the other possible cases?

[a]: https://doc.rust-lang.org/nightly/std/fs/struct.FileType.html#method.is_file

**Comment by tmccombs** [comment]
> But if zero, what are the other possible cases?

That depends on the operating system, and possibly filesystem. On linux I believe that would include character and block special devices. Probably other special file types as well.

**Comment by tavianator** [comment]
On Linux I think block and character devices are the only other file types.  The BSDs and macOS have "whiteout" files.  Solaris and its descendants have "door" and "event port" files.

**Comment by sharkdp** [comment]
@x-yuri Can this be closed?

**Comment by x-yuri** [comment]
I think yes.
