### ISSUE TITLE
Options -u (and -uu) as in ripgrep

### ISSUE THREAD

**Issue by unhammer** [sharkdp/fd#92]
As mentioned in https://github.com/sharkdp/fd/issues/33 , `-u` as an alias for `--no-ignore` and `-uu` as an alias for `--no-ignore --hidden` would make it easier/less surprising to use this alongside ripgrep.

**Comment by sharkdp** [comment]
I'm going to copy over what I said in #33:

I would like to keep the command-line interface as clean and simple as possible (i.e., I don't want the `-h` text to be several pages long), but adding `-u` (and `-u -u`) seems like a good idea. We could possible hide it from the standard help text and add it as a hidden option that would only be mentioned in a man page(?)

**Comment by unsignedint** [comment]
I would like to take this on, if I may :)

**Comment by sharkdp** [comment]
Sure!

**Comment by n8henrie** [comment]
For some reason, I can never remember the `fd` flags to "search everything" when I'm not finding something I *know* should be there, and today for some reason (to my delight) I tried the `ripgrep` flag `-uuu`, and it worked!

However, not finding any documentation about it in the either the `--help` or manpage was a little disconcerting, which led me to the relevant PR and this discussion.

> We could possible hide it from the standard help text and add it as a hidden option that would only be mentioned in a man page(?)

Should something about this be added to the manpage as suggested above?

**Comment by sharkdp** [comment]
Sounds like a good idea, yes.

**Comment by n8henrie** [comment]
Is https://github.com/sharkdp/fd/blob/master/doc/fd.1 manually written? https://github.com/sharkdp/fd/commit/ddfa0873fb42029922a31565fe142fd645970963

I see `-uuu` [appropriately documented in the source code](https://github.com/sharkdp/fd/blob/630749f706957635e982267ed9ef3bb2fc9e5e59/src/app.rs#L53), it's just not in the man page, and even building from source it's not showing up with `--help`.

I think I can figure out the syntax if this file is just built by hand, but I'd be a little surprised if that was the case.

**Comment by sharkdp** [comment]
> Is https://github.com/sharkdp/fd/blob/master/doc/fd.1 manually written? [ddfa087](https://github.com/sharkdp/fd/commit/ddfa0873fb42029922a31565fe142fd645970963)

No. It's mostly auto-generated.

> I see `-uuu` [appropriately documented in the source code](https://github.com/sharkdp/fd/blob/630749f706957635e982267ed9ef3bb2fc9e5e59/src/app.rs#L53), it's just not in the man page, and even building from source it's not showing up with `--help`.

The option is set to "hidden". This is by design. It was added for users that come from ripgrep, but I chose to not display it in the general help text, as it is just a synonym for `-H`/`-I`.

**Comment by sharkdp** [comment]
Concerning the man page, we could either add it by hand, or actually add `-u` to the LONG `--help` text (but not to the short `-h` text).

**Comment by n8henrie** [comment]
> No. It's mostly auto-generated.

What tool are you using to generate the manpage? Found the option to hide only the short command, so with the above PR `-u` appears only in long `--help`, but still not appearing in the manpage.

**Comment by sharkdp** [comment]
Actually, I was wrong. I was thinking about my other projects where I used `help2man` to create an initial version of the man page.

For `fd`, @pickfire actually manually wrote a man page (see #125 and #77).

**Comment by pickfire** [comment]
Yes, I indeed did wrote the man page last hacktoberfest, the man pages are based on suckless.org man pages.
