### ISSUE TITLE
8.3.0 Release Doesn't Include Windows i686 GNU Interop

### ISSUE THREAD

**Issue by mattcargile** [sharkdp/fd#926]
**What version of `fd` are you using?**
`8.2.1`

I only see `fd-v8.3.0-i686-pc-windows-msvc.zip` archive. Is there supposed to be a `fd-v8.3.0-i686-pc-windows-gnu.zip` [release ](https://github.com/sharkdp/fd/releases/tag/v8.3.0)as well like on the `8.2.1`. Apologies if I missed something. I'm not sure if the difference matters in the context of the Chocolatey package ( see below reference ). I was reading about the interop [here](https://rust-lang.github.io/rustup/installation/windows.html). Is the change because the `msvc` iteration supports all toolchains?

EDIT: I guess it has to do with this section from the `rust-lang` docs.

_Since the MSVC ABI provides the best interoperation with other Windows software it is recommended for most purposes. The GNU toolchain is always available, even if you don't use it by default._

Also the Windows scoop package manager is using the `msvc` toolchain.

https://github.com/ScoopInstaller/Main/blob/c0f1efc852b37be128162e4aa82a647aa294a577/bucket/fd.json#L23

```json
                "url": "https://github.com/sharkdp/fd/releases/download/v$version/fd-v$version-x86_64-pc-windows-msvc.zip",
```

#### References
https://github.com/joachimschmidt557/chocolatey-packages-manual-automatic/issues/16#issuecomment-1003608041

**Comment by mattcargile** [comment]
I see it now here.

https://github.com/sharkdp/fd/blob/da7ea790348c352b74c6ffb7c30b1e8b4e09a9b8/.github/workflows/CICD.yml#L76

I wonder if that changes any behavior on windows at all?

**Comment by mattcargile** [comment]
So would the solution be to somehow perform the install of `MinGW-w64` within Github Actions, if it is even possible?

[StackOverflow](https://stackoverflow.com/a/39422911)

**Comment by mattcargile** [comment]
Maybe it is this [action](https://github.com/marketplace/actions/install-mingw) on the marketplace?

**Comment by mattcargile** [comment]
I see I've gotten confused between the `i686` ( 32bit) and the `x86_64` ( 64bit ). I could see maybe the 32bit going by the wayside with `gnu`?

**Comment by sharkdp** [comment]
I think we decided in the past to get rid of the MSVC version because it should work just like the GNU version. And the GNU version does not have any dependencies. The MSVC version relies on a MSVC runtime library.

But if this causes problems, we can also reactivate the MSVC build. It should be as easy as adding an appropriate line in CICD.yml

**Comment by mattcargile** [comment]
I see. I thought it was the GNU 32bit that was missing from the recent builds?

**Comment by sharkdp** [comment]
Oh, sorry. I did confused there. Right. The GNU Windows builds for i686 are missing. Are you actually on that platform? I would be surprised if there are many Windows 32bit users that are not yet happy with the MSVC build, but actually need the GNU build for some reason.

If you think we should add it, let's try to uncomment that line you mentioned above in a small PR and see if it builds.

**Comment by mattcargile** [comment]
Gotcha. I am on 64bit so it didn't end up being a problem. And yeah I assume the 32bit user-ship would be quite low. 

This Issue came about because of the Chocolatey package Issue referenced above. From what I can tell the choco package was using a pattern match on the GNU build that broke when it was removed from the Releases. It has since been fixed by using the MSVC build.

@joachimschmidt557, do see any issue continuing with only the MSVC builds? Was there any specific reason for using the GNU builds? I know [`scoop`](https://scoop.sh/) uses the MSVC build and so far I've been using `8.3.0` on this new build and it is working well.

I'll see if I can figure out how to set up my environment to build.

**Comment by joachimschmidt557** [comment]
@mattcargile As far as I can recall, I didn't have a specific reason for choosing the GNU builds over the MSVC builds. I currently see no problem with continuing to package the MSVC builds in chocolatey.

**Comment by mattcargile** [comment]
So it appears we can close this and the PR OUT?

**Comment by sharkdp** [comment]
Ok, thank you. Closing both for now.
