### ISSUE TITLE
Re-introduce crossbeam channels

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fd#933]
After doing a proper performance evaluation, it would be benefitial to use crossbeam channels instead of the std mpsc channels, because:
- there are some issues with the std channels version of `recv_timeout()` (https://github.com/rust-lang/rust/issues/39364)
- the current channels are not size-restricted and can lead to large memory usage
- crossbeam channels are "supposed to be" faster.

See discussion in #895 and #916.

**Comment by tavianator** [comment]
Looks like Rust might do this for us :) https://github.com/rust-lang/rust/pull/93563

**Comment by ijoseph** [comment]
fwiw, removing the second `-u` 

i.e. from 

```bash
fd -uu  --glob -p  '**/src/kustomization.yaml'
```
to
```bash
fd -u  --glob -p  '**/src/kustomization.yaml'
```

was a valid workaround in my case

**Comment by tavianator** [comment]
@ijoseph Makes sense, but that won't work any more after https://github.com/sharkdp/fd/pull/986.  You'll have to do `fd -I` explicitly.
