### ISSUE TITLE
Search in Files

### ISSUE THREAD

**Issue by rafaelfragosom** [sharkdp/fd#94]
I would be really awesome to have a feature to search text inside files.

**Comment by iology** [comment]
You may need [ripgrep](https://github.com/BurntSushi/ripgrep). E.g. `rg ---files-with-matches -0 PATTERN [path]...`

**Comment by sharkdp** [comment]
Yes, there are other tools that are designed for this purpose (like ripgrep, grep, ag, etc.).

If you have already built a search query in `fd`, you can still use `xargs` to search exactly these files:
```
> fd -e rs '^[am]' 
src/app.rs
src/fshelper/mod.rs
src/lscolors/mod.rs
src/main.rs
tests/testenv/mod.rs

> fd -e rs '^[am]' | xargs grep 'fn main'
src/main.rs:fn main() {
```

**Comment by stellarpower** [comment]
I'd like to re-open this discussion. Yes, we can of course use other tools - find does allow searching within files by `exec`cing grep, but this then becomes a bit of a pain in the arse, and I have to google how to have grep output the filename too every time. Obviously the main selling point of `fd` is that it's more convenient than the GNU utilities we've had for years. I think this is probably a common enough usecase that a quick switch to enable it would be useful for many people, and would like to hear what others think.

**Comment by tmccombs** [comment]
What is the usecase for searching the content that ripgrep does not fill? 

By default if ripgrep is run on multiple files it outputs the name of the file (and I think grep does tool). 

Searching the content of files is really out of scope for fd

**Comment by stellarpower** [comment]
I think it's more having to learn and then remember the syntax for two different utilities, when there's a lot of overlap between the usecases for each of them.

Searching for files by matching a regexp against their name,  and searching for files by matching a regexp against their content, seem to be very closely aligned goals to me, and often I want some element of both in what I am trying to do. Hence why it can be cumbersome using find and execcing grep and then probably saving that to file and going back over it again.

I haven't had time to look through all that ripgrep can do (nor fd if truth be told). Perhaps there is another tool out there that can take something a bit more like a SQL query (i.e. `name matches /.../ AND type is text AND content matches /.../`) but in any case, it does seem to me to limit the utility of either tool if each tool can only handle the one of the two scenarios.
