### ISSUE TITLE
-E flag not respecting caret ^

### ISSUE THREAD

**Issue by gennaro-tedesco** [sharkdp/fd#944]
**What version of `fd` are you using?**
```
$ fd --version
fd 8.3.1
```

## Description of the problem
The flag `-E` does not respect the caret character `^` to grep-exclude in the beginning of the line.

## Example
Find below a reproducible example together with a justification use case:
```
mkdir test && cd test
mkdir .config
mkdir -p project/.config
```
so that we have
```
test
.
├── .config
└── project
   └── .config
```
now I want to list all directories containing `.config` _except_ for the one at root level. I would therefore do
```
$ fd -H -t d -E '^\.config'
.config
project
project/.config
```
allegedly not seeing the caret in the beginning of the line. If instead 
```
$ fd -H -t d -E '\.config'
project
```
I exclude all `.config`, not only the one at root level.

## Use case
The scenario that brought me to this was a case where I was trying to find all `git` repositories on my computer, excluding the trivial cases of plugins or configs, therefore something along the lines of
```
fd -H -t d '\.git' -E '^.config' 
```
that made me realise the config folders were not excluded my the `-E` pattern.

Apologies if this was addressed in the documentation (and I have missed it) or perhaps similar to https://github.com/sharkdp/fd/issues/865?

**Comment by tmccombs** [comment]
The -E flag uses a glob pattern, not a regex on the path. 

However, it does use gitignore style globa, so you could use "/.config" to match the .config file at the root.

**Comment by gennaro-tedesco** [comment]
I see, thank you.

I am now noticing that perhaps even more similar is https://github.com/sharkdp/fd/issues/198, which is being re-opened. I will follow that one in case there is a plan to include an `--exclude-regex` in the future.
