### ISSUE TITLE
Can't find directory with exact name

### ISSUE THREAD

**Issue by c0rv4x** [sharkdp/fd#945]
Hey! I am using fd 8.3.1 version and it can't find a directory if I don't specify an exact directory of the file.

I have `/opt/homebrew/Cellar/emacs-mac` path. `emacs-mac` is what I am looking for.

Searching `fd emacs-mac /opt/homebrew/` returns no result. Meanwhile `fd emacs-mac /opt/homebrew/Cellar` returns `/opt/homebrew/Cellar/emacs-mac` which is pretty weird.

<img width="330" alt="Screenshot 2022-01-20 at 14 04 14" src="https://user-images.githubusercontent.com/7037785/150327258-aa34b357-8086-4e5b-8701-d639fad8995d.png">

Is there something that I am missing?

Funny thing is that I reproduce similar structure on some files in my home, it works absolutely fine

**Comment by tavianator** [comment]
Does `fd -HI emacs-mac /opt/homebrew` work?

**Comment by c0rv4x** [comment]
Yes, it works. Also `fd -I emacs-mac /opt/homebrew` works. I am sitting in `/` or `$HOME` which don't have any git or other ignore files listed in the docs for `-I` flag. I am confused to be honest.

**Comment by tavianator** [comment]
Is it possible that `/`, `/opt`, or `/opt/homebrew` has a `.*ignore` file?

**Comment by c0rv4x** [comment]
Well indeed you are right. I have homebrew .gitignore file: https://github.com/Homebrew/brew/blob/master/.gitignore
which has ```# First, ignore everything.
/*```

Well. Thanks for your help. Sorry for not figuring it out myself.
