### ISSUE TITLE
Print out the inverse result when running for multiple directories

### ISSUE THREAD

**Issue by IzhakJakov** [sharkdp/fd#957]
### For example
When running the command below, it will print all the `go.mod` files found in the given dirs
```
fd -t d '@v' ~/.config/go/pkg/mod/github.com |xargs fd go.mod
```

I would like to have the option of printing out only the dirs where `go.mod` is not found.
When running something like the command below
```
fd -t d '@v' ~/.config/go/pkg/mod/github.com |xargs fd <inverse_flag> go.mod
```
---
Forgive me if this feature already exists, I was looking through the docs but was unable to find it.

**Comment by tmccombs** [comment]
If there was an inverse result option I would expect it to print out every file and directory that doesn't match the pattern, which I don't think is what you want.

**Comment by izhakjakov** [comment]
That's why I want it only for directories, as the title of this issue suggests, when using `fd -t d` ([refer to given example](https://github.com/sharkdp/fd/issues/957#issue-1126584977)).

**Comment by izhakjakov** [comment]
```
fd -t d '@v' ~/.config/go/pkg/mod/github.com |xargs fd --not --containing=go.mod
```

**Comment by izhakjakov** [comment]
Better example:
```
fd -t d '@v' ~/.config/go/pkg/mod/github.com |xargs fd -t d <inverse> --containing=go.mod
```

**Comment by tmccombs** [comment]
I'd still expect an "inverse" operation to output directories that don't match the `@v` pattern.

**Comment by izhakjakov** [comment]
In the example above there are 2 `fd` invocations:
1. Starting with `fd` which looks for all the directories that match `@v` and pipes the output to `xargs`
2. `xargs` in turn invokes `fd` again with the results from the initial `fd` invocation as arguments.

So in the second invocation of `fd` it should already know which dirs to operate on.

**Comment by izhakjakov** [comment]
Is there a chat room for this repository.  I was looking in [gitter](https://gitter.im) but couldn't find anything.

**Comment by sharkdp** [comment]
I'm sorry, but this sounds like a very special use case. I don't expect us to add special functionality for this in `fd`. I would assume it could be easily solved using external tools (Maybe `diff` or `grep -v`) or some (shell) scripting. I'll close this for now.

**Comment by IzhakJakov** [comment]
That's OK

**Comment by IzhakJakov** [comment]
I am not convinced you understand what I am looking for, maybe I am not explaining very well and that's why I wanted to have a chat.

Yes, it can be achieved by external tools but not "easily" (assuming you meant "easy" as "simple") and thus annoying to do from scratch every time.  As well as being extremely inefficient, as it is still looking for every instance of the file needed to be missing instead of skipping the dirs where one instance have already been found.

Example:
`for r in $(fd -t d '@v' ~/.config/go/pkg/mod); do ./doThis $r; done`
Where `doThis` is:
```sh
fd 'go.mod' ${1} |
  grep --quiet . ||
    echo ${1}
```
Whatever `doThis` does can be done by `fd` itself in a way more efficient way and no need to use a for loop to call `fd` twice.

Anyways, if you don't perceive this feature as useful, that's OK.
Thank you for maintaining this great tool! 😊

**Comment by sharkdp** [comment]
I would think that you could do something like:
```
diff <(fd -d2 go.mod -x echo {//} | sort) <(fd -td -d1 | sort)
```
where the first `fd` command searches for all `go.mod` files but then only prints the directory name. And the second `fd` command finds all directories. You might need to adapt the `-d…` options.

**Comment by IzhakJakov** [comment]
This is not what I am looking for.  
I just want to get the list of directories that do **NOT** contain `go.mod` anywhere (including subdirs) within them.

**Comment by IzhakJakov** [comment]
Thank you that was pretty close.
It does not work with `-maxdepth 1`
But this does:
```
find ~/.config/go/pkg/mod -type d -name '*@v*' -not -exec fd -q go.mod {} \; -print
```

---

Now I just wonder if there is a way to do this using `fd` only.
If not, that's fine. I am pretty satisfied with this solution as well :)

**Comment by tavianator** [comment]
Glad that works!  `fd` by itself can't do anything like this (neither can `find`), but the combination works.  There might be a solution with `find ... -exec find ...` but it would be more complicated.

By the way this might be slightly faster, if you don't care about @v directories inside other @v directories:

```
find ~/.config/go/pkg/mod -type d -name '*@v*' -prune -not -exec fd -q go.mod {} \; -print
```

**Comment by IzhakJakov** [comment]
Actually this is not only faster, it is also more correct since I don't want to find subdirs inside the parent `@v`.  Thank you!
