### ISSUE TITLE
when using the -x option, is there any way to print the current file before showing the output associated?

### ISSUE THREAD

**Issue by stephane-archer** [sharkdp/fd#959]
I do the following
```fd -x my command -i  {}  -o out.tmp```
I have some output but I have no idea to what file these input are link to
is there any way to print the current file before showing the output associated?
something similar to ```xargs -t```

**Comment by tavianator** [comment]
See https://github.com/sharkdp/fd/issues/943

**Comment by Flimm** [comment]
You can use `xargs`, like this:

     fd pattern -0 | xargs -0 -I {} sh -c 'echo {}; custom-command {}'
