### ISSUE TITLE
Implement sequence number placeholder {#}

### ISSUE THREAD

**Issue by henry40408** [sharkdp/fd#962]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

I'd like to implement sequence number placeholder `{#}` for `-x` flag. For example:

```bash
$ ls
a.txt b.txt c.txt

$ fd . -x echo '{/}'
a.txt
b.txt
c.txt

$ fd -x echo '{#} {/}'
1 a.txt
2 b.txt
3 c.txt
```

**Describe alternatives you've considered**

Currently I use [GNU parallel](https://www.gnu.org/software/parallel/):

```bash
$ ls
a.txt b.txt c.txt

$ parallel echo '{#} {/}' ::: $(fd)
1 a.txt
2 b.txt
3 c.txt
```

**Additional context**

- #116 
- [GNU parallel documentation](https://www.gnu.org/software/parallel/man.html#options) **OPTIONS > {#}**
- Currently largest finite number of files is `2^128` source: [Comparison of file systems](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits)

**Comment by sharkdp** [comment]
I'd rather not implement this. As @tmccombs suggested, there are easy workarounds. And a sequence number placeholder might indicate that output order is deterministic, which it is not.
