### ISSUE TITLE
How to use fd?

### ISSUE THREAD

**Issue by paxsali** [sharkdp/fd#964]
$ fd --version
fd 8.3.2

$ mkdir -p ~/tmp/new/folder{A,B,C}

$ cd ~/tmp/new

$ command ls -l
total 12
drwx------ 2 paxsali paxsali 4096 Feb 24 17:59 folderA
drwx------ 2 paxsali paxsali 4096 Feb 24 17:59 folderB
drwx------ 2 paxsali paxsali 4096 Feb 24 17:59 folderC

$ fd
[...nothing...]

$ ls -lR > folderA/index.txt
$ ls -lR > folderB/index.txt
$ ls -lR > folderC/index.txt

$ find
.
./folderB
./folderB/index.txt
./folderA
./folderA/index.txt
./folderC
./folderC/index.txt

$ find -ls
   821268      4 drwx------   5 paxsali  paxsali      4096 Feb 24 17:59 .
   821266      4 drwx------   2 paxsali  paxsali      4096 Feb 24 17:59 ./folderB
   821270      4 -rw-------   1 paxsali  paxsali       431 Feb 24 17:59 ./folderB/index.txt
   460583      4 drwx------   2 paxsali  paxsali      4096 Feb 24 17:59 ./folderA
   821269      4 -rw-------   1 paxsali  paxsali       332 Feb 24 17:59 ./folderA/index.txt
   821267      4 drwx------   2 paxsali  paxsali      4096 Feb 24 17:59 ./folderC
   821271      4 -rw-------   1 paxsali  paxsali       530 Feb 24 17:59 ./folderC/index.txt

$ fd
$ command fd
$ fd txt
$ fd inde
$ fd index
$ fd index.txt
$ fd .
[...all nothing...]

From your "how to" section:

$ mkdir -p Software/python/imdb-ratings
$ date > Software/python/imdb-ratings/netflix-details.py
$ fd netfl
[...nothing...]

$ command ls -ld Software/python/imdb-ratings/netflix-details.py
-rw------- 1 paxsali paxsali 29 Feb 24 18:09 Software/python/imdb-ratings/netflix-details.py
$ cat Software/python/imdb-ratings/netflix-details.py
Thu Feb 24 18:09:29 CET 2022

Please, ... enlighten me.

**Comment by tmccombs** [comment]
Have you read https://github.com/sharkdp/fd#fd-does-not-find-my-file ?

**Comment by paxsali** [comment]
> Have you read https://github.com/sharkdp/fd#fd-does-not-find-my-file ?

I have now and none of these folders have a .gitignore nor are they hidden.

Now what do I have to read next?
