### ISSUE TITLE
How to prune multiple directories

### ISSUE THREAD

**Issue by kinghrothgar** [sharkdp/fd#965]
**What version of `fd` are you using?**
fd 8.3.2

I am trying to write a replacement for this find command:
```
find / \( -path /afs -o -path /mnt -o -path /var/cache -o -path /var/lib/pacman/local -o -path /var/lock -o -path /var/run -o -path /var/spool -o -path /var/tmp \) -prune -o -type d -print
```

fd does have a prune command, but it doesn't appear to be able to be specified multiple times. Is there a way to tell fd not to descend into multiple directories?

**Comment by sharkdp** [comment]
Maybe using `--exclude`?

```
    -E, --exclude <pattern>
            Exclude files/directories that match the given
            glob pattern. This overrides any other ignore
            logic. Multiple exclude patterns can be
            specified.
            
            Examples:
              --exclude '*.pyc'
              --exclude node_modules
```

**Comment by kinghrothgar** [comment]
If a directory matches an exclude, does fd not descend that directory? (That is my understand of how prune works)

**Comment by tmccombs** [comment]
> If a directory matches an exclude, does fd not descend that directory while searching?

tha'ts correct.

**Comment by kinghrothgar** [comment]
Sounds like that's the solution then! Thanks.
