### ISSUE TITLE
Remove dot in front  path and file names?

### ISSUE THREAD

**Issue by OilSubjectLoss7** [sharkdp/fd#966]
Latest 

I want
/dog.png
/cat/dog.png

Instead of
./dog.png
./cat/dog

How?

**Comment by sharkdp** [comment]
Are you sure you don't want to remove the slash as well?
```
        --strip-cwd-prefix
            By default, relative paths are prefixed with './' when the
            output goes to a non interactive terminal (TTY). Use this
            flag to disable this behaviour.
```

**Comment by dbaber** [comment]
I don't understand why `-X cmd {}` uses `./` while  the normal `fd` command doesn't output it like this. I would want it to use the same paths the the command outputs.

**Comment by tmccombs** [comment]
Without the ./ In front, if a file started with - or -- then the command would probably interpret the filename as a flag. If a malicious actor was able to control the filename, this could be a security vulnerability.  That's why, by default,  fd includes a ./ before the filename.
