### ISSUE TITLE
Installing fd on Rocky Linux - issues with Fedora COPR mirrors

### ISSUE THREAD

**Issue by x0x000x0x** [sharkdp/fd#977]
fd not installed.

Error as follows:
`sudo dnf install fd-find
Copr repo for fd owned by keefle                                                                                                          429  B/s | 341  B     00:00    
Errors during downloading metadata for repository 'copr:copr.fedorainfracloud.org:keefle:fd':
  - Status code: 404 for https://download.copr.fedorainfracloud.org/results/keefle/fd/fedora-8-x86_64/repodata/repomd.xml (IP: 143.204.68.119)
Error: Failed to download metadata for repo 'copr:copr.fedorainfracloud.org:keefle:fd': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: copr:copr.fedorainfracloud.org:keefle:fd
Last metadata expiration check: 0:09:27 ago on Sat 05 Mar 2022 11:25:49 GMT.
No match for argument: fd-find
Error: Unable to find a match: fd-find
`
Was unable to simply use dnf so had to add the repo, but the mirrors 404'd. Any ideas?

**Comment by tmccombs** [comment]
That's probably something to ask the owner of that copr repo (keefle?) Or possibly fedora.

**Comment by chapmanjacobd** [comment]
It exists outside of COPR...

```
/r/x/backup 🌠 sudo dnf list fd-find
Last metadata expiration check: 0:12:29 ago on Mon Mar  7 17:24:34 2022.
Installed Packages
fd-find.x86_64                                                             8.2.1-5.fc35                                                             @updates
```

It looks like the COPR version is likely old anyway `2021-Apr-27` https://download.copr.fedorainfracloud.org/results/keefle/fd/
