### ISSUE TITLE
feature request: type for multiple levels of directories

### ISSUE THREAD

**Issue by chapmanjacobd** [sharkdp/fd#978]
If there are multiple levels of empty folders then one currently needs to run 

```
fd --type empty --type directory -x rmdir {}
```

multiple times in order to get all of them. This may take quite a while for large drives. I think the current behavior makes sense as the default for type `empty` and type `directory`, but maybe introducing a new type for multiple levels of empty directories makes sense

```
fd --type empty-directories -x rmdir {}
```

or if it is possible to make a generic recursive directories type; maybe this makes sense (although it will probably make documentation confusing and it is making my head hurt when I think of how someone would use this)

```
fd --type empty --type directories -x rmdir {}
```

**Comment by sharkdp** [comment]
I think the root cause of your problem is described here in the last paragraph: https://github.com/sharkdp/fd#deleting-files

> Note: there are scenarios where using fd … -X rm -r can cause race conditions: if you have a path like …/foo/bar/foo/… and want to remove all directories named foo, you can end up in a situation where the outer foo directory is removed first, leading to (harmless) "'foo/bar/foo': No such file or directory" errors in the rm call.

Another related discussion is https://github.com/sharkdp/fd/pull/387. Especially the part how `find` handles this correctly with its `-delete` option.

Also, please take not of the discussion in https://github.com/sharkdp/fd/issues/871

**Comment by chapmanjacobd** [comment]
> root cause of your problem is described here in the last paragraph

I'm not sure that is the case here... (although this is definitely an edge case)

```
~ 🌲 mkdir -p test/test/test/test
~ ⛳ fd -td -te
test/test/test/test
```

only one result

**Comment by chapmanjacobd** [comment]
> even find can't do it by itself

I think `find` must special case this because I tested it recently and it _does_ work. These two commands do the same thing in `bfs` and `find` but not `fd-find` (wrt nested empty folders):

    bfs -type d -empty -delete
    find -type d -empty -delete

( https://github.com/tavianator/bfs/issues/92#issuecomment-2173659284 )

maybe having an option for "post-order traversal" in `fd -x` would make sense in other cases besides this

**Comment by tavianator** [comment]
Huh I should have thought of that.  It works because `-delete` implies `-depth`, so parents are visited after children, and they do become empty after you delete their children
