### ISSUE TITLE
Print with no extensiom just filename

### ISSUE THREAD

**Issue by OilSubjectLoss7** [sharkdp/fd#981]
**?**
[paste the output of `fd --version` here]

`fd "01x01" -e srt`

Output
`01x01.srt`

Expected results
`01x01`

If i do this
`fd "01x01" -e srt {/.}`

I get this
```
[fd error]: Search path '{/.}' is not a directory.
[fd error]: No valid search paths given.
```

**Comment by tmccombs** [comment]
You can do `fd "01x01" -e srt --exec echo '{/.}'`

**Comment by OilSubjectLoss7** [comment]
Thanks
