### ISSUE TITLE
How to find files which haven't changed within a specified period of time

### ISSUE THREAD

**Issue by Ultra-Code** [sharkdp/fd#982]
**What version of `fd` are you using?**
[ `fd 8.3.2` ]

I know that `fd -tf --changed-within=4weeks .` prints files in the current directory that have changed within 4week. how do i find those that haven't changed within 4week

**Comment by sharkdp** [comment]
If you found `--changed-within`, why didn't you find `--change-before`? (serious question, I'm always looking for ways to improve documentation)

```
        --changed-before <date|dur>
            Filter results based on the file modification time. The argument
            can be provided as a specific point in time (YYYY-MM-DD HH:MM:SS)
            or as a duration (10h, 1d, 35min). '--change-older-than' or
            '--older' can be used as aliases.
            Examples:
                --changed-before '2018-10-27 10:00:00'
                --change-older-than 2weeks
                --older 2018-10-27
```
