### ISSUE TITLE
Can support regex positive lookahead？

### ISSUE THREAD

**Issue by Aouchinx** [sharkdp/fd#987]
Can support `regex Positive Lookahead`？

**Comment by Aouchinx** [comment]
@tmccombs 
a use case is to find out files with both 'mutation' and 'asset' in their names
option: `^(?=.*mutation)(?=.*asset).*$`

**Comment by sharkdp** [comment]
Closing in favor of #399 (which is also closed, but I'm happy to continue the discussion there).

**Comment by danny1221** [comment]
@sharkdp I met a use case regarding look-around today, which I think it's not uncommon. 
![1](https://user-images.githubusercontent.com/2139987/206852122-4ec94779-cd96-46bf-8877-68025c236b2b.png)
I want to use pdfgrep to grep something from **any pdf not ending with JPN.pdf**. Without look-around it's not easy to express this requirement. With look-around, i can just type `fd -0 -P '(?<!JPN)\.pdf -X pdfgrep RTT'`

**Comment by sharkdp** [comment]
can you use the exclude option? `-E '*JPN.pdf'`

**Comment by danny1221** [comment]
@sharkdp Thanks very much for your kind reply. I obviously didn't carefully read #399 
![1670767321557](https://user-images.githubusercontent.com/2139987/206908179-2d8f512d-15ee-4cee-9a7a-ed1f18597d17.png)
diff says nothing! And I am now convinced by your decision of 
> fd is trying to stay simple and is only targeting "80% of the use cases"

Yes, stick to the KISS principle. Anyway, fd's regex targets are only file paths, which by their nature are not complicated text.
