### ISSUE TITLE
Strip given <path> prefix from matches

### ISSUE THREAD

**Issue by ds2606** [sharkdp/fd#996]
**What version of `fd` are you using?** 8.3.2

 I'm looking for a way to reduce a ton of wasted space in my searches, particularly when using `fd` as the base executable for `fzf`. For example, right now, I'm searching only through my dropbox, and the search output from `fd . ~/Desktop/Dropbox` looks like: 

```
/Users/dschreck/desktop/dropbox/Misc/Old Desktop/Old iTunes/Tones/Just A Friend.m4r
/Users/dschreck/desktop/dropbox/Misc/Old Desktop/Old iTunes/Tones/Float On.m4r
/Users/dschreck/desktop/dropbox/Misc/Old Desktop/Old iTunes/Tones/What is Love.m4r
/Users/dschreck/desktop/dropbox/Misc/Old Desktop/Old iTunes/Tones/Flashing Lights ft. Dwele.m4r
/Users/dschreck/desktop/dropbox/Misc/Old Desktop/Old iTunes/Tones/Mr. Brightside.m4r
/Users/dschreck/desktop/dropbox/Misc/Old Desktop/Old iTunes/Tones/Beautiful Alarm.m4r`
```

Where I'd just like to output
```
Misc/Old Desktop/Old iTunes/Tones/Just A Friend.m4r
Misc/Old Desktop/Old iTunes/Tones/Float On.m4r
Misc/Old Desktop/Old iTunes/Tones/What is Love.m4r
Misc/Old Desktop/Old iTunes/Tones/Flashing Lights ft. Dwele.m4r
Misc/Old Desktop/Old iTunes/Tones/Mr. Brightside.m4r
Misc/Old Desktop/Old iTunes/Tones/Beautiful Alarm.m4r`
```

Looking through the documentation I see no way to edit path information before it's output to stdout. The closest option I see is something like `--strip-cwd-prefix`, but that's incompatible with including a `<path>`. It seems like there should be some way to strip the given command-line `<path>` from each output match, no?

**Comment by sharkdp** [comment]
`fd` shows absolute paths if the input `<path>` argument is absolute. You can avoid that by passing a relative path, i.e. start the `fd` process from the `~/Desktop/Dropbox` folder and then run it without a path argument. If you want a certain command to work from everywhere, you can also use the `--base-directory <path>` option to make it appear as if you had started `fd` from that path. In addition, you can then use the `--strip-cwd-prefix` option for usage with `fzf` to avoid the `./` prefix:
```bash
fd --base-directory "$HOME/Desktop/Dropbox" --strip-cwd-prefix […]
```

**Comment by ds2606** [comment]
Thanks so much sharkdp, this is super super helpful!! Taking one moment to acknowledge how much I love your app, thanks so much for all the work you put in :heart:

**Comment by sharkdp** [comment]
Thank you for the feedback!
