### ISSUE TITLE
Support bat-style theme configuration

### ISSUE THREAD

**Issue by davidarmstronglewis** [sharkdp/fd#998]
I know very little about how this is implemented, but it would be very nice to be able to override `LS_COLORS` with a bat-style theme.

Thank you for creating and maintaining this tool, I use it practically every day ❤️

**Comment by tavianator** [comment]
You might like https://github.com/sharkdp/vivid :)

**Comment by sharkdp** [comment]
Closing this for now, assuming that vivid can fill this gap(?).

**Comment by davidarmstronglewis** [comment]
Hey! Yeah, this can be closed. I was looking into how to have more dynamic color usage than `export LS_COLORS=$(vivid generate ...)` as I tend to switch color schemes often depending on ambient lighting and found that I could set it dynamically using zsh pre-exec hooks. Here's my zsh config statement for anyone interested:

```zsh
function my_custom_preexec () {
  if test -x "$(which vivid)"; then
    export LS_COLORS=$(vivid generate $(cat ~/.config/vivid/theme))
  fi
}

add-zsh-hook preexec my_custom_preexec
```

Where `~/.config/vivid/theme` contains the name of the `vivid` theme my current color scheme works best with.
